[DATASET] Add cnn_dailymail dataset
PaddlePaddle/PaddleNLP pull request #1061
Opened 2021-09-22 09:10 UTC by gongel

### PR types

New features

### PR changes

Others

### Description

- Add cnn_dailymail dataset

2021-09-23 03:26 UTC, ZeyuChen reviewed
Is it possible just use the latest 3.0.0 version instead of involve tfds concept?

2021-09-23 03:26 UTC, ZeyuChen commented on paddlenlp/datasets/cnn_dailymail.py
> +        if tfds_version >= "2.0.0":
Don't envolve tfds_version concept to paddlenlp dataset, is it possible just use the latest version?

2021-09-23 03:30 UTC, gongel commented on paddlenlp/datasets/cnn_dailymail.py
> +        if tfds_version >= "2.0.0":
I think paddlenlp should be consistent with the original data. For ease of use, ` version` defaults to "3.0.0".

2021-09-25 16:40 UTC, smallv0221 requested changes
我测试一下没读到数据，你测试过了么

2021-09-25 16:48 UTC, smallv0221 commented on paddlenlp/datasets/cnn_dailymail.py
> +        if tfds_version >= "2.0.0":
这里还是用version吧

2021-09-26 02:55 UTC, gongel commented
> 我测试一下没读到数据，你测试过了么

我这边测试没问题，第一次加载解压比较慢。

2021-09-27 07:33 UTC, gongel commented on paddlenlp/datasets/cnn_dailymail.py
> +        if tfds_version >= "2.0.0":
> 这里还是用version吧

Done, thx

2021-09-28 07:37 UTC, smallv0221 approved these changes
LGTM

2021-09-28 11:17 UTC, merged