add sharding for gpt3
PaddlePaddle/PaddleNLP pull request #1064
Opened 2021-09-23 02:52 UTC by zhaoyinglia

### PR types

New features
### PR changes

Models
### Description

add sharding parallel for gpt-3

2021-09-23 03:29 UTC, ZeyuChen reviewed
Please shorter the import path of `DygraphShardingOptimizer` since it's not so friendly for developer.

2021-09-23 03:29 UTC, ZeyuChen commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +from paddle.distributed.fleet.meta_optimizers.dygraph_optimizer.dygraph_sharding_optimizer import DygraphShardingOptimizer
It's too long for this import ,is it ok to update the init file to shorter the import path?

2021-09-23 06:14 UTC, ZHUI requested changes

2021-09-23 06:14 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> -    local_seed = basic_seed + 123 + mp_rank * 10 + pp_rank * 1000
@ForFishes 这里的seed删除没有关系吗？

2021-09-23 06:14 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
>      assert args.device != "cpu"
对，这里需要给一个 warning 吧， @ForFishes 后面可以加一下

2021-09-23 06:14 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> -        clip = paddle.nn.ClipGradByGlobalNorm(clip_norm=args.grad_clip)
？为什么改掉`ClipGradByGlobalNorm`

2021-09-23 06:14 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                data_world_size=worker_num,
这里不能这么改，要考虑MP

2021-09-23 06:14 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                # only worker_index = 0 save model
要考虑MP

2021-09-23 06:34 UTC, JZ-LIANG commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> -        clip = paddle.nn.ClipGradByGlobalNorm(clip_norm=args.grad_clip)
需要支持 ClipGradByGlobalNorm， 如果报错请查看 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/hybrid_parallel_optimizer.py#L45  @zhaoyingli

2021-09-23 06:34 UTC, JZ-LIANG commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                data_world_size=worker_num,
data_world_size 只需要考虑读不同数据等rank？ dp 和 sharding group 读取不同的数据， mp 和 pp 读取相同的数据，所以data_world_size = dp_degree * sharding_degree

2021-09-23 06:34 UTC, JZ-LIANG commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                # only worker_index = 0 save model
需要考虑mp 的什么？ 数据loader 还是 model save ?

2021-09-23 13:25 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                data_world_size=worker_num,
我看岔了，`worker_index worker_num`你们重新定义了，sorry！

2021-09-24 01:17 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +    worker_index = dp_rank * sharding_size + sharding_rank
How about?
```
worker_index -> data_world_rank
worker_num -> data_world_size
```

2021-09-24 01:17 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> -    local_seed = basic_seed + 123 + mp_rank * 10 + pp_rank * 1000
seed 的东西 可否都移入到这里 @zhaoyuchen2018

2021-09-24 01:17 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                        global_step >= args.max_steps) and worker_index == 0:
静态图是专门写了 save_persistable 来save，这里的sharding，需要其他专门的save支持吗？

2021-10-09 11:43 UTC, zhaoyinglia commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +from paddle.distributed.fleet.meta_optimizers.dygraph_optimizer.dygraph_sharding_optimizer import DygraphShardingOptimizer
done.

2021-10-09 11:43 UTC, zhaoyinglia commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> -        clip = paddle.nn.ClipGradByGlobalNorm(clip_norm=args.grad_clip)
已支持ClipGradByGlobalNorm。

2021-10-09 11:43 UTC, zhaoyinglia commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +    worker_index = dp_rank * sharding_size + sharding_rank
done.

2021-10-09 11:43 UTC, zhaoyinglia commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                        global_step >= args.max_steps) and worker_index == 0:
done.

2021-10-11 04:07 UTC, ZHUI submitted a review, later dismissed
LGTM

2021-10-11 04:07 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +    strategy.tensor_parallel_configs = {"tensor_init_seed": 123, }
what's `tensor_init_seed` for ?

2021-10-11 04:07 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                        if mp_rank == 0 and sharding_rank == 0 and pp_rank == 0:
所以目前的策略是，`dp_rank == 0` 下所有参数都保存。

现阶段，可以不加load 参数，但辛苦确认一下，load checkpoint会不会存在问题？

另外记一个合并参数的 TODO 吧

2021-10-11 04:17 UTC, ForFishes commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
>      assert args.device != "cpu"
ok， will fix in next pr.

2021-10-11 04:17 UTC, ForFishes commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +    set_hyrbid_parallel_seed(args.seed, data_world_rank)
所有seed都在这里设置吧

2021-10-11 04:17 UTC, ForFishes commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                        model_to_save.save_state_dict(output_dir)
模型保存这里，没有详细的测试。需要记个TODO

2021-10-11 07:36 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +    strategy.tensor_parallel_configs = {"tensor_init_seed": 123, }
@ForFishes

2021-10-11 08:13 UTC, zhaoyinglia commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                        model_to_save.save_state_dict(output_dir)
已更新

2021-10-11 08:13 UTC, zhaoyinglia commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +    set_hyrbid_parallel_seed(args.seed, data_world_rank)
已更新

2021-10-11 08:13 UTC, zhaoyinglia commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                        if mp_rank == 0 and sharding_rank == 0 and pp_rank == 0:
dp_rank==0下所有参数都保存这个逻辑没有问题，但是现在模型保存没有测试，所以可能会存在问题，比如是否存储了全量的参数。

2021-10-11 08:13 UTC, zhaoyinglia commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +    strategy.tensor_parallel_configs = {"tensor_init_seed": 123, }
set control in tensor parallel

2021-10-11 08:17 UTC, ZHUI approved these changes
LGTM

2021-10-11 15:25 UTC, merged