PaddlePaddle Hackathon 56 提交
PaddlePaddle/PaddleNLP pull request #1088
Opened 2021-09-24 10:27 UTC by JunnYu

- 权重文件等百度云上传，TODO。
- 模型中有的layernorm未设置eps=1e-5。
- 删除`GPTEmbeddings`中`paddle.ParamAttr`的name属性，设置了话会报错，提示说重复使用了相同的名字，单元测试无法通过，jupyter notebook中无法重复初始化。
- 添加compare.py比较转换后的模型预测结果。（该文件所处位置等审核通过后再修改）。
- 添加convert.py转换脚本。（该文件所处位置等审核通过后再修改）。
- `microsoft-DialoGPT-small`转换后的误差有点大，问题与之前的应该类似，其他的两个模型转换后误差正常。（使用了相同的转换代码，因此不存在转换时代码的错误。）
- 添加GPTForTokenClassification, GPTForSequenceClassification这2个类，并添加注释。
- 添加单元测试代码。TestElectraForSequenceClassification，TestGPTForTokenClassification。
- 转换代码时候并未添加`lm_head.weight`，因为是它是与`word embedding`绑定的，所以没必要转换它，如果有需要可自行修改。

2021-09-26 06:51 UTC, ZHUI requested changes

2021-09-26 06:51 UTC, ZHUI commented on paddlenlp/transformers/gpt/modeling.py
>              hidden_size,
`删除GPTEmbeddings中paddle.ParamAttr的name属性，设置了话会报错，提示说重复使用了相同的名字，单元测试无法通过，jupyter notebook中无法重复初始化。`

这个是为什么？

2021-09-26 08:06 UTC, JunnYu commented on paddlenlp/transformers/gpt/modeling.py
>              hidden_size,
错误信息：
ValueError: parameter name [word_embeddings] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

2021-09-27 11:46 UTC, yingyibiao commented
merges.txt也通过百度云上传

2021-09-27 13:03 UTC, JunnYu commented
@yingyibiao baidu网盘包含merges.txt，现在已经删除community/junnyu所有文件。

2021-09-28 02:19 UTC, ZHUI commented on paddlenlp/transformers/gpt/modeling.py
>              hidden_size,
是有两个模型吗？导致参数出现重复？

这里的修改，对静态图的参数 load，是不兼容的。

2021-09-28 03:07 UTC, JunnYu commented on paddlenlp/transformers/gpt/modeling.py
>              hidden_size,
动态图中，在单个py文件中如果初始化加载2次模型，就会发生这个错误。
如果不修改，动态图下的单元测试，就会报这个错

2021-10-13 11:01 UTC, yingyibiao commented
> @yingyibiao baidu网盘包含merges.txt，现在已经删除community/junnyu所有文件。
还是需要在community/junnyu中上传相关文件，具体可以参考：
https://paddlenlp.readthedocs.io/zh/latest/community/contribute_models/contribute_awesome_pretrained_models.html

2021-10-13 16:06 UTC, JunnYu commented on paddlenlp/transformers/gpt/modeling.py
>              hidden_size,
已经修改成原来样子。

2021-10-18 04:39 UTC, yingyibiao commented
> Task: #1074
> 
> * 权重文件等百度云上传，链接：https://pan.baidu.com/s/1dyaOShLEgnL_RJW4sbs40g 提取码：kayr。
> * 模型中有的layernorm未设置eps=1e-5。
> * 删除`GPTEmbeddings`中`paddle.ParamAttr`的name属性，设置了话会报错，提示说重复使用了相同的名字，单元测试无法通过，jupyter notebook中无法重复初始化。
> * 添加compare.py比较转换后的模型预测结果。（该文件所处位置等审核通过后再修改）。
> * 添加convert.py转换脚本。（该文件所处位置等审核通过后再修改）。
> * `microsoft-DialoGPT-small`转换后的误差有点大，问题与之前的应该类似，其他的两个模型转换后误差正常。（使用了相同的转换代码，因此不存在转换时代码的错误。）
> * 添加GPTForTokenClassification, GPTForSequenceClassification这2个类，并添加注释。
> * 添加单元测试代码。TestElectraForSequenceClassification，TestGPTForTokenClassification。
> * 转换代码时候并未添加`lm_head.weight`，因为是它是与`word embedding`绑定的，所以没必要转换它，如果有需要可自行修改。

权重已上传至bos

2021-10-18 04:41 UTC, yingyibiao commented
参照 #1085 的review意见修改类似问题～

2021-10-18 12:12 UTC, yingyibiao commented on community/junnyu/uer-gpt2-chinese-poem/README.md
> +https://huggingface.co/uer/gpt2-chinese-poem
添加一下模型结构，具体任务，以及更换更加切合权重的example

2021-10-18 12:12 UTC, yingyibiao commented on community/junnyu/uer-gpt2-chinese-poem/README.md
> +https://huggingface.co/uer/gpt2-chinese-poem
可以来生成一首诗歌啥的

2021-10-18 12:12 UTC, yingyibiao commented on community/junnyu/microsoft-DialoGPT-small/README.md
> +https://huggingface.co/microsoft/DialoGPT-small
添加一下模型结构，具体任务介绍，以及更换更加切合权重的example
可以来生成一段对话啥的

2021-10-18 12:13 UTC, yingyibiao commented
顺便将 DialoGPT-medium，DialoGPT-large 这两个权重也导入～

2021-10-19 03:30 UTC, yingyibiao commented
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/model_zoo/transformers.rst
这个文件也需要同步修改

2021-10-19 08:50 UTC, ZHUI reviewed
非常不错！
看 `GPTForTokenClassification` `GPTForSequenceClassification ` 是否也能给 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/gpt/ 中添加一些实际使用的例子

2021-10-19 08:50 UTC, ZHUI commented on paddlenlp/transformers/gpt/modeling.py
> +    'GPTForTokenClassification', 'GPTForSequenceClassification'
List 最后加一个 `,`  代码格式化之后，就是每条一行

2021-10-19 08:50 UTC, ZHUI commented on paddlenlp/transformers/gpt/modeling.py
> +        pooled_logits = logits.gather_nd(
这里是获取一个 batch 里面， 每一条数据的最后一个预测的结果？
shape是这样的吗？
`sequence_output [bs, seq_len, hidden_size]`
`logits [bs, seq_len, num_class] `
`pooled_logits [bs, num_class]`

那输入应该是怎样的？

2021-10-19 08:50 UTC, ZHUI commented on paddlenlp/transformers/gpt/modeling.py
> +class GPTForSequenceClassification(GPTPretrainedModel):
`GPTForTokenClassification`
`GPTForSequenceClassification`
这两个东西能否加一个例子到  https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/gpt/  中

2021-10-22 07:56 UTC, JunnYu commented on paddlenlp/transformers/gpt/modeling.py
> +class GPTForSequenceClassification(GPTPretrainedModel):
`GPTForTokenClassification` 跟 `BertForTokenClassification`基本一样的，只是模型不需要输入`token type id`.



`GPTForSequenceClassification` 现已完成

2021-10-22 08:06 UTC, JunnYu commented on paddlenlp/transformers/gpt/modeling.py
> +        pooled_logits = logits.gather_nd(
例子：
```python
# input_ids
[[1,2,3,4,5,6,0,0,0],
[3,4,2,1,5,6,7,0,0],
[2,1,5,3,0,0,0,0,0]]
# 分别获取
batch1的6，batch2的7，batch3的3 处的token
```

2021-10-22 11:14 UTC, JunnYu commented
![1634901105](https://user-images.githubusercontent.com/50394665/138444761-428c359c-75d3-4d48-9615-709ce11f22e6.jpg)

2021-10-22 11:35 UTC, JunnYu commented
@yingyibiao
large和medium的权重在这
链接：https://pan.baidu.com/s/1cdqfjHVrE6CwBvYW5692rg 
提取码：83jh

2021-10-24 07:08 UTC, yingyibiao commented on docs/model_zoo/transformers.rst
> +|                    |                                                                                  |              | 16-heads, _M parameters.                |
补充一下_M

2021-10-24 07:08 UTC, yingyibiao commented on docs/model_zoo/transformers.rst
> +|                    |                                                                                  |              | 20-heads, _M parameters.                |
补充一下_M

2021-10-24 07:18 UTC, yingyibiao commented
> @yingyibiao
> large和medium的权重在这
> 链接：https://pan.baidu.com/s/1cdqfjHVrE6CwBvYW5692rg
> 提取码：83jh

已上传～

2021-10-24 09:08 UTC, yingyibiao commented
LGTM for community related files

2021-10-27 09:12 UTC, JunnYu commented on paddlenlp/transformers/gpt/modeling.py
> +class GPTForSequenceClassification(GPTPretrainedModel):
现已添加使用`GPTForTokenClassification`进行NER的例子，发现效果很差。

2021-11-01 10:45 UTC, ZHUI approved these changes
LGTM

2021-11-01 10:45 UTC, ZHUI commented on examples/language_model/gpt/README.md
> +
这效果感觉可能有些偏低。

2021-11-02 06:56 UTC, ZeyuChen commented on examples/language_model/gpt/README.md
> + Metric                       | Result      |
GPT可以解决TokenClassification问题这个事有相关paper佐证吗？@ZHUI

2021-11-09 07:51 UTC, yingyibiao approved these changes
LGTM

2021-11-09 07:52 UTC, merged