Add to_static support for transformer-base
PaddlePaddle/PaddleNLP pull request #1175
Opened 2021-10-15 09:10 UTC by 2742195759

### PR types

New feature

### PR changes

Models

### Description

Add to_static support for transformer-base and bert-large

2021-10-16 08:43 UTC, ZeyuChen requested changes
Need further discussion if such complicated build strategy of `to_static` is not default option.

2021-10-16 08:43 UTC, ZeyuChen commented on examples/language_model/bert/run_pretrain.py
> +        is_pass = args.enable_pass if hasattr(args, 'enable_pass') else False
这些pass操作，没法智能识别吗？一定得用这些开关吗？

2021-10-16 08:43 UTC, ZeyuChen commented on examples/language_model/bert/run_pretrain.py
> +            build_strategy.fuse_elewise_add_act_ops = True
或者说这些开关可否框架是默认的状态，嵌在框架中。我理解暴露这些开关给到用户会大幅度降低易用性，需要配套大量的文档来帮助用户理解。

2021-10-20 10:39 UTC, Aurelius84 commented on examples/language_model/bert/run_pretrain.py
> +            build_strategy.fuse_elewise_add_act_ops = True
这部分代码暴露在这里确实会让用户感到一丝困惑，我们先移除下build_strategy相关。

2021-10-20 12:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=1175) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=1175) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: 2742195759<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=1175) it.</sub>

2021-10-25 12:41 UTC, ZeyuChen reviewed
strategy=None的话是否还需要露出？

2021-10-25 12:41 UTC, ZeyuChen commented on examples/language_model/bert/run_pretrain.py
> +        build_strategy = None
如果是None了，还有必要传入吗？是否用默认参数就行？

2021-10-25 12:41 UTC, ZeyuChen commented on examples/machine_translation/transformer/util/to_static.py
> +        model = to_static(model, input_spec=specs, build_strategy=build_strategy)
如果是None是否可以不露出？

2021-11-10 07:04 UTC, closed without merging