[GPT-3]add support for pure fp16 in dygraph mode
PaddlePaddle/PaddleNLP pull request #1176
Opened 2021-10-15 12:15 UTC by haohongxiang

### PR types

New features
### PR changes

Others
### Description

[GPT-3]add support for pure fp16 in dygraph mode

单卡FP32与3D混合并行+recompute+FP16的loss曲线精度对比
![image](https://user-images.githubusercontent.com/86215757/137855610-45ffd2fc-a261-4a06-b47d-91c68561c639.png)

2021-10-18 02:45 UTC, ZHUI requested changes
总体来看：
 amp和pure_fp16的一些API使用上，存在一些diff，建议统一。
cc @sandyhouse  @ForFishes 

如果需要同时支持 amp 和 pure_fp16 的,  参数选项可以加 一个 fp16_level, 默认 O2， `use_amp`改成`use_fp16`

2021-10-18 02:45 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/args.py
> -        "--use_amp",
是否以后就只用 `prue_fp16` 了，不再暴露 `amp` 选项给用户？

2021-10-18 02:45 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run.sh
> +export PYTHONPATH=$PYTHONPATH:../../../../
合入的时候，删去此行。默认用户需要安装paddlenlp

2021-10-18 02:45 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +            multi_precision=args.use_pure_fp16)
从API使用建议的角度来讲：
既然我们的用法是`paddle.amp.decorate`去包装optimizer。
这里的 `multi_precision` 选项的操作，如果没有更多使用场景需要 解耦的话，
放到`paddle.amp.decorate`中去操作，是更为合理的。

只是建议，可忽略。cc @sandyhouse

2021-10-18 02:45 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> -        scaler = fleet.distributed_scaler(scaler)
所以普通的amp的话不用`paddle.amp.decorate`去装饰，这个是amp和pure fp16的主要diff？

2021-10-18 02:45 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +        model, optimizer = paddle.amp.decorate(
可以加一行注释，说明，`level O2 means to convert the network to FP16`

2021-10-18 02:45 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                    for i in range((int)(lbs / mbs)):
额，不是太理解了？这里是为了做gradient merge？

2021-10-18 02:45 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                        scaler.update()
`scaler.minimize(optimizer, loss)`
-> `scaler.step(optimizer), scaler.update()` 

这种用法的变化，可否统一？

2021-10-18 02:56 UTC, zhiqiu commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +            multi_precision=args.use_pure_fp16)
> 从API使用建议的角度来讲： 既然我们的用法是`paddle.amp.decorate`去包装optimizer。 这里的 `multi_precision` 选项的操作，如果没有更多使用场景需要 解耦的话， 放到`paddle.amp.decorate`中去操作，是更为合理的。
> 
> 只是建议，可忽略。cc @sandyhouse

嗯嗯，这是我们设计接口decorate的初衷，也是不希望在声明optimizer中有耦合amp的东西。

2021-10-18 02:57 UTC, zhiqiu commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> -        scaler = fleet.distributed_scaler(scaler)
> 所以普通的amp的话不用`paddle.amp.decorate`去装饰，这个是amp和pure fp16的主要diff？

amp O1可以用decorate（会不作操作直接返回），也可以不用。

2021-10-18 03:00 UTC, haohongxiang commented on examples/language_model/gpt-3/dygraph/args.py
> -        "--use_amp",
是的，以后只用pure_fp16，不再暴露amp

2021-10-18 03:00 UTC, haohongxiang commented on examples/language_model/gpt-3/dygraph/run.sh
> +export PYTHONPATH=$PYTHONPATH:../../../../
好的

2021-10-18 03:04 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
>                  position_ids.stop_gradient = True
再请教一个问题。

如果模型的输入是fp32的话， pure_fp16 需不需要对输入dataset的输入也转换为 fp16，即在数据处理阶段，将数据直接转为fp16，减少训练时候cast的开销？

（gpt的话大部分数据tokens是int类型的）

2021-10-18 03:08 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +            multi_precision=args.use_pure_fp16)
嗯嗯，了解了哈👌🏻

现阶段可以去掉 `multi_precision `的话，就直接去掉，不行的话，咱们记一个todo吧 @haohongxiang

2021-10-18 03:09 UTC, haohongxiang commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> -        scaler = fleet.distributed_scaler(scaler)
普通的`amp`也用`paddle.amp.decorate`去装饰，用参数`level`区分，'O1'为`amp`，'O2'为`pure fp16`

2021-10-18 03:10 UTC, haohongxiang commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +            multi_precision=args.use_pure_fp16)
好的

2021-10-18 03:13 UTC, haohongxiang commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +        model, optimizer = paddle.amp.decorate(
> 可以加一行注释，说明，`level O2 means to convert the network to FP16`

好的

2021-10-18 03:14 UTC, haohongxiang commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                    for i in range((int)(lbs / mbs)):
> 额，不是太理解了？这里是为了做gradient merge？

这里是在非pp情况下做各micro batch size的梯度累加

2021-10-18 03:23 UTC, haohongxiang commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                        scaler.update()
> `scaler.minimize(optimizer, loss)` -> `scaler.step(optimizer), scaler.update()`
> 
> 这种用法的变化，可否统一？

好的，可以统一

2021-10-18 03:49 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                    for i in range((int)(lbs / mbs)):
给一点建议
1. accumulate_steps 的计算，放到和 strategy.pipeline_configs 代码附近，统一计算accumulate_steps
2. 这里的 (int)(lbs / mbs) 理论上是需要check是否严格倍数关系，否则需要报错
3. 我看你的 这个累加阶段，只有forward，backward 在for循环外，是否有bug？
3. 这里的 gradient merge 是否需要 no_sync 提升性能 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/DataParallel_cn.html#no_sync

2021-10-18 04:04 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                    for i in range((int)(lbs / mbs)):
小建议:
gradient merge 策略加入到模型精度的CI  cc @ForFishes

2021-10-18 05:12 UTC, haohongxiang commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> +                    for i in range((int)(lbs / mbs)):
> 给一点建议
> 
> 1. accumulate_steps 的计算，放到和 strategy.pipeline_configs 代码附近，统一计算accumulate_steps
> 2. 这里的 (int)(lbs / mbs) 理论上是需要check是否严格倍数关系，否则需要报错
> 3. 我看你的 这个累加阶段，只有forward，backward 在for循环外，是否有bug？
> 4. 这里的 gradient merge 是否需要 no_sync 提升性能 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/DataParallel_cn.html#no_sync

这边的代码有点问题，我修改一下

2021-10-19 06:33 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_pretrain.py
> -                            custom_white_list=[
这里的 `custom_white_list` 和 `custom_black_list` 修改是否有影响?

2021-10-19 06:34 UTC, ZHUI approved these changes
LGTM

2021-10-19 06:47 UTC, merged