[NER] Support ernie and peoples_daily_ner.
PaddlePaddle/PaddleNLP pull request #1361
Opened 2021-11-26 03:41 UTC by ZHUI

### PR types

example optimization
### PR changes

Others
### Description

[NER] Support ernie and peoples_daily_ner.

2021-11-26 03:58 UTC, joey12300 requested changes

2021-11-26 03:58 UTC, joey12300 commented on examples/information_extraction/msra_ner/train.py
> +    logger.info('{:20}:{}'.format("paddle commit id", paddle.version.commit))
可以在args添加log level，默认不展示给用户看

2021-11-26 06:35 UTC, ZHUI commented on examples/information_extraction/msra_ner/train.py
> +    logger.info('{:20}:{}'.format("paddle commit id", paddle.version.commit))
已删除 commit id 打印

2021-11-26 06:35 UTC, ZHUI commented on examples/information_extraction/msra_ner/train.py
> +    logger.info('{:20}:{}'.format("paddle commit id", paddle.version.commit))
已删除 commit id 打印

2021-12-01 12:43 UTC, joey12300 approved these changes
LGTM

2021-12-01 12:44 UTC, merged