Transformer decoding support fuse qkv
PaddlePaddle/PaddleNLP pull request #1455
Opened 2021-12-13 12:57 UTC by FrostML

### PR types

Performance optimization

### PR changes

Models

### Description

Transformer decoding support fuse qkv.

2021-12-15 07:07 UTC, guoshengCS approved these changes, later dismissed
fuse_qkv 如果多了对size的限制的话也加上分支来支持更多size吧

2021-12-15 07:58 UTC, FrostML commented
> fuse_qkv 如果多了对size的限制的话也加上分支来支持更多size吧

Done. Thanks.

2021-12-15 11:33 UTC, guoshengCS commented on paddlenlp/ops/faster_transformer/src/fusion_decoding_op.cc
> +    const bool& fuse_qkv) {
不另外加这个fuse_qkv的attr了吧，直接根据size来判断吧，也保证对之前模型的兼容性

2021-12-16 01:55 UTC, FrostML commented on paddlenlp/ops/faster_transformer/src/fusion_decoding_op.cc
> +    const bool& fuse_qkv) {
`fuse qkv` **没有办法保证**对之前的模型的兼容性。如果要做这个优化，必须得有把 qkv `weight/bias` `concat` 的操作，而且`concat` 只能发生在 `\_\_init\_\_` 里面，写到自定义  op 里面会占用 `forward` 的时间。
如果说，自定义 op 里面通过 `size_per_head` 来判断是否开启，即使是这样，之前的模型因为没有做 `concat`，结果也是错的，还会出现越界错误。

2021-12-16 10:34 UTC, guoshengCS commented on paddlenlp/ops/faster_transformer/transformer/faster_transformer.py
> +                    "decoding.slf_q_" + param_type + "_" +
load和export是否也判断下`self._fuse_qkv`呢

2021-12-16 11:34 UTC, FrostML commented on paddlenlp/ops/faster_transformer/transformer/faster_transformer.py
> +                    "decoding.slf_q_" + param_type + "_" +
目前不会报 warning 也不影响使用。
已优化代码。Thanks.

2021-12-16 11:55 UTC, guoshengCS submitted a review, later dismissed

2021-12-16 15:56 UTC, ZeyuChen requested changes

2021-12-16 15:56 UTC, ZeyuChen commented on paddlenlp/ops/faster_transformer/src/fusion_force_decoding_op.h
> +    const int& topk,
理论上int值的参数，是不需要加const和引用的。因为没有任何加速意义。
string的话通过引用，是会将copy从string降低到指针（32bit）的拷贝。
但是int呢，你不管加不加引用，拷贝的指针地址和拷贝int值是一样的。
正因为如此，所以你加不加const都一样了。

2021-12-17 02:46 UTC, FrostML commented on paddlenlp/ops/faster_transformer/src/fusion_force_decoding_op.h
> +    const int& topk,
Truth. 这里加 const 单纯是不需要修改的形参都习惯性加上 const，加上引用是想让形参列表看起来统一。我新的修改删除了引用，不过对于这样不需要修改的形参，还是建议保留 const。

2021-12-17 03:18 UTC, ZeyuChen approved these changes
LGTM

2021-12-17 03:54 UTC, merged