Add FNet
PaddlePaddle/PaddleNLP pull request #1499
Opened 2021-12-22 09:38 UTC by HJHGJGHHG

### PR types

### PR changes

### Description

添加FNet模型文件

2021-12-22 09:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=1499) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=1499) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=1499) it.</sub>

2021-12-22 09:41 UTC, HJHGJGHHG commented
## 预训练模型位置
### 1.spiece.model
* FNet-Base: https://huggingface.co/HJHGJGHHG/paddle-fnet-base/resolve/main/spiece.model
* FNet-Large: https://huggingface.co/HJHGJGHHG/paddle-fnet-large/resolve/main/spiece.model

### 2.model_state.pdparams
* FNet-Base: https://huggingface.co/HJHGJGHHG/paddle-fnet-base/resolve/main/model_state.pdparams
* FNet-Large: https://huggingface.co/HJHGJGHHG/paddle-fnet-large/resolve/main/model_state.pdparams

2021-12-23 14:06 UTC, gongel commented
@HJHGJGHHG 感谢贡献，麻烦签署一下CLA哈 https://github.com/PaddlePaddle/PaddleNLP/pull/1499#issuecomment-999429780

2021-12-23 14:10 UTC, HJHGJGHHG commented
多谢提醒，已签署。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/PaddleNLP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 晚上10:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/PaddleNLP] Add FNet (PR #1499)





 
@HJHGJGHHG 感谢贡献，麻烦签署一下CLA哈 #1499 (comment)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2021-12-29 02:12 UTC, Steffy-zxf requested changes

2021-12-29 02:12 UTC, Steffy-zxf commented on paddlenlp/transformers/fnet/modeling.py
> +# encoding=utf8
paddlenlp 仅支持python3.6+，不需要指定编码。可以删去

2021-12-29 02:12 UTC, Steffy-zxf commented on paddlenlp/transformers/fnet/modeling.py
> +def gelu_new(x):
这个GELU实现和`paddle.nn.funtional.gelu()`实现有什么不同？
`paddle.nn.funtional.gelu()`是否可以满足需求？

2021-12-29 02:12 UTC, Steffy-zxf commented on paddlenlp/transformers/fnet/modeling.py
> +        return (layer_output,)
只有一个返回值，可以不需要使用tuple

2021-12-29 02:12 UTC, Steffy-zxf commented on paddlenlp/transformers/fnet/modeling.py
> +        return (hidden_states,)
同上

2021-12-29 02:12 UTC, Steffy-zxf commented on paddlenlp/transformers/fnet/modeling.py
> +        return (outputs,)
同上

2021-12-29 02:12 UTC, Steffy-zxf commented on paddlenlp/transformers/fnet/modeling.py
> +        return (fourier_output,)
同上

2021-12-29 02:12 UTC, Steffy-zxf commented on paddlenlp/transformers/fnet/tokenizer.py
> +# encoding=utf8
删去指定编码

2021-12-29 02:12 UTC, Steffy-zxf commented on paddlenlp/transformers/fnet/modeling.py
> +        self.fourier_transform = partial(paddle.fft.fftn, axes=(1, 2))
`paddle.fft.fftn()`不建议用`partial`封装，使用`partial`封装会可能导致出错堆栈信息复杂。直接调用即可。

2021-12-29 02:12 UTC, HJHGJGHHG commented
您的来信已收到。

2021-12-30 08:46 UTC, HJHGJGHHG reviewed
已修改

2021-12-30 08:46 UTC, HJHGJGHHG commented on paddlenlp/transformers/fnet/modeling.py
> +# encoding=utf8
已删除

2021-12-30 08:46 UTC, HJHGJGHHG commented on paddlenlp/transformers/fnet/modeling.py
> +def gelu_new(x):
是paddle.nn.funtional.gelu()在approximate=True时的版本。由于不好指定关键字参数所以此处单独列出，其他模型（如albert）也如此。后续可将paddle.nn.funtional.gelu()拆成两部分，更为精简。

2021-12-31 07:45 UTC, Steffy-zxf approved these changes, later dismissed
LGTM

2022-01-07 06:28 UTC, yingyibiao commented
参考其他模型给modeling.py和tokenizer.py这两个文件添加docstrings

2022-01-07 13:08 UTC, HJHGJGHHG reviewed
已添加docstring

2022-01-10 09:11 UTC, yingyibiao commented
> ## 预训练模型位置
> ### 1.spiece.model
> * FNet-Base: https://huggingface.co/HJHGJGHHG/paddle-fnet-base/resolve/main/spiece.model
> * FNet-Large: https://huggingface.co/HJHGJGHHG/paddle-fnet-large/resolve/main/spiece.model
> 
> ### 2.model_state.pdparams
> * FNet-Base: https://huggingface.co/HJHGJGHHG/paddle-fnet-base/resolve/main/model_state.pdparams
> * FNet-Large: https://huggingface.co/HJHGJGHHG/paddle-fnet-large/resolve/main/model_state.pdparams

可以提供百度网盘或者google_drive下载链接吗～

2022-01-10 09:40 UTC, HJHGJGHHG commented
> > ## 预训练模型位置
> > ### 1.spiece.model
> > 
> > * FNet-Base: https://huggingface.co/HJHGJGHHG/paddle-fnet-base/resolve/main/spiece.model
> > * FNet-Large: https://huggingface.co/HJHGJGHHG/paddle-fnet-large/resolve/main/spiece.model
> > 
> > ### 2.model_state.pdparams
> > 
> > * FNet-Base: https://huggingface.co/HJHGJGHHG/paddle-fnet-base/resolve/main/model_state.pdparams
> > * FNet-Large: https://huggingface.co/HJHGJGHHG/paddle-fnet-large/resolve/main/model_state.pdparams
> 
> 可以提供百度网盘或者google_drive下载链接吗～

我重新上传一下~~

2022-01-10 15:39 UTC, HJHGJGHHG commented
已上传至百度网盘
链接：https://pan.baidu.com/s/1O-cnSmuu6pqBOQp0VNe6CA 
提取码：elnl

2022-01-11 03:05 UTC, yingyibiao approved these changes
LGTM

2022-01-11 03:05 UTC, merged