Fix token cls
PaddlePaddle/PaddleNLP pull request #1583
Opened 2022-01-12 09:54 UTC by joey12300

### PR types

Bug fixes
### PR changes

Models
### Description

Fix token cls batchify_fn bug

2022-01-12 11:07 UTC, ZeyuChen reviewed
这个算bug还是算通用的优化？是不是所有ernie模型训练都有这个没算batch 内最大值

2022-01-12 12:44 UTC, joey12300 commented
@ZeyuChen 目前是bug，之前faster tokenizer默认pad到最大长度，优化后这里报错了。这里逻辑还需要再改改，暂时先关闭了

2022-01-25 04:47 UTC, joey12300 commented
修改序列标注任务的组batch方法，使其生成的batch只pad到batch内最大长度。

2022-01-26 03:51 UTC, Steffy-zxf requested changes

2022-01-26 03:51 UTC, Steffy-zxf commented on examples/faster/faster_ernie/token_cls/train.py
>          if len(label) < max_seq_len:
应该是和batch_max_seq比较

2022-01-26 03:51 UTC, Steffy-zxf commented on examples/faster/faster_ernie/token_cls/train.py
> +            label += [ignore_label] * (batch_max_seq + 2 - len(label))
label长度已经是计算了cls sep长度范围内，无需加2

2022-01-26 05:04 UTC, joey12300 commented on examples/faster/faster_ernie/token_cls/train.py
> +            label += [ignore_label] * (batch_max_seq + 2 - len(label))
Done

2022-01-26 05:04 UTC, joey12300 commented on examples/faster/faster_ernie/token_cls/train.py
>          if len(label) < max_seq_len:
Done

2022-01-26 06:02 UTC, Steffy-zxf approved these changes
LGTM

2022-01-26 06:03 UTC, merged