Add model LUKE
PaddlePaddle/PaddleNLP pull request #1677
Opened 2022-02-15 03:24 UTC by Beacontownfc

Description
Add new model **LUKE**
paddle model weight has been uploaded, you can use LUKE like this:
`from paddlenlp.transformers import LukeModel
`
`model = LukeModel.from_pretrained('luke-base')`

2022-02-21 08:26 UTC, Steffy-zxf requested changes

2022-02-21 08:26 UTC, Steffy-zxf commented on examples/language_model/luke/create_squad_data.py
> +#encoding=utf8
目前PaddleNLP支持python3.6以上版本，无须指定编码

2022-02-21 08:26 UTC, Steffy-zxf commented on examples/language_model/luke/run_open_entity.py
> +# encoding=utf8
同上

2022-02-21 08:26 UTC, Steffy-zxf commented on examples/language_model/luke/run_open_entity.py
> +parser.add_argument("--output_dir", type=str, required=True)
args请天假每个argument的description

2022-02-21 08:26 UTC, Steffy-zxf commented on examples/language_model/luke/run_open_entity.py
> +args.tokenizer = LukeTokenizer.from_pretrained(args.model_type)
tokenizer一定要作为全局变量使用吗？

2022-02-21 08:26 UTC, Steffy-zxf commented on examples/language_model/luke/run_open_entity.py
> +
这个数据集多大？
不建议一次性将所有数据集加载进来，这样有可能造成占用内存溢出。
可以通过继承自`paddle.io.Dataset`, 以迭代的方式返回数据。

2022-02-21 08:26 UTC, Steffy-zxf commented on examples/language_model/luke/run_open_entity.py
> +        return (
给下注释，解释189 - 196 行代码的意义。

2022-02-21 08:26 UTC, Steffy-zxf commented on examples/language_model/luke/run_squad.py
> +        super(DataGenerator, self).__init__()
同上

2022-02-21 08:26 UTC, Steffy-zxf commented on examples/language_model/luke/run_squad.py
> +# encoding=utf8
同上

2022-02-21 08:26 UTC, Steffy-zxf commented on examples/language_model/luke/run_squad.py
> +    if not evaluate:
建议增加data file参数，控制加载的数据集。省去if-else的判断。

2022-02-21 08:26 UTC, Steffy-zxf commented on examples/language_model/luke/utils/reading_comprehension/dataset.py
> +    # def __init__(self, qas_id, title, question_text, context_text, answers, is_impossible=False):
删去无用注释

2022-02-21 15:36 UTC, Beacontownfc commented on examples/language_model/luke/create_squad_data.py
> +#encoding=utf8
Done

2022-02-21 15:36 UTC, Beacontownfc commented on examples/language_model/luke/run_open_entity.py
> +# encoding=utf8
Done

2022-02-21 15:36 UTC, Beacontownfc commented on examples/language_model/luke/run_open_entity.py
> +parser.add_argument("--output_dir", type=str, required=True)
Done

2022-02-21 15:36 UTC, Beacontownfc commented on examples/language_model/luke/run_open_entity.py
> +args.tokenizer = LukeTokenizer.from_pretrained(args.model_type)
已修改

2022-02-21 15:38 UTC, Beacontownfc commented on examples/language_model/luke/run_open_entity.py
> +
两个数据集，open_entity数据集不到1MB，SQuAD1.1数据集不到30MB.

2022-02-21 15:38 UTC, Beacontownfc commented on examples/language_model/luke/run_squad.py
> +        super(DataGenerator, self).__init__()
Done

2022-02-21 15:39 UTC, Beacontownfc commented on examples/language_model/luke/run_open_entity.py
> +        return (
已解释

2022-02-21 15:39 UTC, Beacontownfc commented on examples/language_model/luke/run_squad.py
> +# encoding=utf8
Done

2022-02-21 15:39 UTC, Beacontownfc commented on examples/language_model/luke/run_squad.py
> +    if not evaluate:
已修改

2022-02-21 15:39 UTC, Beacontownfc commented on examples/language_model/luke/utils/reading_comprehension/dataset.py
> +    # def __init__(self, qas_id, title, question_text, context_text, answers, is_impossible=False):
Done

2022-02-21 15:51 UTC, Beacontownfc commented on examples/language_model/luke/run_open_entity.py
> +
已根据您的建议修改

2022-02-24 07:57 UTC, Steffy-zxf requested changes

2022-02-24 07:57 UTC, Steffy-zxf commented on examples/language_model/luke/run_open_entity.py
> +def load_examples(args, fold="train"):
`fold`建议修改为`mode`

2022-02-24 07:57 UTC, Steffy-zxf commented on examples/language_model/luke/run_open_entity.py
> +    "--eval_batch_size",
建议统一用batch_size，不用区分`eval_batch_size` 和 `train_batch_size`

2022-02-24 07:57 UTC, Steffy-zxf commented on examples/language_model/luke/utils/feature.py
> +            exit()
192 - 194 行 代码作用？

2022-02-24 07:57 UTC, Steffy-zxf commented on examples/language_model/luke/utils/squad_processor.py
> +        is_training='train' in data_file)
以上参数是否还有简化的空间呢？可以看看是否有默认参数可以省去。目前API参数量太多了，可读性差。

2022-02-27 10:05 UTC, Beacontownfc commented on examples/language_model/luke/run_open_entity.py
> +    "--eval_batch_size",
已修改

2022-02-27 10:07 UTC, Beacontownfc commented on examples/language_model/luke/utils/feature.py
> +            exit()
此代码是LUKE模型作者提供的实体检测代码，我们使用他的代码检测实体，但在SQuAD1.1数据集上并没有检测到实体，我们已经把实体检测相关代码删除。

2022-02-27 10:07 UTC, Beacontownfc commented on examples/language_model/luke/utils/squad_processor.py
> +        is_training='train' in data_file)
代码已优化

2022-03-07 02:12 UTC, Steffy-zxf requested changes

2022-03-07 02:12 UTC, Steffy-zxf commented on examples/language_model/luke/run_squad.py
> +    #NOTE: Almost the same functionality as HuggingFace's prepare_train_features function. The main difference is
`# NOTE`

2022-03-07 02:12 UTC, Steffy-zxf commented on examples/language_model/luke/run_squad.py
> +    #NOTE: Almost the same functionality as HuggingFace's prepare_train_features function. The main difference is
`# NOTE:`

2022-03-07 02:12 UTC, Steffy-zxf commented on examples/language_model/luke/run_squad.py
> +            print("init checkpoint from %s" % args.model_name_or_path)
"Loads checkpoints from %s."

2022-03-07 02:12 UTC, Steffy-zxf commented on examples/language_model/luke/run_squad.py
> +                    attention_mask=attention_mask, )
去掉末尾逗号

2022-03-07 02:12 UTC, Steffy-zxf commented on examples/language_model/luke/run_squad.py
> +            "attention_mask": Pad(axis=0, pad_val=tokenizer.pad_token_type_id), }): fn(samples)
attention_mask是否一定需要传入指定吗？比如BERT可以根据pad token id确定是否attention_mask

2022-03-07 02:12 UTC, Steffy-zxf commented on examples/language_model/luke/trainer.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
这个trainer.py的作用是？似乎没看见用到。

2022-03-07 05:01 UTC, Beacontownfc commented on examples/language_model/luke/run_squad.py
> +    #NOTE: Almost the same functionality as HuggingFace's prepare_train_features function. The main difference is
已修改

2022-03-07 05:02 UTC, Beacontownfc commented on examples/language_model/luke/run_squad.py
> +    #NOTE: Almost the same functionality as HuggingFace's prepare_train_features function. The main difference is
Done

2022-03-07 05:02 UTC, Beacontownfc commented on examples/language_model/luke/run_squad.py
> +            print("init checkpoint from %s" % args.model_name_or_path)
Done

2022-03-07 05:02 UTC, Beacontownfc commented on examples/language_model/luke/run_squad.py
> +                    attention_mask=attention_mask, )
Done

2022-03-07 05:02 UTC, Beacontownfc commented on examples/language_model/luke/run_squad.py
> +            "attention_mask": Pad(axis=0, pad_val=tokenizer.pad_token_type_id), }): fn(samples)
无需指定，已删除attention_mask

2022-03-07 05:03 UTC, Beacontownfc commented on examples/language_model/luke/trainer.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
用于在open entity数据集上训练，我已将其与run_open_entity.py合并

2022-03-09 02:40 UTC, Steffy-zxf approved these changes

2022-03-10 04:44 UTC, merged