add Prohetnet model
PaddlePaddle/PaddleNLP pull request #1698
Opened 2022-02-21 10:25 UTC by d294270681

### Description
Add new model Prophetnet
The model weight:
链接：https://pan.baidu.com/s/1FOnd01rNvDJoONYegacq1Q
提取码：o28q
The tokenizer vocab file:
链接：https://pan.baidu.com/s/1pUxLy6eGTZFqzf85OlIzUg
提取码：ltp6

2022-02-28 05:47 UTC, smallv0221 requested changes
数据集读取的问题再看看，cnn_daliymail和gigaword数据集都可以通过load_dataset传入名称加载，不同点是前者是paddlenlp数据集，后者是HuggingFace数据集。但是访问和处理方式应该没什么差别

2022-02-28 05:47 UTC, smallv0221 commented on examples/text_summarization/prophetnet/README.md
> +    --warmup_updates=1000 \
用warmup_steps比较好

2022-02-28 05:47 UTC, smallv0221 commented on examples/text_summarization/prophetnet/generate.py
> +    test_dataset = load_dataset(
这里可以直接使用paddlenlp内置的cnn_daliymail数据集么

2022-02-28 05:47 UTC, smallv0221 commented on paddlenlp/transformers/prophetnet/tokenizer.py
> +class Trie:
这个trie在基类里有，应该不用重新定义吧

2022-02-28 05:47 UTC, smallv0221 commented on examples/text_summarization/prophetnet/train_prophetnet.py
> +train_dataset = load_dataset(
这里应该可以直接读内置的cnn_daliymail数据集，gigaword数据集在huggingface上也有，paddlenlp的load_dataset也可以读取HF的数据集

2022-02-28 05:49 UTC, smallv0221 commented
如果都能通过传入数据集名称直接加载，应该可以省略一些数据处理代码

2022-03-01 03:55 UTC, d294270681 commented on examples/text_summarization/prophetnet/README.md
> +    --warmup_updates=1000 \
已修改

2022-03-01 03:55 UTC, d294270681 commented on paddlenlp/transformers/prophetnet/tokenizer.py
> +class Trie:
已修改

2022-03-01 04:33 UTC, d294270681 commented on examples/text_summarization/prophetnet/generate.py
> +    test_dataset = load_dataset(
[源码](https://github.com/microsoft/ProphetNet/tree/master/GLGE_baselines)使用的是GLGE baseline的cnn_dailymail，和paddlenlp的cnn_daliymail有点区别，GLGE的文本会多个[S_SEP]标签，不知道会不会产生影响。

2022-03-01 06:54 UTC, smallv0221 commented on examples/text_summarization/prophetnet/generate.py
> +    test_dataset = load_dataset(
那GLGE baseline的这两个数据集和hugging face的这两个数据集一样么

2022-03-01 14:24 UTC, d294270681 commented on examples/text_summarization/prophetnet/generate.py
> +    test_dataset = load_dataset(
cnndm和gigaword都存在一些差别

2022-03-03 07:45 UTC, smallv0221 reviewed
example下的那个__init__.py去掉吧

2022-03-04 03:22 UTC, d294270681 commented
> example下的那个__init__.py去掉吧
已修改

2022-03-04 03:23 UTC, d294270681 commented
> example下的那个__init__.py去掉吧

已修改

2022-03-04 09:51 UTC, smallv0221 approved these changes
LGTM

2022-03-07 02:30 UTC, merged