Add model Rembert
PaddlePaddle/PaddleNLP pull request #1701
Opened 2022-02-22 14:00 UTC by Beacontownfc

Description
Add new model RemBert
The model weight:
链接：https://aistudio.baidu.com/aistudio/datasetdetail/129105

2022-04-08 11:40 UTC, gongel requested changes

2022-04-08 11:40 UTC, gongel commented on paddlenlp/transformers/rembert/tokenizer.py
> +        self.cls_token = cls_token
101-105行可以省略

2022-04-08 11:40 UTC, gongel commented on paddlenlp/transformers/rembert/modeling.py
> +        attention_probs = nn.Softmax(axis=-1)(attention_scores)
这里可以挪到__init__或者F.softmax

2022-04-08 11:40 UTC, gongel commented on paddlenlp/transformers/rembert/modeling.py
> +layer_norm_eps = 1e-12
这个可以尝试挪到config里面，便于配置

2022-04-08 11:40 UTC, gongel commented on paddlenlp/transformers/rembert/modeling.py
> +        self.loss_fn = nn.CrossEntropyLoss()
这个删掉吧

2022-04-08 11:41 UTC, gongel commented
感谢贡献，麻烦根据comment修改下哈😊 @Beacontownfc

2022-04-09 01:26 UTC, Beacontownfc commented on paddlenlp/transformers/rembert/tokenizer.py
> +        self.cls_token = cls_token
Done

2022-04-09 01:27 UTC, Beacontownfc commented on paddlenlp/transformers/rembert/modeling.py
> +        attention_probs = nn.Softmax(axis=-1)(attention_scores)
Done

2022-04-09 01:27 UTC, Beacontownfc commented on paddlenlp/transformers/rembert/modeling.py
> +layer_norm_eps = 1e-12
Done

2022-04-09 01:27 UTC, Beacontownfc commented on paddlenlp/transformers/rembert/modeling.py
> +        self.loss_fn = nn.CrossEntropyLoss()
Done

2022-04-09 01:28 UTC, Beacontownfc commented
已根据您的要求进行了修改 @gongel

2022-04-12 09:02 UTC, gongel approved these changes, later dismissed
LGTM

2022-04-12 11:28 UTC, Beacontownfc commented
@yingyibiao 一切OK，请求批准合入😊

2022-04-12 13:08 UTC, gongel commented
@Beacontownfc padding输入有问题，麻烦check一下哈
```python
import io
import os
import shutil
import importlib

import numpy as np
import paddle
import torch
import transformers as hfnlp
import paddlenlp
from paddlenlp.data import Pad
import paddlenlp.transformers as ppnlp

os.environ["TRANSFORMERS_CACHE"] = "./hf/"
os.environ["PPNLP_HOME"] = "./pdnlp/"


def compute_diff(torch_data, paddle_data):
	torch_data = torch_data.detach().numpy()
	paddle_data = paddle_data.numpy()
	out_dict = dict()
	diff = np.abs(torch_data - paddle_data)
	out_dict = "max: {}    mean: {}    min: {}".format(diff.max(), diff.mean(), diff.min())
	return out_dict


def compare_base(model_id):
	sentences = [
		"This is an example sentence.", 
		"Each sentence is converted .", 
		"欢迎使用 PaddlePaddle  。",
		"欢迎使用 PaddleNLP 。"
	]
	
	# Calculate HF output
	hf_tokenizer = hfnlp.RemBertTokenizer.from_pretrained('google/rembert') # google/rembert
	hf_model = hfnlp.RemBertModel.from_pretrained('google/rembert') # google/rembert
	hf_model.eval()
	with torch.no_grad():
		hf_inputs = hf_tokenizer(sentences, padding=True, return_tensors="pt")
		print(hf_inputs)
		hf_out = hf_model(**hf_inputs).last_hidden_state
	
	# Calculate Paddle output
	pd_tokenizer = ppnlp.RemBertTokenizer.from_pretrained('rembert')
	pd_model = ppnlp.RemBertModel.from_pretrained('rembert')
	pd_model.eval()
	with paddle.no_grad():
		pd_inputs = pd_tokenizer(sentences)
		input_ids = paddle.to_tensor(Pad(axis=0, pad_val=pd_tokenizer.pad_token_id)([pd_input for pd_input in pd_inputs["input_ids"]]))
		token_type_ids = paddle.to_tensor(Pad(axis=0, pad_val=pd_tokenizer.pad_token_type_id)([pd_input for pd_input in pd_inputs["token_type_ids"]]))
		print(input_ids)
		print(token_type_ids)
		pd_out = pd_model(input_ids, token_type_ids)[0]

	return compute_diff(hf_out, pd_out)

print(compare_base("rembert"))
```

2022-04-12 14:45 UTC, Beacontownfc commented
> ```python
> input_ids = paddle.to_tensor(Pad(axis=0, pad_val=pd_tokenizer.pad_token_id)([pd_input for pd_input in pd_inputs["input_ids"]]))
> ```

您好，这行代码
`input_ids = paddle.to_tensor(Pad(axis=0, pad_val=pd_tokenizer.pad_token_id)([pd_input for pd_input in pd_inputs["input_ids"]]))`
换成BertTokenizer运行也是出现报错，我认为此行代码应该改成这样
`input_ids = paddle.to_tensor( Pad(axis=0, pad_val=pd_tokenizer.pad_token_id)([pd_input["input_ids"] for pd_input in pd_inputs]))`
这样代码正常运行了

2022-04-13 03:33 UTC, gongel commented
请问你的paddlenlp是哪个版本呢？develop代码目前没问题

2022-04-14 07:10 UTC, gongel approved these changes

2022-04-14 08:36 UTC, merged

2022-06-08 02:42 UTC, gongel commented
@Beacontownfc 可以再适配一下[Auto](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/auto)哈