[DOC] Update GPT Readme
PaddlePaddle/PaddleNLP pull request #1718
Opened 2022-03-02 02:30 UTC by ZHUI

Update GPT Readme

### PR types

Others
### PR changes

Docs
### Description

Update GPT Readme

2022-03-02 03:28 UTC, ZeyuChen requested changes

2022-03-02 03:28 UTC, ZeyuChen commented on examples/language_model/gpt/README.md
> +然后使用[data_tools](../data_tools)工具下的`create_pretraining_data.py`脚本进行数据集制作。先安装一些依赖的安装包`pip install tqdm numpy pybind11 lac zstandard`，然后运行下面命令：
你这行代码跟你上面环境依赖那里是不是重复了？是否补充在上面的环境依赖即可？

2022-03-02 09:31 UTC, ZHUI commented on examples/language_model/gpt/README.md
> +然后使用[data_tools](../data_tools)工具下的`create_pretraining_data.py`脚本进行数据集制作。先安装一些依赖的安装包`pip install tqdm numpy pybind11 lac zstandard`，然后运行下面命令：
是的，已修改，补充到上面。

2022-03-04 01:06 UTC, ZeyuChen approved these changes

2022-03-04 01:06 UTC, merged