Add CLUE benchmark
PaddlePaddle/PaddleNLP pull request #1722
Opened 2022-03-03 03:55 UTC by w5688414

### PR types

New features

### PR changes

Others
### Description

Add CLUE benchmark

2022-03-03 04:13 UTC, tianxin1860 requested changes
先整体检查下，不要有无用的注释，例如注释掉的 print 代码

2022-03-03 04:13 UTC, tianxin1860 commented on examples/benchmark/clue/classification/data.py
> +    # print('预测的label标签为 {}'.format(out2.numpy()[0]))
先整体检查一下代码, 避免这种无用的注释。

2022-03-03 13:17 UTC, w5688414 commented on examples/benchmark/clue/classification/data.py
> +    # print('预测的label标签为 {}'.format(out2.numpy()[0]))
已修改

2022-03-03 14:55 UTC, ZeyuChen requested changes
改成AutoModle和AutoTokenizer，确认代码格式化工具有启用。注释如果可以全面英文化，以及选取关键点注释。不要在一些代码很简单的地方加注释。

2022-03-03 14:55 UTC, ZeyuChen commented on examples/benchmark/clue/classification/predict.py
> +    pretrained_model = ppnlp.transformers.ErnieGramModel.from_pretrained('ernie-gram-zh')
可否改为使用Auto

2022-03-03 14:55 UTC, ZeyuChen commented on examples/benchmark/clue/classification/predict.py
> +    model=WSCModel(pretrained_model,len(train_ds.label_list))
代码风格明显不正确，没有自动格式化吗？

2022-03-03 14:55 UTC, ZeyuChen commented on examples/benchmark/clue/classification/train.py
> +        #准确率更新
所有注释井号后面都要有空格，请全面改成英文注释。

2022-03-03 14:55 UTC, ZeyuChen commented on examples/benchmark/clue/classification/train.py
> +    pretrained_model = ppnlp.transformers.ErnieGramModel.from_pretrained(
改为AutoModel和AutoTokenizer

2022-03-03 14:55 UTC, ZeyuChen commented on examples/benchmark/clue/classification/train.py
> +    pretrained_model = ppnlp.transformers.ErnieGramModel.from_pretrained(
去掉ppnlp的import路径。
改成from paddlenlp import AutoTokenizer, AutoModel
然后这里直接使用AutoToknizer和AutoModel

2022-03-03 14:55 UTC, ZeyuChen commented on examples/benchmark/clue/mrc/train_c3.py
> +
这些无用的空行是符合规范的么？

2022-03-03 14:55 UTC, ZeyuChen commented on examples/benchmark/clue/mrc/train_mrc.py
> +
代码清洗下吧，怎么会有这些奇怪的空行呢，应该格式化工具会识别出来

2022-03-07 05:39 UTC, tianxin1860 reviewed
为什么需要针对不同的分类任务创建不同的 Model 类？所有分类任务共用 1 个类如何？

2022-03-07 05:39 UTC, tianxin1860 commented on examples/benchmark/clue/classification/model.py
> +class WSCModel(nn.Layer):
为什么 WSC 任务需要 1 个额外的 Model 类？

2022-03-07 05:39 UTC, tianxin1860 commented on examples/benchmark/clue/classification/model.py
> +class NLIModel(nn.Layer):
为什么 NLIModel 需要单独一个类来实现？

2022-03-07 05:39 UTC, tianxin1860 commented on examples/benchmark/clue/classification/model.py
> +                attention_mask=None):
为什么需要 LongTextClassification 和 ShortTextClassification 2 个类？

2022-03-08 07:38 UTC, w5688414 commented on examples/benchmark/clue/classification/predict.py
> +    pretrained_model = ppnlp.transformers.ErnieGramModel.from_pretrained('ernie-gram-zh')
已经修改

2022-03-08 07:46 UTC, w5688414 commented on examples/benchmark/clue/classification/train.py
> +    pretrained_model = ppnlp.transformers.ErnieGramModel.from_pretrained(
已经修改

2022-03-08 07:47 UTC, w5688414 commented on examples/benchmark/clue/mrc/train_c3.py
> +
已经修改

2022-03-08 07:48 UTC, w5688414 commented on examples/benchmark/clue/mrc/train_mrc.py
> +
已经修改

2022-03-08 08:19 UTC, w5688414 commented on examples/benchmark/clue/classification/model.py
> +                attention_mask=None):
这样写就可以针对每个任务进行修改，不然一修改，会把其他任务的模型给修改掉了

2022-03-08 08:19 UTC, w5688414 commented on examples/benchmark/clue/classification/model.py
> +class NLIModel(nn.Layer):
这样写就可以针对每个任务进行修改，不然一修改，会把其他任务的模型给修改掉了

2022-03-08 08:20 UTC, w5688414 commented on examples/benchmark/clue/classification/model.py
> +class WSCModel(nn.Layer):
这样写就可以针对每个任务进行修改，不然一修改，会把其他任务的模型给修改掉了

2022-03-08 08:45 UTC, w5688414 commented on examples/benchmark/clue/classification/train.py
> +        #准确率更新
已经修改

2022-03-15 09:01 UTC, closed without merging