Add clue benchmark for classification
PaddlePaddle/PaddleNLP pull request #1732
Opened 2022-03-07 07:21 UTC by LiuChiachi

### PR types

New features
### PR changes

Models
### Description

run_clue.py for classification

2022-03-15 02:58 UTC, tianxin1860 requested changes
README 逻辑建议稍微调整下：先展示评测结果，再教用户如何一件运行评测。

2022-03-15 02:58 UTC, tianxin1860 commented on examples/benchmark/clue/README.md
> +| CLUE Score            | AFMQC   | TNEWS   | IFLYTEK | CMNLI   | OCNLI   | CLUEWSC2020 | CSL     | CMRC2018 | CHID    | C3      |
CLUE Score -> 模型？更合适一些

2022-03-15 02:58 UTC, tianxin1860 commented on examples/benchmark/clue/README.md
> +
是否在这里先整体展示评测结果表格？表格下方描述清楚评测方式。然后再接快速开始教用户如何评测？

2022-03-16 03:16 UTC, LiuChiachi commented on examples/benchmark/clue/README.md
> +
感谢建议，已经修改:)

2022-03-16 03:16 UTC, LiuChiachi commented on examples/benchmark/clue/README.md
> +| CLUE Score            | AFMQC   | TNEWS   | IFLYTEK | CMNLI   | OCNLI   | CLUEWSC2020 | CSL     | CMRC2018 | CHID    | C3      |
Thanks， 已经修改了

2022-03-16 07:01 UTC, tianxin1860 reviewed
Leave some comments

2022-03-16 07:01 UTC, tianxin1860 commented on examples/benchmark/clue/README.md
> +本项目是 CLUE 评测任务 在 PaddlePaddle 2.0 上的开源实现。
本项目基于 PaddlePaddle 在 CLUE 数据集上对领先的开源预训练模型模型进行了充分评测，为开发者在预训练模型选择上提供参考，同时开发者基于本项目可以轻松一键复现模型效果，也可以参加 CLUE 竞赛取得好成绩。

2022-03-16 07:01 UTC, tianxin1860 commented on examples/benchmark/clue/README.md
> +是目前应用最广泛的中文语言测评指标之一，被包括阿里巴巴达摩院、腾讯 AI 实验室、华为诺亚方舟实验室在内的 20 多家国内语言实验室所采纳。学术引用 100+，github star 超 6000+。详细可参考 [CLUE论文](https://arxiv.org/abs/2004.05986)
`****是目前最广泛的语言评测指标之一。` 这句话之后的描述删掉吧。

2022-03-16 07:01 UTC, tianxin1860 commented on examples/benchmark/clue/README.md
> +## 整体结果
CLUE 评测结果

2022-03-16 07:01 UTC, tianxin1860 commented on examples/benchmark/clue/README.md
> +使用ERNIE 3.0 Base 和 RoBERTa-wwm-ext-large 进行 Fine-tuning，在 CLUE 的各验证集上有如下结果：
这些信息在表格里已经有体现，删掉吧。

2022-03-16 07:01 UTC, tianxin1860 commented on examples/benchmark/clue/README.md
> +1.上表所有模型的精度测试均是基于下方超参数范围进行的 Grid Search 超参寻优。在每个配置下训练时，每隔 100 个 steps 在验证集上评估一次，取验证集上最佳准确率作为当前超参数配置下的准确率；
**NOTE:具体评测方式如下**
1. 以上所有任务均基于 Grid Search 方式进行超参寻优，训练每间隔 100 steps 评估验证集效果，取验证集最优效果作为表格中的汇报指标。
2. Grid Search 超参范围:  batch_size: 16, 32, 64; learning rates: 1e-5, 2e-5, 3e-5, 5e-5
3. 因为 CLUEWSC2020 数据集效果对 batch_size 较为敏感，CLUEWSC2020 评测时额外增加了 batch_size = 8 的超参搜索。

2022-03-16 07:01 UTC, tianxin1860 commented on examples/benchmark/clue/README.md
> +## 快速开始
## 一键复现模型效果

2022-03-16 07:01 UTC, tianxin1860 commented on examples/benchmark/clue/README.md
> +## 快速开始
这一小节以 TNEWS 任务为例教用户怎样一键复现我们的评测结果

2022-03-16 07:01 UTC, tianxin1860 commented on examples/benchmark/clue/README.md
> +```
## 参加 CLUE 竞赛
这一小节教用户怎样做预测，生成符合 CLUE 榜单提交格式的预测结果就 OK

2022-03-17 07:18 UTC, ZeyuChen reviewed
去掉那部分logger的代码，改成paddlenlp自己的logger

2022-03-17 07:18 UTC, ZeyuChen commented on examples/benchmark/clue/classification/predict_clue_classifier.py
> +FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
我理解paddlenlp有统一的log，能去掉这部分代码吗？

2022-03-17 07:18 UTC, ZeyuChen commented on examples/benchmark/clue/classification/run_clue_classifier.py
> +FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
这个logger统一成paddlenlp的logger吧

2022-03-18 02:49 UTC, tianxin1860 approved these changes
LGTM

2022-03-18 02:50 UTC, LiuChiachi commented on examples/benchmark/clue/classification/predict_clue_classifier.py
> +FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
感谢，已经删掉

2022-03-18 02:51 UTC, merged