Add WR strategy
PaddlePaddle/PaddleNLP pull request #1747
Opened 2022-03-09 13:00 UTC by w5688414

### PR types

New features

### PR changes

Others

### Description

| 模型  | 策略| LCQMC | BQ_Corpus|STS-B|ATEC|
| ------- |-------|-------|-----|------|-----|
| ERNIE-1.0|Infer_with_fc| 52.33 | 43.75 | 66.66 | 29.78 |
| ERNIE-1.0|-| 57.01 | **51.72** | 74.76 | 33.56 |
| ERNIE-1.0|WR (word reptition)| **59.56** | 50.54 | **77.28** | **34.02** |

除此之外，在公开的英文数据集上做了 WR 策略的对比实验，实验结果如下：

| 策略| STS12  | STS13 | STS14 | STS15 | STS16 | STSBenchmark | SICKRelatedness | Avg |
|-------|-------|-----|------|-----|-----|-----|-----|-----|
|SimCSE| 68.46 | 81.90 | 71.57| 79.75 | 77.22 | 75.24 | 69.38 | 74.79 |
|+ WR | 66.95 | 80.68 | **72.58**| **82.26** | **78.13** | **76.77** | **69.51** | **75.27**|

2022-03-09 13:23 UTC, tianxin1860 requested changes
Leave some comments

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +本项目分别使用 LCQMC、BQ_Corpus、STS-B、ATEC 这 4 个中文语义匹配数据集的训练集作为无监督训练集(仅使用文本信息，不适用 Label)，并且在各自数据集上的验证集上进行效果评估，评估指标采用 SimCSE 论文中采用的 Spearman 相关系数，Spearman 相关系数越高，表示模型效果越好。
不适用 Label -> 不使用 Label

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
>  我们实现了 SimCSE 模型，并在 4 个常用中文语义匹配数据集上对 SimCSE 模型的无监督匹配效果进行了评测。SimCSE 模型适合缺乏监督数据，但是又有大量无监督数据的匹配和检索场景。
我们实现了 SimCSE 模型，并借鉴 ESimCSE 论文思想，通过 Word Repetition(WR) 策略进一步提升了 SimCSE 模型效果，在 4 个权威中文语义匹配数据集和 7 个权威英文语义匹配数据集上做了充分效果评测。SimCSE 模型适合缺乏监督数据，但是又有大量无监督数据的匹配和检索场景。

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> -| 模型  | Infer_with_fc| LCQMC | BQ_Corpus|STS-B|ATEC|
Infer_with_fc 这个不用在表格里体现了，直接对比 SimCSE 和 SimCSE + WR 的效果就行，训练代码默认把 Infer_with_fc 开关关掉，提示信息告诉用户关掉之后效果最好就行。

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
>  **Note**:
Infer_with_fc 的相关解释直接删掉

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +## 超参数设置
英文数据 Word Repetition 超参数配置补充一下

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
>  * `infer_with_fc_pooler`：可选，在预测阶段计算文本 embedding 表示的时候网络前向是否会过训练阶段最后一层的 fc;  建议打开模型效果最好。
建议打开模型效果最好 -> 关闭效果好吧？

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +* `user_word_reptition`: 可选，在训练阶段使用 word reptition策略，默认关闭。
默认打开吧，让用户默认就跑增强版本的 SimCSE, 拿到最优结果。

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +* `dup_rate`: 可选，word reptition 的比例，默认是0.32。
解释一下: 一般 Word Repetition 比例采用 0.32 模型效果最好。

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/data.py
> +        # if sequence length is less than 5, skip it
首字母大写

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/data.py
> +            # skip cls and sep position
同上

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/data.py
> +            # insert duplicate word
同上

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/data.py
> +    # padding the data to the same length
同上

2022-03-09 13:23 UTC, tianxin1860 commented on examples/text_matching/simcse/train.py
> +parser.add_argument("--user_word_reptition", action='store_true', help="Whether use word reptition strategy.")
需要 2 个参数吗？dup_rate > 0.0 的时候打开 WR 策略，否则关闭如何？

2022-03-10 08:07 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +本项目分别使用 LCQMC、BQ_Corpus、STS-B、ATEC 这 4 个中文语义匹配数据集的训练集作为无监督训练集(仅使用文本信息，不适用 Label)，并且在各自数据集上的验证集上进行效果评估，评估指标采用 SimCSE 论文中采用的 Spearman 相关系数，Spearman 相关系数越高，表示模型效果越好。
Done

2022-03-10 08:07 UTC, w5688414 commented on examples/text_matching/simcse/README.md
>  我们实现了 SimCSE 模型，并在 4 个常用中文语义匹配数据集上对 SimCSE 模型的无监督匹配效果进行了评测。SimCSE 模型适合缺乏监督数据，但是又有大量无监督数据的匹配和检索场景。
Done

2022-03-10 08:08 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> -| 模型  | Infer_with_fc| LCQMC | BQ_Corpus|STS-B|ATEC|
Done

2022-03-10 08:09 UTC, w5688414 commented on examples/text_matching/simcse/README.md
>  **Note**:
Done

2022-03-10 08:14 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +## 超参数设置
Done

2022-03-10 08:18 UTC, w5688414 commented on examples/text_matching/simcse/data.py
> +        # if sequence length is less than 5, skip it
Done

2022-03-10 08:18 UTC, w5688414 commented on examples/text_matching/simcse/data.py
> +            # skip cls and sep position
Done

2022-03-10 08:18 UTC, w5688414 commented on examples/text_matching/simcse/data.py
> +            # insert duplicate word
Done

2022-03-10 08:18 UTC, w5688414 commented on examples/text_matching/simcse/data.py
> +    # padding the data to the same length
Done

2022-03-10 08:19 UTC, w5688414 commented on examples/text_matching/simcse/train.py
> +parser.add_argument("--user_word_reptition", action='store_true', help="Whether use word reptition strategy.")
Done

2022-03-10 10:12 UTC, tianxin1860 reviewed
Leave some comments

2022-03-10 10:12 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +| ERNIE-1.0|-| 57.01 | **51.72** | 74.76 | 33.56 |
策略那一列删掉，只用模型这一列。第一行 SimCSE， 第二行 SimCSE + WR

2022-03-10 10:12 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +中文数据集训练的超参数设置如下：
SimCSE + WR 策略在中文数据集训练的超参数设置如下：

2022-03-10 10:12 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +| 策略| 数据集|epoch | learning rate | dropout| dup rate|
策略这一列删掉

2022-03-10 10:12 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +| 策略| STS12  | STS13 | STS14 | STS15 | STS16 | STSBenchmark | SICKRelatedness | Avg |
1. 策略 -> 模型；第2行: SimCSE 第3行: SimCSE + WR

2022-03-10 10:12 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +英文数据集的训练超参数配置如下：
SimCSE + WR 策略在英文数据集的训练超参数配置如下：

2022-03-10 10:12 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +| 策略| 数据集|epoch | learning rate | batch size| max_seq_length|dup rate|
策略这一列删掉

2022-03-10 10:22 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +英文数据集的训练超参数配置如下：
Done

2022-03-10 10:22 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +| 策略| 数据集|epoch | learning rate | batch size| max_seq_length|dup rate|
Done

2022-03-10 10:23 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +| 策略| STS12  | STS13 | STS14 | STS15 | STS16 | STSBenchmark | SICKRelatedness | Avg |
Done

2022-03-10 10:24 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +| 策略| 数据集|epoch | learning rate | dropout| dup rate|
Done

2022-03-10 10:27 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +中文数据集训练的超参数设置如下：
Done

2022-03-10 10:30 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +| ERNIE-1.0|-| 57.01 | **51.72** | 74.76 | 33.56 |
Done

2022-03-10 10:32 UTC, w5688414 commented on examples/text_matching/simcse/README.md
>  * `infer_with_fc_pooler`：可选，在预测阶段计算文本 embedding 表示的时候网络前向是否会过训练阶段最后一层的 fc;  建议打开模型效果最好。
Done

2022-03-10 10:32 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +* `user_word_reptition`: 可选，在训练阶段使用 word reptition策略，默认关闭。
Done

2022-03-10 10:32 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +* `dup_rate`: 可选，word reptition 的比例，默认是0.32。
Done

2022-03-10 11:29 UTC, tianxin1860 reviewed
Leave some comments

2022-03-10 11:29 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +| 数据集|epoch | learning rate | dropout| dup rate|
超参这里为什么没有 batch_size ?

2022-03-10 11:29 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +| 数据集|epoch | learning rate | batch size| max_seq_length|dup rate|
超参这里丢了 dropout ?

2022-03-10 11:35 UTC, tianxin1860 reviewed
是否整体提供下中文语义匹配数据下载地址和英文语义匹配数据下载地址？

2022-03-10 11:35 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> -| ERNIE-1.0|否| 57.01 | 51.72 | 74.76 | 33.56 |
补充一行: 中文语义匹配数据集效果

2022-03-10 11:35 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +除此之外，在公开的英文数据集上做了 WR 策略的对比实验，实验结果如下：
英文语义匹配数据集效果

2022-03-10 11:35 UTC, tianxin1860 commented on examples/text_matching/simcse/README.md
> +|wiki1m|1| 3E-5 | 64 |32| 0.32 |
wiki1m 数据集加上下载超链吧

2022-03-11 05:51 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +| 数据集|epoch | learning rate | batch size| max_seq_length|dup rate|
原版的simcse没有显式的设置dropout，用的是encoder里面的dropout

2022-03-11 05:57 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +| 数据集|epoch | learning rate | dropout| dup rate|
Done

2022-03-11 05:58 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +|wiki1m|1| 3E-5 | 64 |32| 0.32 |
Done

2022-03-11 06:01 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> -| ERNIE-1.0|否| 57.01 | 51.72 | 74.76 | 33.56 |
Done

2022-03-11 06:02 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +除此之外，在公开的英文数据集上做了 WR 策略的对比实验，实验结果如下：
Done

2022-03-11 08:27 UTC, w5688414 commented on examples/text_matching/simcse/README.md
> +|wiki1m|1| 3E-5 | 64 |32| 0.32 |
英文的结果是在原版的simcse上评估的

2022-03-11 08:59 UTC, tianxin1860 approved these changes
LGTM

2022-03-11 11:33 UTC, merged