Add RocketQA ranking model
PaddlePaddle/PaddleNLP pull request #1783
Opened 2022-03-17 08:23 UTC by LiuChiachi

### PR types

New features
### PR changes

APIs
### Description

Add RocketQA ranking model

2022-03-18 14:54 UTC, ZeyuChen approved these changes, later dismissed
LGTM

2022-03-19 07:03 UTC, tianxin1860 requested changes
排序模型静态图、动态图精度对齐数据可以贴一下。

2022-03-22 03:04 UTC, tianxin1860 requested changes
召回和排序都放在这个目录下的话，目录命名改成 semantic_search 更合适一些。

2022-03-22 03:04 UTC, tianxin1860 commented on paddlenlp/transformers/semantic_indexing/modeling.py
> +class ErnieForRanking(ErniePretrainedModel):
为什么需要再独立出来 1 个 ErnieForRanking 这个类？而不是统一对外就 1 个类 ErnieCrossEncoder ?

2022-03-22 03:04 UTC, tianxin1860 commented on paddlenlp/transformers/semantic_indexing/modeling.py
> +            inputs = tokenizer("Welcome to use PaddlePaddle and PaddleNLP!")
CrossEncoder 的输入是一个句对，然后模型对句对进行二分类输出概率分布。

2022-03-22 03:04 UTC, tianxin1860 commented on paddlenlp/transformers/semantic_indexing/modeling.py
> +    def get_pooled_output(self,
cross_encoder 我理解没有抽取向量的需求，用户输入 文本 pair, 模型走前向返回相似概率数值就可以了。

2022-03-22 03:04 UTC, tianxin1860 commented on paddlenlp/transformers/semantic_indexing/modeling.py
> +    def get_pooled_output(self,
1. 函数命名参考 RocketQA 接口命名: matching
2. 返回值: 文本对的相似概率值，不用返回 2 分类概率分布。

2022-03-22 04:06 UTC, LiuChiachi commented on paddlenlp/transformers/semantic_indexing/modeling.py
> +class ErnieForRanking(ErniePretrainedModel):
现在只对外暴露`ErnieCrossEncoder`。不过去掉` ErnieForRanking `保留一个类也可以，不过这样`ErnieCrossEncoder`需要继承`ErniePretrainedModel`，初始化需要`.from_pretrained(model_name)`，不再是直接调`__init__(model_name)`，写法和用法都会和召回模型不一样。

2022-03-22 05:34 UTC, LiuChiachi commented on paddlenlp/transformers/semantic_indexing/modeling.py
> +class ErnieForRanking(ErniePretrainedModel):
感谢提醒，对`ErnieEncoder`进行了修改，2个Encoder都借助这一个中间类即可

2022-03-22 05:34 UTC, LiuChiachi commented on paddlenlp/transformers/semantic_indexing/modeling.py
> +            inputs = tokenizer("Welcome to use PaddlePaddle and PaddleNLP!")
Thanks. 接口和示例代码均已修改

2022-03-22 05:35 UTC, LiuChiachi commented on paddlenlp/transformers/semantic_indexing/modeling.py
> +    def get_pooled_output(self,
Thanks. 接口和示例代码均已修改，和rocketqa一致。

2022-03-22 05:35 UTC, LiuChiachi commented on paddlenlp/transformers/semantic_indexing/modeling.py
> +    def get_pooled_output(self,
Thanks. 接口和示例代码均已修改，和rocketqa一致。

2022-03-22 05:36 UTC, LiuChiachi commented on paddlenlp/transformers/semantic_search/modeling.py
> +                 return_prob_distributation=False):
this argument is for training

2022-03-22 06:42 UTC, tianxin1860 approved these changes
LGTM

2022-03-22 06:43 UTC, merged