Add faq solution
PaddlePaddle/PaddleNLP pull request #1785
Opened 2022-03-17 09:22 UTC by w5688414

### PR types

New features 

### PR changes

Others

### Description

|  模型 |  Recall@1 | Recall@5 |Recall@10 |
| ------------ | ------------ | ------------ |--------- |
|  SimCSE |  81.882	 | 94.094| 96.296|
|  SimCSE + WR |  84.785 | 95.896| 97.197|

2022-03-17 11:26 UTC, tianxin1860 reviewed
现在整体看系统结构上还有个 Bug: 不能停留在返回用户输入 Query 的相似 Query 就结束，得把标准问的标准答案返回给用户，这里需要考虑 QA 对的存储用什么比较合适，最简单的可以先基于 Python 字典形式加载 4000 QA 对进内存，功能先做完整。 二期我们再评估是否基于 Redis 或者其它存储做 QA 对的存储后端。

2022-03-17 11:26 UTC, tianxin1860 commented on applications/question_answering/faq_system/README.md
> +* [1. 背景介绍](#场景概述)
统一标题: 场景概述

2022-03-17 11:26 UTC, tianxin1860 commented on applications/question_answering/faq_system/README.md
> +# 端到端政务问答
政务问答检索式 FAQ System

2022-03-17 11:26 UTC, tianxin1860 commented on applications/question_answering/faq_system/README.md
> +    + 手把手搭建起检索系统
手把手搭建检索式 FAQ System

2022-03-17 11:26 UTC, tianxin1860 commented on applications/question_answering/faq_system/README.md
> +    + 无需标注数据也能构建检索系统
无需相似 Query-Query Pair 标注数据也能构建 FAQ System

2022-03-17 11:26 UTC, tianxin1860 commented on applications/question_answering/faq_system/README.md
> +	+ 问答场景预训练模型：RocketQA 预训练模型
业界领先的检索预训练模型: RocketQA DualEncoder。

2022-03-17 11:26 UTC, tianxin1860 commented on applications/question_answering/faq_system/README.md
> +    + 针对无标注数据场景的端到端专业方案
针对无标注数据场景的领先解决方案: 检索预训练模型 + 增强的无监督语义索引微调

2022-03-17 11:26 UTC, tianxin1860 commented on applications/question_answering/faq_system/README.md
> +**语义索引**：由于我们只有无监督数据，所以结合 SimCSE 和 WR (word reptition)策略的方式训练一个不错的语义索引模型。
逻辑不对，我们是专门针对无监督这个最高频的场景需求提供无监督的解决方案，而不是因为我们只有无监督数据。

2022-03-17 11:26 UTC, tianxin1860 commented on applications/question_answering/faq_system/README.md
> +
这里一句话概括执行 export_to_serving.py 这个脚本是在做什么事情

2022-03-18 05:52 UTC, w5688414 commented on applications/question_answering/faq_system/README.md
> +* [1. 背景介绍](#场景概述)
Done

2022-03-18 05:53 UTC, w5688414 commented on applications/question_answering/faq_system/README.md
> +# 端到端政务问答
Done

2022-03-18 05:54 UTC, w5688414 commented on applications/question_answering/faq_system/README.md
> +    + 无需标注数据也能构建检索系统
Done

2022-03-18 05:54 UTC, w5688414 commented on applications/question_answering/faq_system/README.md
> +    + 手把手搭建起检索系统
Done

2022-03-18 05:54 UTC, w5688414 commented on applications/question_answering/faq_system/README.md
> +    + 针对无标注数据场景的端到端专业方案
Done

2022-03-18 05:54 UTC, w5688414 commented on applications/question_answering/faq_system/README.md
> +	+ 问答场景预训练模型：RocketQA 预训练模型
Done

2022-03-18 06:02 UTC, w5688414 commented on applications/question_answering/faq_system/README.md
> +**语义索引**：由于我们只有无监督数据，所以结合 SimCSE 和 WR (word reptition)策略的方式训练一个不错的语义索引模型。
Done

2022-03-18 07:56 UTC, w5688414 commented on applications/question_answering/faq_system/README.md
> +
Done

2022-03-23 08:14 UTC, tianxin1860 requested changes
1.方案指标需要更新。
2.测试数据构造方式和 PPT 讲的内容保持一致。

2022-03-23 08:14 UTC, tianxin1860 commented on applications/question_answering/faq_system/README.md
> +|  SimCSE + WR |  84.785 | 95.896| 97.197|
指标按照 PPT 上终版效果更新一下

2022-03-23 08:14 UTC, tianxin1860 commented on applications/question_answering/faq_system/README.md
> +其中评估集的问题对的构造使用了中英文回译的方法，使用的是百度翻译的API，详情请参考[百度翻译](https://fanyi-api.baidu.com/?fr=simultaneous)
数据构造方式和 PPT 讲内容的对应起来

2022-03-23 10:50 UTC, w5688414 commented on applications/question_answering/faq_system/README.md
> +|  SimCSE + WR |  84.785 | 95.896| 97.197|
Done

2022-03-23 11:17 UTC, w5688414 commented on applications/question_answering/faq_system/README.md
> +其中评估集的问题对的构造使用了中英文回译的方法，使用的是百度翻译的API，详情请参考[百度翻译](https://fanyi-api.baidu.com/?fr=simultaneous)
Done

2022-03-23 11:23 UTC, tianxin1860 approved these changes
LGTM

2022-03-23 13:26 UTC, merged