【Hackathon No.77】基于ERNIE_DOC完成长文本分类任务
PaddlePaddle/PaddleNLP pull request #1845
Opened 2022-03-28 09:09 UTC by zche4846

### PR types

Example writing
### PR changes

Models
### Description

基于 examples/language_model/ernie_doc 编写，针对动转静问题修改了部分方法名称，将memories的数据类型从list转为tensor用以实现动转静。
完成训练，预测，和动转静样例撰写。

2022-03-28 09:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=1845) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=1845) before we can accept your contribution.<br/><hr/>**zihaocheng** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=1845) it.</sub>

2022-05-06 09:40 UTC, joey12300 requested changes

2022-05-06 09:40 UTC, joey12300 commented on examples/text_classification/ernie_doc/export_model.py
> +    trainer_num = paddle.distributed.get_world_size()
导出模型不需要使用分布式，这里可以删掉。

2022-05-06 09:40 UTC, joey12300 commented on examples/text_classification/ernie_doc/export_model.py
> +        os.system("rm -r {}".format(args.static_path))
注意windows兼容性问题。可以使用`shutil. rmtree()`删除目录

2022-05-06 09:40 UTC, joey12300 commented on examples/text_classification/ernie_doc/modeling.py
> +    def forward(self, enc_input, memories, rel_pos, rel_task, attn_mask):
注释memories的shape

2022-05-06 09:40 UTC, joey12300 commented on examples/text_classification/ernie_doc/modeling.py
> +            memories (List[Tensor]):
修改memories的注释，描述其shape

2022-05-06 09:40 UTC, joey12300 commented on examples/text_classification/ernie_doc/predict.py
> +import os
这个放到版权信息下面，其余文件有类似的都改一下

2022-05-06 09:40 UTC, joey12300 commented on examples/text_classification/ernie_doc/predict.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
2021->2022，其余文件都相应改一下

2022-05-06 09:40 UTC, joey12300 commented on examples/text_classification/ernie_doc/predict.py
> +            with dygraph_mode_guard():
这个可以去掉

2022-05-06 09:40 UTC, joey12300 commented on examples/text_classification/ernie_doc/predict.py
> +        create_memory = partial(init_memory, self.batch_size, self.memory_len,
在预测脚本中，可以专门写一个numpy版本的`init_memory`，避免后面在预测喂入数据时，调用tensor.numpy()接口

2022-06-07 07:50 UTC, zche4846 commented on examples/text_classification/ernie_doc/predict.py
> +        create_memory = partial(init_memory, self.batch_size, self.memory_len,
感谢review，sorry，很久没有看这个项目了，我会尽快修改。🙏

2022-06-09 01:23 UTC, zche4846 commented on examples/text_classification/ernie_doc/predict.py
> +        create_memory = partial(init_memory, self.batch_size, self.memory_len,
已经都改好了，希望有时间可以再review一下

2022-06-09 02:15 UTC, joey12300 approved these changes
LGTM

2022-06-09 02:16 UTC, joey12300 commented on examples/text_classification/ernie_doc/predict.py
> +        create_memory = partial(init_memory, self.batch_size, self.memory_len,
> 已经都改好了，希望有时间可以再review一下

OK 没问题了，可以合入 👍

2022-06-09 06:55 UTC, merged