Add the checkpoint for the pretrained model
PaddlePaddle/PaddleNLP pull request #195
Opened 2021-03-26 06:23 UTC by wawltor

### PR types
 New features

### PR changes
APIs
### Describe
Add the checkpoint for the pretrained model, those state will load from the checkpoint 
1)   optimizer state 
2)  learning_rate message 
3)  random state 
4)  global_step & checkpoint_time 
5)  training arguments

2021-03-26 16:19 UTC, ZeyuChen requested changes
Need further discussion, seems not so natural.

2021-03-26 16:19 UTC, ZeyuChen commented on examples/language_model/bert/run_pretrain.py
> +                        checkpoint.save_checkpoint(output_dir, global_step,
checkpoint.save_checkpoint的动作语义就不太自然
应该是model.save_checkpoint比较合理，理想的语义是代码即注释。

2021-03-26 16:19 UTC, ZeyuChen commented on paddlenlp/utils/checkpoint.py
> +# coding:utf-8
总感觉单独的checkpoint设计，脱离Trainer的考虑不是特别自然

2021-03-26 16:19 UTC, ZeyuChen commented on examples/language_model/bert/run_pretrain.py
> +                        checkpoint.save_checkpoint(output_dir, global_step,
感觉这里的搭配用法非常奇怪，既要model_to_save, 又要checkpoint.save

2021-03-27 01:25 UTC, wawltor commented on examples/language_model/bert/run_pretrain.py
> +                        checkpoint.save_checkpoint(output_dir, global_step,
这里的checkpoint主要是checkpoint optimizer和learning_rate，random相关状态

2021-03-27 01:25 UTC, wawltor commented on paddlenlp/utils/checkpoint.py
> +# coding:utf-8
这里的checkpoint主要是checkpoint optimizer和learning_rate，random相关状态

2021-04-23 15:18 UTC, closed without merging