Add ONNX Export
PaddlePaddle/PaddleNLP pull request #2061
Opened 2022-05-05 08:45 UTC by wjj19950828

### PR types

New features

### PR changes

Others

### Description

Add ONNX model export option

2022-05-05 08:50 UTC, jiangjiajun requested changes

2022-05-05 08:50 UTC, jiangjiajun commented on paddlenlp/trainer/trainer_base.py
> +            export_model_format (Optional[str], optional): Export model format. Defaults to Paddle.
注释写清楚有哪些可选项

2022-05-05 08:50 UTC, jiangjiajun commented on paddlenlp/trainer/trainer_base.py
> +            logger.info("ONNX model exported.")
处理else的情况，给出明确的提示

2022-05-05 08:52 UTC, ZHUI commented on paddlenlp/trainer/trainer_base.py
> +                     export_model_format: Optional[str]="Paddle"):
`export_model_format` 建议小写，内部处理的时候，再统一转一下小写。
```python
export_model_format = export_model_format.lower()
```

2022-05-05 09:10 UTC, wjj19950828 commented on paddlenlp/trainer/trainer_base.py
> +            export_model_format (Optional[str], optional): Export model format. Defaults to Paddle.
Done.

2022-05-05 09:10 UTC, wjj19950828 commented on paddlenlp/trainer/trainer_base.py
> +            logger.info("ONNX model exported.")
Done.

2022-05-05 09:10 UTC, wjj19950828 commented on paddlenlp/trainer/trainer_base.py
> +                     export_model_format: Optional[str]="Paddle"):
Done.

2022-05-05 10:00 UTC, ZHUI submitted a review, later dismissed
LGTM

2022-05-05 10:38 UTC, jiangjiajun approved these changes, later dismissed

2022-05-05 15:29 UTC, ZeyuChen reviewed
似乎没看见在requirements中新增paddle2onnx依赖

2022-05-05 15:29 UTC, ZeyuChen commented on paddlenlp/trainer/trainer_base.py
> +                     export_model_format: Optional[str]="paddle"):
export_model_format -> model_format
因为函数已经表示当作export，参数变量更多是修饰这个动作即可。

2022-05-06 02:36 UTC, wjj19950828 commented on paddlenlp/trainer/trainer_base.py
> +                     export_model_format: Optional[str]="paddle"):
Done.并在requirements中新增paddle2onnx依赖

2022-05-06 05:10 UTC, ZeyuChen approved these changes

2022-05-06 05:10 UTC, merged