Ernie3.0 python deploy dev
PaddlePaddle/PaddleNLP pull request #2077
Opened 2022-05-07 16:13 UTC by yeliang2258

### PR types

Performance optimization

### PR changes

Others

### Description

Ernie3.0 python deploy script

2022-05-08 15:31 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/python/README.md
> +# Ernie-3.0 Python部署说明
新增deploy层级

2022-05-08 15:31 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/python/README.md
> +- paddle2onnx develop版本
到时paddlenlp内置paddle2onnx，务必确保正式版本匹配，所以不用增加这一项。

2022-05-08 15:31 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/python/README.md
> +python infer.py --model_path tnews/pruned_fp32/float32 --device ‘cpu’
cpu这里的符号全半角有问题
--device ‘cpu’ -> --device 'cpu'

2022-05-08 15:31 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/python/infer.py
> +# C#opyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
Copyright有Typo

2022-05-08 15:31 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/python/infer_backend.py
> +# C#opyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
Typo

2022-05-08 15:31 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/python/infer.py
> +    batchify_fn = lambda samples, fn=Tuple(
与liqi讨论，需要换成非batchify function的版本

2022-05-09 09:07 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/python/README.md
> +# Ernie-3.0 Python部署说明
Done

2022-05-09 09:07 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/python/README.md
> +- paddle2onnx develop版本
Done

2022-05-09 09:07 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/python/README.md
> +python infer.py --model_path tnews/pruned_fp32/float32 --device ‘cpu’
Done

2022-05-09 09:07 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/python/infer.py
> +# C#opyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
Done

2022-05-09 09:07 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/python/infer_backend.py
> +# C#opyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
Done

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +# Ernie-3.0 Python部署指南
ERNIE 3.0
无横杆

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +Ernie-3.0的部署分为cpu和gpu两种情况，请根据你的部署环境安装对应的依赖。
ERNIE 3.0
cpu -> CPU
gpu -> GPU

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +Ernie-3.0的部署分为cpu和gpu两种情况，请根据你的部署环境安装对应的依赖。
大小写要保持一致

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +pip install -r requirement_gpu.txt
requirements_cpu.txt
requirements_gpu.txt

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +pip install -r requirement_gpu.txt
带s

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +在计算能力大于7.0的GPU硬件上，比如T4，如需FP16或者Int8量化推理加速，还需安装TensorRT和PaddleInference-TRT，具体硬件和精度支持情况请参考：[GPU算力和支持精度对照表](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-840-ea/support-matrix/index.h
计算能力（Compute Capability）

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +|--enable_fp16 | 是否使用FP16进行加速 |
use_fp16

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +|--batch_size |测试的batch size大小|
注意上下一致，没有默认值？

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +|--enable_quantize | 是否启动ONNX FP32的动态量化进行加速 |
不用露出ONNX，
是否启动ONNX FP32的动态量化进行加速->是否使用动态量化进行加速

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +|--task_name | 配置任务名称，默认tnews|
还有什么其他选项呢？换其他选项也能跑通吗？

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +        if args.collect_shape:
补充一些注释

2022-05-10 11:56 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +            args.num_threads = 10
设置为自动根据当前硬件的核数，进行加速

2022-05-10 12:49 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +|--enable_quantize | 是否启动ONNX FP32的动态量化进行加速 |
Done

2022-05-10 12:49 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +|--batch_size |测试的batch size大小|
Done

2022-05-10 12:49 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +在计算能力大于7.0的GPU硬件上，比如T4，如需FP16或者Int8量化推理加速，还需安装TensorRT和PaddleInference-TRT，具体硬件和精度支持情况请参考：[GPU算力和支持精度对照表](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-840-ea/support-matrix/index.h
Done

2022-05-10 12:49 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +pip install -r requirement_gpu.txt
Done

2022-05-10 12:49 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +Ernie-3.0的部署分为cpu和gpu两种情况，请根据你的部署环境安装对应的依赖。
Done

2022-05-10 12:50 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +# Ernie-3.0 Python部署指南
Done

2022-05-10 12:50 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +|--enable_fp16 | 是否使用FP16进行加速 |
Done

2022-05-11 13:04 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +        if args.collect_shape:
Done

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +# Ernie3.0 Python部署指南
Ernie3.0 -> ERNIE 3.0 Python部署

全局的Ernie 3.0 -> ERNIE 3.0

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +在进行GPU部署之前请先确保机器已经安装好CUDA11.04和CUDNN8.2+，然后请使用如下指令安装所需依赖
CUDA >= 11.04, cuDNN >= 8.2

注意专业术语的标准大小写形式

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +如果在支持avx512_vnni的CPU机器上，比如Intel(R) Xeon(R) Gold 6271C或11代CPU以上机器，可开启enable_quantize开关，无需数据便可对FP32模型进行量化，获得1到2倍的加速效果，具体部署指令如下
```
**Note**：在支持avx512_vnni指令集或Intel® DL Boost的CPU设备上，可开启enable_quantize开关对FP32模型进行动态量化以获得更高的推理性能，加速性能相比如下表所示：

```

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +|--num_threads | 配置cpu的线程数，默认为cpu的最大线程数 |
将上述的Note放在这个位置，并提供数据表格支撑

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +|--collect_shape | 配置是否自动配置TensorRT的dynamic shape，开启enable_fp16或者进行int8量化推理时需要先开启此选项进行dynamic shape配置，生成shapeinfo.txt后再关闭，默认关闭 |
全局讲enable_fp16统一为use_fp16 保持统一，不要一下子use一下子enable

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +python infer_gpu.py --task_name tnews --model_path ./quantize_model/int8
确定下GPU的量化部署是否需要分成两步走，第一步Dump Shape？

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +        print(">>> [InferBackend] creat engine ...")
creat -> Creating Engine...

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +                assert device == 'gpu', "When use_fp16, please set device to gpu and install requirement_gpu.txt."
requirements_gpu.txt

全局日志修改下，这里少了s

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +        exe = fluid.Executor(fluid.CPUPlace())
是否可以改成非fluid的代码
采用paddle.static.Exuctor, 消除下fluid. @jiangjiajun

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +             fetch_vars] = fluid.io.load_inference_model(model_dir, exe)
使用paddle.static 下的API

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +             fetch_vars] = fluid.io.load_inference_model(
使用paddle.static下的APi

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +                      paddle.fluid.core_avx.PaddleInferPredictor):
为什么需要这个判断？

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +                input_ids, segment_ids, label = batchify_fn(batch)
逐渐替换为非batchify版本

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/infer_cpu.py
> +#Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
这里的井号后面要有一个空格

2022-05-11 15:15 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/infer_cpu.py
> +    batchify_fn = lambda samples, fn=Tuple(
后面需要替换为非batchify_fn版本，使用tokenizer版本

2022-05-11 15:32 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +                      paddle.fluid.core_avx.PaddleInferPredictor):
因为这里有两种predictor，onnxruntime和paddleinference

2022-05-12 08:56 UTC, jiangjiajun requested changes

2022-05-12 08:56 UTC, jiangjiajun commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +在计算能力（Compute Capability）大于7.0的GPU硬件上，比如T4，如需FP16或者Int8量化推理加速，还需安装TensorRT和PaddleInference-TRT，计算能力（Compute Capability）和精度支持情况请参考：[GPU算力和支持精度对照表](https://docs.nvidia.com/deeplearning/tensorrt/archive
PaddleInference-TRT改成Paddle Inference

2022-05-12 08:56 UTC, jiangjiajun commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +    (1)下载TensorRT8.4版本,文件名TensorRT-XXX.tar.gz，[下载链接](https://developer.nvidia.com/tensorrt)
Paddle Inference目前只适配了8.2

2022-05-12 08:56 UTC, jiangjiajun commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +    (2)使用pip install安装下载好的PaddleInference-TRT安装包
这里只考虑了Linux，Windows上的下载地址，以及环境变量tensorrt的安装都不同

2022-05-12 08:56 UTC, jiangjiajun commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +    (1)下载对应版本的PaddleInference-TRT，[PaddleInference-TRT下载路径](https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python)
下载对应cuda环境，python版本的Paddle Inference预测库包。 其中注意须下载支持tensort的预测包，如`linux-cuda11.2-cudnn8.2-trt8-gcc8.2`

2022-05-12 09:01 UTC, jiangjiajun requested changes

2022-05-12 09:01 UTC, jiangjiajun commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +            float_onnx_file = "model.onnx"
这里是否一定要写到本地，不能直接传中间转换结果吗

2022-05-12 09:01 UTC, jiangjiajun commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +            sess_options.optimized_model_filepath = "./optimize_model.onnx"
这里同理

2022-05-12 09:02 UTC, jiangjiajun requested changes

2022-05-12 09:02 UTC, jiangjiajun commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +在进行GPU部署之前请先确保机器已经安装好CUDA >= 11.04，CuDNN >= 8.2，然后请使用如下指令安装所需依赖
确认下是11.04还是11.4

2022-05-12 09:03 UTC, jiangjiajun requested changes

2022-05-12 09:03 UTC, jiangjiajun commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +-----------------------------
这里的输出打印值，跟代码里面的demo是不同的？

2022-05-12 09:13 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +-----------------------------
![image](https://user-images.githubusercontent.com/30516196/168036073-451dff95-ffee-4b7d-a1c4-ee1a0373c1b0.png)
相同的

2022-05-12 09:25 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +            float_onnx_file = "model.onnx"
Done

2022-05-12 09:25 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +            sess_options.optimized_model_filepath = "./optimize_model.onnx"
Done

2022-05-12 09:26 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +    (1)下载对应版本的PaddleInference-TRT，[PaddleInference-TRT下载路径](https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python)
Done

2022-05-12 09:29 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/README.md
> +在进行GPU部署之前请先确保机器已经安装好CUDA >= 11.04，CuDNN >= 8.2，然后请使用如下指令安装所需依赖
11.2就可以了

2022-05-12 09:36 UTC, jiangjiajun requested changes

2022-05-12 09:36 UTC, jiangjiajun commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +        file_name = model_path.split('/')[-1]
代码考虑Windows/Linux兼容性，不要用字符串split，而是os.path.split

2022-05-12 09:36 UTC, jiangjiajun commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +        model = paddle.jit.load(model_dir + "/" + file_name)
使用os.path.join

2022-05-12 09:36 UTC, jiangjiajun commented
看起来代码和文档并未在Windows进行测试过， @ZeyuChen 我们看是否有必要支持Windows，如若有必要，需要进行实测

2022-05-12 09:51 UTC, yeliang2258 commented on examples/language_model/ernie-3.0/deploy/python/ernie_predictor.py
> +        model = paddle.jit.load(model_dir + "/" + file_name)
路径相关的都删除了

2022-05-12 12:44 UTC, ZeyuChen approved these changes

2022-05-12 12:44 UTC, ZeyuChen commented on examples/language_model/ernie-3.0/deploy/python/infer_gpu.py
> +        default='tnews_quant_models/mse4/int8',
这种参数不适合设置默认值

2022-05-12 12:44 UTC, merged