The English Version of quick_start
PaddlePaddle/PaddleNLP pull request #245
Opened 2021-04-09 02:57 UTC by monika19950721

### PR types

Others
### PR changes
Docs

### Describe

有两个地方需要审核一下，麻烦啦！
1、此时即可输入ERNIE模型中得到相应输出。
At this time, you can take the outputs of ERNIE as the input.
2、获取分类数据标签：
Acquire the labels of classification data:
注意⚠️：有两个链接需要重新提供一下哦～

2021-04-12 15:51 UTC, ZeyuChen requested changes
有些译法得斟酌下

2021-04-12 15:51 UTC, ZeyuChen commented on docs/get_started/quick_start_ENG.md
> +>>> pip install --upgrade paddlenlp>=2.0.0rc -i https://pypi.org/simple
`pip install --upgrade paddlenlp>=2.0.0rc -i https://pypi.org/simple`
->`pip install --upgrade paddlenlp -i https://pypi.org/simple`

2021-04-12 15:51 UTC, ZeyuChen commented on docs/get_started/quick_start_ENG.md
> +...     'This hotel was a little old, and the special promotion room was not bad. Overall, it was just so so',
这里不太这么合适这么直译，要么得选英文的模型，要么得保持中文。

2021-04-15 03:30 UTC, monika19950721 commented on docs/get_started/quick_start_ENG.md
> +...     'This hotel was a little old, and the special promotion room was not bad. Overall, it was just so so',
您好，这里已经处理完毕！

但是，我看到这行代码原文就是上面一行，所以我不太知道要不要修改
pip install --upgrade paddlenlp>=2.0.0rc -i https://pypi.org/simple
->pip install --upgrade paddlenlp -i https://pypi.org/simple

2021-05-17 16:32 UTC, closed without merging