Update installation.rst
PaddlePaddle/PaddleNLP pull request #2543
Opened 2022-06-16 13:44 UTC by freeliuzc

增加“使用Docker镜像体验PaddleOCR”章节

### PR types

Others
### PR changes

Docs
### Description

Add "Use PaddleNLP with Docker" content.

2022-06-16 14:24 UTC, ZeyuChen requested changes

2022-06-16 14:24 UTC, ZeyuChen commented on docs/get_started/installation.rst
> +使用Docker镜像体验PaddleOCR
使用Docker镜像体验PaddleOCR -> PaddleNLP

2022-06-17 07:26 UTC, freeliuzc commented on docs/get_started/installation.rst
> +使用Docker镜像体验PaddleOCR
已更新

2022-06-17 13:28 UTC, ZeyuChen approved these changes

2022-06-17 13:28 UTC, merged