Fix some bugs in deploy
PaddlePaddle/PaddleNLP pull request #2780
Opened 2022-07-12 01:53 UTC by yeliang2258

### PR types

Others

### PR changes

Others

### Description

Fix some bugs in deploy

2022-07-12 07:51 UTC, ZeyuChen commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            precision_type = inference.PrecisionType.Half
为什么这个不放在use_fp16里面？

在最外面是不是应该定义FP32的精度

2022-07-12 07:54 UTC, yeliang2258 commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            precision_type = inference.PrecisionType.Half
要进入这个地方，只能是在开启fp16或者int8的时候，否则就不会进入到这里

2022-07-12 07:54 UTC, yeliang2258 commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            precision_type = inference.PrecisionType.Half
![image](https://user-images.githubusercontent.com/30516196/178438880-9802ccb7-b34e-4293-8d9d-f7fa314fdfd6.png)

2022-07-12 12:34 UTC, jiangjiajun requested changes

2022-07-12 12:34 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            device (str): The deployed device can be set to cpu, gpu or xpu, the default is cpu.
`ort`的缩写建议改成onnxruntime，更直观

2022-07-12 12:34 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            use_fp16 (bool): Whether to use fp16 to inference, the default is False.
是否能支持GPU，如果不行，这里补充说明， Only available while inference on GPU

2022-07-12 12:34 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            use_quantize (bool): Whether to use ort dynamic quantize , the default is False.
这个是在CPU，还是GPU上使用。如果只在CPU，补充说明， Only available while inference on CPU with onnxruntime as inference backend.

2022-07-12 12:34 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            model_path)  # Determine whether a Paddle model is a quantized model
所有的代码注释都写在函数上面吧，避免一行的代码太长，或者原本的一行代码被折叠成两行

2022-07-12 12:34 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            model_path)  # Determine whether a Paddle model is a quantized model
```
# Check if the model is quantized
is_int8_model = self.paddle_quantize_model(model_path)
```

2022-07-12 12:34 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +        # quantized model, deploy on xpu, deploy on cpu and use_quantize is disabled
```
The quantized paddle model is not supported to deploy on XPU/CPU now.
```

2022-07-12 12:34 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +        if is_int8_model or device == "xpu" or device == "cpu" and not use_quantize:
这里的条件判断是
(是int8模型 或 是XPU 或 是CPU) 且不使用onnxruntime_quantize的时候?
这个条件注释还是需要再直观写明下这里的if block是处理啥情况下的部署

2022-07-12 12:34 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +                paddle.set_device("gpu")
使用paddle_inference时，应该无需这行代码

2022-07-12 12:34 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +                    f.write(onnx_model)
这里假设了本地是可写的状态，进行了文件的写入操作，实际上可能会出问题。 这里onnx模型是否可以不写入磁盘，直接内存中传递

2022-07-12 12:34 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +                onnx.save_model(trans_model, deploy_onnx_model)
同上

2022-07-12 12:53 UTC, yeliang2258 commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            use_fp16 (bool): Whether to use fp16 to inference, the default is False.
CPU上也可以进行配置，intel提了PR增加了支持

2022-07-12 12:57 UTC, yeliang2258 commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +                onnx.save_model(trans_model, deploy_onnx_model)
这个地方用到了ORT提供的工具，只能用一个onnx模型文件

2022-07-12 12:57 UTC, yeliang2258 commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +        if is_int8_model or device == "xpu" or device == "cpu" and not use_quantize:
是int8模型 或 是XPU 或 是CPU且不使用onnxruntime_quantize的时候

2022-07-13 02:47 UTC, LiuChiachi commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            use_fp16 (bool): Whether to use fp16 to inference, the default is False.
是否可以统一设一个参数'precision_mode'，可以是fp32、fp16、int8的其中一种，infer_gpu.py和infer_cpu.py也是一样

2022-07-13 02:47 UTC, LiuChiachi commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +        min_seq_len, max_seq_len, opt_seq_len = 2, max_seq_length, max_seq_length
不同数据集的`opt_seq_len`不同，这里可以设成`max_seq_length`吗

2022-07-13 02:47 UTC, LiuChiachi commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +                    config.collect_shape_range_info(shape_info_file)
如果已经有了`set_dynamic_shape`这个函数，是否还需要保留`collect_shape_range_info`这块获取shape info的逻辑呢

2022-07-13 02:47 UTC, LiuChiachi commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +        """
文档和代码标准格式应该是不超过80列，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/.style.yapf

2022-07-13 02:47 UTC, LiuChiachi commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +                    if is_int8_model:
如果用了'precision_mode'这里可以简化吗

2022-07-13 02:47 UTC, LiuChiachi commented on model_zoo/ernie-3.0/deploy/python/requirements_gpu.txt
> +onnxconverter-common
看起来是有一些新功能，是否对paddle版本有要求呢，如果有的话应该更新文档也行。

2022-07-13 02:55 UTC, yeliang2258 commented on model_zoo/ernie-3.0/deploy/python/requirements_gpu.txt
> +onnxconverter-common
这个是ONNXRuntime的，和Paddle没有关系。另外量化模型在CPU上推理，要求Paddle版本2.3.1，因为用了enable_mkldnn_int8()这个开关，这个开关在Paddle2.3.1上才有

2022-07-13 03:00 UTC, yeliang2258 commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +                    config.collect_shape_range_info(shape_info_file)
set_dynamic_shape是开关，打开的时候collect_shape_range_info为Inference-TRT存储shape_info，关闭的时候就读取shape_info

2022-07-13 07:01 UTC, LiuChiachi approved these changes, later dismissed
LGTM

2022-07-13 07:51 UTC, LiuChiachi commented on model_zoo/ernie-3.0/deploy/python/README.md
> +|--precision_mode | 推理精度，可选fp32，fp16或者int8，当输入非量化模型并设置int8时使用动态量化进行加速，默认fp32 |
在环境依赖中，GPU FP16下用户不需要再安装paddle inference~

2022-07-13 08:00 UTC, LiuChiachi commented on model_zoo/ernie-3.0/deploy/python/README.md
> +|--precision_mode | 推理精度，可选fp32，fp16或者int8，当输入非量化模型并设置int8时使用动态量化进行加速，默认fp32 |
如需使用量化（INT8）部署，请确保 GPU 设备的 CUDA 计算能力 (CUDA Compute Capability) 大于 7.0，典型的设备包括 V100、T4、A10、A100、GTX 20 系列和 30 系列显卡等。需要安装 TensorRT 以及 包含 TensorRT 预测库的 PaddlePaddle 。
更多关于 CUDA Compute Capability 和精度支持情况请参考 NVIDIA 文档：[GPU 硬件与支持精度对照表](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-840-ea/support-matrix/index.html#hardware-precision-matrix)
1. TensorRT 安装请参考：[TensorRT 安装说明](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-840-ea/install-guide/index.html#overview)，Linux 端简要步骤如下：
    (1)下载 TensorRT8.2，文件名 TensorRT-XXX.tar.gz，[下载链接](https://developer.nvidia.com/tensorrt)
    (2)解压得到 TensorRT-XXX 文件夹
    (3)通过 `export LD_LIBRARY_PATH=TensorRT-XXX/lib:$LD_LIBRARY_PATH` 将 lib 路径加入到`LD_LIBRARY_PATH` 中
    (4)使用 `pip install` 安装 `TensorRT-XXX/python` 中对应的 `TensorRT` 安装包
2. 含有预测库的 PaddlePaddle 的安装请参考：[Paddle Inference 的安装文档](https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/source_compile.html)，Linux 端简要步骤如下：
    (1)根据 CUDA 环境和 Python 版本下载对应的支持 TensorRT 的 Paddle Inference 预测库，如 linux-cuda11.2-cudnn8.2-trt8-gcc8.2。[Paddle Inference 下载路径](https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python)
    (2)使用 pip install 安装下载好的 Paddle Inference 安装包


我稍微改了一下，你看可以不，中文和英文、数字之间需要有空格。

2022-07-13 08:00 UTC, LiuChiachi commented on model_zoo/ernie-3.0/deploy/python/README.md
> +|--precision_mode | 推理精度，可选fp32，fp16或者int8，当输入非量化模型并设置int8时使用动态量化进行加速，默认fp32 |
如需使用量化（INT8）部署，请确保 GPU 设备的 CUDA 计算能力 (CUDA Compute Capability) 大于 7.0，典型的设备包括 V100、T4、A10、A100、GTX 20 系列和 30 系列显卡等。需要安装 TensorRT 以及 包含 TensorRT 预测库的 PaddlePaddle 。
更多关于 CUDA Compute Capability 和精度支持情况请参考 NVIDIA 文档：[GPU 硬件与支持精度对照表](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-840-ea/support-matrix/index.html#hardware-precision-matrix)
1. TensorRT 安装请参考：[TensorRT 安装说明](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-840-ea/install-guide/index.html#overview)，Linux 端简要步骤如下：
    (1)下载 TensorRT8.2，文件名 TensorRT-XXX.tar.gz，[下载链接](https://developer.nvidia.com/tensorrt)
    (2)解压得到 TensorRT-XXX 文件夹
    (3)通过 `export LD_LIBRARY_PATH=TensorRT-XXX/lib:$LD_LIBRARY_PATH` 将 lib 路径加入到`LD_LIBRARY_PATH` 中
    (4)使用 `pip install` 安装 `TensorRT-XXX/python` 中对应的 `TensorRT` 安装包
2. 含有预测库的 PaddlePaddle 的安装请参考：[Paddle Inference 的安装文档](https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/source_compile.html)，Linux 端简要步骤如下：
    (1)根据 CUDA 环境和 Python 版本下载对应的支持 TensorRT 的 Paddle Inference 预测库，如 linux-cuda11.2-cudnn8.2-trt8-gcc8.2。[Paddle Inference 下载路径](https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python)
    (2)使用 pip install 安装下载好的 Paddle Inference 安装包


我稍微改了一下，你看可以不，中文和英文、数字之间需要有空格。

2022-07-13 08:20 UTC, jiangjiajun requested changes

2022-07-13 08:20 UTC, jiangjiajun commented on model_zoo/ernie-3.0/deploy/python/ernie_predictor.py
> +            # args.use_quantize = False
注释的代码不需要了吗，那移除掉吧

2022-07-13 08:54 UTC, yeliang2258 commented on model_zoo/ernie-3.0/deploy/python/README.md
> +|--precision_mode | 推理精度，可选fp32，fp16或者int8，当输入非量化模型并设置int8时使用动态量化进行加速，默认fp32 |
感谢提醒，已经更新

2022-07-13 09:03 UTC, LiuChiachi approved these changes
LGTM

2022-07-13 12:48 UTC, jiangjiajun approved these changes
LGTM

2022-07-14 02:47 UTC, merged