run_qa.py add xpu chioce of device,*test=kunlun
PaddlePaddle/PaddleNLP pull request #3046
Opened 2022-08-15 07:10 UTC by dongfangshenzhu

### PR types
Others 

### PR changes
Others 

### Description
qa任务中device选项添加xpu

2022-08-15 07:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=3046) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=3046) before we can accept your contribution.<br/><hr/>**dongfangshenzhu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=3046) it.</sub>

2022-08-15 07:27 UTC, ZeyuChen requested changes

2022-08-15 07:27 UTC, ZeyuChen commented on model_zoo/ernie-3.0/run_qa.py
> +        choices=['cpu', 'gpu','xpu'],
代码没过yapf，目前不符合coding style规范。
gpu逗号后面应该有个空格。

2022-08-15 07:45 UTC, dongfangshenzhu commented on model_zoo/ernie-3.0/run_qa.py
> +        choices=['cpu', 'gpu','xpu'],
好的

2022-08-16 00:05 UTC, ZeyuChen approved these changes

2022-08-16 00:05 UTC, merged