Adding XLNet modeling and tokenizer
PaddlePaddle/PaddleNLP pull request #31
Opened 2021-02-23 06:42 UTC by yingyibiao

2021-02-23 17:32 UTC, ZeyuChen requested changes
模型文件进行托管以及确认Author和License是否需要更新

2021-02-23 17:32 UTC, ZeyuChen commented on paddlenlp/transformers/xlnet/tokenizer.py
> +            "xlnet-base-cased": "https://huggingface.co/xlnet-base-cased/resolve/main/spiece.model",
相关模型文件应该在paddlenlp的bos上托管一份

2021-02-23 17:32 UTC, ZeyuChen commented on paddlenlp/transformers/xlnet/modeling.py
> +    pretrained_resource_files_map = {"xlnet-base-cased": "/yingyibiao/pretrained_models/xlnet-base-cased.pdparams"}
将参数托管至BOS

2021-02-23 17:32 UTC, ZeyuChen commented on paddlenlp/transformers/xlnet/modeling.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
如果这一文件中的代码存在参考或者搬了原始实现，需要将参考的CopyRight和Author写上来

2021-02-26 07:40 UTC, yingyibiao commented
> 模型文件进行托管以及确认Author和License是否需要更新

已更改

2021-02-26 07:41 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/tokenizer.py
> +            "xlnet-base-cased": "https://huggingface.co/xlnet-base-cased/resolve/main/spiece.model",
> 相关模型文件应该在paddlenlp的bos上托管一份

已托管

2021-02-26 07:42 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +    pretrained_resource_files_map = {"xlnet-base-cased": "/yingyibiao/pretrained_models/xlnet-base-cased.pdparams"}
> 将参数托管至BOS

已托管

2021-02-26 07:42 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
> 如果这一文件中的代码存在参考或者搬了原始实现，需要将参考的CopyRight和Author写上来

已更新

2021-02-26 07:44 UTC, ZeyuChen reviewed
Some comments for  installation and argparse

2021-02-26 07:44 UTC, ZeyuChen commented on examples/language_model/xlnet/README.md
> +   pip install paddlenlp>=2.0.0b
`pip install paddlenlp\>=2.0.0rc`

2021-02-26 07:44 UTC, ZeyuChen commented on examples/language_model/xlnet/README.md
> +##### GLUE评测任务数据
markdown 层级不对

2021-02-26 07:44 UTC, ZeyuChen commented on examples/language_model/xlnet/run_glue.py
> +FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
这里的logger改用paddlenlp.utils.logger

2021-02-26 07:44 UTC, ZeyuChen commented on examples/language_model/xlnet/run_glue.py
> +MODEL_CLASSES = {"xlnet": (XLNetForSequenceClassification, XLNetTokenizer), }
单模型的话是否可以去掉这个MODEL_CLASSES

2021-02-26 07:44 UTC, ZeyuChen commented on examples/language_model/xlnet/run_glue.py
> +        "--model_type",
单模型不用考虑model type吧

2021-02-26 07:44 UTC, ZeyuChen commented on examples/language_model/xlnet/README.md
> +   pip install paddlenlp>=2.0.0rc
安装脚本不对 `pip install paddlenlp\>=2.0.0rc`

2021-02-26 07:44 UTC, ZeyuChen commented on examples/language_model/xlnet/README.md
> +- `model_type` 指示了模型类型，使用XLNet模型时设置为xlnet即可。
是否无需考虑model_type了，就是xlnet

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/tokenizer.py
> +import sentencepiece as spm
请参考GPT2中tokenizer的做法使用try_import来动态依赖

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +dtype_float = 'float32'
如果要使用全局的dtype，可以使用paddle默认的全局dtype

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +            exec("self.add_parameter(_str, paras)")
这里为什么要使用exec呢，下同

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +                mems_mask = paddle.cast(paddle.zeros([data_mask.shape[0], mlen, bsz]), dtype=dtype_float)
如果要使用全局的dtype，最好通过`get_default_dtype()`获取。另可以使用其他tensor的dtype来传递设置当前tensor的dtype，以避免全局dtype的使用。下面的这些`dtype=dtype_float`相同。

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/tokenizer.py
> +# Copyright (c) 2018, NVIDIA CORPORATION.  All rights reserved.
去掉这行，这个Copyright只是其他代码中相关的

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/tokenizer.py
> +        return self._tokenize(text)
注意`__call__`和tokenizer最新代码的统一性。还请 @smallv0221  确认下

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +                 ff_activation,):
这里建议和其他Model风格一致的通过xlnet参数来初始化

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +    def prepare_inputs_for_generation(self, input_ids, past=None, use_mems_train=False, use_mems_eval=False, **kwargs):
没有使用且没有验证过的代码建议先行去掉。`prepare_inputs_for_generation`这个会在后面生成API中统一考虑设计

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +            loss = loss_fct(logits.reshape([-1, logits.shape[-1]]), labels.reshape([-1]))
loss建议不放在模型内部，可能会给后续使用hapi或者预测部署带来些困扰，其他模型中也都放在了外部。

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +# Copyright (c) 2018, NVIDIA CORPORATION.  All rights reserved.
去掉这行，这个Copyright只是其他代码中相关的

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +        x = paddle.index_select(x, index=paddle.arange(klen, dtype='int64'), axis=3)
`rel_shift_bnij`是论文模型在代码实现上相对trick的地方，建议增加注释说明

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +            k_head_h = paddle.reshape(k_head_h, shape=[h.shape[0], h.shape[1], self.n_head, self.d_head])
这里是否有误，`h.shape[0], h.shape[1]`应为`cat.shape[0], cat.shape[1]`。 这里应该是由于没有跑带mems的recurrent分支所以没有报错

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +            v_head_h = paddle.reshape(v_head_h, shape=[h.shape[0], h.shape[1], self.n_head, self.d_head])
同上，这里是否有误，`h.shape[0], h.shape[1]`应为`cat.shape[0], cat.shape[1]`。 这里应该是由于没有跑带mems的recurrent分支所以没有报错

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +            k_head_r = paddle.reshape(k_head_r, shape=[h.shape[0], h.shape[1], self.n_head, self.d_head])
同上，这里是否有误，`h.shape[0], h.shape[1]`应为`r.shape[0], r.shape[1]`。 这里应该是由于没有跑带mems的recurrent分支所以没有报错

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +            v_head_h = paddle.reshape(v_head_h, shape=[h.shape[0], h.shape[1], self.n_head, self.d_head])
同上，注意`h.shape[0], h.shape[1]`修改为`cat.shape[0], cat.shape[1]`

2021-02-26 14:34 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +    ):
一些重要的注意添加文档

2021-02-26 15:01 UTC, smallv0221 commented on paddlenlp/transformers/xlnet/tokenizer.py
> +    def __call__(self, text):
这里的__call__()实现的功能应该是基础的convert_to_feature功能。如果XLnet的此功能跟PretrainTokenizer相同的话就是接继承PretrainTokenizer。用tokenize()方法调用self._tokenize()。参考bert。

2021-02-27 13:21 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/tokenizer.py
> +    def __call__(self, text):
谢谢，已修改

2021-02-27 13:22 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +            v_head_h = paddle.reshape(v_head_h, shape=[h.shape[0], h.shape[1], self.n_head, self.d_head])
谢谢，已修改

2021-02-27 13:22 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +            k_head_r = paddle.reshape(k_head_r, shape=[h.shape[0], h.shape[1], self.n_head, self.d_head])
谢谢，已修改

2021-02-27 13:22 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +            v_head_h = paddle.reshape(v_head_h, shape=[h.shape[0], h.shape[1], self.n_head, self.d_head])
谢谢，已修改

2021-02-27 13:22 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +            k_head_h = paddle.reshape(k_head_h, shape=[h.shape[0], h.shape[1], self.n_head, self.d_head])
谢谢，已修改

2021-02-27 13:22 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +        x = paddle.index_select(x, index=paddle.arange(klen, dtype='int64'), axis=3)
谢谢，已添加

2021-02-27 13:22 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +# Copyright (c) 2018, NVIDIA CORPORATION.  All rights reserved.
谢谢，已删除

2021-02-27 13:23 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +            loss = loss_fct(logits.reshape([-1, logits.shape[-1]]), labels.reshape([-1]))
谢谢，已修改

2021-02-27 13:23 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +    def prepare_inputs_for_generation(self, input_ids, past=None, use_mems_train=False, use_mems_eval=False, **kwargs):
谢谢，已删除

2021-02-27 13:23 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +                 ff_activation,):
谢谢，已修改

2021-02-27 13:24 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/tokenizer.py
> +        return self._tokenize(text)
谢谢，已修改

2021-02-27 13:24 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/tokenizer.py
> +# Copyright (c) 2018, NVIDIA CORPORATION.  All rights reserved.
谢谢，已删除

2021-02-27 13:24 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +                mems_mask = paddle.cast(paddle.zeros([data_mask.shape[0], mlen, bsz]), dtype=dtype_float)
谢谢，已修改

2021-02-27 13:25 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +            exec("self.add_parameter(_str, paras)")
这里为了复用代码，节约代码量

2021-02-27 13:25 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +dtype_float = 'float32'
谢谢，已修改

2021-02-27 13:25 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/tokenizer.py
> +import sentencepiece as spm
谢谢，已修改

2021-02-27 13:25 UTC, yingyibiao commented on examples/language_model/xlnet/README.md
> +- `model_type` 指示了模型类型，使用XLNet模型时设置为xlnet即可。
谢谢，已修改

2021-02-27 13:25 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +        "--model_type",
谢谢，已修改

2021-02-27 13:25 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +MODEL_CLASSES = {"xlnet": (XLNetForSequenceClassification, XLNetTokenizer), }
谢谢，已删除

2021-02-27 13:26 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
谢谢，已修改

2021-02-27 13:26 UTC, yingyibiao commented on examples/language_model/xlnet/README.md
> +##### GLUE评测任务数据
谢谢，已修改

2021-02-27 14:45 UTC, smallv0221 commented on paddlenlp/transformers/xlnet/tokenizer.py
> +
好像还缺一个build_offset_mapping_with_special_tokens()方法，参见bert

2021-02-28 07:10 UTC, ZeyuChen reviewed
建议使用易于理解的代码来实现，一些Tricky的做法尽量去除。同时注释注意规范标准。

2021-02-28 07:10 UTC, ZeyuChen commented on paddlenlp/transformers/xlnet/modeling.py
> +            exec("self.add_parameter(_str, paras)")
感觉不是一种标准的python编码方式，有点tricky。如果用原生python代码写会很复杂吗

2021-02-28 07:10 UTC, ZeyuChen commented on paddlenlp/transformers/xlnet/modeling.py
> +        # create relative positional encoding.
所有的英文注释统一标准英文语法，首字母大写
# Create relative ...

2021-03-01 04:29 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +        # create relative positional encoding.
谢谢，已修改

2021-03-01 04:29 UTC, yingyibiao commented
> 建议使用易于理解的代码来实现，一些Tricky的做法尽量去除。同时注释注意规范标准。

谢谢，已修改

2021-03-01 04:30 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/tokenizer.py
> +
谢谢，已添加

2021-03-01 04:30 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +    ):
谢谢，已添加

2021-03-01 04:31 UTC, yingyibiao commented on examples/language_model/xlnet/README.md
> +   pip install paddlenlp>=2.0.0b
谢谢，已修改

2021-03-01 04:31 UTC, yingyibiao commented on examples/language_model/xlnet/README.md
> +   pip install paddlenlp>=2.0.0rc
谢谢，已修改

2021-03-01 04:31 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +            exec("self.add_parameter(_str, paras)")
谢谢，已修改

2021-03-01 08:11 UTC, yingyibiao commented
> 模型文件进行托管以及确认Author和License是否需要更新

模型文件已托管，Author和License已更新

2021-03-01 11:43 UTC, smallv0221 commented on paddlenlp/transformers/xlnet/tokenizer.py
> +
如果pad_token_type_id不是0的话在这里写一下，例如pad_token_type_id=3

2021-03-01 11:49 UTC, smallv0221 commented on paddlenlp/transformers/xlnet/tokenizer.py
> +
pad_token_type_id放在这里吧，不用放在init里了

2021-03-01 11:49 UTC, smallv0221 commented on paddlenlp/transformers/xlnet/tokenizer.py
> +
pad_token_type_id放在这里吧，不用放在init里了

2021-03-02 03:27 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/tokenizer.py
> +
谢谢，已修改

2021-03-02 03:27 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/tokenizer.py
> +
谢谢，已修改

2021-03-02 03:49 UTC, smallv0221 commented on examples/language_model/xlnet/run_glue.py
> +        return example['input_ids'], example['segment_ids'], example['input_mask'], len(example['input_ids']), label
这里和下面segment_ids改成token_type_ids

2021-03-02 07:01 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +        return example['input_ids'], example['segment_ids'], example['input_mask'], len(example['input_ids']), label
谢谢，已修改

2021-03-03 06:20 UTC, guoshengCS commented on examples/language_model/xlnet/run_glue.py
> +        "--eager_run", type=eval, default=True, help="Use dygraph mode.")
去掉这个参数吧

2021-03-03 06:20 UTC, guoshengCS commented on examples/language_model/xlnet/run_glue.py
> +        help="number of gpus to use, 0 for cpu.")
多卡是否需要按照 http://wiki.baidu.com/pages/viewpage.action?pageId=1365860576 讨论，统一使用launcher方式

2021-03-03 06:20 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +        self.add_parameter("q", q)
`self.q = self.create_parameter([self.d_model, self.n_head * self.d_head])` ，下同

2021-03-03 06:20 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +            use_mems_eval=False,
输入参数这里为什么要分为`use_mems_train`和`use_mems_train`呢，看下面也是直接根据`if self.training`判断的

2021-03-03 06:20 UTC, guoshengCS commented on paddlenlp/transformers/xlnet/modeling.py
> +        labels=None,
`labels`也可以去掉了

2021-03-03 06:20 UTC, guoshengCS commented on examples/language_model/xlnet/run_glue.py
> +        help="number of gpus to use, 0 for cpu.")
另外args这块也按照wiki中的要求通过yapf:disable一个参数一行吧，可以参照wiki过一遍

2021-03-04 03:18 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +            use_mems_eval=False,
目前XLNet作者的设置是预训练阶段use_mems=True，fine-tuning阶段和eval阶段use_mems=False; 我这里的考虑是我们可以通过设置use_mems_train和use_mems_eval这两个参数来支持fine-tuning阶段和eval阶段使用不同的use_mems策略。

2021-03-04 03:18 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +        "--eager_run", type=eval, default=True, help="Use dygraph mode.")
done

2021-03-04 03:24 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +        labels=None,
done

2021-03-04 03:27 UTC, yingyibiao commented on paddlenlp/transformers/xlnet/modeling.py
> +        self.add_parameter("q", q)
done

2021-03-04 06:51 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +        help="number of gpus to use, 0 for cpu.")
done

2021-03-04 07:38 UTC, smallv0221 commented on examples/language_model/xlnet/run_glue.py
> +def convert_example(example,
glue数据集以更新，可以参考glue/run_glue.py改成新的用法。

2021-03-04 08:40 UTC, smallv0221 reviewed
数据流部分再跟glue/run_glue.py对一对

2021-03-04 08:40 UTC, smallv0221 commented on examples/language_model/xlnet/run_glue.py
> +    dataset_class, metric_class = TASK_CLASSES[args.task_name]
这个dataset_class是不是没用了

2021-03-04 08:40 UTC, smallv0221 commented on examples/language_model/xlnet/run_glue.py
> +from paddlenlp.datasets import GlueCoLA, GlueSST2, GlueMRPC, GlueSTSB, GlueQQP, GlueMNLI, GlueQNLI, GlueRTE
不用再import这些了吧

2021-03-04 08:40 UTC, smallv0221 commented on examples/language_model/xlnet/run_glue.py
> +TASK_CLASSES = {
这里也参考glue/run_glue.py修改

2021-03-04 11:25 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +TASK_CLASSES = {
done

2021-03-04 11:25 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +from paddlenlp.datasets import GlueCoLA, GlueSST2, GlueMRPC, GlueSTSB, GlueQQP, GlueMNLI, GlueQNLI, GlueRTE
done

2021-03-04 11:25 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +    dataset_class, metric_class = TASK_CLASSES[args.task_name]
done

2021-03-05 03:38 UTC, guoshengCS commented on examples/language_model/xlnet/run_glue.py
> +            if not any(nd in n for nd in ["bias", "norm", "LayerNorm"])
因为LayerNorm是赋给`self.layer_norm`的，这里`any(nd in n for nd in ["bias", "norm", "LayerNorm"])`中的要改为`any(nd in n for nd in ["bias", "LayerNorm"])`才是符合预期的，看看这个是不是造成精度问题点原因

2021-03-05 06:12 UTC, guoshengCS commented on examples/language_model/xlnet/run_glue.py
> +            optimizer.clear_gradients()
使用新的`clear_grad()`接口

2021-03-05 06:59 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +            if not any(nd in n for nd in ["bias", "norm", "LayerNorm"])
model.named_parameters()的key是小写的，例如“transformer.layer.10.rel_attn.layer_norm.weight”，
所以是否应该改为 any(nd in n for nd in ["bias", "layer_norm"])？

2021-03-05 07:24 UTC, guoshengCS commented on examples/language_model/xlnet/run_glue.py
> +            if not any(nd in n for nd in ["bias", "norm", "LayerNorm"])
是的

2021-03-05 07:35 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +            optimizer.clear_gradients()
done

2021-03-05 07:35 UTC, yingyibiao commented on examples/language_model/xlnet/run_glue.py
> +            if not any(nd in n for nd in ["bias", "norm", "LayerNorm"])
done

2021-03-05 08:05 UTC, guoshengCS approved these changes

2021-03-05 08:07 UTC, merged