Add question generation application and taskflow
PaddlePaddle/PaddleNLP pull request #3165
Opened 2022-08-30 13:58 UTC by westfish

### PR types

New features

### PR changes

Models

### Description

Add question generation application and taskflow.

2022-08-31 03:23 UTC, ZeyuChen reviewed
不需要指明这么细的目录让git ignore

2022-08-31 03:23 UTC, ZeyuChen commented on .gitignore
> +applications/question_generation/drawer
gitignore用法不对

2022-08-31 13:46 UTC, westfish commented on .gitignore
> +applications/question_generation/drawer
这个.gitignore里面的# temp的内容是用来把目前还是草稿的东西注释掉不上传

2022-08-31 13:47 UTC, westfish commented on .gitignore
> +applications/question_generation/drawer
后面等差不多了会把里面的内容删除掉的

2022-09-08 08:54 UTC, tianxin1860 reviewed
关于 mode 划分部分当面对一下吧。

2022-09-08 08:54 UTC, tianxin1860 commented on .gitignore
PR 里不需要额外再引入一个 .gitignore 文件

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/adversarial_utils.py
> +import copy
明确对抗训练部分收益很有限情况下，这部分代码可以不对外开源。

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/deploy/paddle_serving/log.txt
> +02-Sep-22 03:09:14 - Starting new HTTP connection (1): paddlepaddle.org.cn:80
日志文件不需要提交

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/gen_utils.py
> +    if mode == 'pretrain' or mode == 'pretrain_test':
这个 mode 是在做基于答案生成上下文的预训练？

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/gen_utils.py
> +    if mode == 'train' or mode == 'pretrain':
这里的 mode 是对应做什么？

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/gen_utils.py
> +    elif mode == 'test' or mode == 'pretrain_test':
test 和 pretrain_test 为什么放在一起？

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/gen_utils.py
> +    outstr = instr.strip('在已知答案的前提下，问题：')
模板可以考虑作为参数或者配置传入？避免在代码里硬编码

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/pretrain.py
> +import os
pretrian.py 的整体逻辑是 基于 answer 生成上下文的预训练么？

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/scripts/finetune_incremental_data_run.sh
> +# unset CUDA_VISIBLE_DEVICES
无用的注释可以删掉

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/scripts/finetune_run.sh
> +# unset CUDA_VISIBLE_DEVICES
无用的注释可以注释

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/scripts/generate_run.sh
> +    # --predict_file=/root/project/data/dureader_qg/raw/DuReaderQG/minidev.json \
同上

2022-09-08 08:54 UTC, tianxin1860 commented on applications/question_generation/scripts/paddle_inference.sh
> +               #    --predict_file /root/project/data/dureader_qg/raw/DuReaderQG/minidev.json \
同上

2022-09-09 03:13 UTC, westfish commented on applications/question_generation/adversarial_utils.py
> +import copy
好的

2022-09-09 03:15 UTC, westfish commented on .gitignore
好的，刚刚向别人请教了一下如何操作

2022-09-09 03:20 UTC, westfish commented on applications/question_generation/deploy/paddle_serving/log.txt
> +02-Sep-22 03:09:14 - Starting new HTTP connection (1): paddlepaddle.org.cn:80
好的，已删除

2022-09-09 03:22 UTC, westfish commented on applications/question_generation/gen_utils.py
> +    if mode == 'pretrain' or mode == 'pretrain_test':
是的，就是之前的那个answer-containing sentence generation预训练

2022-09-09 03:30 UTC, westfish commented on applications/question_generation/gen_utils.py
> +    if mode == 'train' or mode == 'pretrain':
前面的if else的mode是用来分辨是预训练阶段（包括训练和测试）还是非预训练阶段（包括训练和测试），对应着不同的文件读取和模版策略；这里的if else的mode是用来分辨是训练阶段（包括预训练和普通训练）还是测试阶段（包括预训练的测试和普通测试），对应不同的模型输入要求

2022-09-09 03:31 UTC, westfish commented on applications/question_generation/pretrain.py
> +import os
是的，基于answer和扣除了answer所在句子的上下文，生成answer所在句子

2022-09-09 03:33 UTC, westfish commented on applications/question_generation/scripts/finetune_incremental_data_run.sh
> +# unset CUDA_VISIBLE_DEVICES
scripts主要是我实验阶段用到的脚本，后面会单独处理

2022-09-09 03:33 UTC, westfish commented on applications/question_generation/scripts/finetune_run.sh
> +# unset CUDA_VISIBLE_DEVICES
scripts目录下主要是我实验阶段用到的脚本，后面会单独处理

2022-09-09 03:34 UTC, westfish commented on applications/question_generation/scripts/generate_run.sh
> +    # --predict_file=/root/project/data/dureader_qg/raw/DuReaderQG/minidev.json \
好的

2022-09-09 03:34 UTC, westfish commented on applications/question_generation/scripts/paddle_inference.sh
> +               #    --predict_file /root/project/data/dureader_qg/raw/DuReaderQG/minidev.json \
好的

2022-09-09 03:38 UTC, westfish commented on .gitignore
> +applications/question_generation/drawer
已经把.gitignore删除

2022-09-09 03:43 UTC, westfish commented on .gitignore
已删除.gitignore

2022-09-09 03:50 UTC, westfish commented on applications/question_generation/adversarial_utils.py
> +import copy
但是主文件gen_utils中有用到该文件，目前先不删除？

2022-09-16 06:11 UTC, SunYanCN commented on docs/model_zoo/taskflow.md
> +* `max_length`：生成代码的最大长度，默认为128。
生成代码的最大长度改成生成问题？

2022-09-29 04:20 UTC, ZeyuChen requested changes
@tianxin1860 @wawltor

2022-09-29 04:20 UTC, ZeyuChen commented on paddlenlp/taskflow/question_generation.py
> +           question_generation([{"context": "平安银行95511电话按9转报案人工服务。 1.寿险 :95511转1 2.信用卡 95511转2 3.平安银行 95511转3 4.一账通 95511转4转8 5.产险 95511转5 6.养老险团体险 95511转6 7.健康险 95511转7 8.证券 95511转8 9.车险报案95511转9 0.
不宜露出这类带有其他企业品牌的字眼作为注释，需要选择中立无关的

2022-09-29 04:20 UTC, ZeyuChen commented on paddlenlp/taskflow/question_generation.py
> +        # seq_len = paddle.to_tensor(batch['seq_len'], dtype='int64')
清除无用注释

2022-09-29 04:20 UTC, ZeyuChen commented on paddlenlp/taskflow/question_generation.py
> +        # for ids, scores in zip(ids_list, scores_list):
删除无用注释

2022-09-29 04:20 UTC, ZeyuChen commented on applications/question_generation/deploy/paddle_serving/README.md
> +input:  {'context': '平安银行95511电话按9转报案人工服务。 1.寿险 :95511转1 2.信用卡 95511转2 3.平安银行 95511转3 4.一账通 95511转4转8 5.产险 95511转5 6.养老险团体险 95511转6 7.健康险 95511转7 8.证券 95511转8 9.车险报案95511转9 0.重听', 'answer': '95511'}
是否有更中立点的case？

2022-09-29 11:22 UTC, westfish commented on paddlenlp/taskflow/question_generation.py
> +           question_generation([{"context": "平安银行95511电话按9转报案人工服务。 1.寿险 :95511转1 2.信用卡 95511转2 3.平安银行 95511转3 4.一账通 95511转4转8 5.产险 95511转5 6.养老险团体险 95511转6 7.健康险 95511转7 8.证券 95511转8 9.车险报案95511转9 0.
好的

2022-09-29 11:23 UTC, westfish commented on paddlenlp/taskflow/question_generation.py
> +        # seq_len = paddle.to_tensor(batch['seq_len'], dtype='int64')
好的

2022-09-29 11:24 UTC, westfish commented on paddlenlp/taskflow/question_generation.py
> +        # for ids, scores in zip(ids_list, scores_list):
好的

2022-09-29 11:43 UTC, westfish commented on applications/question_generation/deploy/paddle_serving/README.md
> +input:  {'context': '平安银行95511电话按9转报案人工服务。 1.寿险 :95511转1 2.信用卡 95511转2 3.平安银行 95511转3 4.一账通 95511转4转8 5.产险 95511转5 6.养老险团体险 95511转6 7.健康险 95511转7 8.证券 95511转8 9.车险报案95511转9 0.重听', 'answer': '95511'}
{"context": "奇峰黄山千米以上的山峰有77座，整座黄山就是一座花岗岩的峰林，自古有36大峰，36小峰，最高峰莲花峰、最险峰天都峰和观日出的最佳点光明顶构成黄山的三大主峰。", "answer": "莲花峰", "id": ""} 
"question": "黄山最高的山峰是什么峰？",

,{"context": "弗朗索瓦·韦达外文名：franciscusvieta国籍：法国出生地：普瓦图出生日期：1540年逝世日期：1603年12月13日职业：数学家主要成就：为近代数学的发展奠定了基础。", "answer": "法国", "id": ""}
"question": "著名的数学家韦达是哪国人？",

,{"context": "华山寺位于广东省陆丰市南塘镇，东连甲子待渡山，西接五峰山，南眺碣石玄武山、北览九九连峰笔架同朝拱。", "answer": "广东", "id": ""}
"question": "华山寺在哪个省？", 

,{"context": "韩国最大的岛屿,整个济州岛是一座典型的火山岛，120万年前开始火山活动而形成的岛屿，岛中央是通过火山爆发而形成的海拔1951米的韩国最高峰———汉拿山。海洋性气候的济州岛素有“韩国夏威夷”之称。<e>青瓦台<e>韩国总统府。韩国政治中心青瓦台最显著的特征就是它的靑瓦，一到青瓦台首先看到的是主楼的靑瓦。<e>龙头岩<e>龙头岩是200万前年熔岩喷发后冷却而形成的岩石。在济州岛。", "answer": "济州岛", "id": ""}
"question": "韩国最大的岛屿是哪个岛?", 

,{"context": "酒精是有机溶剂,比较稳定,不易于其它物质发生化学反应,但易挥发.所以只要密封的都没有什么问题", "answer": "密封", "id": ""}
"question": "酒精怎样保存",

2022-09-29 11:44 UTC, westfish commented on applications/question_generation/deploy/paddle_serving/README.md
> +input:  {'context': '平安银行95511电话按9转报案人工服务。 1.寿险 :95511转1 2.信用卡 95511转2 3.平安银行 95511转3 4.一账通 95511转4转8 5.产险 95511转5 6.养老险团体险 95511转6 7.健康险 95511转7 8.证券 95511转8 9.车险报案95511转9 0.重听', 'answer': '95511'}
又生成了5条，你看有没有合适的可以作为样例？

2022-09-29 11:45 UTC, westfish commented on docs/model_zoo/taskflow.md
> +* `max_length`：生成代码的最大长度，默认为128。
好的

2022-09-30 10:38 UTC, closed without merging