Improve CodeGen unittest
PaddlePaddle/PaddleNLP pull request #3371
Opened 2022-09-26 13:48 UTC by gongel

### PR types

Function optimization
### PR changes

Models
### Description

- Remove AttentionMask automatically generate
- Support token_type_ids

Fix: https://github.com/PaddlePaddle/PaddleNLP/pull/3348

2022-09-27 03:41 UTC, FrostML requested changes

2022-09-27 03:41 UTC, FrostML commented on paddlenlp/transformers/codegen/modeling.py
> +        if batch_size == 1 and past_length != 0:
不对。把 batch size 判断放到 attention mask 为 None 里面，这样即使动转静，也一定会提供 mask，那就不会存在潜在问题

2022-09-27 05:59 UTC, gongel commented on paddlenlp/transformers/codegen/modeling.py
> +        if batch_size == 1 and past_length != 0:
DONE and thx

2022-09-28 15:33 UTC, FrostML approved these changes

2022-09-28 16:29 UTC, ZeyuChen approved these changes

2022-09-28 17:31 UTC, merged