add keep_extend_vocab_only option
PaddlePaddle/PaddleNLP pull request #34
Opened 2021-02-23 12:34 UTC by joey12300

### PR types

New features
### PR changes

APIs
### Describe

* add keep_extend_vocab_only option
* simplify the embedding example doc

2021-02-23 17:44 UTC, ZeyuChen requested changes
参数名修改

2021-02-23 17:44 UTC, ZeyuChen commented on paddlenlp/embeddings/token_embedding.py
> +            Whether keep the extend vocabulary only, only effective if provides extended_vocab_path
only effective if provides extended_vocab_path
->
will be effective only if `extendted_vocab_path` provided.

2021-02-23 17:44 UTC, ZeyuChen commented on paddlenlp/embeddings/token_embedding.py
> +            Whether keep the extend vocabulary only, only effective if provides extended_vocab_path
keep_extend_vocab_only  -> keep_extended_vocab_only   
extended才是形容词，不然是两个动词连用表意错误

2021-02-24 02:01 UTC, joey12300 commented on paddlenlp/embeddings/token_embedding.py
> +            Whether keep the extend vocabulary only, only effective if provides extended_vocab_path
done

2021-02-24 14:06 UTC, ZeyuChen approved these changes
LGTM

2021-02-24 14:07 UTC, merged