unite electra pretrain, fine-tune and deploy
PaddlePaddle/PaddleNLP pull request #35
Opened 2021-02-24 11:10 UTC by jeff41404

1. electra模型支持全流程：预训练、fine-tuning和推理部署，并无缝衔接；
2. electra模型支持混合精度(float16)训练、支持一键切换float64训练；
3. electra模型支持断点恢复训练；
4. electra模型组网动静统一、支持动态图转静态图，支持静态图推理部署

2021-02-24 12:34 UTC, smallv0221 commented on paddlenlp/transformers/electra/tokenizer.py
> +    def tokenize(self, text):
还有一个function需要接入，build_offset_mapping_with_special_tokens()，参考BertTokenizer。

2021-02-24 12:34 UTC, smallv0221 commented on paddlenlp/transformers/electra/tokenizer.py
>          """
删除encode()方法，这个方法也继承PretrainedTokenizer就行。

2021-02-24 12:34 UTC, smallv0221 commented on paddlenlp/transformers/electra/tokenizer.py
>          End-to-end tokenization for Electra models.
注释里面有几处写的还是BERT，是不是需要改一下

2021-02-24 12:57 UTC, jeff41404 commented on paddlenlp/transformers/electra/tokenizer.py
> +    def tokenize(self, text):
已加上

2021-02-24 12:57 UTC, jeff41404 commented on paddlenlp/transformers/electra/tokenizer.py
>          """
已删除

2021-02-24 12:58 UTC, jeff41404 commented on paddlenlp/transformers/electra/tokenizer.py
>          End-to-end tokenization for Electra models.
之前好像有同学改过，已修改

2021-02-24 13:54 UTC, smallv0221 commented on paddlenlp/transformers/electra/tokenizer.py
辛苦在最上面在加一下HuggingFace的license，也参考BertTokenizer

2021-02-24 14:04 UTC, ZeyuChen requested changes
Finetune示例建议采用SST-2，同时推理部署示例采用文本分类

2021-02-24 14:04 UTC, ZeyuChen commented on examples/language_model/electra/README.md
> +使用../glue/run_glue.py运行，详细可参考../glue/README.md，有两种方式：
这里的路径指引好像不太准确

2021-02-24 14:04 UTC, ZeyuChen commented on examples/language_model/electra/README.md
> +以 GLUE/SST-2 任务为例，启动 Fine-tuning 的方式如下（`paddlenlp` 要已经安装或能在 `PYTHONPATH` 中找到）：
`paddlenlp` 要已经安装或能在 `PYTHONPATH` 中找到
应该不用强调这点

2021-02-24 14:04 UTC, ZeyuChen commented on examples/language_model/electra/README.md
> +    --input_model_dir ./pretrain_model/model_40000.pdparams/ \
部署导出的模型，是否应该以--output_dir下finetune后的模型产出为示例比较合理。而不是以与训练阶段的参数。因为部署都是针对下游finetune的模型进行部署

2021-02-24 14:04 UTC, ZeyuChen commented on examples/language_model/electra/README.md
> +对于每1句话模型推理分别给出1个推理结果，即Discriminator的Replaced Token Detection(RTD)任务结果，是由0和1组成的list，list长度等于句子长度加2（因推理时会在每句话首尾添加特殊符号[CLS]和[SEP]，和训练时的数据处理一致），0表示句子中对应位置上的单词没有被替换过（是原文），1表示句子中对应位置上的单词是被替换过的（不是原文&不符合语言逻辑
感觉以这个场景作为ELECTRA的部署示例不太准确，因为用户需要的是针对下游的finetune任务
如文本分类，序列标注等，以ELECTRA判别的输出作为推理部署不是一个主流的用户用法。

2021-02-24 14:04 UTC, ZeyuChen commented on examples/language_model/electra/deploy/python/predict.py
> +def parse_args():
为了减少args这地方占用的代码行数
建议使用#yapf: disable 和 #yapf: enable的block隔离出来
改为单行的方式来呈现

2021-02-24 14:04 UTC, ZeyuChen commented on examples/language_model/electra/deploy/python/predict.py
> +    #import pdb; pdb.set_trace()
应该删除无用的代码。
建议使用SST-2最容易理解的情感分类数据作为部署预测示例比较好

2021-02-24 14:04 UTC, ZeyuChen commented on examples/language_model/electra/README.md
> +对于每1句话模型推理分别给出1个推理结果，即Discriminator的Replaced Token Detection(RTD)任务结果，是由0和1组成的list，list长度等于句子长度加2（因推理时会在每句话首尾添加特殊符号[CLS]和[SEP]，和训练时的数据处理一致），0表示句子中对应位置上的单词没有被替换过（是原文），1表示句子中对应位置上的单词是被替换过的（不是原文&不符合语言逻辑
可以考虑使用GLUE/SST-2情感分类的数据集作为部署推理的示例更好。
这个是主流的NLP场景应用

2021-02-24 14:04 UTC, ZeyuChen commented on examples/language_model/electra/README.md
> +使用../glue/run_glue.py运行，详细可参考../glue/README.md，有两种方式：
建议Finetune这里直接使用简单的SST-2任务来示例，方便与后面的预测推理部署打通。

2021-02-25 09:29 UTC, jeff41404 commented on paddlenlp/transformers/electra/tokenizer.py
已添加

2021-02-25 09:37 UTC, jeff41404 commented on examples/language_model/electra/README.md
> +使用../glue/run_glue.py运行，详细可参考../glue/README.md，有两种方式：
因为预训练、Fine-tuning 和 推理部署均在不同的目录，所以在文档第3章已说明：如下所有命令均假设在 PaddleNLP/examples/language_model/electra/ 下执行，包括预训练、Fine-tuning 和 推理部署的命令。且这些相对路径均已手工验证过

2021-02-25 10:36 UTC, jeff41404 commented on examples/language_model/electra/README.md
> +以 GLUE/SST-2 任务为例，启动 Fine-tuning 的方式如下（`paddlenlp` 要已经安装或能在 `PYTHONPATH` 中找到）：
之前是参考bert写的，现已去掉

2021-02-25 10:37 UTC, jeff41404 commented on examples/language_model/electra/README.md
> +    --input_model_dir ./pretrain_model/model_40000.pdparams/ \
已修改预测部署的input_model_dir为finetune后的模型

2021-02-25 10:37 UTC, jeff41404 commented on examples/language_model/electra/README.md
> +对于每1句话模型推理分别给出1个推理结果，即Discriminator的Replaced Token Detection(RTD)任务结果，是由0和1组成的list，list长度等于句子长度加2（因推理时会在每句话首尾添加特殊符号[CLS]和[SEP]，和训练时的数据处理一致），0表示句子中对应位置上的单词没有被替换过（是原文），1表示句子中对应位置上的单词是被替换过的（不是原文&不符合语言逻辑
推理部署的示例已修改为SST-2

2021-02-25 10:41 UTC, jeff41404 commented on examples/language_model/electra/deploy/python/predict.py
> +    #import pdb; pdb.set_trace()
已删除

2021-02-25 13:38 UTC, jeff41404 commented on examples/language_model/electra/README.md
> +使用../glue/run_glue.py运行，详细可参考../glue/README.md，有两种方式：
按照讨论，从长远考虑，已建立electra/run_glue.py，readme中相关路径已修改

2021-02-25 13:56 UTC, jeff41404 commented on examples/language_model/electra/deploy/python/predict.py
> +def parse_args():
占了较多的行是pre-commit修改，已尽量精简，目前只有9个参数

2021-02-25 14:55 UTC, ZeyuChen reviewed
留了一些意见

2021-02-25 14:55 UTC, ZeyuChen commented on examples/language_model/electra/deploy/python/predict.py
> +        # run 运行predictor
不要在代码中出现中文字符。注释尽量使用全英文，否则容易在windows场景中运行python遇到中文编码问题。

2021-02-25 14:55 UTC, ZeyuChen commented on examples/language_model/electra/export_model.py
> +MODEL_CLASSES = {"electra": (ElectraForTotalPretraining, ElectraTokenizer), }
这一变量是否已经无用了？

2021-02-25 14:55 UTC, ZeyuChen commented on examples/language_model/electra/run_glue.py
>      # Truncate to the truncate_length,
下面这段注释是否是有意义的？

2021-02-25 14:55 UTC, ZeyuChen commented on examples/language_model/electra/run_pretrain.py
> +                    if len(log_list) > 0:
为什么要使用这种方法额外存log，而不使用户自己在外自己用重定向的方式保存log？

2021-02-25 14:55 UTC, ZeyuChen commented on paddlenlp/transformers/electra/modeling.py
>          # todo: we can remove 4 lines after when CrossEntropyLoss(reduction='mean') improved
这一个TODO最新的Paddle版本仍然是这样吗？

2021-02-25 14:55 UTC, ZeyuChen commented on examples/language_model/electra/run_glue.py
> +FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
这里的logger单独拉3行代码出来的目的是？

2021-02-25 14:55 UTC, ZeyuChen commented on examples/language_model/electra/run_glue.py
>  MODEL_CLASSES = {
如果这个目录专门针对electra的话，我们是否还需要用MODEL_CLASSES的方式来管理？

2021-02-25 14:55 UTC, ZeyuChen commented on examples/language_model/electra/run_glue.py
> +    parser.add_argument(
这一args是否可以删除？

2021-02-26 03:00 UTC, jeff41404 commented on examples/language_model/electra/deploy/python/predict.py
> +        # run 运行predictor
已去除中文

2021-02-26 03:03 UTC, jeff41404 commented on examples/language_model/electra/export_model.py
> +MODEL_CLASSES = {"electra": (ElectraForTotalPretraining, ElectraTokenizer), }
原来考虑用于export pretrain model，目前主要是export fine-tune model，已去除

2021-02-26 03:05 UTC, jeff41404 commented on examples/language_model/electra/run_glue.py
>      # Truncate to the truncate_length,
这里应该是之前其它同学关于tokenizer升级的改动，已删除

2021-02-26 03:06 UTC, jeff41404 commented on examples/language_model/electra/run_pretrain.py
> +                    if len(log_list) > 0:
这样log能够同时显示在终端和文件中，huggingface也是类似实现

2021-02-26 03:07 UTC, jeff41404 commented on paddlenlp/transformers/electra/modeling.py
>          # todo: we can remove 4 lines after when CrossEntropyLoss(reduction='mean') improved
是的，还没有完全修复

2021-02-26 03:10 UTC, jeff41404 commented on examples/language_model/electra/run_glue.py
> +FORMAT = '%(asctime)s-%(levelname)s: %(message)s'
如沟通，这些diff是先删除run_glue再从glue/run_glue导致的，其实本次重点是预训练和fine-tuning部分，没有修改run_glue

2021-02-26 03:11 UTC, jeff41404 commented on examples/language_model/electra/run_glue.py
>  MODEL_CLASSES = {
如沟通，这些diff是先删除run_glue再从glue/run_glue导致的，其实本次重点是预训练和fine-tuning部分，没有修改run_glue，之后可以再考虑精简

2021-02-26 03:12 UTC, jeff41404 commented on examples/language_model/electra/run_glue.py
> +    parser.add_argument(
如沟通，这些diff是先删除run_glue再从glue/run_glue导致的，其实本次重点是预训练和fine-tuning部分，没有修改run_glue

2021-02-26 04:58 UTC, ZeyuChen approved these changes
LGTM

2021-02-26 04:58 UTC, merged