Enable Model and Tokenizer to directly load paddlepaddle models from huggingface hub
PaddlePaddle/PaddleNLP pull request #3786
Opened 2022-11-16 12:38 UTC by sijunhe

### PR types
New features

### PR changes
APIs

### Description
Enable Model and Tokenizer to directly load paddlepaddle models from huggingface hub

#### Test Tokenizer
```
# load from HF works
tokenizer = AutoTokenizer.from_pretrained("PaddlePaddle/ernie-3.0-nano-zh", from_hf_hub=True)
# load official pre-trained works
tokenizer = AutoTokenizer.from_pretrained("ernie-3.0-nano-zh")
tokenizer.save_pretrained("temp_test_tokenizer")
# load from local
tokenizer = AutoTokenizer.from_pretrained("temp_test_tokenizer")
```

#### Test Model
```
# load from HF works
model = AutoModel.from_pretrained("PaddlePaddle/ernie-3.0-nano-zh", from_hf_hub=True)
# load official pre-trained works
model = AutoModel.from_pretrained("ernie-3.0-nano-zh")
model.save_pretrained("temp_test_tokenizer")
# load from local
model = AutoModel.from_pretrained("temp_test_tokenizer")
```

2022-11-17 02:33 UTC, wj-Mcat requested changes
你的这个 pr 我觉得非常棒，看起来很令人兴奋，不过我除了留的 comment，还有几点想跟你讨论：

1. 你现在是直接在老版本的from_pretrained（新版本为`from_pretrained_v2`）上面做的，可是后面的主流模型都会迁移到新版本上，所以我感觉这部分的调整是否直接在新的接口上来完成是否比较好？
2. `from_hf_hub`的核心逻辑应该是数据源的问题，那是否可以把这部分的逻辑抽离成一个单独的函数来完成下载的这个工作呢？
3. 是否不用添加`from_hf_hub`这个参数，当在框架(pretrained_init_configuration)本地、community 都没找到的情况下，是否可以直接默认去 huggingface 上面去找呢？

2022-11-17 02:33 UTC, wj-Mcat commented on paddlenlp/transformers/auto/modeling.py
> +
这个方法在我的`cli` PR里面有，后续此类方法可抽离成utils公共模块。

2022-11-17 02:33 UTC, wj-Mcat commented on paddlenlp/transformers/auto/modeling.py
> +
由于此方法比较通用，我建议可放到`paddlenlp/transformers/utils.py`模块当中，这样其他模块也可以复用，你觉得呢？

2022-11-17 02:33 UTC, wj-Mcat commented on paddlenlp/transformers/auto/modeling.py
> +
另外，目前为了和 hf 对齐，我们也是兼容：`architectures`这个字段的，所以在这个模块也是考虑此字段的信息的，特别是针对于未来新模型。

2022-11-17 02:33 UTC, wj-Mcat commented on paddlenlp/transformers/auto/modeling.py
> +                    **kwargs)
如果`config_file`不存在的话，是否需要给一个 warning 或者 error 呢？

因为如果说是不存在的话，理论上应该终止模型的初始化逻辑处理。

2022-11-17 02:33 UTC, wj-Mcat commented on paddlenlp/transformers/auto/tokenizer.py
> +                'We use pattern recognition to recognize the Tokenizer class.')
这类提示信息都应该基于`logger`来提供给开发者吧，是否需要将`print`改成`logger.info`呢？

2022-11-17 02:33 UTC, wj-Mcat commented on paddlenlp/transformers/auto/tokenizer.py
> +                if pattern in pretrained_model_name_or_path.lower():
我在想，这里的`pattern in name_or_path`这个操作会不会太松散，比如在以下情况下就会出现问题：

```python
cls._name_mapping = {
    "BertTokenizer": "bert",
    "AlbertTokenizer": "albert",
    "RobertaTokenizer": "roberta",
}
pretrained_model_name_or_path = "tinybert-4l-312d"
```

2022-11-17 13:10 UTC, sijunhe commented on paddlenlp/transformers/auto/tokenizer.py
> +                if pattern in pretrained_model_name_or_path.lower():
since this is the original code, it's out of scope for this PR. I added a TODO and referenced your comment.

2022-11-17 13:12 UTC, sijunhe commented on paddlenlp/transformers/auto/modeling.py
> +                    **kwargs)
added a warning

2022-11-17 13:19 UTC, sijunhe commented
> 你的这个 pr 我觉得非常棒，看起来很令人兴奋，不过我除了留的 comment，还有几点想跟你讨论：
> 
> 1. 你现在是直接在老版本的from_pretrained（新版本为`from_pretrained_v2`）上面做的，可是后面的主流模型都会迁移到新版本上，所以我感觉这部分的调整是否直接在新的接口上来完成是否比较好？
> 2. `from_hf_hub`的核心逻辑应该是数据源的问题，那是否可以把这部分的逻辑抽离成一个单独的函数来完成下载的这个工作呢？
> 3. 是否不用添加`from_hf_hub`这个参数，当在框架(pretrained_init_configuration)本地、community 都没找到的情况下，是否可以直接默认去 huggingface 上面去找呢？
> 4. 是否需要针对于调整添加一些单测来保证稳定性呢？

1. added the logic in `from_pretrained_v2` as well, which is tested through the `bert` model
2-3. discussed offline that we need `from_hf_hub`
4. added integration test

2022-11-17 13:21 UTC, sijunhe commented on paddlenlp/transformers/auto/modeling.py
> +
out of the scope for this PR but added a TODO

2022-11-17 13:23 UTC, sijunhe commented on paddlenlp/transformers/auto/modeling.py
> +                    **kwargs)
added a logger.warning messasge

2022-11-18 08:54 UTC, wj-Mcat approved these changes, later dismissed

2022-11-18 10:30 UTC, wj-Mcat approved these changes

2022-11-20 06:40 UTC, merged