add T5Config to T5Model
PaddlePaddle/PaddleNLP pull request #3856
Opened 2022-11-22 04:20 UTC by Yam0214

### PR types

New features
### PR changes

Models
### Description

add t5 config and support `config.get(key, default)`[#3844](https://github.com/PaddlePaddle/PaddleNLP/issues/3844)

2022-11-22 07:36 UTC, wj-Mcat requested changes
一些小建议

2022-11-22 07:36 UTC, wj-Mcat commented on paddlenlp/transformers/configuration_utils.py
> +
新增的这个函数可以在`tests/transformers/tes_configuration_utils.py`里面添加对应的测试。

可以参考：`test_parse_config_and_model_with_model_and_kwargs`等测试风格来。

尽量保证新增的方法都需要有测试覆盖到，从而保证其运行的正确性。

2022-11-22 07:36 UTC, wj-Mcat commented on paddlenlp/transformers/t5/configuration.py
> +                 enable_recompute=False,
建议把type hinting 这个 feature 添加上，可以参考：

https://github.com/PaddlePaddle/PaddleNLP/blob/eeb5cfeed5a2adc91b41d90063b8b3efbe585b9f/paddlenlp/transformers/bert/configuration.py#L394-L411

这样无论从代码智能提示和阅读性上而言都有一定的提升。

2022-11-22 11:02 UTC, Yam0214 commented on paddlenlp/transformers/t5/configuration.py
> +                 enable_recompute=False,
已添加测试，并且加上了 type hinting

2022-11-25 04:59 UTC, FrostML commented on paddlenlp/transformers/t5/configuration.py
> +        self.is_gated_act = act_info[0] == "gated"
上面这两个似乎都没有用到？

2022-11-25 04:59 UTC, FrostML commented on paddlenlp/transformers/t5/modeling.py
> +        config (:class:`T5tConfig`):
typo

2022-11-25 04:59 UTC, FrostML commented on tests/transformers/test_configuration_utils.py
> +#         self.b = config.b
这些代码注释掉是什么情况？

2022-11-25 05:30 UTC, Yam0214 commented on tests/transformers/test_configuration_utils.py
> +#         self.b = config.b
> 上面这两个似乎都没有用到？

确实没有用到，已删除

> typo

已更正

> 这些代码注释掉是什么情况？

`parse_config`函数未实现，暂时注释相关的代码等京京修复

2022-11-25 09:28 UTC, FrostML submitted a review, later dismissed

2022-11-28 06:23 UTC, wj-Mcat approved these changes, later dismissed

2022-12-01 09:17 UTC, wj-Mcat requested changes
就type hint，其它没什么意见

2022-12-01 09:17 UTC, wj-Mcat commented on paddlenlp/transformers/t5/modeling.py
> +    def __init__(self, config):
对于新版本，建议还是加上type hint: 尽量给函数写上类型注释，比如这里就需要写成：

```python
def __init__(self, config: T5Config):
```

2022-12-01 09:17 UTC, wj-Mcat commented on paddlenlp/transformers/t5/modeling.py
> +    def __init__(self, config):
下面的也是一样，添加上类型注释即可。

2022-12-01 09:19 UTC, FrostML commented on paddlenlp/transformers/configuration_utils.py
> +    # TODO
补充下 TODO 的内容。

2022-12-01 09:19 UTC, FrostML commented on paddlenlp/transformers/configuration_utils.py
> +        Return the value for key if config class has the attribute , else default. If default is not given, it defaults to None, so that this method never raises a AttributeError.
如果不是格式检查导致，文档还是适当长度换个行，太长确实阅读上不方便

2022-12-01 09:29 UTC, FrostML approved these changes, later dismissed

2022-12-01 09:53 UTC, FrostML approved these changes

2022-12-01 09:55 UTC, wj-Mcat approved these changes

2022-12-02 00:57 UTC, merged