[HF] improve compatibility of model-config
PaddlePaddle/PaddleNLP pull request #3887
Opened 2022-11-24 04:15 UTC by wj-Mcat

### PR types

Function optimization

### PR changes

APIs

### Description

make it possible to load config.json from hf hub

目前是准备放：ernie/ernie-m/Pegasus 三个模型，前两者在 hf 上没有，所以不用做兼容；后者的兼容实现方法也已经写了，可是没有办法去hf 上加载model_state.pdparams文件。

2022-11-24 05:39 UTC, sijunhe commented
通过这个`map_hf_config`来完成hf_config到paddle的model_config确实是一种方案，能够解决问题。但是我觉得这是一个bandage solution, 后期得一直维护，也没做到真正的兼容。
目前paddlenlp的PretrainedConfig刚刚开始做，没有什么历史包袱。这个时候我们应该做一个一劳永逸的方案，直接和hf那边完全兼容。我提出一个思路，你看看可不可行:
1. 在PretrainedConfig中，直接把我们的model_config.json改名成config.json, 直接兼容。我看大部分的字段我们其实和hf是一样的，小部分的不同(init_class vs architecture)可以在PretrainedConfig加一些简单的逻辑里解决
2. 对于我们希望支持的模型, 在1的基础上, 通过整合PretrainedConfig + from_pretrained_v2来完成兼容. 后续我们每在一个新的模型上支持from_pretrained_v2, 同时也就支持了hf
3. 这里我们要做好测试，尤其是integration test （用https://github.com/PaddlePaddle/PaddleNLP/blob/develop/tests/transformers/test_modeling_common.py#L573). 至于你说的"可是没有办法去hf 上加载model_state.pdparams文件", 我们可以在ernie的repo(改成config.json后) 里测, 也可以自己造一个既有pytorch.bin又要model_state.pdparams的repo来测兼容性

2022-11-24 07:13 UTC, wj-Mcat commented
在 PretrainedConfig 解决方案实现代价是最小，而且也可持续的。可是目前有很多模型还是沿用老的`from_pretrained`，特别是`Ernie`系列的，近期有很多工作都在这个上面，迁移的代价有点大，这又是为什么现在还是需要支持老版本`from_pretrained`的原因。不过，两者肯定都是要加的。

2022-11-24 09:38 UTC, wj-Mcat commented
我现在通过`config_attribute_mapping`字段来做diff 字段的映射，其它字段可直接使用。这样就是最小代价完成config 的映射了。  @sijunhe 有时间 review 再一下

2022-11-25 01:54 UTC, gongel commented on paddlenlp/transformers/model_utils.py
> +                config[paddle_key] = config.pop(paddle_key, None) or config.pop(
`config_attribute_mapping`是指hf到pd的映射吗？和`configuration.py`的`attribute_map`字段有些命名类似

2022-11-29 03:06 UTC, wj-Mcat commented on paddlenlp/transformers/model_utils.py
> +                config[paddle_key] = config.pop(paddle_key, None) or config.pop(
确实是指 hf 到 pd 的映射，命名有些类似，在这点上我感觉还是需要调整一下：`hf_config_map` ？ 这样觉得如何？

2022-11-29 07:52 UTC, wj-Mcat commented
这边在测试的时候发现另外一个问题：在 paddlenlp 中某一个模型中实现了不同的 tokenizer，如chinese tokenizer 和 bpe tokenizer，此时兼容性测试也会出现问题，其中在 roberta 模型当中就会出现问题：

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("roberta-base")
tokenizer.save_pretrained(tempdir)

from paddlenlp.transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(tempdir)
```

错误的原因在于RobertaTokenizer其实只是一个分发器，重写了from_pretrained函数之后根据model-name 返回不同类型的 tokenizer，可是在 hf 当中只会有一个tokenizer：RobertaTokenizer 。

2022-12-07 04:18 UTC, sijunhe requested changes
几个大的点:
1. 统一命名: 我建议统一命名standard config还有legacy config, 取消之前的hf config, model_config等等名字
2. 我建议我们仅把逻辑加入from_pretrained_v2, 尽量不更改老的from_pretrained, 后续通过让所有的模型支持PretrainedConfig来达到对于standard config的支持
3. 我们这里需要一些end2end的单测
- 在模型common_test中加入新的test_save_load测试（只对支持PretrainedConfig的模型开启），主要测试模型是否可以兼容新老config. 大概逻辑可以这样: standard config远程加载测试模型, 通过legacy config (这里可能要在from_pretrained里加入一个force_legacy_config选项)远程加载模型, 然后两个模型应该一样
- 对于已经支持PretrainedConfig的模型，save_pretrained应该产出standard config

2022-12-07 04:18 UTC, sijunhe commented on tests/transformers/test_compatibility.py
> +    def run_compatibility_test(self, model_name: str):
1. 统一用TestCase中的self.assert吧
2. 如果没有特殊理由的话, import还是统一放顶上吧, 用`import AutoTokenizer as HfAutoTokenizer `分开paddle和hf的同一名字的class

2022-12-07 04:18 UTC, sijunhe commented on tests/transformers/test_compatibility.py
> +            assert hf_tokens[index] == tokens[index]
python的list支持__eq__, 所以可以直接用hf_tokens == tokens

2022-12-07 04:18 UTC, sijunhe commented on tests/transformers/test_configuration_utils.py
> +            pass
没看懂这里为啥要包一层

2022-12-07 04:18 UTC, sijunhe commented on tests/transformers/bert/test_configuration.py
> +        config = BertConfig.from_pretrained("prajjwal1/bert-tiny", from_hf_hub=True)
这里用`hf-internal-testing/tiny-random-BertModel`, https://huggingface.co/hf-internal-testing/tiny-random-BertModel

2022-12-07 04:18 UTC, sijunhe commented on paddlenlp/transformers/ernie/modeling.py
> +
这个应该是之前留下来的，应该删掉

2022-12-07 04:18 UTC, sijunhe commented on paddlenlp/transformers/model_utils.py
> -# TODO(fangzeyang) Temporary fix and replace by paddle framework downloader later
确认一下这个解决了没有，没解决的话TODO保留

2022-12-07 04:18 UTC, sijunhe commented on paddlenlp/transformers/configuration_utils.py
> +def do_standard_config_map(standard_config_map: Dict[str, str], config: Dict[str, Any]) -> Dict[str, Any]:
convert_to_legacy_config

2022-12-07 04:18 UTC, sijunhe commented on paddlenlp/transformers/model_utils.py
> +            resource_files["config_file"] = cls.config_file
这里得讨论一下。
我的想法是, 我们只在`from_pretrained_v2`里支持standard_config, `from_pretrained_v2`仍然由model_config来加载。后续模型只需要使用PretraindConfig就可以，这样子说来，是不是`from_pretrained_v2`以外都不需要加上standard config的逻辑?

2022-12-07 04:50 UTC, wj-Mcat commented on paddlenlp/transformers/configuration_utils.py
> +def do_standard_config_map(standard_config_map: Dict[str, str], config: Dict[str, Any]) -> Dict[str, Any]:
这个名称好，我就换这个了。

2022-12-07 04:53 UTC, wj-Mcat commented on paddlenlp/transformers/model_utils.py
> +            resource_files["config_file"] = cls.config_file
其实也是可以的，我的想法是由于 PretrainedConfig 的落地效率比较慢，那咱们得hf 兼容难道要一直等吗？所以老版本也加上了。如果咱们的速度后面再快一点，其实就不需要做这块的兼容了。

2022-12-07 04:54 UTC, wj-Mcat commented on paddlenlp/transformers/model_utils.py
> -# TODO(fangzeyang) Temporary fix and replace by paddle framework downloader later
@ZHUI 说现在这阶段其实是可以用我们自己的了，所以可以直接移除，@wawltor 你觉得呢？

2022-12-07 04:55 UTC, wj-Mcat commented on paddlenlp/transformers/ernie/modeling.py
> +
嗯嗯，这个没注意到，这个确实是应该删掉的。

2022-12-07 04:56 UTC, wj-Mcat commented on tests/transformers/bert/test_configuration.py
> +        config = BertConfig.from_pretrained("prajjwal1/bert-tiny", from_hf_hub=True)
好，那就用这个。

2022-12-07 05:00 UTC, wj-Mcat commented on tests/transformers/test_configuration_utils.py
> +            pass
如果不用继承的关系包一层的话，那就是在单测当中直接修改`RoFormerv2ForTokenClassification`类的静态属性：`standard_config_map`，此时会影响其它单测的运行：不想执行完这个单测之后，其它单测中使用到RoFormerv2ForTokenClassification类时，config 出现问题。

2022-12-07 05:01 UTC, wj-Mcat commented on tests/transformers/test_compatibility.py
> +            assert hf_tokens[index] == tokens[index]
嗯嗯，好，这块我来调整一下，之前我一直怀疑数组能否直接 equal 。

2022-12-07 05:10 UTC, wj-Mcat commented on tests/transformers/test_compatibility.py
> +    def run_compatibility_test(self, model_name: str):
self.assert*的使用主要是为了更好的生成测试报告，而且这个仅限于在 uniitest 里面。而现在是切换成pytest 来执行单测，它对于assert 和 self.assert 的**报告生成效果**是一致的。

其实我最主要的想法是，用 assert 代码更简洁易读。

参考链接：

* https://docs.pytest.org/en/7.1.x/how-to/assert.html

2022-12-09 12:13 UTC, sijunhe commented
implemented through other PRs

2022-12-09 12:13 UTC, closed without merging