[ModelZoon] Refactor GPT in Model Zoo
PaddlePaddle/PaddleNLP pull request #3917
Opened 2022-11-27 14:30 UTC by wj-Mcat

### PR types

Breaking changes

### PR changes

APIs

### Description

GPT 的 Model Zoo 升级

2023-01-03 12:24 UTC, wawltor commented on model_zoo/gpt/README.md
> +CUDA_VISIBLE_DEVICES=0 python run_pretrain.py --config=./configs/default.yaml
这里保留一个命令行即可

2023-01-03 12:24 UTC, wawltor commented on model_zoo/gpt/args.py
> +    if paddle.get_device() == "cpu":
这里的判断过于绝对吧，目前NPU、XPU的硬件设配也是PaddleNLP重点硬件适配

2023-01-03 12:24 UTC, wawltor commented on model_zoo/gpt/configs/default.yaml
> +  device: cpu
这里的device是不是改成gpu比较合适？

2023-01-03 12:24 UTC, wawltor commented on model_zoo/gpt/configs/default.yaml
> +  device: cpu
同上

2023-01-03 12:24 UTC, wawltor commented on model_zoo/gpt/run_pretrain.py
> +class ModelArguments(TrainingArguments):
我看这里的参数全部集中在ModelArguments，原因是什么了？

2023-01-03 12:24 UTC, wawltor commented on model_zoo/gpt/run_pretrain.py
> +    def evaluate(self, eval_dataset=None, ignore_keys=None, metric_key_prefix: str = "eval"):
这里重载Trainer的目的是什么了？

2023-01-04 03:02 UTC, wj-Mcat commented on model_zoo/gpt/README.md
> +CUDA_VISIBLE_DEVICES=0 python run_pretrain.py --config=./configs/default.yaml
ok

2023-01-04 03:13 UTC, wj-Mcat commented on model_zoo/gpt/args.py
> +    if paddle.get_device() == "cpu":
关于这块代码的作用我想解释一下：

```python
def get_device(device: str):
    if device == "cpu":
        return "cpu"
    if paddle.get_device() == "cpu":
        logger.warning("not detect gpu but receive GPU related params, we will run the model on cpu")
        return "cpu"
    return device
```

我想处理的 case：

1. 如果运行环境是 cpu，可是配置中写的 gpu，将会自动切换成cpu 的环境，这样就避免了开发者再次调整的工作。
2. 如果运行环境是 npu，`paddle.get_device()` 会直接返回`npu:0`之类的字符串，所以这里也会直接跳过。
3. 如果运行环境是 非 cpu，可是配置中使用了 cpu 的环境，还是会继续使用 cpu 的环境。

所以，这里的判断并非绝对，而是判断了多种不同环境下的 case 的代码，你觉得呢 @wawltor

2023-01-04 03:33 UTC, wj-Mcat commented on model_zoo/gpt/configs/default.yaml
> +  device: cpu
好，我都调整过来。

2023-01-04 03:34 UTC, wawltor commented on model_zoo/gpt/args.py
> +    if paddle.get_device() == "cpu":
如果用户设置的device是NPU，但是运行环境是CPU环境，上面的报错就有点奇怪

2023-01-04 03:52 UTC, wj-Mcat commented on model_zoo/gpt/run_pretrain.py
> +class ModelArguments(TrainingArguments):
这是跟 @ZHUI 沟通之后决定做的一个尝试，思考如下：

1. Arguments 的统一主要体现在 common args 和 model-args，前者使用内置好的统一参数配置，后者针对于不同模型添加自定义参数：ModelArguments。 虽然是通过继承的方式放在一个类里面了，可都是在sys.argv上面解析，所以效果是一模一样的。
2. 其实我（初次使用trainer 的参数）在写training_args和model_args的时候时常弄混某参数到底是在training_args还是在model_args中，所以在想，既然是 args，为何不能是同一的获取入口呢？所以就直接使用继承的方式统一了入口。
3. 分开解析无法很好的实现 [type hint](https://peps.python.org/pep-0484/) ， type hint 是属于python 编程中最基础的一个编程体验之一，可是在 [paddle 的 Tensor](https://github.com/PaddlePaddle/Paddle/issues/45979) 中并没有实现，不过也已经在实现的路上了。  说这么多，其实是在强调 type hint 也是属于基础功能（开发体验）以及其重要性，我是这样解决的：


* 以前的写法

> 参考：[trainer.md](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/docs/trainer.md#trainer%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95%E4%BB%8B%E7%BB%8D).
```python
parser = PdArgumentParser(TrainingArguments, DataArguments)
(training_args, data_args) = parser.parse_args_into_dataclasses()
```
在编码时，training_args 属于Any 类型，是没有任何代码智能提示的。

* 现在的写法：

```python
model_args: ModelArguments = PdArgumentParser([ModelArguments]).parse_args_into_dataclasses()[0]
```

此时model_args可具备type hint的基础功能，IDE 都可推断出其所有子属性。

2023-01-04 03:53 UTC, wj-Mcat commented on model_zoo/gpt/run_pretrain.py
> +    def evaluate(self, eval_dataset=None, ignore_keys=None, metric_key_prefix: str = "eval"):
这个是参考ernie/run_pretrained中的Trainer，因为在 evaluation 的时候有自定义的逻辑，这个也是和 @ZHUI 沟通之后的做法。

2023-01-04 05:59 UTC, wawltor approved these changes, later dismissed
LGTM

2023-01-04 07:19 UTC, ZHUI commented on model_zoo/gpt/run_pretrain.py
> +class ModelArguments(TrainingArguments):
我说一下。
1、你建议 [type hint](https://peps.python.org/pep-0484/)  很好。
但是，看是不是有其他方式可以做到，至少目前这样处理的话不是很好。

2、拆分，是有意义的。把一些参数拆解开，会更加清晰。
这里如果是为了你迁移方便的话，先和在一起也不是不行。

> 在写training_args和model_args的时候时常弄混某参数到底是在training_args还是在model_args中
3、原则上，训练需要的控制参数都在 training_args 中。

2023-01-04 07:24 UTC, ZHUI commented on model_zoo/gpt/run_pretrain.py
> +    )
很多参数在 trainer 里面已经有了。
```suggestion
    model_name_or_path: str = field(default="gpt2-en", metadata={"help": ""})
    max_seq_len: int = field(default=128, metadata={"help": "max sequence length"})
    input_dir: str = field(default="", metadata={"help": "input idr of dataset"})
    to_static: bool = field(default=False, metadata={"help": "whether use static pretraining mode."})
    min_lr: float = field(default=1e-5, metadata={"help": "The initial min learning rate for Adam."})
    split: str = field(default="949,50,1", metadata={"help": "Train/valid/test data split."})
```

2023-01-04 07:24 UTC, ZHUI commented on model_zoo/gpt/run_pretrain.py
> +    )
比如剩下的几个参数
ModelArguments
```python
    model_name_or_path: str = field(default="gpt2-en", metadata={"help": ""})
    max_seq_len: int = field(default=128, metadata={"help": "max sequence length"})
    to_static: bool = field(default=False, metadata={"help": "whether use static pretraining mode."})
```

TrainingArguments
```python
    min_lr: float = field(default=1e-5, metadata={"help": "The initial min learning rate for Adam."})
```
DataArguments
```python
    input_dir: str = field(default="", metadata={"help": "input idr of dataset"})
    split: str = field(default="949,50,1", metadata={"help": "Train/valid/test data split."})
```

2023-01-04 07:42 UTC, ZHUI requested changes

2023-01-04 07:42 UTC, ZHUI commented on model_zoo/gpt/run_pretrain.py
> +    # support: python run_pretrain.py --config=./configs/default.yaml
https://github.com/huggingface/transformers/blob/1e3f17b5abcc6452ec6c9a742375975874978f3e/src/transformers/hf_argparser.py#L395-L413

看能不能直接用 argparser 的 parse_json_file ？

现在这样很丑

2023-01-05 12:13 UTC, wj-Mcat commented on model_zoo/gpt/run_pretrain.py
> +    # support: python run_pretrain.py --config=./configs/default.yaml
已经取消掉了config file 的支持，所以不需要parse_json_file 。

2023-01-05 12:23 UTC, wj-Mcat commented on model_zoo/gpt/run_pretrain.py
> +    )
你的建议是将这个拆分成不同的 dataclass 来处理吧。

2023-01-06 08:00 UTC, wj-Mcat commented on model_zoo/gpt/run_pretrain.py
> +    )
我在最新的commit 当中拆分成不同args 来处理了。

2023-01-06 08:37 UTC, wawltor approved these changes
LGTM

2023-01-06 08:39 UTC, ZHUI approved these changes

2023-01-06 08:40 UTC, merged

2023-02-07 04:00 UTC, ZHUI commented on model_zoo/gpt/run_pretrain.py
> +        start_time = time.time()
eval_iters 呢？

2023-02-07 04:00 UTC, ZHUI commented on model_zoo/gpt/run_pretrain.py
> +    if training_args.weight_decay == "none":
这个是 lr schedule

2023-02-07 04:00 UTC, ZHUI commented on model_zoo/gpt/run_pretrain.py
> +    model = GPTForPretraining.from_pretrained(model_args.model_name_or_path)
加载训练好的模型参数，来做预训练？

2023-02-07 04:00 UTC, ZHUI commented on model_zoo/gpt/run_pretrain.py
> -        grad_clip=clip,
clip 为什么删掉了吗？