Update README.md
PaddlePaddle/PaddleNLP pull request #3978
Opened 2022-12-01 09:18 UTC by chenxiangzhen

remove redundant arguments

### PR types

### PR changes

### Description

2022-12-05 03:51 UTC, lugimzzz requested changes

2022-12-05 03:51 UTC, lugimzzz commented on applications/text_classification/multi_class/README.md
> -    --num_train_epochs 100 \
文本分类使用的是早停策略，num_train_epochs默认值为3，使用早停策略建议设置一个较大的num_train_epochs，这个参数是有必要的

2022-12-06 05:30 UTC, wawltor approved these changes
LGTM

2022-12-08 03:15 UTC, sijunhe commented
如@lugimzzz所说， 这个参数有必要，所以我们决定不移除. Closing the PR.
Thank you for your contribution anyway! @chenxiangzhen

2022-12-08 03:15 UTC, closed without merging