Add PretrainedConfig to Bart/MBart/CodeGen/UNIMO/UnifiedTransformer
PaddlePaddle/PaddleNLP pull request #3998
Opened 2022-12-02 04:23 UTC by Yam0214

### PR types

New features

### PR changes

models

### Description

add PretrainedConfig to Bart/MBart/CodeGen/UNIMO/UnifiedTransformer

2022-12-06 08:25 UTC, Yam0214 commented
@wj-Mcat

2022-12-07 03:06 UTC, wj-Mcat requested changes
`standard_config_map` 目前还在PR 中，不过你可以先配置上，具体可见： https://github.com/PaddlePaddle/PaddleNLP/pull/3887/files#diff-4e5f9da3d502f616d62fd9f581359823abc0f6328c952a29ee48c2e282124dcfR447


我觉得整体上的实现没什么问题，就是 attribute_map 的理解错了，需要切换到 `standard_config_map`上面去。

2022-12-07 03:06 UTC, wj-Mcat commented on paddlenlp/transformers/bart/configuration.py
> +    }
attribute_map 只是为了做下游模型的兼容，所以这里不应该将：`num_decoder_layers`这些配置放到这里，详细可见知识库中的<PretrainedConfig编写方法>。

2022-12-07 03:06 UTC, wj-Mcat commented on paddlenlp/transformers/codegen/configuration.py
> +        "inner_dim": "n_inner",
这里也是一样的，需要把这些配置添加到：standard_config_map 静态属性当中。

2022-12-07 03:06 UTC, wj-Mcat commented on tests/transformers/mbart/test_modeling.py
>          # self.use_cache = True
you can delete this line.

2022-12-07 03:06 UTC, wj-Mcat commented on tests/transformers/mbart/test_modeling.py
> +        # outputs_use_cache_conf = model(input_ids, return_dict=self.parent.return_dict)
如果这样代码没使用的话，就删掉吧。

2022-12-09 06:04 UTC, sijunhe commented
Hello @Yam0214 , #4035合入后，这个PR有小幅影响，需要略微调整。麻烦@wj-Mcat 配合review一下

2022-12-11 13:50 UTC, wj-Mcat commented
@Yam0214 有时间回复一下我的 comment，我们也可以尽快推进这个 pr。

2022-12-16 07:41 UTC, sijunhe commented on tests/transformers/codegen/test_modeling.py
> +        return CodeGenConfig.from_dict(
直接用constructor创建，不要from_dict

2022-12-16 07:41 UTC, sijunhe commented on tests/transformers/bart/test_modeling.py
> +        return BartConfig.from_dict(
直接用constructor创建，不要from_dict

2022-12-16 07:41 UTC, sijunhe commented on tests/transformers/mbart/test_modeling.py
> +        return MBartConfig.from_dict(
直接用constructor创建，不要from_dict

2022-12-16 07:41 UTC, sijunhe commented on tests/transformers/unified_transformer/test_modeling.py
> +        return UnifiedTransformerConfig.from_dict(
直接用constructor创建，不要from_dict

2022-12-16 07:41 UTC, sijunhe commented on tests/transformers/unimo/test_modeling.py
> +        return UNIMOConfig.from_dict(
直接用constructor创建，不要from_dict

2022-12-16 09:51 UTC, sijunhe commented on paddlenlp/transformers/codegen/modeling.py
>      pretrained_resource_files_map = {"model_state": {}}
pretrained_init_configuration = CODEGEN_PRETRAINED_INIT_CONFIGURATION
pretrained_resource_files_map = CODEGEN_PRETRAINED_RESOURCE_FILES_MAP

2022-12-16 09:51 UTC, sijunhe commented on paddlenlp/transformers/codegen/modeling.py
这里加入一下这个
```
# import at the top 
from paddlenlp.utils.env import CONFIG_NAME
model_config_file = CONFIG_NAME
```

2022-12-16 10:09 UTC, sijunhe commented on pyproject.toml
> -addopts = "-ra -q --ignore tests/transformers/t5/test_modeling.py"
addopts = "-ra -q"

2022-12-16 10:44 UTC, Yam0214 commented on pyproject.toml
> -addopts = "-ra -q --ignore tests/transformers/t5/test_modeling.py"
@wj-Mcat 
* 使用 standard_config_map 处理`num_encoder_layers`等

@sijunhe 
* 修改`XXConfig.from_dict()`为`XXConfig()`
* 修改 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/tests/transformers/test_modeling_common.py#L516
* 给 ErnieMConfig加上`num_choices`
* 加上了 CONFIG_NAME
* 改正了pyproject.toml

2022-12-16 12:21 UTC, sijunhe approved these changes
LGTM! @wj-Mcat please review

2022-12-16 12:26 UTC, sijunhe requested changes

2022-12-16 12:26 UTC, sijunhe commented on paddlenlp/transformers/ernie_m/configuration.py
> +        num_choices: int = 2,
这个看起来不对，应该是`**kwargs`. 请参考bert或者ernie的config

2022-12-16 12:36 UTC, wj-Mcat commented on paddlenlp/transformers/ernie_m/configuration.py
> +        num_choices: int = 2,
`num_choices`会在基类里面来处理，所以不需要在这里添加 `num_choices`, `num_labels`等类型的字段。

2022-12-16 15:45 UTC, wj-Mcat submitted a review, later dismissed
你的调整很好，有一些东西需要调整，你可以看看。

另外，你以后你可以尝试拆分成不同的 pr来，这么大的 pr 看起来有点费劲。

2022-12-16 15:45 UTC, wj-Mcat commented on paddlenlp/transformers/bart/configuration.py
> +        num_labels: int = 3,
在`configuration.py`中的__init__构造函数中，理论上只需要设置与原始模型相关的配置字段相关即可。

原始模型配置字段：初始化BartModel 的那些字段。

所以在你这里的字段除了以下都是不需要写在这里的。

```python
vocab_size,
        bos_token_id=0,
        pad_token_id=1,
        eos_token_id=2,
        forced_eos_token_id=2,
        decoder_start_token_id=2,
        d_model=768,
        num_encoder_layers=6,
        num_decoder_layers=6,
        encoder_attention_heads=12,
        decoder_attention_heads=12,
        encoder_ffn_dim=3072,
        decoder_ffn_dim=3072,
        dropout=0.1,
        activation_function="gelu",
        attention_dropout=0.1,
        activation_dropout=0.1,
        max_position_embeddings=1024,
        init_std=0.02,
```

2022-12-16 15:45 UTC, wj-Mcat commented on paddlenlp/transformers/bart/configuration.py
> +        num_labels: int = 3,
你也对应调整一下其他Configuration 构造函数中的参数列表。

2022-12-16 15:45 UTC, wj-Mcat commented on paddlenlp/transformers/bart/configuration.py
> +        num_labels: int = 3,
`forced_bos_token_id`是fast-tokenizer的配置，为什么要放在这里呢？

`use_cache`和`classifier_dropout`都是没必要天添加到这里的字段。

2022-12-16 15:45 UTC, wj-Mcat commented on paddlenlp/transformers/bart/modeling.py
> +        self.num_labels = config.num_labels
这里不需要传入**kwargs参数，所有的配置参数都会存储在`kwargs`中。

2022-12-16 15:45 UTC, wj-Mcat commented on paddlenlp/transformers/codegen/configuration.py
> +        use_cache: bool = True,
`use_cache`、`scale_attn_weights`、 `tie_word_embeddings` 不需要出现在这里。

2022-12-16 15:45 UTC, wj-Mcat commented on paddlenlp/transformers/codegen/modeling.py
> +    def __init__(self, inner_dim: int, config: CodeGenConfig):
都已经将config传过来了，为什么还要传inner_dim？难道不能通过 config 中的参数直接或间接的得到吗？

2022-12-16 15:45 UTC, wj-Mcat commented on tests/transformers/bart/test_modeling.py
> +        decoder = BartModel(config).get_decoder()
你这里初始化了两次BartModel，有点浪费资源，可以使用以下代码：

```python
model = BartModel(config)
encoder = model.get_encoder()
decoder = model.get_decoder()
```

2022-12-16 15:45 UTC, wj-Mcat commented on tests/transformers/bart/test_modeling.py
> +        config["num_labels"] = 2
尽量使用attr 的方式来设置值：`config.num_labels=2`。

2022-12-19 13:00 UTC, Yam0214 commented on tests/transformers/bart/test_modeling.py
> +        config["num_labels"] = 2
@wj-Mcat @sijunhe 
* 从config中去除了`use_cache`、`classifier_dropout`、`num_labels`、`scale_attn_weights`、`tie_word_embeddings` 和 `num_choices`
* 去掉了`BartForSequenceClassification`构造函数里的`**kwargs`
* 修改了`class CodeGenMLP(Layer):`，从config中得到inner_dim
* 初始化一次`BartModel`，拿到encoder和decoder
* 检查了所有的`config["attr"]`，并调整为`config.attr`

2022-12-19 15:39 UTC, sijunhe reviewed
没啥大问题，很接近了
1. scale_embedding那个再看下
2. type hints按道理这个不归你这个PR管。但是正好大规模修改，就把forward都加上type hints吧

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/bart/configuration.py
> +        self.scale_embedding = False
为什么这里要强行`self.scale_embedding = False`呢？是bart不能支持这个，还是仅仅是预训练模型把这个设成False? 如果是后者，可以把这个存到上面的BART_PRETRAINED_INIT_CONFIGURATION里

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/bart/modeling.py
> +        return_dict=None,
这里最好加一下type hints, `Optional[bool]`, 要不然别人不知道这个是bool

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/bart/modeling.py
> +        return_dict=None,
同上

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/bart/modeling.py
> +        return_dict=None,
同上

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/bart/modeling.py
> +        >>>>>>> 18584165176b41678c9fb773c7e578d4a3fb094b
这个conflict要merge干净

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/bart/modeling.py
> +        return_dict=None,
同上

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/bart/modeling.py
> +        return_dict=None,
同上

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/bart/modeling.py
> +        return_dict=None,
同上

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/codegen/modeling.py
>      ):
type hints

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/mbart/configuration.py
> +        self.scale_embedding = True  # scale factor will be sqrt(d_model) if True
和上面bart的scale_embedding一样

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/mbart/modeling.py
> +        return_dict=None,
type hints

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/mbart/modeling.py
> +        return_dict=None,
type hints

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/mbart/modeling.py
> +        return_dict=None,
type hints

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/mbart/modeling.py
> +        output_hidden_states=None,
type hints

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/unified_transformer/modeling.py
> +        return_dict=None,
type hints

2022-12-19 15:39 UTC, sijunhe commented on paddlenlp/transformers/unified_transformer/modeling.py
> +        return_dict=None,
type hints

2022-12-20 02:19 UTC, Yam0214 commented on paddlenlp/transformers/bart/configuration.py
> +        self.scale_embedding = False
好的，稍后我把forward里加上type hints
另外，我们的bart和mbart在组网的时候没有提供scale_embedding选择，[bart](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bart/modeling.py#L244)只支持False，[mbart](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/mbart/modeling.py#L308)只支持True。

2022-12-20 05:36 UTC, sijunhe commented on paddlenlp/transformers/bart/configuration.py
> +        self.scale_embedding = False
这样的话，我建议把scale_embedding的true和false两个情况都在两个模型里实现一下（应该就是加不加 `self.d_model**0.5`的区别）。然后在BART_PRETRAINED_INIT_CONFIGURATION都加上{"scale_embedding": False}, 在mbart里加上{"scale_embedding": True}

2022-12-21 06:09 UTC, sijunhe approved these changes
LGTM. 看起来没什么问题。这个PR实在太大，没办法看的很细。我们先merge, 后续有问题再修改

2022-12-21 06:09 UTC, sijunhe commented on paddlenlp/transformers/codegen/modeling.py
> +        return_dict: Optional[Tensor] = None,
Optional[bool]

2022-12-21 06:09 UTC, merged

2022-12-26 02:00 UTC, wj-Mcat commented
辛苦 @sijunhe 帮忙 review, @Yam0214  我上周生病休息没来得及估计这个事情，真的比较抱歉。