[ModelZoo] Refactor ERNIE-Layout usage
PaddlePaddle/PaddleNLP pull request #4122
Opened 2022-12-15 03:07 UTC by linjieccc

### PR types

Breaking changes
### PR changes

APIs
### Description

- ModelZoo ERNIE-Layout 升级

2022-12-15 08:30 UTC, wj-Mcat requested changes
目前还没有添加ernie-layout的测试，yaml 文件也是需要调整，跟 @wawltor  沟通之后再同步到此 pr 当中。

2022-12-15 08:30 UTC, wj-Mcat commented on paddlenlp/transformers/ernie_layout/modeling.py
> +            config["hidden_act"],
建议使用`config.hidden_size`的方式来获取值，尽量不要使用老的写法，本模块中其它地方同理。

2022-12-15 10:07 UTC, sijunhe commented on paddlenlp/transformers/ernie_layout/modeling.py
> +        self.num_classes = config.num_labels
num_classes要全部替换成num_labels

2022-12-15 10:07 UTC, sijunhe commented on paddlenlp/transformers/ernie_layout/modeling.py
> +        self.ernie_layout = ErnieLayoutModel(config)
重复了

2022-12-15 10:07 UTC, sijunhe commented
测试那块应该也得改一下

2022-12-19 07:03 UTC, sijunhe commented on paddlenlp/transformers/ernie_layout/modeling.py
>      model_config_file = "model_config.json"
```suggestion
    model_config_file = "config.json"
```

2022-12-23 02:48 UTC, sijunhe commented
@linjieccc #4170 已合入。update一下，这个PR可以继续推进

2023-01-05 06:11 UTC, closed without merging