【CI】 add ci scripts
PaddlePaddle/PaddleNLP pull request #4249
Opened 2022-12-27 06:39 UTC by zjjlivein

### PR types

### PR changes

### Description

add ci scripts
make release for release test
make key for fast test examples

2022-12-27 08:00 UTC, wj-Mcat commented on Makefile
> +	bash ./tests/ci/run_release.sh ${cudaid1} ${cudaid2} ${test_all_examples}
```suggestion
.PHONY: release
release: 
	test_all_examples=all
	cudaid1=0
	cudaid2=0,1
	bash ./tests/ci/run_release.sh ${cudaid1} ${cudaid2} ${test_all_examples}
```

2022-12-27 08:01 UTC, wj-Mcat commented on Makefile
> +	bash ./tests/ci/run_release.sh ${cudaid1} ${cudaid2} ${test_key_examples}
```suggestion
.PHONY: key
key: 
	test_key_examples=p0
	cudaid1=0
	cudaid2=0,1
	bash ./tests/ci/run_release.sh ${cudaid1} ${cudaid2} ${test_key_examples}
```

2022-12-27 08:04 UTC, wj-Mcat requested changes
`Makefile` 中的变量定义life time scope 有些问题， 其它文件基本上是原始test repo 中的脚本，还需要 @guoshengCS @wawltor @sijunhe  来看看。

2022-12-29 13:32 UTC, sijunhe reviewed
我这里问题不大，稍微修改一下makefile之后先合入进来在iPipe跑通。后续有需要再调整吧

2022-12-29 13:32 UTC, sijunhe commented on Makefile
> +.PHONY: release
```suggestion
.PHONY: regression-all
```

2022-12-29 13:32 UTC, sijunhe commented on Makefile
> +.PHONY: key
```suggestion
.PHONY: regression-key
```

2022-12-29 13:32 UTC, sijunhe commented on Makefile
> +	bash ./scripts/regression/run_release.sh ${cudaid1} ${cudaid2} ${test_all_examples}
这里能不能直接`bash ./scripts/regression/run_release.sh 0 0,1 all` 呢？就不用定义上面那个变量了，因为我不太确定这个变量定义过后会不会消失

2022-12-29 14:02 UTC, wj-Mcat commented on Makefile
> +	bash ./scripts/regression/run_release.sh ${cudaid1} ${cudaid2} ${test_all_examples}
> 这里能不能直接`bash ./scripts/regression/run_release.sh 0 0,1 all` 呢？就不用定义上面那个变量了，因为我不太确定这个变量定义过后会不会消失

其实这里本身就是写死了，所以直接写这样也无所谓。

2022-12-30 02:26 UTC, zjjlivein commented on Makefile
> +	bash ./scripts/regression/run_release.sh ${cudaid1} ${cudaid2} ${test_all_examples}
./scripts/regression/run_release.sh 0 0,1 all 测试通过

2022-12-30 02:39 UTC, sijunhe approved these changes
lgtm

2022-12-30 02:41 UTC, wj-Mcat approved these changes

2022-12-30 02:43 UTC, merged