Refactor CLIP model
PaddlePaddle/PaddleNLP pull request #4270
Opened 2022-12-28 13:39 UTC by JunnYu

### PR types

Others
### PR changes

Models
### Description

- 重构CLIP模型，支持使用Config加载，兼容旧版model_config.json文件。（权重参数命名没有变化，只修改了Config的参数名）；
- 添加CLIP的单测。

2022-12-28 13:51 UTC, JunnYu commented
TODO：ERNIEVIl还需要更新一下

DONE

2023-01-04 02:43 UTC, wj-Mcat requested changes
你的这个 PR 太大了，看起来很花费时间，所以我只留了几个 comment。

至于 converter 这块我还是会继续兼容你这边的工作，保证你这边能够正常工作。

2023-01-04 02:43 UTC, wj-Mcat commented on paddlenlp/transformers/__init__.py
> +from .chineseclip.converter import *
这个文件中关于converter的import 建议都删掉，因为后续会融入到model.convert中去。

2023-01-04 02:43 UTC, wj-Mcat commented on paddlenlp/transformers/bit/configuration.py
> +        kwargs.update({"return_dict": return_dict})
感觉这里的代码可以简写成：

```suggestion
        kwargs["return_dict"] = kwargs.pop("return_dict", True)
```

2023-01-04 02:43 UTC, wj-Mcat commented on paddlenlp/transformers/chineseclip/configuration.py
> +        kwargs.update({"return_dict": return_dict})
这里的建议跟上面一致。

2023-01-04 02:43 UTC, wj-Mcat commented on paddlenlp/transformers/chineseclip/converter.py
> +        return pytorch_config
现在与 HF Hub 兼容有一个原则：除了权重文件不能复用，其它文件都直使用hf 上面的，其中就包括config.json。所以关于这块你可能也需要做一定的调整。

2023-01-05 01:54 UTC, JunnYu commented on paddlenlp/transformers/__init__.py
> +from .chineseclip.converter import *
done

2023-01-05 01:54 UTC, JunnYu commented on paddlenlp/transformers/bit/configuration.py
> +        kwargs.update({"return_dict": return_dict})
done

2023-01-05 01:57 UTC, JunnYu commented on paddlenlp/transformers/chineseclip/converter.py
> +        return pytorch_config
done

2023-01-06 14:15 UTC, wj-Mcat approved these changes

2023-01-06 14:17 UTC, merged