update BRIO
PaddlePaddle/PaddleNLP pull request #4348
Opened 2023-01-05 04:57 UTC by LazyFyh

### PR types

New features

### PR changes

Model

### Description

Update BRIO Model

2023-01-05 07:14 UTC, gongel requested changes
1. `applications/text_summarization/BRIO/tokenizer.py`、`applications/text_summarization/BRIO/generate_cand/tokenizers_pegasus.py`可以删除，直接复用我们自己的`PegasusChineseTokenizer`；
2. 清除Debug和无用的注视；
3. 增加requirements.txt

2023-01-05 07:14 UTC, gongel commented on applications/text_summarization/BRIO/generate_cand/data_utils.py
> +def shift_tokens_right(input_ids: torch.Tensor, pad_token_id: int, decoder_start_token_id: int):
这个函数有用到吗？没用到可以删除

2023-01-05 07:14 UTC, gongel commented on applications/text_summarization/BRIO/generate_cand/data_utils.py
> +def shift_tokens_right(input_ids: torch.Tensor, pad_token_id: int, decoder_start_token_id: int):
其他的函数也确认下，没用到的都删除掉

2023-01-05 07:14 UTC, gongel commented on applications/text_summarization/BRIO/pegasus.py
> +            # if attention_mask.ndim == 2:
这些注释可以删除，其他的地方也一样。

2023-01-05 07:14 UTC, gongel commented on applications/text_summarization/BRIO/pegasus.py
> +# class CustomPegasusModel(PegasusPretrainedModel):
不用的可以删除。

2023-01-06 03:39 UTC, gongel commented
TODO：按我们最晚讨论的进行整理

2023-01-06 08:16 UTC, LazyFyh commented on applications/text_summarization/BRIO/generate_cand/data_utils.py
> +def shift_tokens_right(input_ids: torch.Tensor, pad_token_id: int, decoder_start_token_id: int):
Done in [tidy other code](https://github.com/PaddlePaddle/PaddleNLP/pull/4348/commits/54eb3dfe0af4214bb18ddf5134b307905f0125eb)

2023-01-06 08:16 UTC, LazyFyh commented on applications/text_summarization/BRIO/pegasus.py
> +            # if attention_mask.ndim == 2:
Done in [tidy other code](https://github.com/PaddlePaddle/PaddleNLP/pull/4348/commits/54eb3dfe0af4214bb18ddf5134b307905f0125eb)

2023-01-06 08:16 UTC, LazyFyh commented on applications/text_summarization/BRIO/pegasus.py
> +# class CustomPegasusModel(PegasusPretrainedModel):
Done in [tidy model code](https://github.com/PaddlePaddle/PaddleNLP/pull/4348/commits/c6aadc1197bb736450e6344835b51fba0589acbe)

2023-01-06 08:17 UTC, LazyFyh commented on applications/text_summarization/BRIO/pegasus.py
> +            # if attention_mask.ndim == 2:
Done in [tidy model code](https://github.com/PaddlePaddle/PaddleNLP/pull/4348/commits/c6aadc1197bb736450e6344835b51fba0589acbe)

2023-01-06 08:27 UTC, gongel commented on paddlenlp/transformers/pegasus/modeling.py
> +        pad_token_id=None,
这里的pad id如果和model本身的是一样的，就不用传，直接调self.pegasus.pad_token_id

2023-01-06 08:55 UTC, LazyFyh commented on paddlenlp/transformers/pegasus/modeling.py
> +        pad_token_id=None,
Done

2023-10-30 07:31 UTC, closed without merging