add docs
PaddlePaddle/PaddleNLP pull request #45
Opened 2021-03-01 06:39 UTC by chenxiaozeng

### PR types

### PR changes

### Describe

2021-03-01 06:47 UTC, ZeyuChen requested changes
基础框架修改意见

2021-03-01 06:47 UTC, ZeyuChen commented on docs/source/advanced_guide/model_distill.rst
> +============
文件名应为model_compression

2021-03-01 06:47 UTC, ZeyuChen commented on docs/source/get_started/install.md
> +pip install paddlex -i https://mirror.baidu.com/pypi/simple
文档内容不是PaddleNLP的，是否可以改为PaddleNLP的通用安装

2021-03-01 06:47 UTC, ZeyuChen commented on docs/source/get_started/install.md
> +以下安装过程默认用户已安装好**paddlepaddle-gpu或paddlepaddle(版本大于或等于1.8.1)**，paddlepaddle安装方式参照[飞桨官网](https://www.paddlepaddle.org.cn/install/quick)
版本改为2.0

2021-03-01 06:47 UTC, ZeyuChen commented on docs/source/get_started/quick_start.rst
> +    >>> pip install --upgrade paddlenlp>=2.0.0b -i https://pypi.org/simple
安装命令应为 paddlenlp\>=2.0.0rc

2021-03-01 06:47 UTC, ZeyuChen commented on docs/source/index.rst
> +* 项目GitHub: https://github.com/PaddlePaddle/models
GitHub地址需要更新

2021-03-01 06:47 UTC, ZeyuChen commented on docs/source/index.rst
> +* GitHub Issue反馈: https://github.com/PaddlePaddle/models/issues
GitHub地址需要更新

2021-03-01 06:47 UTC, ZeyuChen commented on docs/source/tutorials.rst
> +   /tutorials/embedding
rst后缀都没了？下同

2021-03-01 06:47 UTC, ZeyuChen commented on docs/source/tutorials/lexical_analysis
> +========================
缺少rst后缀

2021-03-03 11:45 UTC, chenxiaozeng commented
to fix some bugs.

2021-03-03 11:45 UTC, chenxiaozeng commented
to fix bugs

2021-03-03 11:45 UTC, closed without merging