Add BART converter and Chinese  BART models
PaddlePaddle/PaddleNLP pull request #4636
Opened 2023-02-03 06:59 UTC by gongel

### PR types

New features 
### PR changes

Others
### Description

- Add BART model converter from torch to paddlepaddle
- Add Chinese BART models
  - fnlp/bart-base-chinese
  - fnlp/bart-large-chinese
  - uer/bart-base-chinese-cluecorpussmall 
  - uer/bart-chinese-6-960-cluecorpussmall 
  - uer/bart-large-chinese-cluecorpussmall 
  - uer/bart-chinese-4-768-cluecorpussmall
  - HIT-TMG/dialogue-bart-base-chinese
  - HIT-TMG/dialogue-bart-large-chinese-DuSinc
  - HIT-TMG/dialogue-bart-large-chinese
  - shibing624/bart4csc-base-chinese
  - IDEA-CCNL/Randeng-BART-139M-QG-Chinese 
  - IDEA-CCNL/Randeng-BART-759M-Chinese-BertTokenizer 
  - IDEA-CCNL/Randeng-BART-139M-SUMMARY 
  - IDEA-CCNL/Randeng-BART-139M

2023-02-03 06:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=4636) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=4636) before we can accept your contribution.<br/><hr/>**gongel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=4636) it.</sub>

2023-02-03 07:08 UTC, gongel commented
后续可支持AutoConverter，黑客马拉松选手也可参考该实现。

2023-02-03 07:26 UTC, sijunhe requested changes
模型自动转化能力由AutoConverter承载，请参考https://github.com/PaddlePaddle/PaddleNLP/pull/4477 添加bart结构

2023-02-13 05:42 UTC, sijunhe approved these changes

2023-02-13 05:42 UTC, merged