Add MT5 model
PaddlePaddle/PaddleNLP pull request #4765
Opened 2023-02-13 06:09 UTC by LazyFyh

### PR types

New model

### PR changes

Models

### Description

新增了MT5模型，包括配置代码和模型代码

2023-02-13 06:16 UTC, gongel commented on paddlenlp/transformers/mt5/modeling.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
2021-->2022，其它同此

2023-02-13 06:16 UTC, gongel commented on paddlenlp/transformers/mt5/modeling.py
> +    def _get_name_mappings(cls, config: MT5Config) -> list[StateDictNameMapping]:
这里可以加个TODO，后续load_torch完善后可支持AutoConverter

2023-02-13 06:36 UTC, sijunhe requested changes, later dismissed
请参考t5增加单测 test_modeling.py和test_tokenizer.py

2023-02-13 07:39 UTC, LazyFyh commented on paddlenlp/transformers/mt5/modeling.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
Done

2023-02-13 07:39 UTC, LazyFyh commented on paddlenlp/transformers/mt5/modeling.py
> +    def _get_name_mappings(cls, config: MT5Config) -> list[StateDictNameMapping]:
Done

2023-02-15 07:09 UTC, sijunhe commented on tests/transformers/mt5/test_tokenizer.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
如果mt5没有自己的tokenizer的话，就不需要单独的测试了

2023-02-15 07:10 UTC, sijunhe reviewed
删掉test_tokenizer.py我这边觉得就ok了。@gongel 也看下，ok的话我们尽快合入吧

2023-02-15 07:25 UTC, LazyFyh commented on tests/transformers/mt5/test_tokenizer.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
已经删除

2023-02-15 09:11 UTC, gongel approved these changes

2023-02-15 09:11 UTC, merged