[PPDiffuers] Add pipeline_fastdeploy_cycle_diffusion.py
PaddlePaddle/PaddleNLP pull request #4945
Opened 2023-02-22 12:05 UTC by joey12300

### PR types

### PR changes

### Description

2023-02-28 05:00 UTC, guoshengCS approved these changes, later dismissed

2023-02-28 05:00 UTC, guoshengCS commented on ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_fastdeploy_cycle_diffusion.py
> +                text_input_ids, untruncated_ids
`text_input_ids`和`untruncated_ids`是np的，这里paddle.equal_all是否需要用np的呢

2023-02-28 05:00 UTC, guoshengCS commented on ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_fastdeploy_cycle_diffusion.py
> +                    paddle.device.cuda.synchronize()
这里是否是必须的呢，看其他的pipelile包括FastDeploy pipeline里没有这个

2023-02-28 07:38 UTC, joey12300 commented on ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_fastdeploy_cycle_diffusion.py
> +                    paddle.device.cuda.synchronize()
主要保证多流kernel异步发射的最终结果正确，需要同步

2023-02-28 12:00 UTC, joey12300 commented on ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_fastdeploy_cycle_diffusion.py
> +                text_input_ids, untruncated_ids
感谢review，已经更新了~

2023-02-28 12:15 UTC, jiangjiajun requested changes

2023-02-28 12:15 UTC, jiangjiajun commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +        option.set_trt_cache_file(cache_file)
看到上面的代码已经开始在使用1.0.4的API了， `option.paddle_infer_option`，那就统一都开始切为新版本API吧

改为`option.trt_option.serialize_file = cache_file`

2023-02-28 12:15 UTC, jiangjiajun commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +            option.enable_paddle_trt_collect_shape()
`option.paddle_infer_option.collect_trt_shape = True`

2023-02-28 12:15 UTC, jiangjiajun commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +                    key,
option.trt_option.set_shape(name, min, opt, max)

2023-02-28 12:15 UTC, jiangjiajun commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +        option.set_lite_device_names(["huawei_ascend_npu"])
此行代码应该无需显式调用，删除即可

2023-02-28 12:15 UTC, jiangjiajun commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +            "HUAWEI_ASCEND_NPU_SELECTED_DEVICE_IDS={};HUAWEI_ASCEND_NPU_PRECISION_MODE=allow_mix_precision".format(
```
option.paddle_lite_option.nnadapter_model_cache_dir = os.path.join(model_dir, model_prefix)
option.paddle_lite_option.nnadapter_context_properties = "HUAWEI_ASCEND_NPU_SELECTED_DEVICE_IDS={};HUAWEI_ASCEND_NPU_PRECISION_MODE=allow_mix_precision".format(device_id)
```

2023-02-28 12:15 UTC, jiangjiajun commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +    option.enable_trt_fp16()
option.trt_option.enable_fp16 = True

2023-02-28 12:15 UTC, jiangjiajun commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +    option.set_trt_max_workspace_size(workspace)
option.trt_option.max_workspace_size = workspace

2023-02-28 12:15 UTC, jiangjiajun commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +            option.set_trt_input_shape(
option.set_shape

2023-02-28 12:15 UTC, jiangjiajun commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +    option.set_trt_cache_file(cache_file)
option.trt_option.serialize_file = cache_file

2023-02-28 12:24 UTC, joey12300 commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +        option.set_trt_cache_file(cache_file)
Done

2023-02-28 12:28 UTC, joey12300 commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +                    key,
done

2023-02-28 12:29 UTC, joey12300 commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +        option.set_lite_device_names(["huawei_ascend_npu"])
Done

2023-02-28 12:29 UTC, joey12300 commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +            option.enable_paddle_trt_collect_shape()
Done

2023-02-28 12:30 UTC, joey12300 commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +            "HUAWEI_ASCEND_NPU_SELECTED_DEVICE_IDS={};HUAWEI_ASCEND_NPU_PRECISION_MODE=allow_mix_precision".format(
Done

2023-02-28 12:33 UTC, joey12300 commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +    option.set_trt_cache_file(cache_file)
Done

2023-02-28 12:33 UTC, joey12300 commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +            option.set_trt_input_shape(
Done

2023-02-28 12:33 UTC, joey12300 commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +    option.set_trt_max_workspace_size(workspace)
Done

2023-02-28 12:34 UTC, joey12300 commented on ppdiffusers/deploy/text_guided_img_to_img_infer.py
> +    option.enable_trt_fp16()
Done

2023-03-01 07:39 UTC, guoshengCS approved these changes

2023-03-01 07:48 UTC, merged