[BigBird P0] Add PretrainedConfig and unit tests
PaddlePaddle/PaddleNLP pull request #4961
Opened 2023-02-23 08:30 UTC by tsinghua-zhang

### PR types

### PR changes

### Description

2023-02-24 11:06 UTC, wj-Mcat requested changes
代码整体看起来很好，就是有点小问题需要调整。

2023-02-24 11:06 UTC, wj-Mcat commented on tests/transformers/bigbird/test_modeling.py
> +class BigBirdModelTest(ModelTesterMixin, unittest.TestCase):
这个单测是需要使用使用`parameterize`来增加测试参数场景的，例如：

```python
@parameterized_class(
    ("return_dict", "use_labels"),
    [
        [False, False],
        [False, True],
        [True, False],
        [True, True],
    ],
)
class BertModelTest(ModelTesterMixin, unittest.TestCase):
```
具体可参考：

https://github.com/PaddlePaddle/PaddleNLP/blob/ee78a00b30c2b3f835a40f614658cc70df40c0cf/tests/transformers/bert/test_modeling.py#L360-L369

2023-02-24 11:06 UTC, wj-Mcat commented on tests/transformers/bigbird/test_tokenizer.py
> +    def BigBird_base_tokenizer(self):
这个函数的命令不是很规范：所有函数的名称都应该是小写驼峰式命名，而不是这种大写混杂小写

```suggestion
    def get_bigbird_base_tokenizer(self):
```

2023-02-24 11:06 UTC, wj-Mcat commented on tests/transformers/bigbird/test_tokenizer.py
> +    def BigBird_base_tokenizer(self):
调用这个函数的几个地方同样都是要调整的。

2023-02-24 11:06 UTC, wj-Mcat commented on tests/transformers/bigbird/test_tokenizer.py
> +    def test_eos_treatment(self):
因为在这个函数中需要从 bos 上下载全量的信息，所以属于 slow 的范畴：所有调用 `get_bigbird_base_tokenizer`  地方都要加上@slow 的装饰器。

2023-02-24 11:06 UTC, wj-Mcat commented on tests/transformers/bigbird/test_tokenizer.py
> +        pass
这个为什么要关掉呢？能否说明一下原因。

此外如果必须要关掉的话，这边建议使用unittest.skip ，并附带说明原因。

2023-02-24 17:11 UTC, sijunhe commented on tests/transformers/bigbird/test_modeling.py
> +class BigBirdModelTest(ModelTesterMixin, unittest.TestCase):
这个可以暂时不用加，因为bigbird目前既没有return_dict也没有labels输入。可以等到P1再加

2023-02-28 01:59 UTC, wj-Mcat approved these changes

2023-02-28 01:59 UTC, wj-Mcat commented on tests/transformers/bigbird/test_tokenizer.py
> +    def bigbird_base_tokenizer(self):
因为这个函数并不是单测函数（不是以`test`开头的函数），所以这里并不需要添加@slow的装饰器。

不过这个你可以在下一个pr 中调整吧。

2023-02-28 01:59 UTC, merged