[Reformer P1] Add loss, return_dict, hidden and attention outputs
PaddlePaddle/PaddleNLP pull request #4981
Opened 2023-02-24 04:44 UTC by tsinghua-zhang

### PR types

### PR changes

### Description

2023-02-27 11:49 UTC, wj-Mcat reviewed
1. 在 reformer 当中最初是没有基于 dataclass 来构造Output，这部分属于历史遗留问题，所以64-75 行的`*Output`相关的nametuple都要转化成dataclass来构造输出。

2023-02-28 02:50 UTC, wj-Mcat requested changes, later dismissed
整体上的实现结构我觉得很好，就是在小细节上面需要调整。

2023-02-28 02:50 UTC, wj-Mcat commented on paddlenlp/transformers/reformer/modeling.py
> +        )
在这块的模型组网这边有一些问题：

1. dropout = (None,) 这行代码需要删掉，估计是写的时候就没有注意。
2. 另外，transformers 那边是没有`dropout`这一层的，所以咱们这边也是需要同步删掉的。
3. 现在有了`PretrainedConfig`模块，所以类似于 `self.reformer.config["hidden_dropout_prob"]` 的代码都应该调整成为：`self.reformer.config.hidden_dropout_prob`。BTW：我搜索了下大概有 20 处左右出现这样的问题。

2023-02-28 02:50 UTC, wj-Mcat commented on paddlenlp/transformers/reformer/modeling.py
> +            return_dict=return_dict,
另外，在所有的`ReformerForXX`模型中，`return_dict`的初始化都应该在模型的 forward 中完成，不然当return_dict为 None 的时候，没办法通过self.config.return_dict来初始化，具体可参考：

https://github.com/PaddlePaddle/PaddleNLP/blob/c35b670699a114b39ff4f78ab72dd1dc343a56a1/paddlenlp/transformers/bert/modeling.py#L705

2023-02-28 02:50 UTC, wj-Mcat commented on paddlenlp/transformers/reformer/modeling.py
> +            return_dict=return_dict,
其它模型类似的地方都应该调整。

2023-02-28 02:50 UTC, wj-Mcat commented on paddlenlp/transformers/reformer/modeling.py
> +        )
此外，如果是`ReformerForXXX`模型，可直接`self.config`来获取`ReformerConfig`对象，可以不用`self.reformer.config`。

2023-02-28 02:50 UTC, wj-Mcat commented on paddlenlp/transformers/reformer/modeling.py
> +        )
你现在给部分函数的参数添加了type hint, 可是其他的参数都没有添加，所以我建议其他的都添加上把：目前可只修改：forward 函数就行。

例如：

https://github.com/PaddlePaddle/PaddleNLP/blob/9ef80869adbd2b311720e31a84c91365833e6035/paddlenlp/transformers/reformer/modeling.py#L2877-L2888

这里：input_ids 参数都添加上。

> 如果这里有input_embed参数 (P2 的功能)，input_ids 可以为 None，可是目前还支持P1 阶段，严谨上来讲是不应该为 None，不过以后注意了，现在就先这样。

2023-02-28 02:50 UTC, wj-Mcat commented on tests/transformers/reformer/test_modeling.py
>          self.parent.assertTrue(paddle.allclose(output_padded, output_padded_rolled, atol=1e-3))
这里的 atol=1e-3 还是有点小了，咱们模型单测精度统一使用1e-4 。

2023-02-28 11:38 UTC, sijunhe reviewed
挺好，修一下小东西就可以合入了

2023-02-28 11:38 UTC, sijunhe commented on paddlenlp/transformers/reformer/modeling.py
> +                    std=self.axial_norm_std if hasattr(self, "axial_norm_std") else self.config.axial_norm_std,
直接self.config.axial_norm_std 就可以了

2023-02-28 11:38 UTC, sijunhe commented on paddlenlp/transformers/reformer/modeling.py
> +                    else self.config.initializer_range,
直接self.config. initializer_range

2023-02-28 11:38 UTC, sijunhe commented on paddlenlp/transformers/reformer/modeling.py
> +                        std=self.axial_norm_std if hasattr(self, "axial_norm_std") else self.config.axial_norm_std,
直接self.config.axial_norm_std

2023-02-28 11:38 UTC, sijunhe commented on paddlenlp/transformers/reformer/modeling.py
> +        self.config = config
这行应该不用，self.config是基类自带的

2023-02-28 11:38 UTC, sijunhe commented on paddlenlp/transformers/reformer/modeling.py
> +        if self.config.is_decoder is True:
```suggestion
        if self.config.is_decoder:
```

2023-02-28 11:38 UTC, sijunhe commented on paddlenlp/transformers/reformer/modeling.py
> +        if self.config.is_decoder is True:
```suggestion
        if self.config.is_decoder:
```

2023-02-28 11:38 UTC, sijunhe commented on paddlenlp/transformers/reformer/modeling.py
> +@dataclass
这里所有的dataclass 都多了一行空格，可以删除

2023-03-01 03:52 UTC, sijunhe approved these changes
lgtm

2023-03-01 05:57 UTC, sijunhe approved these changes
great job!

2023-03-01 05:57 UTC, merged

2023-03-02 02:31 UTC, wj-Mcat commented
@sijunhe  thanks for reviewing.