Add default attention to gpt and generate example
PaddlePaddle/PaddleNLP pull request #510
Opened 2021-06-07 13:36 UTC by smallv0221

### PR types

Others
### PR changes

Models
### Description

Add default attention to gpt and generate example

2021-06-08 01:43 UTC, ZHUI requested changes

2021-06-08 01:43 UTC, ZHUI commented on paddlenlp/transformers/gpt/modeling.py
> +
1. Why do we need `attn_mask` and `causal_mask` in the same time?
2. The `causal_mask` should be the sequence length, but it is initialized with `embed_dim`.  where `key_length` > `embed_dim`, there may be serious bugs.

2021-06-09 04:07 UTC, guoshengCS commented on paddlenlp/transformers/gpt/modeling.py
> +            input_ids)[-1]]
建议causal_mask在这里和传进来的attention_mask使用相加或者与或合起来，后面只传attention_mask，简单一些，在每层的attention中也减少一个mask的处理更快一点

2021-06-09 04:07 UTC, guoshengCS commented on paddlenlp/transformers/gpt/modeling.py
> +            input_ids)[-1]]
刚才和 @smallv0221  讨论，这个也依赖于attention_mask的统一。当前对各模型、tokenzier、生成API对mask的要求没有统一起来，有的是0-1，有的是1-0，有的是0, -INF，相对完备一些的是之前paddle.nn.Transformer中的处理，这个也见之前的说明 https://github.com/PaddlePaddle/PaddleNLP/pull/311#discussion_r621985230

2021-06-09 04:07 UTC, guoshengCS commented on paddlenlp/transformers/gpt/tokenizer.py
> +            eol_token='\u2583',  # The token of newline.
这种换参数名的方式可能会导致一些兼容性的风险，此前用户本地存的配置可能会无法使用。这种情况是要保留原有的，还是咱们增强PretrainedTokenizer/PretrainedTokenizer提供对参数版本升级的支持。另外包括bos上的模型，咱们是否也需要一个版本升级的支持，比如之前有一些预训练模型没有head部分的参数。  @ZeyuChen

2021-06-09 08:53 UTC, ZHUI commented on paddlenlp/transformers/gpt/modeling.py
> +            input_ids)[-1]]
这里 GPT mask 采用bool mask方式，分布式的同学反馈有性能问题。经查，`mask_score = (causal_mask - 1.0) * 10000.0` 的一些写法有性能问题。建议 causal_mask，attention_mask 统一改成 -INF的mask，统一起来。 @smallv0221

2021-06-09 11:35 UTC, ZHUI commented on examples/language_model/gpt/run_pretrain_static.py
> +            # Create the learning_rate sheduler and optimizergit
typos

2021-06-09 11:35 UTC, ZHUI commented on paddlenlp/transformers/gpt/modeling.py
> +                        causal_mask,
typo ? `causal_mask`

2021-06-09 11:35 UTC, ZHUI commented on paddlenlp/transformers/gpt/modeling.py
> +        self.register_buffer("bias",
是否验证导出功能正常？

2021-06-09 11:35 UTC, ZHUI commented on paddlenlp/transformers/gpt/modeling.py
> +            attention_mask = attention_mask + causal_mask
此处的如果传进来 `attention_mask ` 是 `causal_mask`， 相当于还是做了一次加法对吧？

2021-06-09 11:35 UTC, ZHUI commented on .pre-commit-config.yaml
> +    rev: v0.16.2
此处的 yapf 版本修改，是否会导致大面积的代码格式化变动？

2021-06-09 12:32 UTC, ZHUI approved these changes
LGTM

2021-06-10 02:56 UTC, merged