[BigBird P2] Add inputs_embeds
PaddlePaddle/PaddleNLP pull request #5186
Opened 2023-03-10 07:55 UTC by tsinghua-zhang

### PR types

### PR changes

### Description

- Added inputs_embeds

- Since BigBird defines its own attention, encoder and encoder layer, adding past_key_values is non-trivial. Skipping for now

2023-03-10 17:17 UTC, sijunhe reviewed
挺好的。之前ci有些问题，需要merge develop以后再提交一次

2023-03-13 01:28 UTC, wj-Mcat requested changes
整体质量比较高，就是一个变量边缘异常检测的小问题。

2023-03-13 01:28 UTC, wj-Mcat commented on paddlenlp/transformers/bigbird/modeling.py
> +            inputs_embeds = self.word_embeddings(input_ids)
你可以参考 gpt 这里的写法，添加一些边缘判断，让代码更鲁邦。

2023-03-14 01:37 UTC, wj-Mcat approved these changes
LGTM

2023-03-14 01:37 UTC, merged