Faqnlp
PaddlePaddle/PaddleNLP pull request #526
Opened 2021-06-08 15:27 UTC by mawenjie8731

### PR types
New features 

### PR changes
Docs

### Description
add PaddleNLP_FAQ.md

2021-06-08 15:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=526) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=526) before we can accept your contribution.<br/><hr/>**小五井** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=526) it.</sub>

2021-06-08 16:00 UTC, ZeyuChen requested changes

2021-06-08 16:00 UTC, ZeyuChen commented on PaddleNLP_FAQ.md
> +### PaddleNLP之FAQ文档
不能加在根目录
文件名放在docs/faq.md下面

2021-06-08 16:00 UTC, ZeyuChen commented on PaddleNLP_FAQ.md
> ++ 通过Paddle原生的[save接口](#save)保存
这些技术措辞不准确。

2021-06-08 16:00 UTC, ZeyuChen commented on PaddleNLP_FAQ.md
> +#### 1、自定义数据集
既然是FAQ，就应该按照Q & A的方式来整理，请对一些Repo的FAQ做下调研后调整下话术。

2021-06-09 06:26 UTC, mawenjie8731 commented on PaddleNLP_FAQ.md
> +### PaddleNLP之FAQ文档
已放至docs/faq.md下

2021-06-15 06:02 UTC, yingyibiao commented on PaddleNLP_FAQ.md
> +### PaddleNLP之FAQ文档
> 已放至docs/faq.md下

把PaddleNLP_FAQ.md删了哈

2021-06-15 06:37 UTC, yingyibiao requested changes
几个建议：
1. 问题按照类别分类成几个部分，比如关于数据的，关于模型加载的，关于模型评估的等等，问题也不需要添加编号。
2. 问题应该口语化一点，是我们对用户的常见问题的总结，比如 **如何自定义数据集** 这个问题不太像用户提问的，反而像我们的文档，改问题可以更改为：**我想使用自己的数据进行BertForSequenceClassification等模型的fine-tuning，应该怎么做？**，
3. 答案需要详细一点专业一点，不要只是引用其他文档。比如上述问题，答案可以拆分为几个步骤，一步一步指导用户解决问题。引用的自定义数据集文档只是其中的一个步骤介绍。

2021-06-16 05:52 UTC, ZeyuChen commented
@mawenjie8731 参考下OCR团队的FAQ文档撰写吧

2021-07-25 16:53 UTC, ZeyuChen commented
Please resubmit a new FAQ doc and refer to PaddleOCR's FAQ doc.

2021-07-25 16:53 UTC, ZeyuChen commented
Please resubmit a new FAQ doc and refer to PaddleOCR's FAQ doc.

2021-07-25 16:53 UTC, closed without merging