【Hackathon 4th No.102】给AutoConverter增加新的模型组网的支持 CLIPModel
PaddlePaddle/PaddleNLP pull request #5595
Opened 2023-04-10 12:15 UTC by megemini

### PR types

New features

### PR changes

APIs

### Description

【Hackathon 4th No.102】给AutoConverter增加新的模型组网的支持 CLIPModel

Hackathon 4th No.102 这个任务里面有5个模型，我计划每个模型单独提PR，这个PR是处理 ``clip`` 模型。

- 使用的测试模型 ``hf-internal-testing/tiny-random-CLIPModel``

反馈几个问题：
- 使用 ``hf-internal-testing/tiny-random-CLIPModel`` 这个模型，``transformers`` 在 ``CLIPTextModelWithProjection`` 和 ``CLIPVisionModelWithProjection`` 模型转换会出现：
  ``` python
  RuntimeError: Error(s) in loading state_dict for CLIPTextModelWithProjection:
	  size mismatch for text_projection.weight: copying a param with shape torch.Size([64, 32]) from checkpoint, the shape in current model is torch.Size([32, 32]).
	  You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
  ```
  添加  ``ignore_mismatched_sizes=True`` 后初始化可以，但是最后的 ``torch_logit.text_embeds.shape`` 不一致，有什么好的处理方式？
- 使用 ``openai/clip-vit-base-patch32`` 模型就行测试，会提示报错：
  ``` python
  [2023-04-10 20:10:21,733] [    INFO] - start to convert pytorch weight file</tmp/tmp85dqy6e_/models--openai--clip-vit-base-patch32/snapshots/e6a30b603a447e251fdaca1c3056b2a16cdfebeb/pytorch_model.bin> to paddle weight file</tmp/tmp85dqy6e_/model_state.pdparams> ...
  ---------------------------------------------------------------------------
  ValueError                                Traceback (most recent call last)
  /tmp/ipykernel_13624/2676101560.py in <module>
        5 with tempfile.TemporaryDirectory() as tempdir:
        6     model_id = "openai/clip-vit-base-patch32"
  ----> 7     clip_p = CLIPModel.from_pretrained(model_id, from_hf_hub=True, cache_dir=tempdir)
  
  /mnt/workspace/PaddleNLP/paddlenlp/transformers/model_utils.py in from_pretrained(cls, pretrained_model_name_or_path, from_hf_hub, subfolder, *args, **kwargs)
      661         if cls.constructed_from_pretrained_config():
      662             return cls.from_pretrained_v2(
  --> 663                 pretrained_model_name_or_path, from_hf_hub=from_hf_hub, subfolder=subfolder, *args, **kwargs
      664             )
      665 
  
  /mnt/workspace/PaddleNLP/paddlenlp/transformers/model_utils.py in from_pretrained_v2(cls, pretrained_model_name_or_path, from_hf_hub, subfolder, *args, **kwargs)
     1547                     f"paddle weight file<{os.path.join(cache_dir, PADDLE_WEIGHT_FILE_NAME)}> ..."
     1548                 )
  -> 1549                 model_state_dict = cls.convert(model_weight_file, config, cache_dir)
     1550             else:
     1551                 raise ValueError(
  
  /mnt/workspace/PaddleNLP/paddlenlp/transformers/conversion_utils.py in convert(cls, weight_file, config, cache_dir)
      867         name_mappings = cls._get_name_mappings(config)
      868 
  --> 869         state_dict = load_torch(weight_file)
      870 
      871         # 3. convert state_dict
  
  /mnt/workspace/PaddleNLP/paddlenlp/utils/serialization.py in load_torch(path, **pickle_load_args)
      208     unpickler_stage = UnpicklerWrapperStage(io.BytesIO(data_iostream), **pickle_load_args)
      209     unpickler_stage.persistent_load = persistent_load
  --> 210     state_dict = unpickler_stage.load()
      211     torch_zip.close()
      212     return state_dict
  
  /mnt/workspace/PaddleNLP/paddlenlp/utils/serialization.py in _rebuild_tensor_stage(storage, storage_offset, size, stride, requires_grad, backward_hooks)
      150         order = "C"
      151 
  --> 152     return storage.reshape(size, order=order)
      153 
      154 
  
  ValueError: cannot reshape array of size 786432 into shape (512,512)

  ```
  这里在模型mapping之前，好像是转换模型文件错误。

由于是第一次做这种任务，希望大佬帮忙指导一下，谢谢！：）

2023-04-11 11:14 UTC, wj-Mcat requested changes
目前 paddlenlp 中针对于`load_torch` 的加载不兼容 HF Hub 上的部分CLIP模型，你可以先不用尝试加载全量模型`openai/clip-vit-base-patch32`，只需要兼容`hf-internal-testing/tiny-random-CLIPModel`即可。

当然如果你想在本地测试的话，可以调整一下：`paddlenlp.utils.serialization.load_torch`方法：

```python
def load_torch(path: str, **pickle_load_args):
    from paddlenlp.utils.import_utils import import_module
    torch_model = import_module("torch")
    if torch_model is not None:
        state_dict = torch_model.load(path)
        return {key: value.cpu().numpy() for key, value in state_dict.items()}
```

2023-04-11 11:14 UTC, wj-Mcat commented on paddlenlp/transformers/clip/modeling.py
> +                ["text_projection.weight", "text_projection", "transpose"],
这个需要通过 `cls`判断下是否有`text_project`这个layer，然后再添加`text_projection`的映射，如果是没有的话是不需要添加到这里的配置中来。

2023-04-12 11:47 UTC, megemini commented
增加了 text/vision projection 的判断，请评审，谢谢！

2023-04-14 09:43 UTC, sijunhe reviewed
lgtm. 请顺带删除`clip/converter.py`

2023-04-14 10:21 UTC, megemini commented
> lgtm. 请顺带删除`clip/converter.py`

已删～

2023-04-14 11:02 UTC, sijunhe approved these changes
lgtm

2023-04-14 11:02 UTC, merged