Erine code
PaddlePaddle/PaddleNLP pull request #6166
Opened 2023-06-13 13:02 UTC by KB-Ding

### PR types

### PR changes

### Description

2023-06-22 14:26 UTC, gongel requested changes
mt5和t5的改动都可以去掉了；另外适配下auto

2023-06-22 14:26 UTC, gongel commented on model_zoo/ernie-code/predict.py
> +sys.path.append("/home/PaddleNLP")
这些path都去掉吧

2023-06-22 14:26 UTC, gongel commented on model_zoo/ernie-code/predict.py
> +    pdb.set_trace()
pdb去掉

2023-06-22 14:26 UTC, gongel commented on paddlenlp/transformers/__init__.py
> +from .ernie_code.configuration import *
auto目录下面也要适配下

2023-06-22 14:26 UTC, gongel commented on paddlenlp/transformers/ernie_code/tokenizer.py
> +from ..albert.tokenizer import AlbertEnglishTokenizer
直接继承T5就可以，只要重写pre_process方法，其他的代码省略掉

2023-06-22 14:26 UTC, gongel commented on tests/transformers/ernie_code/test_tokenizer.py
> +sys.path.append("/home/PaddleNLP")
这里去掉

2023-07-06 11:45 UTC, gongel approved these changes

2023-07-07 07:12 UTC, KB-Ding commented on model_zoo/ernie-code/predict.py
> +sys.path.append("/home/PaddleNLP")
Done

2023-07-07 07:12 UTC, KB-Ding commented on model_zoo/ernie-code/predict.py
> +    pdb.set_trace()
Done

2023-07-07 07:12 UTC, KB-Ding commented on paddlenlp/transformers/__init__.py
> +from .ernie_code.configuration import *
Done

2023-07-07 07:12 UTC, KB-Ding commented on paddlenlp/transformers/ernie_code/tokenizer.py
> +from ..albert.tokenizer import AlbertEnglishTokenizer
Done

2023-07-07 07:13 UTC, KB-Ding commented on tests/transformers/ernie_code/test_tokenizer.py
> +sys.path.append("/home/PaddleNLP")
Done

2023-07-11 02:29 UTC, gongel requested changes

2023-07-11 02:29 UTC, gongel commented on model_zoo/ernie-code/README.md
> +## 模型导出预测
模型参数转换(PyTorch-->PaddlePaddle)

2023-07-11 02:29 UTC, gongel commented on model_zoo/ernie-code/README.md
> +- [ERNIE-Code: Beyond English-Centric Cross-lingual Pretraining for Programming Languages](https://arxiv.org/abs/2212.06742)
可以挂个ACL：https://aclanthology.org/2023.findings-acl.676.pdf

2023-07-11 02:29 UTC, gongel commented on paddlenlp/transformers/ernie_code/configuration.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
2023

2023-07-11 02:29 UTC, gongel commented on tests/transformers/ernie_code/test_tokenizer.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
2023

2023-07-11 02:29 UTC, gongel commented on tests/transformers/ernie_code/test_tokenizer.py
> +# Copyright 2018 Google ErnieCode Authors and HuggingFace Inc. team.
Baidu，其他的统一改下。

2023-07-11 03:21 UTC, KB-Ding commented on model_zoo/ernie-code/README.md
> +## 模型导出预测
Done

2023-07-11 03:21 UTC, KB-Ding commented on model_zoo/ernie-code/README.md
> +- [ERNIE-Code: Beyond English-Centric Cross-lingual Pretraining for Programming Languages](https://arxiv.org/abs/2212.06742)
Done

2023-07-11 03:21 UTC, KB-Ding commented on paddlenlp/transformers/ernie_code/configuration.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
Done

2023-07-11 03:21 UTC, KB-Ding commented on tests/transformers/ernie_code/test_tokenizer.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
Done

2023-07-11 03:22 UTC, KB-Ding commented on tests/transformers/ernie_code/test_tokenizer.py
> +# Copyright 2018 Google ErnieCode Authors and HuggingFace Inc. team.
Done

2023-07-11 13:54 UTC, gongel submitted a review, later dismissed

2023-07-12 10:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=6166) <br/>All committers have signed the CLA.

2023-07-14 10:44 UTC, gongel approved these changes

2023-07-14 10:44 UTC, merged