DygraphShardingOptimizer do not need to be invoked explicitly anymore
PaddlePaddle/PaddleNLP pull request #6177
Opened 2023-06-14 09:24 UTC by pangengzheng

### PR types

Others
### PR changes

Others
### Description

Others

2023-06-14 09:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=6177) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=6177) before we can accept your contribution.<br/><hr/>**pangengzheng** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=6177) it.</sub>

2023-06-14 09:36 UTC, ZHUI requested changes

2023-06-14 09:36 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +            self.optimizer = optimizer_cls(
这里删掉了 `DygraphShardingOptimizer`, 请问stage1 如何生效的呢？

还有需要考虑一下版本兼容问题？

2023-06-14 09:44 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +            self.optimizer = optimizer_cls(
我看还要用 DygraphShardingOptimizer 包一下 self.optimizer 才对。

https://github.com/PaddlePaddle/Paddle/pull/54069

2023-06-14 09:44 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +            self.optimizer = optimizer_cls(
另外这里可以做一个兼容吗?

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/trainer.py#L132 

类似这里

2023-06-16 02:43 UTC, pangengzheng commented on paddlenlp/trainer/trainer.py
> +            self.optimizer = optimizer_cls(
嗯会有一个对应的paddle版本匹配的问题。我这里先把pr提上来，我到时候再确认一下怎么做版本兼容的问题

2023-08-07 02:35 UTC, closed without merging