[LLM] Upgrade sharding stage1 for new develop paddle
PaddlePaddle/PaddleNLP pull request #6360
Opened 2023-07-11 07:26 UTC by liuzhenhai93

### PR types

Function optimization
### PR changes

Others
### Description

套件适配 sharding

2023-07-12 23:01 UTC, FeixLiu commented on examples/language_model/llama/finetune_generation.py
> +        tensor_parallel_output=False,
这块为啥也需要改动呀

2023-07-13 01:41 UTC, FeixLiu approved these changes
LGTM for the sharding update

2023-07-14 03:00 UTC, wawltor submitted a review, later dismissed
LGTM

2023-07-14 03:19 UTC, ZHUI requested changes

2023-07-14 03:19 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_finetune.py
>  import time
@wawltor  这里的脚本也帮忙看一下吧

2023-07-14 03:19 UTC, ZHUI commented on examples/language_model/gpt-3/dygraph/run_glue_mp.py
> +    optimizer = build_optimizer.apply(model, args, lr_scheduler, clip, decay_params, strategy)
这里代码有啥改动吗？还是等价替换？

2023-07-14 03:19 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +                try:
现在stage1的推荐用法是？我看不出来

是得 distributed_optimizer 包一下吗？那现在其他情形的是否用 distributed_optimizer 都包装了呢？

这些东西都得确认！

2023-07-18 03:11 UTC, liuzhenhai93 commented on paddlenlp/trainer/trainer.py
> +                try:
stage1  是被 distributed_optimizer 包了；

2023-07-18 03:19 UTC, liuzhenhai93 commented on examples/language_model/gpt-3/dygraph/run_glue_mp.py
> +    optimizer = build_optimizer.apply(model, args, lr_scheduler, clip, decay_params, strategy)
统一封装了一下

2023-07-18 03:20 UTC, liuzhenhai93 commented on paddlenlp/trainer/trainer.py
> +                try:
stage1 目前的用法是通过封装；
stage2 和 stage3 是走 group shard api

2023-07-18 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=6360) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=6360) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: liuzhenhai93<br/>:x: liuzhenhai<br/><hr/>**liuzhenhai** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=6360) it.</sub>

2023-07-18 13:20 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +                    pass
这里可以参考下面的代码，用一个函数替换，不要用try catch了。
```python
def is_dp_group_support_in_group_sharded_parallel():
    return "dp_group" in set(inspect.signature(paddle.distributed.sharding.group_sharded_parallel).parameters.keys())
```

2023-07-19 01:56 UTC, liuzhenhai93 commented on paddlenlp/trainer/trainer.py
> +                    pass
这个能判别框架版本吗？

2023-07-19 02:40 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +                    pass
有API变动的话，可以检查出来

2023-07-19 09:54 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +                def ShardingOptimizerWrapped():
`ShardingOptimizerWrapped`

-> 
```
is_new_version_sharding_stagge1_optimizer
```

2023-07-20 03:57 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +            self.optimizer = optimizer_cls(
这里还用 else:  分支吧，减少代码变动

2023-07-20 03:57 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +                    return self.optimizer
这里也别 return，下面用 else 分支，减少代码改动。

2023-07-20 06:49 UTC, ZHUI approved these changes
LGTM

2023-07-20 07:28 UTC, ZHUI approved these changes
LGTM

2023-07-20 07:28 UTC, merged