Add fused linear for the LLAMA MLP block and multi-head attention block
PaddlePaddle/PaddleNLP pull request #6425
Opened 2023-07-18 07:35 UTC by littsk

### PR types
New features

### PR changes
Models

### Description
Add fused linear operation for MLP and multi-head attention in LLAMA.

2023-07-18 08:00 UTC, ZHUI commented on examples/language_model/llama/run_pretrain.py
> -    fuse_attention_qkv: bool = field(
就用 fuse_attention_qkv 吧

2023-07-18 08:00 UTC, ZHUI commented on paddlenlp/transformers/llama/modeling.py
> +                self.qkv_proj = mpu.ColumnParallelLinear(
预训练参数加载转换，看看能不能根据fuse 搞成自动的。

2023-07-18 08:00 UTC, ZHUI commented on paddlenlp/transformers/llama/modeling.py
> +            self.gate_up_fused_proj = mpu.ColumnParallelLinear(
这里fuse参数的切分。需要注意。

2023-07-18 10:30 UTC, littsk commented on paddlenlp/transformers/llama/modeling.py
> +                self.qkv_proj = mpu.ColumnParallelLinear(
请问大佬，具体是啥意思呀

2023-07-21 04:21 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +            self.gate_up_fused_proj = mpu.ColumnParallelLinear(
这个改动有多少提速呀？

2023-07-21 05:41 UTC, littsk commented on paddlenlp/transformers/llama/modeling.py
> +            self.gate_up_fused_proj = mpu.ColumnParallelLinear(
2%左右吧，主要是减少了一次通信😁

2023-07-21 06:38 UTC, sijunhe requested changes

2023-07-21 06:38 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
当前这个写法是有问题的：
1. 直接在组网里面把这两个权重fuse起来会导致我们以前的模型参数全部加载不进来，也没做向后兼容
2. 当前这个多卡切法把每张卡上的参数chunk成了2个是有点问题的，同样一套参数无法适配不同的卡数，实在需要fuse应该考虑奇偶切，而不是chunk

2023-07-21 07:57 UTC, littsk commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
好滴谢谢

2023-07-21 08:20 UTC, FeixLiu commented on paddlenlp/transformers/llama/modeling.py
> +            self.gate_up_fused_proj = mpu.ColumnParallelLinear(
在llama 13B，mp2 sharding 4的配置下，提速约6%。当然这是两个fuse一起的总提速（fuse qkv + fuse gate）。单一提速没有单独测试过，预计2-3%。

2023-07-21 08:24 UTC, FeixLiu commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
对于1，是的，fuse参数与非fuse参数永远是不兼容的。譬如fuse qkv这个变化也会导致之前的参数加载不进来。但是这个是可解的，基本做法就是离线对参数进行处理。
对于2，没太理解什么叫奇偶切分。而且这里chunk的是linear的输出。若果想说的是不同mp degree之间的参数转换，没有这个fuse的话，不同mp degree之间也没法适配吧，也需要进行参数转换的吧。

2023-07-21 08:27 UTC, FeixLiu commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
chunk成2不是基于当前分布式策略考虑的。是就应该chunk为2。
原来的逻辑是

2023-07-21 10:59 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
> 对于1，是的，fuse参数与非fuse参数永远是不兼容的。譬如fuse qkv这个变化也会导致之前的参数加载不进来。但是这个是可解的，基本做法就是离线对参数进行处理。

这个只能离线处理我们自己host的权重，但是这个模型已经发布好几个月了，很多人已经下载缓存好了，这个时候如果这样子改代码的话，使用以前权重的人不就全部用不了了吗？所以说这个fuse必须得用一个开关控制，不能像现在这样强制切换

2023-07-21 11:03 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
> 只是在不同mp之间进行参数转化需要一些考量
> mp0: a = [w1, w2] * x
> mp1: b = [w3, w4] * x
> 变成单卡的等价转换是
> c = [w1, w3, w2, w4] * x
这套不太work, 因为我们需要做到同样一份权重在单卡, mp2, mp4, mp8上都正确加载，对齐精度. 这种切法不同mp都会切的不一样。建议考虑奇偶切，即奇数的channel是w0, 偶数的idx是w1, 例子[chatglm_v2](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/chatglm_v2/modeling.py#L390)

2023-07-21 11:12 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
> 没有这个fuse的话，不同mp degree之间也没法适配吧，也需要进行参数转换的吧

这里说的是可以不同mp degree加载**单分片的参数**。当前PaddleNLP有逻辑可以在分布式训练完成以后存储一份单分片的参数，方便后续任意mp degree加载

2023-07-21 12:35 UTC, FeixLiu commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
> > 对于1，是的，fuse参数与非fuse参数永远是不兼容的。譬如fuse qkv这个变化也会导致之前的参数加载不进来。但是这个是可解的，基本做法就是离线对参数进行处理。
> 
> 这个只能离线处理我们自己host的权重，但是这个模型已经发布好几个月了，很多人已经下载缓存好了，这个时候如果这样子改代码的话，使用以前权重的人不就全部用不了了吗？所以说这个fuse必须得用一个开关控制，不能像现在这样强制切换

同意加一个开关来控制这个

2023-07-21 12:37 UTC, FeixLiu commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
> > 只是在不同mp之间进行参数转化需要一些考量
> > mp0: a = [w1, w2] * x
> > mp1: b = [w3, w4] * x
> > 变成单卡的等价转换是
> > c = [w1, w3, w2, w4] * x
> 
> 这套不太work, 因为我们需要做到同样一份权重在单卡, mp2, mp4, mp8上都正确加载，对齐精度. 这种切法不同mp都会切的不一样。建议考虑奇偶切，即奇数的channel是w0, 偶数的idx是w1, 例子[chatglm_v2](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/chatglm_v2/modeling.py#L390)

我不太理解一份权重如何在mp2，mp4，mp8下同时加载。是说同一份单卡的权重，加载了之后再切分么？如果是需要再切分，我觉得现在个没什么区别，只是切分的方式需要特殊处理。如果是mp4加载mp2的参数，那我觉得这个本来就是有问题的。他们俩参数的shape都不一样啊，如何进行正确加载的呀？

2023-07-21 12:38 UTC, FeixLiu commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
> > 没有这个fuse的话，不同mp degree之间也没法适配吧，也需要进行参数转换的吧
> 
> 这里说的是可以不同mp degree加载**单分片的参数**。当前PaddleNLP有逻辑可以在分布式训练完成以后存储一份单分片的参数，方便后续任意mp degree加载

如果是这样，感觉可以在dist save，dist load的时候进行特殊处理，把gate的参数名进行特殊标记，然后对这个参数进行特殊的处理。

2023-07-23 15:00 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +            gate_out, up_out = paddle.chunk(self.gate_up_fused_proj(x), chunks=2, axis=-1)
> 如果是这样，感觉可以在dist save，dist load的时候进行特殊处理，把gate的参数名进行特殊标记，然后对这个参数进行特殊的处理。

这套我们已经有现成方案了，就是上面链接的按照奇偶channels切分，可以做到多卡下一致

2023-07-24 05:56 UTC, sijunhe reviewed
我看ok.
@ZHUI 看下呢？

2023-07-25 03:20 UTC, ZHUI commented on paddlenlp/transformers/llama/modeling.py
> +                )
https://github.com/PaddlePaddle/PaddleNLP/blob/64128922c3c9b959dfb20b159b0af5fb8d2c8492/paddlenlp/transformers/llama/modeling.py#L610-L647

这部分的逻辑你适配一下，Tensor Parallel自动切分合并参数的

2023-07-25 12:00 UTC, ZHUI submitted a review, later dismissed

2023-07-25 12:00 UTC, ZHUI commented on paddlenlp/transformers/llama/modeling.py
> +            # 为了减少张量并行的通信量，将两个linear合并成一个
中文注释 删掉

2023-07-25 12:00 UTC, ZHUI commented on paddlenlp/transformers/llama/modeling.py
> +            if config.fuse_mlp_linear:
这个 `fuse_mlp_linear` 是不是换个名字更好？
`fuse_gate_up_proj` ? 或者其他？

2023-07-26 02:39 UTC, littsk commented on paddlenlp/transformers/llama/modeling.py
> +            if config.fuse_mlp_linear:
好的好的

2023-07-26 02:53 UTC, ZHUI approved these changes
LGTM

2023-07-26 03:01 UTC, FeixLiu approved these changes
LGTM for the fuse

2023-07-26 03:35 UTC, sijunhe approved these changes

2023-07-26 05:31 UTC, merged