paddle support stride, fix dy2st
PaddlePaddle/PaddleNLP pull request #6539
Opened 2023-07-28 06:11 UTC by wanghuancoder

### PR types

Others 
### PR changes

Others 
### Description

Paddle支持stride后，需要检查动转静不一致的情况。但检查难度大，简单的检查会有误报，但这种方式获得评审会的同意。通过with可以避免误报。

2023-08-01 06:39 UTC, ZeyuChen requested changes
不能新增Fluid相关API，如果API很关键新增非Fluid目录下的API

2023-08-01 06:43 UTC, ZeyuChen reviewed
Add more comment and future TODO

2023-08-01 06:48 UTC, ZHUI commented on paddlenlp/transformers/ernie/modeling.py
> +        with paddle.fluid.framework._stride_in_no_check_dy2st_diff():
需要保证旧版本的paddle正常运行，如 paddle 2.4.0

2023-08-02 02:28 UTC, wanghuancoder commented
> 不能新增Fluid相关API，如果API很关键新增非Fluid目录下的API

done, thx!

2023-08-02 02:29 UTC, wanghuancoder commented
> 

done, thx!

2023-08-02 02:29 UTC, wanghuancoder commented
> Add more comment and future TODO

done, thx!

2023-08-02 02:29 UTC, wanghuancoder commented on paddlenlp/transformers/ernie/modeling.py
> +        with paddle.fluid.framework._stride_in_no_check_dy2st_diff():
done, thx!

2023-08-02 07:06 UTC, ZHUI approved these changes

2023-08-02 07:06 UTC, ZHUI commented on paddlenlp/transformers/ernie/modeling.py
> +        if hasattr(paddle.framework, "_no_check_dy2st_diff"):
LGTM

2023-08-02 07:42 UTC, ZeyuChen approved these changes
LGTM

2023-08-03 04:06 UTC, merged