eliminate transpose in sequence parallel for llama
PaddlePaddle/PaddleNLP pull request #6574
Opened 2023-08-01 12:24 UTC by littsk

### PR types
Performance optimization

### PR changes
Models

### Description
Eliminate transpose operation in sequence parallel for LLAMA, resulting in a 3% performance increase in the mp4pp2 configuration.

2023-08-02 03:00 UTC, sijunhe reviewed
PR有问题，llama单测挂好多了，看起来是shape不对，麻烦看下

2023-08-02 08:16 UTC, ZHUI commented on llm/llama/modeling_pp.py
> +            # [bs, seq_len, num_head * head_dim] -> [bs * seq_len, num_head * head_dim]
@DesmonDay  斯铭review吧，double check一下

2023-08-02 08:32 UTC, DesmonDay requested changes
建议先跑通 llama 目录下的单测 tests/test_sequence_parallel.py，多测试几种不同分布式情况，保证shape 和精度没有问题。

2023-08-04 02:57 UTC, DesmonDay commented on llm/llama/tests/test_sequence_parallel.py
> +        np.testing.assert_allclose(ret[0].item(), ret_mp_pp, rtol=1e-5, atol=1e-5)
为何修改 rtol?

2023-08-07 03:29 UTC, ZHUI commented on paddlenlp/transformers/llama/configuration.py
> +        self.seq_length = seq_length
问什么必须加 seq_length ?

2023-08-07 11:00 UTC, littsk commented on paddlenlp/transformers/llama/configuration.py
> +        self.seq_length = seq_length
因为对于attn的需要的输入是[bs, seq_length, n_head, head_dim]，但是实际去掉了transpose之后的输入是[bs * seq_length, n_head * head_dim], bs和seq_length必须知道一个才可以转化成前面的形状

2023-08-08 03:19 UTC, DesmonDay commented on llm/llama/modeling_pp.py
> +            input_embeds = paddle.reshape_(input_embeds, [bs * seq_len, self.hidden_size])
这里的 self.hidden_size，直接从101行就可以获得吧？ bs, seq_len, hidden_size = input_embeds.shape

2023-08-08 03:20 UTC, DesmonDay commented on paddlenlp/transformers/llama/modeling.py
> +            inputs_embeds = paddle.reshape_(inputs_embeds, [bs * seq_len, self.hidden_size])
hidden_size 可以直接从932行获取吧？bs, seq_len, hidden_size = inputs_embeds.shape

2023-08-08 03:20 UTC, DesmonDay commented on paddlenlp/transformers/llama/modeling.py
> +            # inputs_embeds = paddle.reshape_(inputs_embeds, [bs, seq_len, self.hidden_size])
937行删掉

2023-08-08 08:05 UTC, DesmonDay submitted a review, later dismissed
LGTM

2023-08-09 02:49 UTC, ZHUI approved these changes, later dismissed

2023-08-09 02:49 UTC, ZHUI commented on paddlenlp/transformers/llama/configuration.py
> +        seq_length=1024,
建议修改为 2048，一般跟 max_position_embeddings 一致。

2023-08-09 03:23 UTC, littsk commented on paddlenlp/transformers/llama/configuration.py
> +        seq_length=1024,
好滴

2023-08-09 03:54 UTC, ZHUI approved these changes

2023-08-09 06:49 UTC, DesmonDay approved these changes
LGTM

2023-08-09 12:03 UTC, merged