[paddle-pipelines] Update document store
PaddlePaddle/PaddleNLP pull request #6599
Opened 2023-08-03 00:42 UTC by w5688414

### PR types

### PR changes

### Description

2023-08-03 13:10 UTC, sijunhe commented on pipelines/pipelines/document_stores/elasticsearch.py
> +            # bulk(self.client, documents_to_index, request_timeout=300, refresh=self.refresh_type, headers=headers)
remove

2023-08-03 13:10 UTC, sijunhe commented on pipelines/pipelines/document_stores/elasticsearch.py
> +            ):
参数化一下这个吧

2023-08-03 13:10 UTC, sijunhe commented on pipelines/pipelines/nodes/retriever/base.py
> +            # breakpoint()
remove

2023-08-03 13:10 UTC, sijunhe commented on pipelines/pipelines/document_stores/elasticsearch.py
> +                )
这里没配置thread?

2023-08-03 13:10 UTC, sijunhe commented on pipelines/pipelines/document_stores/elasticsearch.py
> +    from elasticsearch.helpers import bulk, parallel_bulk, scan
bulk可以不import了？

2023-08-04 02:05 UTC, w5688414 commented on pipelines/pipelines/document_stores/elasticsearch.py
> +            # bulk(self.client, documents_to_index, request_timeout=300, refresh=self.refresh_type, headers=headers)
已删除

2023-08-04 02:05 UTC, w5688414 commented on pipelines/pipelines/document_stores/elasticsearch.py
> +            ):
已修改

2023-08-04 02:14 UTC, w5688414 commented on pipelines/pipelines/document_stores/elasticsearch.py
> +    from elasticsearch.helpers import bulk, parallel_bulk, scan
已修改

2023-08-04 02:15 UTC, w5688414 commented on pipelines/pipelines/document_stores/elasticsearch.py
> +                )
已修改

2023-08-04 02:15 UTC, w5688414 commented on pipelines/pipelines/nodes/retriever/base.py
> +            # breakpoint()
已修改

2023-08-04 03:27 UTC, sijunhe requested changes
lgtm

2023-08-04 03:27 UTC, merged