[WIP] Add BART model
PaddlePaddle/PaddleNLP pull request #663
Opened 2021-06-29 07:40 UTC by gongel

### PR types

New features
### PR changes

Models
### Description

Feat: add BART model
- Need upload pretrained models;
- Need adapt to encoder-decoder generation api;

2021-07-06 05:38 UTC, guoshengCS commented on paddlenlp/transformers/bart/modeling.py
> +                [1, 1, output_shape[-1]]))
这里最好加个TODO说明下需要支持bool tensor的index，后面支持后改过来，另外这个需求也可以提个反馈到API相应同学或者提个卡片。

2021-07-06 05:38 UTC, guoshengCS commented on paddlenlp/transformers/bart/modeling.py
> +                    dtype=paddle.get_default_dtype()) * -np.inf),
这里`paddle.ones()*-np.inf`用paddle.full呢

2021-07-06 08:20 UTC, smallv0221 requested changes
qkv那个缓存机制也需要参照GPT再加一下

2021-07-06 08:20 UTC, smallv0221 commented on paddlenlp/transformers/bart/modeling.py
> +        if attention_mask is None:
因为生成的时候需要缓存encoder_output，所以还是需要参照HF写一套BartEncoder和BartDecoder把nn.transformerencoder包起来让BartEncoder和BartDecoder直接接受ids。然后默认attention_mask的生成放在BartEncoder和BartDecoder里面

2021-07-06 08:20 UTC, smallv0221 commented on paddlenlp/transformers/bart/modeling.py
> +        memory = self.encoder(encoder_input, src_mask=attention_mask)
这里的命名看看能不能优化一下，比如encoder_output。

2021-07-12 10:01 UTC, gongel commented on paddlenlp/transformers/bart/modeling.py
> +                    dtype=paddle.get_default_dtype()) * -np.inf),
DONE, THX

2021-07-12 10:01 UTC, gongel commented on paddlenlp/transformers/bart/modeling.py
> +                [1, 1, output_shape[-1]]))
DONE, THX

2021-07-12 10:01 UTC, gongel commented on paddlenlp/transformers/bart/modeling.py
> +        if attention_mask is None:
DONE, THX

2021-07-12 10:01 UTC, gongel commented on paddlenlp/transformers/bart/modeling.py
> +        memory = self.encoder(encoder_input, src_mask=attention_mask)
DONE, THX

2021-07-21 06:06 UTC, smallv0221 approved these changes
LGTM

2021-07-21 06:12 UTC, merged