supports llama-dybatch-V1
PaddlePaddle/PaddleNLP pull request #6676
Opened 2023-08-10 03:38 UTC by carryyu

### PR types

New features
### PR changes

Models
### Description

supports llama-dybatch-V1

2023-08-14 03:55 UTC, wj-Mcat requested changes
我觉得大部分的工作都非常棒，有几点想跟你讨论的。

另外，后面有时间可以也加一加相关单测，目前 paddlenlp 合入进去的相关东西一般都是要加的。

2023-08-14 03:55 UTC, wj-Mcat commented on paddlenlp/ops/generation/encode_rotary_qk.cu
> +// Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
`paddlenlp/ops/generation` 目录下的 ops 我这边推荐使用：`csrc`这个目录，考虑如下：

1. 为了和主流框架自定义算子风格保持一致。
2. `csrc`目录有比较强的**分类说明**：C 相关的代码（只能够是 ops）
3. 未来 paddlenlp 也可能会有更多的加速自定义算子，此时也是可以放在这个里面，而不仅仅只是针对于生成式相关。


参考项目：

* https://github.com/Dao-AILab/flash-attention
* https://github.com/vllm-project/vllm
* https://github.com/TimDettmers/bitsandbytes

以上开源项目的自定义算子都是放在 csrc 目录下，所以建议为了和主流开源项目保持一致的风格，建议采用`csrc`这个目录。

2023-08-14 03:55 UTC, wj-Mcat commented on paddlenlp/ops/generation/setup_cuda.py
> +    name="custom_setup_ops",
这里的 name 建议改成：`paddlenlp_ops`，从语义上更适合 paddlenlp，属于 paddlenlp 的一部分。

2023-08-14 03:55 UTC, wj-Mcat commented on paddlenlp/transformers/fused_multi_transformer_fine_grained.py
> +    if not in_dynamic_mode():
这个 branch 会执行到吗？ 这个函数只是在创建类的时候才会用到，可是创建模型是在动态图模式下，并非是静态图模式下，所以这个 branch 应该是不会走到的。

除非是在静态图模式下创建类，这种场景在 paddlenlp 中从来没有实现过。

2023-08-14 03:55 UTC, wj-Mcat commented on paddlenlp/transformers/fused_multi_transformer_fine_grained.py
> +    else:
这里的代码是否可简化成：

```python
if in_dynamic_mode():
    return ...
helper = LayerHelper("fused_bias_act")
...
```

我看你下面的部分代码也是这样写的。

2023-08-14 03:55 UTC, wj-Mcat commented on paddlenlp/transformers/llama/modeling.py
> +        ln_scale_attrs = [paddle.ParamAttr(name="fusellama.{}.ln_scale".format(i)) for i in range(self.num_layers)]
关于 fusedmt 中的parameter name 命名，我有不同的想法：尽量保持和原生动态图保持一致。

比如说：LLama 中的 `llama.layers[0].input_layernorm.weight` 就直接对应着：`fusellama.0.ln_scale`这个参数，然后在fusedmt 中定义的时候就直接写成：

`ln_scale_attrs = [paddle.ParamAttr(name="llama.layers[0].input_layernorm.weight".format(i)) for i in range(self.num_layers)]`

这样有如下优点：

1. 在模型定义的时候，语义更加清晰。
2. 在 set_state_dict 函数中只需要针对于 qkv transpose 就行，其他参数可直接 set 进去，甚至可以通过配置不重写 set_state_dict 函数，大大减少相关代码，从而减少 fusedmt 模型适配成本。

2023-08-14 05:31 UTC, carryyu commented on paddlenlp/ops/generation/encode_rotary_qk.cu
> +// Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
收到，请问这个csrc目录放在哪个路径下

2023-08-14 05:34 UTC, carryyu commented on paddlenlp/transformers/fused_multi_transformer_fine_grained.py
> +    if not in_dynamic_mode():
支持静态图接口 是为了在 动转静导出的时候使用的

2023-08-14 05:38 UTC, carryyu commented on paddlenlp/ops/generation/setup_cuda.py
> +    name="custom_setup_ops",
已修改

2023-08-14 05:38 UTC, carryyu commented on paddlenlp/transformers/fused_multi_transformer_fine_grained.py
> +    else:
已修改

2023-08-14 05:39 UTC, carryyu commented on paddlenlp/transformers/llama/modeling.py
> +        ln_scale_attrs = [paddle.ParamAttr(name="fusellama.{}.ln_scale".format(i)) for i in range(self.num_layers)]
收到，后续会调整

2023-08-14 08:16 UTC, qingqing01 commented on paddlenlp/transformers/fused_multi_transformer_fine_grained.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
1. fused_transformer_layers.py 
2. 另外一些API合入框架之后，这里就不需要了吧

2023-08-14 08:19 UTC, qingqing01 reviewed
需要补充使用文档

2023-08-14 08:19 UTC, qingqing01 commented on llm/llama/dybatch/export_generation_model.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
都已经在llm目录里， 文件命名可以简单一些， export_model.py

2023-08-14 08:20 UTC, xiaoxiaohehe001 commented on paddlenlp/transformers/fused_multi_transformer_fine_grained.py
> +def mmha_wrapper(
api 直接调用这些就可以 from paddle.incubate.nn.functional import masked_multihead_attention

2023-08-14 09:06 UTC, wj-Mcat commented on paddlenlp/ops/generation/encode_rotary_qk.cu
> +// Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
我觉得就想像 其他库一样放置在根目录下，你觉得呢？

2023-08-14 09:07 UTC, wj-Mcat commented on llm/llama/dybatch/export_generation_model.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
我觉得是 ok 的，就直接用`export_model.py` 命名。

2023-08-14 12:26 UTC, carryyu commented on paddlenlp/ops/generation/encode_rotary_qk.cu
> +// Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
OK

2023-08-14 14:22 UTC, carryyu commented on paddlenlp/transformers/fused_multi_transformer_fine_grained.py
> +def mmha_wrapper(
已修改

2023-08-14 14:22 UTC, carryyu commented on llm/llama/dybatch/export_generation_model.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
已修改

2023-08-14 14:22 UTC, carryyu commented on paddlenlp/transformers/fused_multi_transformer_fine_grained.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
已修改

2023-08-14 14:22 UTC, carryyu commented on paddlenlp/ops/generation/encode_rotary_qk.cu
> +// Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
已修改

2023-08-14 14:28 UTC, carryyu commented
> 需要补充使用文档

已添加

2023-08-16 03:28 UTC, wawltor commented on csrc/encode_rotary_qk.cu
> +// Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
这块的目录建议在csrc的目录下新增一个generation的子目录，便于后续的其他custom op的拓展

2023-08-16 03:28 UTC, wawltor commented on llm/llama/dybatch/README.md
> +# LLaMA DyBatch
目前在LLM目录模型的使用方法基本得到统一，微调、预测、量化相关的脚本都是共用一套

动态插入的脚本是否可以得到统一

2023-08-16 07:39 UTC, xiaoxiaohehe001 commented on paddlenlp/transformers/fused_transformer_layers.py
> +                if trans_qkvw
trans_qkvw False 修改下。

2023-08-16 08:03 UTC, carryyu commented on paddlenlp/transformers/fused_transformer_layers.py
> +                if trans_qkvw
已修改

2023-08-17 02:57 UTC, heavengate commented on llm/llama/dybatch/split_weight.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
这里可以服用PaddleNLP自己的权重切分方法，xxx.from_pretrain里会做权重切分

2023-08-17 02:58 UTC, heavengate commented on llm/llama/dybatch/utils.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
这个建议放到paddlenlp/transformers目录，组织方式 @wj-Mcat 帮忙看下~

2023-08-18 02:51 UTC, carryyu commented on llm/llama/dybatch/README.md
> +# LLaMA DyBatch
这部分可能不太好统一，后续还有各种量化方法，全部放到一起显得不够清晰，或者在主README里面加一下跳转链接这样呢

2023-08-18 02:53 UTC, carryyu commented on csrc/encode_rotary_qk.cu
> +// Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
已修改

2023-08-18 02:53 UTC, carryyu commented on llm/llama/dybatch/split_weight.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
这个from_pretrain应该切分有问题，会炸显存，所以重新写了一套

2023-08-18 06:09 UTC, heavengate commented on llm/llama/dybatch/split_weight.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
这里需要看看有个通用的权重切分方法 @wj-Mcat @wawltor

2023-08-18 06:11 UTC, heavengate commented on llm/llama/dybatch/export_model.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
这个目录下的文件看下能否删掉，在llm/llama目录的文件加一个`--enable_dybatch`的参数，通过分支来维护

2023-08-18 06:22 UTC, heavengate reviewed
确认下是否是在tests/transformer/llama目录下添加单测

2023-08-18 11:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=6676) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=6676) before we can accept your contribution.<br/><hr/>**lizhenyu04** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=6676) it.</sub>

2023-08-21 06:19 UTC, heavengate commented on experimental/inference/llama/README.md
> +# LLaMA Inference
1. 按llm目录的组织方式，这里.sh文件删掉吧，文档按Python命令方式给一下，区分一下单卡和多卡
2. 多卡权重拆分的统一脚本 @wj-Mcat 看下

2023-08-21 06:20 UTC, heavengate commented on experimental/inference/llama/run.sh
> +export FLAGS_use_cutlass_fmha=1
1. 非必要的flag建议删掉，如log相关
2. 其余flag在README里简单说明一下作用

2023-08-21 07:21 UTC, wj-Mcat commented on experimental/inference/llama/README.md
> +# LLaMA Inference
> 按llm目录的组织方式，这里.sh文件删掉吧，文档按Python命令方式给一下，区分一下单卡和多卡

我在最新的 commit 当中已经删掉了。

2023-08-21 12:59 UTC, wj-Mcat commented
截止目前，完成了 InferenceModel：

- [x] 单卡动态图、动转静和静态图验证
- [x] 多卡动态图、动转静和静态图验证
- [x] REAMD 文档的调整
- [x] inferenceModel 的调整

2023-08-21 13:13 UTC, wj-Mcat commented on paddlenlp/transformers/llama/modeling.py
> +        y_is_distributed = tensor_parallel_degree > 1
动态图下 y.is_distributed 为真实值，可是在静态图下y.is_distributed 一直为 False，于是会影响最终 Logits 的维度，从而影响解码的精度。

在此处针对于静态图做了一定的适配。

2023-08-21 13:50 UTC, wj-Mcat approved these changes

2023-08-22 01:37 UTC, wawltor commented on llm/predictor.py
> +class DygraphInferencePredictor(BasePredictor):
这里的命名后续可以修改一下，之前的理解是dygraph表示动态图，inference表示静态图推理


自己记个TODO吧

2023-08-22 01:37 UTC, wawltor commented on llm/predictor.py
> +class StaticInferencePredictor(BasePredictor):
同时这里区分动态batch和非动态batch的了

2023-08-22 01:50 UTC, wj-Mcat commented on llm/predictor.py
> +class StaticInferencePredictor(BasePredictor):
这里有两个 flag：
* mode: dygraph, static
* inference_model: bool 类型

通过以上两个 flag 来控制这四种情况。

2023-08-22 01:52 UTC, wj-Mcat commented on llm/predictor.py
> +class DygraphInferencePredictor(BasePredictor):
这里的命名暂时没有比较优雅合适的名字：

* DygraphInferencePredictor（中庸）
* DygraphinferenceModelPredictor（太长）
* DIPredictor（缩写，什么鬼）

大家有什么合适的名字也可以来参与讨论。

2023-08-22 02:00 UTC, wj-Mcat commented on llm/predictor.py
> +class StaticInferencePredictor(BasePredictor):
dygraph -> dynamic

2023-08-22 02:06 UTC, wawltor approved these changes
LGTM

2023-08-22 02:06 UTC, merged