[TextCNN] Add TextCNN example for sentiment analysis
PaddlePaddle/PaddleNLP pull request #674
Opened 2021-07-01 07:03 UTC by linjieccc

### PR types

### PR changes

### Description

2021-07-01 07:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=674) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=674) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=674) it.</sub>

2021-07-02 03:27 UTC, Steffy-zxf requested changes
数据集的加载方式还需要修改。

2021-07-02 03:27 UTC, Steffy-zxf commented on examples/sentiment_analysis/textcnn/README.md
> +#### 使用PaddleNLP内置数据集
数据集建议修改为加载自定义数据集的方式。

2021-07-02 03:27 UTC, Steffy-zxf commented on examples/sentiment_analysis/textcnn/model.py
> +    def forward(self, text, seq_len=None):
textcnn不需要seq_len

2021-07-02 03:27 UTC, Steffy-zxf commented on examples/sentiment_analysis/textcnn/README.md
> +- https://arxiv.org/pdf/1408.5882.pdf
建议修改为
[EMNLP2014-Convolutional Neural Networks for Sentence Classification](https://aclanthology.org/D14-1181.pdf)

2021-07-02 03:27 UTC, Steffy-zxf commented on examples/sentiment_analysis/textcnn/README.md
> +- https://arxiv.org/pdf/1510.03820.pdf
这篇不是TextCNN原论文，可以先不写

2021-07-02 03:27 UTC, Steffy-zxf commented on examples/sentiment_analysis/textcnn/model.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
2021

2021-07-02 03:27 UTC, Steffy-zxf commented on examples/sentiment_analysis/textcnn/predict.py
> +    """
max_gram_filter_size从哪里来的，没有解释清楚

并且增加相应的api注释

2021-07-02 03:27 UTC, Steffy-zxf commented on examples/sentiment_analysis/textcnn/train.py
> +    train_ds, dev_ds = load_dataset("robotchat", splits=["train", "dev"])
这个样例数据集 没有 测试集吗？

2021-07-02 03:27 UTC, Steffy-zxf commented on paddlenlp/datasets/robotchat.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
改成加载自定义数据集的方式

2021-07-03 03:47 UTC, ZeyuChen commented on examples/sentiment_analysis/textcnn/README.md
> +train_ds, dev_ds, test_ds = load_dataset("robotchat", splits=["train", "dev", "test"])
这份数据集建议外挂，而不是作为官方数据集。

2021-07-03 05:40 UTC, ZeyuChen commented on examples/sentiment_analysis/textcnn/deploy/python/predict.py
> +from scipy.special import softmax
为什么要从scipy引入softmax？

2021-07-03 05:40 UTC, ZeyuChen commented on examples/sentiment_analysis/textcnn/model.py
> +        fc_out = paddle.tanh(self.fc(encoder_out))
代码的层次有点乱，建议一个layer一行。
不要一会合并一行，一会分两行。

2021-07-03 05:40 UTC, ZeyuChen commented on examples/sentiment_analysis/textcnn/train.py
> +    valid_length = np.array(len(input_ids), dtype='int64')
需要len吗？

2021-07-03 05:40 UTC, ZeyuChen commented on examples/sentiment_analysis/textcnn/train.py
> +
删除无意义的空行

2021-07-04 10:25 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/README.md
> +#### 使用PaddleNLP内置数据集
已修改

2021-07-04 10:25 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/model.py
> +    def forward(self, text, seq_len=None):
已修改

2021-07-04 10:26 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/README.md
> +- https://arxiv.org/pdf/1408.5882.pdf
已修改

2021-07-04 10:26 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/README.md
> +- https://arxiv.org/pdf/1510.03820.pdf
已删除

2021-07-04 10:26 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/model.py
> +# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
已修改

2021-07-04 10:26 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/predict.py
> +    """
已修改并增加注释

2021-07-04 10:27 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/train.py
> +    train_ds, dev_ds = load_dataset("robotchat", splits=["train", "dev"])
已添加

2021-07-04 10:27 UTC, linjieccc commented on paddlenlp/datasets/robotchat.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
已修改

2021-07-04 10:27 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/README.md
> +train_ds, dev_ds, test_ds = load_dataset("robotchat", splits=["train", "dev", "test"])
已修改

2021-07-04 10:28 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/deploy/python/predict.py
> +from scipy.special import softmax
已修改为paddle.nn.functional.softmax

2021-07-04 10:28 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/model.py
> +        fc_out = paddle.tanh(self.fc(encoder_out))
已修改

2021-07-04 10:28 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/train.py
> +    valid_length = np.array(len(input_ids), dtype='int64')
已删除length

2021-07-04 10:28 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/train.py
> +
已修改

2021-07-05 02:27 UTC, Steffy-zxf commented on examples/sentiment_analysis/textcnn/data.py
> +        examples (obj:`List(Example)`): The processed data whose each element is a Example (pad) object.
注释对吗？Example是什么？

2021-07-05 02:27 UTC, Steffy-zxf commented on examples/sentiment_analysis/textcnn/data.py
> +    Args:
55行之后增加一空行

2021-07-05 02:27 UTC, Steffy-zxf commented on examples/sentiment_analysis/textcnn/deploy/python/predict.py
> +            model (obj:`paddle.nn.Layer`): A model to classify texts.
注释不对，建议通篇检查下

2021-07-05 03:53 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/data.py
> +        examples (obj:`List(Example)`): The processed data whose each element is a Example (pad) object.
已修改

2021-07-05 03:53 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/data.py
> +    Args:
已修改

2021-07-05 03:53 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/deploy/python/predict.py
> +            model (obj:`paddle.nn.Layer`): A model to classify texts.
已修改

2021-07-05 15:37 UTC, ZeyuChen commented on examples/sentiment_analysis/textcnn/predict.py
> +    paddle.set_device(args.device.lower())
如果是args用了choice的话，这里不需要lower

2021-07-06 03:11 UTC, linjieccc commented on examples/sentiment_analysis/textcnn/predict.py
> +    paddle.set_device(args.device.lower())
已修改

2021-07-06 03:37 UTC, Steffy-zxf approved these changes
LGTM

2021-07-06 17:07 UTC, merged