Support chatglm fine grained dybatch v1.
PaddlePaddle/PaddleNLP pull request #6798
Opened 2023-08-22 18:13 UTC by xiaoxiaohehe001

### PR types

New features
### PR changes

Models
### Description

Support chatglm fine grained dybatch v1.

2023-08-23 06:31 UTC, carryyu commented on paddlenlp/experimental/transformers/generation_utils.py
> +        return model_kwargs, next_tokens
是否需要返回next_tokens？

2023-08-23 07:36 UTC, heavengate commented on llm/predictor.py
> +            inputs["tgt_generation_mask"] = self.tgt_generation_mask
这里看着主要的diff是tgt_pos的处理，只有chatglm有这个2d position的区别么，这里看看把这块也封装一下，通过参数is_2d_pos之类的来区分，在代码里直接通过chatglm判断不是很易扩展
@wj-Mcat @carryyu 也看下怎么封装好一些

2023-08-23 07:37 UTC, heavengate commented on llm/predictor.py
> +                model = LlamaForCausalLMInferenceModel.from_pretrained(
这里看下能否走AutoModelForCausalLM那种方式，内部根据config去分发

2023-08-23 07:38 UTC, heavengate commented on llm/predictor.py
> +            # "My name is?"
注释可以删一下

2023-08-23 10:34 UTC, wj-Mcat requested changes

2023-08-23 10:34 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +            # import pdb;pdb.set_trace()
这里的 pdb 代码应该删掉

2023-08-23 10:34 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +        return model_kwargs, next_tokens
这里的 set_multi_stops 应该可以放到 sample 函数里面来处理吧，所以就可以不在这里返回 next_tokens。

尽量和paddlenlp 现有的函数输入和输出保持一致。

2023-08-23 10:34 UTC, wj-Mcat commented on llm/predictor.py
> +    model_type: str = field(default="llama", metadata={"help": "the type name of static model"})
这里可以通过self.model.__class__ 来判断是否是 chatglm 的模型，这样就不需要新增一个参数来单独控制前处理的不一致性，减少给开发者的使用复杂度。

2023-08-23 10:34 UTC, wj-Mcat commented on llm/predictor.py
> +        if "chatglm" in config.model_type:
可以添加一个私有属性：_is_chatglm，在里面就是通过 self.model.__class__ 来进行判断

2023-08-23 10:34 UTC, wj-Mcat commented on llm/predictor.py
> +                model = LlamaForCausalLMInferenceModel.from_pretrained(
目前还不能通过 AutoModelForCausalLM 来分发，所以初始化目前只能够 hardcode。

不过判断是哪种模型可以通过上面的 config.architectures 来判断。

2023-08-23 10:34 UTC, wj-Mcat commented on llm/predictor.py
> +                    ChatGLMForCausalLMDyBatch,
这里的模型名称要调整成为：ChatGLMForCausalLMInferenceModel。

2023-08-23 10:34 UTC, wj-Mcat commented on llm/predictor.py
> +                model.model.transformer.set_state_dict(state_dict)
这里是权重的 state_dict 无法和模型匹配上吗？为什么要在这里手动 set_state_dict，这部分的逻辑能够写到 ChatGLMForCausalLMInferenceModel 里面呢?

2023-08-23 10:34 UTC, wj-Mcat commented on llm/utils.py
> +
尽量不要使用这种 hack 的写法，这种很容易 break，能否尽量复用from_pretrained 的逻辑呢？如果实在不行的话，可以将问题抛出来解决。

2023-08-25 02:24 UTC, xiaoxiaohehe001 commented on paddlenlp/experimental/transformers/generation_utils.py
> +        return model_kwargs, next_tokens
Done~

2023-08-25 02:25 UTC, xiaoxiaohehe001 commented on llm/predictor.py
> +            # "My name is?"
Done

2023-08-25 02:26 UTC, xiaoxiaohehe001 commented on paddlenlp/experimental/transformers/generation_utils.py
> +            # import pdb;pdb.set_trace()
Done

2023-08-25 02:36 UTC, xiaoxiaohehe001 commented on llm/predictor.py
> +    model_type: str = field(default="llama", metadata={"help": "the type name of static model"})
Done

2023-08-25 02:36 UTC, xiaoxiaohehe001 commented on llm/predictor.py
> +                    ChatGLMForCausalLMDyBatch,
Done

2023-08-25 03:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=6798) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=6798) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: xiaoxiaohehe001<br/>:x: zhengzekang<br/><hr/>**zhengzekang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=6798) it.</sub>

2023-08-25 04:28 UTC, xiaoxiaohehe001 commented on llm/predictor.py
> +                model.model.transformer.set_state_dict(state_dict)
Done

2023-08-25 07:22 UTC, wj-Mcat commented on llm/predictor.py
> +            inputs["tgt_generation_mask"] = self.tgt_generation_mask
商量了下，先暂时这个样子，等后面针对于 chatglm 的tokenizer 再调整一下，此时这里的分支代码就可以删掉了。

2023-08-25 07:22 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/__init__.py
> +from .chatglm import *
这个的 import 应该是要放到 `from .fused_transformer_layers import *`  下面的。

2023-08-25 07:22 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +    def update_model_kwargs_for_generation(cache, just_decoder, next_tokens, eos_token_id, config, model_kwargs):
通过和 @xiaoxiaohehe001 商量之后，为了给模型足够的控制范围，决定将参数转化为实例函数(去掉 @staticmethod), 这样派生模型就可以通过 self.config 来获取到对应的配置，同时也可以重写对应函数。

2023-08-28 11:17 UTC, wj-Mcat approved these changes
LGTM

2023-08-28 11:17 UTC, merged