GenerationConfig, logits_process unittests, streamer(unittests)
PaddlePaddle/PaddleNLP pull request #6855
Opened 2023-08-29 07:53 UTC by wtmlon

### PR types

### PR changes

### Description

generate模块重构，加入generation config，加入streamer

2023-08-30 06:30 UTC, wj-Mcat requested changes, later dismissed
这部分的调整很好，让CI通过了基本上就可以合入了。

不过，目前 generation_config 还没有添加到 PretrainedModel 中去，这个也是一个todo.

而且这部分的工作对于动转静是一个breaking change，应该会有一大批的模型动转静会挂掉，不过没关系，这个 PR 合入之后就立马来调整动转静的模块。

2023-08-30 06:30 UTC, wj-Mcat commented on paddlenlp/transformers/generation/configuration_utils.py
> +            configuration_file = os.path.join(pretrained_model_name_or_path, configuration_file)
```suggestion
            configuration_file = os.path.join(pretrained_model_name_or_path, GENERATION_CONFIG_NAME)
```

2023-08-30 06:30 UTC, wj-Mcat commented on paddlenlp/transformers/generation/logits_process.py
> +            logits[:, self.eos_token_id] = -float("inf")
```suggestion
            logits[:, self.eos_token_id] = paddle.finfo(logits.dtype).min
```

-float("inf") 这个是 float32 的类型，在实际运行的过程中很可能会出现问题，用 finfo 会比较稳妥一些。

2023-08-30 06:30 UTC, wj-Mcat commented on paddlenlp/transformers/generation/logits_process.py
> +            logits[:, self.eos_token_id] = -float("inf")
下同，我看还有几处也是用 -float("inf")的方式来获取最小值，也同步调整一下。

2023-08-30 06:30 UTC, wj-Mcat commented on paddlenlp/transformers/generation/logits_process.py
> +def _get_generated_ngrams(banned_ngrams, prev_input_ids, ngram_size, cur_len):
发现这里的一些函数没有 docstring或完整的 docstring，导致函数的可阅读性比较差，这里能否从 hf 那边补充过来呢？

2023-08-30 06:30 UTC, wj-Mcat commented on paddlenlp/transformers/generation/stopping_criteria.py
> +    def __call__(self, input_ids: paddle.Tensor, scores: paddle.Tensor, **kwargs) -> bool:
这里添加了 type hinting，非常好，如果你添加的其他函数也添加一些这个功能就非常棒了。因为这个一定程度上是可以提升代码的可阅读性以及IDE 中的代码智能提示。

2023-08-30 06:30 UTC, wj-Mcat commented on paddlenlp/transformers/generation/streamer.py
> +        >>> _ = model.generate(**inputs, streamer=streamer, max_tokens=20)
```suggestion
        >>> _ = model.generate(**inputs, streamer=streamer, max_length=20)
```

2023-08-30 06:30 UTC, wj-Mcat commented on paddlenlp/transformers/generation/streamer.py
> +        >>> generation_kwargs = dict(inputs, streamer=streamer, max_tokens=20)
```suggestion
        >>> generation_kwargs = dict(inputs, streamer=streamer, max_length=20)
```

2023-08-30 06:30 UTC, wj-Mcat commented on paddlenlp/transformers/generation/streamer.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
这个文件名叫：`streamers`，麻烦调整一下。

2023-08-30 06:30 UTC, wj-Mcat commented on paddlenlp/transformers/generation/utils.py
> +                    attention_mask=inputs['attention_mask'],
这里的 input_ids 都可以通过 **inputs 的方式传入，就不必要挨个儿获取出来，docstring 中的其他地方相同道理。

2023-08-30 06:30 UTC, wj-Mcat commented on paddlenlp/transformers/generation/utils.py
> +            generation_config = GenerationConfig()
这里的初始化应该是：GenerationConfig.from_model_config，具体参考：https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L1411

因为像 eos_token_id 这些数据都是可以通过config.json 来初始化的，这样外面就可以不必传入generation_config 了。

2023-09-01 09:46 UTC, sijunhe commented on tests/transformers/test_modeling_common.py
> +        paddle.disable_static()
不需要setUp的时候disable_static吧？这样到时候动转静的测试咋办，是不是tearDown的时候disable就够了？ @wj-Mcat

2023-09-01 11:35 UTC, wj-Mcat commented on tests/transformers/test_modeling_common.py
> +        paddle.disable_static()
1. 动转静的单测里面首先会初始化动态图（再进行动转静），此时如果当前的 mode 是 static 的话，动态图模型就没办法初始化。
2. 在动转静的过程中，会有 static_guard，用来保证动转静之前enable_static, 成功之后就 disable_static，可是一旦动转静失败之后，static_guard 就不会 disable_static，所以就会导致其他单测处于：static 的状态。

这也是为什么setUp 单测里面也是要 disable_static.

此外，理论上所有的单测都是要处于动态图下才能执行的，所以在基类里面添加 disable_static 里面添加这个也是为了保证其他单测不收到动转静失败的影响。

2023-09-03 12:44 UTC, sijunhe reviewed
现在使用max_length输入的话会有deprecation warning, 后续这个参数应该是要逐渐废弃掉，要么通过stopping_criteria=StoppingCriteriaList([MaxLengthCriteria(max_length=max_length)]) 来控制，要么通过`max_new_token`这个新参数。看了下好像我们还没有max_new_token这个新参数，应该加入一下

2023-09-04 04:27 UTC, sijunhe approved these changes

2023-09-04 04:28 UTC, merged