[Paddle Inference]support miniGPT4's second part dy2st
PaddlePaddle/PaddleNLP pull request #6905
Opened 2023-09-04 06:19 UTC by zhoutianzi666

### PR types

### PR changes

### Description

2023-09-04 12:28 UTC, wj-Mcat requested changes

2023-09-04 12:28 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +
generation_utils.py 理论上是和模型无关的，这里不应该融入过多的与模型逻辑有关的代码，所以这块不应该将 llama 相关的逻辑代码嵌入到这边来，建议将这些逻辑写到llama/modeling.py 文件里面去。

2023-09-04 12:28 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/llama/modeling.py
> +        # past_key_values is useless,as it is replaced by kwargs["cache"], so confusion.
这边是为了和 hf 对齐，所以优先建议使用 past_key_values 参数来，所以建议这里的 comment 删掉。

2023-09-04 12:28 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +        inputs_embeds=None,
你这个新加的 inputs_embeds 参数需要放在 temperature 后面，不然大部分调用 sample 函数的代码处都会报错，所以这个改动是很危险的。

你可以全局搜索一下：`.sample(`就会发现调用这个函数的地方都是通过 args 的方式来传值

2023-09-04 12:28 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +            model_kwargs["inputs_embeds"] = inputs_embeds
目前 llama 模型是支持传入 inputs_embeds 参数，所以你这边就直接塞到 model_inputs 里面去就行了，让他传入到模型里面去。

2023-09-04 12:28 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +    def generate_with_image_features_to_static(self, output_path: str, config: dict):
还是建议直接用to_static 这个方法，避免重复性的工作，调整起来也是比较简单：在 llama for  causallm 类里面重写一些 to_static 的方法，避免将这种逻辑上升到通用函数中去。

2023-09-04 12:28 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +        model = paddle.jit.to_static(self.generate_with_image_features, input_spec=input_spec)
self.self.generate_with_image_features 可以通过 config.get("generate_method", self.generate) 这种方式来，这样外面也可以实现自动化配置。

2023-09-04 12:28 UTC, wj-Mcat commented on llm/export_llama_for_minigpt4.py
> +    generate_rank_mapping(os.path.join(export_args.output_path, "rank_mapping.csv"))
这个文件其实是可以和 export_model.py 融合到一起的。

2023-09-04 12:29 UTC, wj-Mcat commented
此外，你 update develop branch 把，我看你代码的版本有些 delay 了。

2023-09-05 07:53 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/generation_utils.py
> +
> generation_utils.py 理论上是和模型无关的，这里不应该融入过多的与模型逻辑有关的代码，所以这块不应该将 llama 相关的逻辑代码嵌入到这边来，建议将这些逻辑写到llama/modeling.py 文件里面去。

done，感谢

2023-09-05 09:57 UTC, wj-Mcat requested changes
你这里的调整非常好，可是有如下小问题，


此外，等 https://github.com/PaddlePaddle/PaddleNLP/pull/6923 合入之后，建议使用 `model_type` 来代替 `llm_for_img2txt`

2023-09-05 09:57 UTC, wj-Mcat commented on llm/predictor.py
> +                        LlamaForminiGPT4InferenceModel as LlamaInferenceModel,
```suggestion
                        LlamaForMiniGPT4InferenceModel as LlamaInferenceModel,
```

2023-09-05 09:57 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +            model_kwargs["inputs_embeds"] = inputs_embeds
这块的逻辑是需要迁移到模型的 forward 里面去的，而不是在 generation_utils 里面，具体可参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/llama/modeling.py#L1189

在 experimental/transformers/llama/modeling.py 下面目前是没有对应的 checking，所以建议你将这部分的代码挪过去一下，非常感谢。

2023-09-05 12:11 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/generation_utils.py
> +            model_kwargs["inputs_embeds"] = inputs_embeds
> 这块的逻辑是需要迁移到模型的 forward 里面去的，而不是在 generation_utils 里面，具体可参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/llama/modeling.py#L1189
> 
> 在 experimental/transformers/llama/modeling.py 下面目前是没有对应的 checking，所以建议你将这部分的代码挪过去一下，非常感谢。

已改，辛苦review

2023-09-07 02:05 UTC, wj-Mcat approved these changes
LGTM

2023-09-07 02:05 UTC, merged