Add LLM benchmark scripts
PaddlePaddle/PaddleNLP pull request #6906
Opened 2023-09-04 06:27 UTC by MARD1NO

### PR types
New features

### PR changes
Others

### Description
Support Benchmark in LLM

when benchmark argument is set, we will let LLM input padding to src_length and decode to max_length, which is helpful to compute LLM Inference throughput.

2023-09-04 07:45 UTC, MARD1NO commented on paddlenlp/experimental/transformers/generation_utils.py
> +        length_cond = paddle.greater_than(model_kwargs["step_idx"], model_kwargs["max_dec_len"])
此处修改后，解码次数就是 max_length - src_length 了，不会出现少1次的情况

2023-09-04 11:24 UTC, wj-Mcat requested changes
代码整体很好，有几个小问题

2023-09-04 11:24 UTC, wj-Mcat commented on llm/benchmark.sh
> +export PYTHONPATH=$PYTHONPATH:/root/paddlejob/workspace/env_run/zhengzekang/DevelopPaddleNLP/PaddleNLP
这里可以通过：

```shell
export PYTHONPATH=$(dirname $(pwd)):$PYTHONPATH
```

来设置 pythonpath。

2023-09-04 11:24 UTC, wj-Mcat commented on llm/predictor.py
> +                outputs = predictor.predict(batch_source_text)
这边两个建议：
* 这个 benchmark 函数看起来还是别放在 predict 函数中比较好，建议整一个新的 benchmark 函数，将这部分的逻辑放到里面去，你觉得呢？这样就让 predict 函数看起来比较干净。
* 这里的数据集要不使用上面提供的如何？
* 这里计算总 token 数量应该要通过 outputs 来吧，不应该直接 max_length - predictor_args.src_length 把，因为也有可能early stop 之类的，就导致解码的 id 长度和 计算出来的不匹配。

2023-09-04 11:24 UTC, wj-Mcat commented on llm/predictor.py
> +                outputs = predictor.predict(batch_source_text)
另外，paddlenlp 这边统一性能评估指标：tokens/s（ips），所以建议在打印的内容里面添加一下这个指标。

2023-09-05 07:00 UTC, wj-Mcat approved these changes
LGTM

2023-09-05 07:00 UTC, merged