[CI] add_llm_unittest
PaddlePaddle/PaddleNLP pull request #6913
Opened 2023-09-04 11:17 UTC by zjjlivein

### PR types

### PR changes

### Description
<!-- Describe what this PR does --
新增 llm CI 测试规范，以llama为例

2023-09-08 02:55 UTC, wj-Mcat requested changes
单测整体非常好，个人觉得在一些代码设计上需要一定的调整。

2023-09-08 02:55 UTC, wj-Mcat commented on tests/llm/test_llama.py
> +        print(self.path + "/llama")
这里的 print 可以删掉了

2023-09-08 02:55 UTC, wj-Mcat commented on tests/llm/test_llama.py
> +        }
这里的配置可以放到 llama.yaml 中去，然后通过 load_test_yaml 来加载。

2023-09-08 02:55 UTC, wj-Mcat commented on tests/llm/test_llama.py
> +        finetune_params.update({"output_dir": "./llm/checkpoints/llama_lora_ckpts"})
这里的 output_dir 建议通过 tempfile.TempDirectory 来创建，因为如果我们在本地开发的话，这个单测会在本地生成一大堆临时文件，并且单测中的输出文件本身是一种临时文件，可以通过 tempdir 来构建。

2023-09-08 02:55 UTC, wj-Mcat commented on tests/llm/test_llama.py
> +        finetune_params.update({"output_dir": "./llm/checkpoints/llama_lora_ckpts"})
其他地方的 output_dir 也是类似的。

2023-09-08 02:55 UTC, wj-Mcat commented on tests/llm/test_llama.py
> +            "prefix_path": "./llm/checkpoints/llama_pt_ckpts/checkpoint-2/",
可以在 setup 中通过tempfile.TempDirectory 创建一个 self.prefix_path 来存储，然后 pt_predict_config 也可以复用 predict_config 中的配置，用这种方式可以大大简化这边的代码。

2023-09-08 02:55 UTC, wj-Mcat commented on tests/llm/test_llama.py
> +            "prefix_path": "./llm/checkpoints/llama_pt_ckpts/checkpoint-2/",
其他类似于 st_predict 也是类似的。

2023-09-11 12:26 UTC, zjjlivein commented on tests/llm/test_llama.py
> +        print(self.path + "/llama")
已删除

2023-09-11 12:26 UTC, zjjlivein commented on tests/llm/test_llama.py
> +        }
done

2023-09-11 12:27 UTC, zjjlivein commented on tests/llm/test_llama.py
> +        finetune_params.update({"output_dir": "./llm/checkpoints/llama_lora_ckpts"})
ok

2023-09-13 09:44 UTC, wj-Mcat approved these changes
LGTM

2023-09-13 09:44 UTC, merged