first commit
PaddlePaddle/PaddleNLP pull request #7010
Opened 2023-09-12 10:12 UTC by zhoutianzi666

### PR types

### PR changes

### Description

2023-09-18 02:36 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/generation_utils.py
> +        model_kwargs["past_kv_length"] = paddle.full(shape=[batch], dtype="int32", fill_value=0)
这里加了个这个变量，这个变量需要给opt-2.7b使用

2023-09-18 02:40 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/generation_utils.py
> +        next_tokens = paddle.full(shape=[batch, 1], dtype="int32", fill_value=0)
这里检查了下，因为有的时候input_ids是None，

2023-09-18 02:41 UTC, zhoutianzi666 commented on paddlenlp/transformers/opt/modeling.py
> +        if input_ids is not None and input_embeddings is None:
这里加了个检查

2023-09-18 03:20 UTC, wj-Mcat requested changes
这个 PR 非常棒，给 OPT 模型添加 inference-model 推理。

以下是我的建议，此外 llm 目录下已经添加了对应的 llm 的单测，建议仿照 llm/test_pretrain 中的 llama 来添加对应的单元测试。

2023-09-18 03:20 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +            if model_kwargs["all_input_ids"] is None:
model_kwargs["all_input_ids"] 已经在sample 中初始化过了的：https://github.com/PaddlePaddle/PaddleNLP/blob/7a1b56ea5b35c3c3f810984bb0f6b3509aa41ebf/paddlenlp/experimental/transformers/generation_utils.py#L307 ，这里不需要重复初始化。

2023-09-18 03:20 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +        model_kwargs["past_kv_length"] = paddle.full(shape=[batch], dtype="int32", fill_value=0)
这里为通用模块，不建议在这里专门给 opt 模型做一个 magic number。

你要是先 past_kv_length 的话，可以直接通过 all_input_ids 变量来就行了，这个数值包含：input_ids, decoded_ids

2023-09-18 03:20 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +            model_kwargs["past_kv_length"] = model_kwargs["seq_len_encoder"].reshape([batch])
这里的输入可以通过: all_input_ids 和  seq_len_encoder 都可以获取到

2023-09-18 03:20 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/opt/modeling.py
> +        self.hidden_size = config.hidden_size
这里的代码很明显没有过 lint，建议：

```shell
pip install --upgrade pre-commit
pre-commit install
```

来安装本地 git hook

2023-09-18 03:20 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/opt/modeling.py
> +        ffn2_bias_attrs = [paddle.ParamAttr(name="opt.decoder.layers.{}.linear2.bias".format(i)) for i in range(config.num_hidden_layers)]
非常好，这里的 name 能够和原始模型的 layer name 对应上，可以一定程度上减少概念上的迁移，提升代码可阅读性，非常赞 👍

2023-09-18 03:20 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/opt/modeling.py
> +        with paddle.base.framework._stride_in_no_check_dy2st_diff():
在 paddlenlp 中建议使用：  https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/experimental/transformers/llama/modeling.py#L292 

方法来做动转静的检查。

2023-09-18 03:20 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/opt/modeling.py
> +        self.final_layer_norm.bias.set_value(paddle.to_tensor(state_dict["opt.decoder.final_layer_norm.bias"]))
我觉得这部分代码以下问题：

假如模型权重大小为 10GB，模型初始化的过程中显存会达到 20G +，建议在本地查看一下这个问题。可能的解决方案为：set_value(state_dict.pop("layer-name"))， paddle.to_tensor 也会创建一份新的tensor，回影响性能。

在本地测试一下？？

2023-09-18 03:20 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/opt/modeling.py
> +        kwargs["use_safetensors"] = False
```suggestion
        kwargs["use_safetensors"] = kwargs.get("use_safetensors", False)
```

建议用这个代码，因为在单卡情况下，safetensor 还是可以用的。

2023-09-18 03:20 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/opt/modeling.py
> +            "past_kv_length": past_kv_length,
"past_kv_length": kwargs.get("all_input_ids").shape[1],

可以使用这个代码来初始化 past_kv_length的数据。

2023-09-18 07:34 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/opt/modeling.py
> +        with paddle.base.framework._stride_in_no_check_dy2st_diff():
> 在 paddlenlp 中建议使用： https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/experimental/transformers/llama/modeling.py#L292
> 
> 方法来做动转静的检查。

done

2023-09-18 07:36 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/opt/modeling.py
> +        kwargs["use_safetensors"] = False
> kwargs["use_safetensors"] = kwargs.get("use_safetensors", False)

done

2023-09-18 08:03 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/opt/modeling.py
> +        self.final_layer_norm.bias.set_value(paddle.to_tensor(state_dict["opt.decoder.final_layer_norm.bias"]))
> 我觉得这部分代码以下问题：
> 
> 假如模型权重大小为 10GB，模型初始化的过程中显存会达到 20G +，建议在本地查看一下这个问题。可能的解决方案为：set_value(state_dict.pop("layer-name"))， paddle.to_tensor 也会创建一份新的tensor，回影响性能。
> 
> 在本地测试一下？？

本地测试不会造成你说的这个情况。这个我先不改动吧

2023-09-18 08:07 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/generation_utils.py
> +            model_kwargs["past_kv_length"] = model_kwargs["seq_len_encoder"].reshape([batch])
> 这里的输入可以通过: all_input_ids 和 seq_len_encoder 都可以获取到

对于图生文对case，generate的输入 input_ids为None，这个不太好办

2023-09-18 09:52 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/opt/modeling.py
> +            "past_kv_length": past_kv_length,
> "past_kv_length": kwargs.get("all_input_ids").shape[1],
> 
> 可以使用这个代码来初始化 past_kv_length的数据。

对于图生文对case，generate的输入 input_ids为None，造成kwargs.get("all_input_ids").shap[1]其实是比真实的past_kv_length要小的

2023-09-18 11:40 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/opt/modeling.py
> +        self.hidden_size = config.hidden_size
> 这里的代码很明显没有过 lint，建议：
> 
> ```shell
> pip install --upgrade pre-commit
> pre-commit install
> ```
> 
> 来安装本地 git hook

感谢 done

2023-09-21 02:22 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/generation_utils.py
> +            if model_kwargs["all_input_ids"] is None:
> model_kwargs["all_input_ids"] 已经在sample 中初始化过了的：
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/7a1b56ea5b35c3c3f810984bb0f6b3509aa41ebf/paddlenlp/experimental/transformers/generation_utils.py#L307
> 
> ，这里不需要重复初始化。

这里主要是检查下初始化的东西是不是None，可能你上面初始化的东西是个None

2023-09-21 02:43 UTC, xiaoxiaohehe001 approved these changes
LGTM

2023-09-21 06:41 UTC, wj-Mcat approved these changes
LGTM

2023-09-21 06:41 UTC, merged