[WIP]Add MINILM
PaddlePaddle/PaddleNLP pull request #704
Opened 2021-07-07 06:40 UTC by LiuChiachi

### PR types

New features
### PR changes

Models
### Description

A implementation of MINILMv2, a general distillation algorithm, and update `distill_utils.py` to support MINILM.

2021-07-07 07:34 UTC, ZeyuChen reviewed
要注意同步更新模型文档列表

2021-07-30 04:46 UTC, tianxin1860 reviewed
Optimizer 部分需要一些修改

2021-07-30 04:46 UTC, tianxin1860 commented on examples/model_compression/minilm/general_distill.py
> +    optimizer = paddle.optimizer.Adam(
Adam with WeightDecay 的实现不应该使用这个 API  吧,  替换成 AdamW ?

2021-07-30 04:46 UTC, tianxin1860 commented on examples/model_compression/minilm/general_distill.py
> +    optimizer = paddle.optimizer.Adam(
Adam 和 weight_decay 结合起来使用的时候，并不是所有参数都需要 weight_decay: bias、norm 相关参数不需要 decay.

2021-07-30 04:46 UTC, tianxin1860 commented on examples/model_compression/minilm/general_distill.py
> +    optimizer = paddle.optimizer.Adam(
AdamW optimizer 在使用的时候最好加入梯度裁剪 Clip 限制梯度最大 Norm， 否则训练过程中遇见噪音数据可能模型就发散了.

2021-08-08 12:26 UTC, tianxin1860 requested changes
Leave some comment

2021-08-08 12:26 UTC, tianxin1860 commented on examples/model_compression/minilm/general_distill.py
> +    clip = paddle.nn.ClipGradByGlobalNorm(clip_norm=1.0)
尽量避免硬编码，`clip_norm = args.max_grad_norm` 合适一些.

2021-08-08 12:26 UTC, tianxin1860 commented on examples/model_compression/minilm/general_distill.py
> +    student = to_distill(student, return_qkv=True, layer_index=5)
layer_index 参数是否考虑拆分作为 teacher_layer_index 和 student_ layer_index 从命令行传入比较合适？

2021-08-08 12:26 UTC, tianxin1860 commented on examples/model_compression/minilm/general_distill.py
> +                f_start_id * paddle.distributed.get_world_size() +
f_start_id 的取值始终为 0 ？

2021-08-13 13:53 UTC, tianxin1860 requested changes
Leave some comment

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/minilm/general_distill.py
> +        "--model_type",
是否命名为 student_model_type 与 teacher_model_type 相对应?

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/tinybert/general_distill.py
> +def create_pretraining_dataset(input_file, shared_list, args, worker_init,
`shared_list` is an unused variable

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/minilm/general_distill.py
> +def create_pretraining_dataset(input_file, shared_list, args, worker_init,
`shared_list` is an unused variable

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/minilm/general_distill.py
> +            kl_loss_fct = paddle.nn.KLDivLoss('sum')
`kl_loss_fct` -> `kl_loss_func` 表意更清楚一些.

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/tinybert/general_distill.py
> +    ce_loss_fct = paddle.nn.CrossEntropyLoss(soft_label=True)
`kl_loss_fct` -> `kl_loss_func`

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/tinybert/general_distill.py
> +    mse_loss_fct = paddle.nn.MSELoss()
同上

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/tinybert/general_distill.py
> +                attention_mask = paddle.unsqueeze(
`attention_mask ` is unused ？

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/tinybert/general_distill.py
> +                attention_mask = paddle.unsqueeze(
1. 此处的 attention_mask 计算出来之后为什么不需要传到前向 forward 函数里？
2. 如果不传的话，此处没必要计算 attention_mask.

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/tinybert/task_distill.py
> +        return_qkv=True,
应该是 `return_qkv=False` ?

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/tinybert/task_distill.py
> +        return_qkv=True,
同上

2021-08-13 13:53 UTC, tianxin1860 commented on examples/model_compression/tinybert/task_distill.py
> +            attention_mask = paddle.unsqueeze(
计算了 attention_mask 没有使用

2021-08-13 13:53 UTC, tianxin1860 commented on paddlenlp/transformers/distill_utils.py
> +def calc_minilm_loss(loss_fct, s, t, attn_mask, num_relation_heads=0):
calc_minilm_loss 的逻辑属于 MiniLM 策略的一部分，是否放在 MiniLM 目录下实现合适一些？ distill_utils.py 我理解应该是一些模型无关的通用逻辑实现?

2021-08-13 13:53 UTC, tianxin1860 commented on paddlenlp/transformers/distill_utils.py
>      for i, mod in enumerate(self.layers):
`mod` 变量命名表意不清楚

2021-08-24 08:05 UTC, LiuChiachi commented on examples/model_compression/minilm/general_distill.py
> +    optimizer = paddle.optimizer.Adam(
Done. Thanks!

2021-08-24 08:05 UTC, LiuChiachi commented on examples/model_compression/minilm/general_distill.py
> +    clip = paddle.nn.ClipGradByGlobalNorm(clip_norm=1.0)
Done. Thanks!

2021-08-24 08:05 UTC, LiuChiachi commented on examples/model_compression/minilm/general_distill.py
> +    student = to_distill(student, return_qkv=True, layer_index=5)
Done. Thanks!

2021-08-24 08:05 UTC, LiuChiachi commented on examples/model_compression/minilm/general_distill.py
> +        "--model_type",
Done. Thanks!

2021-08-24 08:05 UTC, LiuChiachi commented on examples/model_compression/tinybert/general_distill.py
> +def create_pretraining_dataset(input_file, shared_list, args, worker_init,
Done. Thanks!

2021-08-24 08:05 UTC, LiuChiachi commented on examples/model_compression/minilm/general_distill.py
> +def create_pretraining_dataset(input_file, shared_list, args, worker_init,
Done. Thanks!

2021-08-24 08:05 UTC, LiuChiachi commented on examples/model_compression/minilm/general_distill.py
> +            kl_loss_fct = paddle.nn.KLDivLoss('sum')
Done. Thanks!

2021-08-24 08:05 UTC, LiuChiachi commented on examples/model_compression/tinybert/general_distill.py
> +    ce_loss_fct = paddle.nn.CrossEntropyLoss(soft_label=True)
Done. Thanks!

2021-08-24 08:05 UTC, LiuChiachi commented on examples/model_compression/tinybert/task_distill.py
> +        return_qkv=True,
Done. Thanks!

2021-08-24 08:05 UTC, LiuChiachi commented on examples/model_compression/tinybert/task_distill.py
> +        return_qkv=True,
Done. Thanks!

2021-08-24 08:06 UTC, LiuChiachi commented on examples/model_compression/tinybert/task_distill.py
> +            attention_mask = paddle.unsqueeze(
Deleted. Thanks!

2021-08-24 08:06 UTC, LiuChiachi commented on paddlenlp/transformers/distill_utils.py
> +def calc_minilm_loss(loss_fct, s, t, attn_mask, num_relation_heads=0):
希望不止是在这个example里可以用到minilmv2策略

2021-09-01 07:02 UTC, tianxin1860 reviewed
Leave a comment

2021-09-01 07:02 UTC, tianxin1860 commented on examples/model_compression/minilm/README.md
> +假设我们把数据文件都放在`/PaddleNLP/dataset`下，那么我们可以运行如下命令用单机八卡进行预训练蒸馏：
CLUE 数据集不是已经集成到 PaddleNLP dataset 里了吗？

2021-09-02 05:01 UTC, LiuChiachi commented on paddlenlp/transformers/distill_utils.py
>      for i, mod in enumerate(self.layers):
这里参考了框架transformer API的写法。

2021-09-02 06:43 UTC, tianxin1860 approved these changes
LGTM

2021-09-02 07:04 UTC, merged