[llm benchmark] Add flash attention
PaddlePaddle/PaddleNLP pull request #7057
Opened 2023-09-18 06:10 UTC by w5688414

### PR types

### PR changes

### Description

2023-09-20 03:58 UTC, sijunhe commented on paddlenlp/transformers/bloom/configuration.py
> +        self.use_flash_attention = use_flash_attention
这个字段放到基类里面吧，默认为false

2023-09-20 03:58 UTC, sijunhe commented on paddlenlp/transformers/chatglm/modeling.py
> +                is_causal=attention_mask is None,
chatglm不可能是causal mask, 直接is_causal=False

2023-09-20 03:58 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
>              raise ValueError("Flash Attention does not support ALiBi yet")
这里也需要支持一下，不能再直接报错了

2023-09-20 03:58 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +            is_causal=attention_mask is None,
这样子不行，会和上次一样，让预训练也走入带mask的FA. 我和阿辉商量了，这块我来提一个PR处理一下，你基于这个修改吧

2023-09-20 11:17 UTC, w5688414 commented on paddlenlp/transformers/chatglm/modeling.py
> +                is_causal=attention_mask is None,
已修改

2023-09-20 11:19 UTC, w5688414 commented on paddlenlp/transformers/llama/modeling.py
>              raise ValueError("Flash Attention does not support ALiBi yet")
已修改

2023-10-18 14:02 UTC, sijunhe requested changes
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm/llama#3-%E9%A2%84%E8%AE%AD%E7%BB%83
llama的预训练也需要验证一下

2023-10-18 14:02 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +            is_causal=config.is_causal,
如果真的要is_causal这个，是不是应该用185行的is_causal传入进来？
@ZHUI 一起来看一下这个地方, 之前我考虑过预训练不传入attention_mask来控制FA的is_causal, 但是当前的写法是如果不传入attention_mask的话，https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/llama/modeling.py#L1223 这个地方会先生成2D mask再expand成4D, 到了scaled_dot_product这里就无法区分了

2023-10-18 14:02 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +        # TODO: attention_mask is None is not reliable
如果is_causal, attention_mask是否应该赋值为None

2023-10-19 02:46 UTC, ZHUI commented on paddlenlp/transformers/llama/modeling.py
> +            is_causal=config.is_causal,
> https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/llama/modeling.py#L1223 这个地方会先生成2D

可以这里如果是`use_flash_attention`的话，不制作attention_mask吗？

2023-10-24 03:18 UTC, ZHUI commented on paddlenlp/transformers/llama/modeling.py
> +        if is_casual:
```suggestion
        if is_casual and self.use_flash_attention:
```

2023-10-25 03:33 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +        if is_casual:
这个地方应该只有self.use_flash_attention为true的时候，才需要is_casual_mask。不开FA可以不跑这个

2023-10-25 03:38 UTC, sijunhe commented on paddlenlp/transformers/llama/modeling.py
> +    return (inf_mask == attention_mask).all().item()
1. 当前的实现方法264行的dtype需要是bool, 要不然动转静报错，见单测
2. 这里的实现可以更简单些，不用重新造一个inf_mask. 可不可以直接`paddle.tril(attention_mask) == attention_mask`这个逻辑呢？

2023-10-25 04:08 UTC, w5688414 commented on paddlenlp/transformers/llama/modeling.py
> +        if is_casual:
我添加到is_casual_mask的上面了

2023-10-25 04:24 UTC, w5688414 commented on paddlenlp/transformers/llama/modeling.py
> +    return (inf_mask == attention_mask).all().item()
已修改

2023-10-25 07:55 UTC, sijunhe approved these changes
lgtm

2023-10-26 04:21 UTC, merged