Simbert
PaddlePaddle/PaddleNLP pull request #706
Opened 2021-07-07 13:48 UTC by leeyy2020

### PR types

New features
### PR changes

Models
### Description

1.add simbert-base-chinese
2.为BertModel增加参数with_pool以适应集成simbert
3.在examples/text_matching下增加simbert文件夹，增加predict.py和README.md

2021-07-07 13:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=706) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=706) before we can accept your contribution.<br/><hr/>**liyueyang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=706) it.</sub>

2021-07-07 17:42 UTC, tianxin1860 requested changes
数据预处理部分和一些代码风格需要修改下

2021-07-07 17:42 UTC, tianxin1860 commented on examples/text_matching/simbert/predict.py
> +paddle_model = BertModel.from_pretrained(paddle_model_name,with_pool="linear")
1. 注意变量命名符合规范: `paddle_model` -> `model`
2. 代码风格规范: `with_pool="linear"` 与 `,` 之间需要加1个空格

2021-07-07 17:42 UTC, tianxin1860 commented on examples/text_matching/simbert/predict.py
> +paddle_model.eval()
变量命名可以去掉前缀 `paddle_`, 更符合常规用法

2021-07-07 17:42 UTC, tianxin1860 commented on examples/text_matching/simbert/predict.py
> +paddle_model_name = 'simbert-base-chinese'
demo 示例目前就 1 个 `'simbert-base-chinese'` 模型，可以直接把字符串传入 `from_pretrained` 函数

2021-07-07 17:42 UTC, tianxin1860 commented on examples/text_matching/simbert/predict.py
> +# 加载数据
数据预处理逻辑: tokenize、组 Batch 这些操作需要基于 PaddleNLP 相关接口实现，目前的预测每次只支持每次抽取 1 条文本向量。参考示例:  https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/text_matching/ernie_matching/predict_pointwise.py

2021-07-08 05:41 UTC, ZeyuChen commented
@leeyy2020 SignCLA first, thanks!

2021-07-08 05:52 UTC, ZeyuChen commented on examples/text_matching/simbert/README.md
> +SimBERT的模型权重是以Google开源的BERT模型为基础，基于微软的UniLM思想设计了融检索与生成于一体的任务，来进一步微调后得到的模型，所以它同时具备相似问生成和相似句检索能力。
建议加上SimBERT原始出处的地址

2021-07-08 05:52 UTC, ZeyuChen commented on examples/text_matching/simbert/README.md
> +```
需要补充上SimBERT相关Reference

2021-07-08 05:52 UTC, ZeyuChen commented on examples/text_matching/simbert/predict.py
> +paddle_model_name = 'simbert-base-chinese'
他只有一个base是吗？

2021-07-08 05:53 UTC, ZeyuChen reviewed
原始SimBERT是否有提供Pretrain的代码？

2021-07-08 06:29 UTC, leeyy2020 commented on examples/text_matching/simbert/predict.py
> +paddle_model_name = 'simbert-base-chinese'
还有tiny和small

2021-07-08 06:30 UTC, leeyy2020 commented on examples/text_matching/simbert/predict.py
> +paddle_model_name = 'simbert-base-chinese'
> 他只有一个base是吗？
还有tiny和small没有转换

2021-07-08 06:37 UTC, leeyy2020 commented
> 原始SimBERT是否有提供Pretrain的代码？

有提供

2021-07-08 08:09 UTC, tianxin1860 commented on examples/text_matching/simbert/predict.py
> +paddle_model_name = 'simbert-base-chinese'
顺手把 `tiny` 和 `small` 版本也转换进来吧，比较完整一些.

2021-07-08 08:50 UTC, ZeyuChen commented
@tianxin1860 是否需要增加下预训练部分代码，或者是与SimCSE如何结合？

2021-07-09 07:16 UTC, tianxin1860 reviewed
> @tianxin1860 是否需要增加下预训练部分代码，或者是与SimCSE如何结合？

SimBERT 预训练方式没有权威的论文产出，暂时先不用集成预训练部分. SimCSE 初步计划是会在 text_matching 目录下新开1个目录.

2021-07-09 07:16 UTC, tianxin1860 commented on examples/text_matching/simbert/README.md
> +SimBERT的模型权重是以Google开源的BERT模型为基础，基于微软的UniLM思想设计了融检索与生成于一体的任务，来进一步微调后得到的模型，所以它同时具备相似问生成和相似句检索能力。
这里可以给 `SimBERT` 加上原始地址的超链接引用，用户点击就会链接到 SimBERT 原始 github Repo

2021-07-09 07:23 UTC, leeyy2020 commented on examples/text_matching/simbert/README.md
> +SimBERT的模型权重是以Google开源的BERT模型为基础，基于微软的UniLM思想设计了融检索与生成于一体的任务，来进一步微调后得到的模型，所以它同时具备相似问生成和相似句检索能力。
已加入

2021-07-09 07:23 UTC, leeyy2020 commented on examples/text_matching/simbert/README.md
> +```
已补充

2021-07-09 07:26 UTC, tianxin1860 reviewed
Leave some comments

2021-07-09 12:22 UTC, ZeyuChen commented on examples/text_matching/simbert/predict.py
> +paddle_model_name = 'simbert-base-chinese'
记得同步更新transformer模型列表整体文档

2021-07-13 09:21 UTC, leeyy2020 commented on examples/text_matching/simbert/README.md
> +SimBERT的模型权重是以Google开源的BERT模型为基础，基于微软的UniLM思想设计了融检索与生成于一体的任务，来进一步微调后得到的模型，所以它同时具备相似问生成和相似句检索能力。
已修改

2021-07-13 09:22 UTC, leeyy2020 commented on examples/text_matching/simbert/predict.py
> +paddle_model_name = 'simbert-base-chinese'
已同步

2021-07-13 09:23 UTC, leeyy2020 commented on examples/text_matching/simbert/predict.py
> +paddle_model_name = 'simbert-base-chinese'
> 记得同步更新transformer模型列表整体文档

已同步

2021-07-13 09:23 UTC, leeyy2020 commented on examples/text_matching/simbert/README.md
> +SimBERT的模型权重是以Google开源的BERT模型为基础，基于微软的UniLM思想设计了融检索与生成于一体的任务，来进一步微调后得到的模型，所以它同时具备相似问生成和相似句检索能力。
> 这里可以给 `SimBERT` 加上原始地址的超链接引用，用户点击就会链接到 SimBERT 原始 github Repo

已修改

2021-07-13 09:38 UTC, tianxin1860 commented on docs/model_zoo/transformers.rst
> +|                    |                                     |              | text.                                   |
Trained on cased Chinese Simplified texts and similar question pairs from Baidu Knows.

2021-07-13 09:39 UTC, tianxin1860 requested changes
SimBERT 的训练数据用了 2200 万从百度知道上挖掘的相似问句 pair

2021-07-13 09:55 UTC, leeyy2020 commented
> SimBERT 的训练数据用了 2200 万从百度知道上挖掘的相似问句 pair

已修改

2021-07-13 10:56 UTC, tianxin1860 approved these changes
LGTM

2021-07-13 11:38 UTC, ZeyuChen approved these changes
LGTM

2021-07-13 11:38 UTC, merged

2021-07-19 02:53 UTC, LiuChiachi commented on paddlenlp/transformers/bert/modeling.py
> +    def __init__(self, hidden_size, with_pool):
这里是否可以改成兼容的升级呢？

2021-07-19 03:58 UTC, leeyy2020 commented on paddlenlp/transformers/bert/modeling.py
> +    def __init__(self, hidden_size, with_pool):
已修改https://github.com/PaddlePaddle/PaddleNLP/pull/765