[LLM] Support gpt3 fine grained dybatch v1
PaddlePaddle/PaddleNLP pull request #7080
Opened 2023-09-19 08:23 UTC by yuanlehome

### PR types

Others
### PR changes

Others
### Description

Support gpt3 fine grained dybatch v1.

2023-09-19 09:15 UTC, vivienfanghuagood commented on llm/predictor.py
> -                    config.tensor_parallel_rank = tensor_parallel_rank
怎么把多卡的处理逻辑去掉了？

2023-09-19 09:21 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/gpt/modeling.py
> +        ln_scale_attrs = [paddle.ParamAttr(name="fusemt.{}.ln_scale".format(i)) for i in range(self.num_layers)]
这里的这些名字能和GPT里面的名字取得一样吗？否则有点绕啊

2023-09-19 09:25 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/gpt/modeling.py
> +            hidden_states, _ = self.transformer_block(
用 with dy2st_nocheck_guard_context(): 代替with paddle.base.framework._stride_in_no_check_dy2st_diff():

2023-09-19 09:36 UTC, yuanlehome commented on paddlenlp/experimental/transformers/gpt/modeling.py
> +            hidden_states, _ = self.transformer_block(
好的

2023-09-19 09:36 UTC, yuanlehome commented on paddlenlp/experimental/transformers/gpt/modeling.py
> +        ln_scale_attrs = [paddle.ParamAttr(name="fusemt.{}.ln_scale".format(i)) for i in range(self.num_layers)]
可以的，我改下

2023-09-19 09:36 UTC, yuanlehome commented on llm/predictor.py
> -                    config.tensor_parallel_rank = tensor_parallel_rank
往上面找几行，删除的是冗余的

2023-09-20 07:41 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/gpt/modeling.py
> +        for k, v in state_dict.items():
这里的if代码有点多啊？能改的和llama里的一样吗？

2023-09-20 07:46 UTC, yuanlehome commented on paddlenlp/experimental/transformers/gpt/modeling.py
> +        for k, v in state_dict.items():
建议先这样写，因为gpt的模型来源比较复杂，参数名比较乱，这种if写法已经尽可能多的兼容各种命名的模型了

2023-09-20 09:25 UTC, wj-Mcat requested changes
代码质量很好，有两个小建议

2023-09-20 09:25 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/gpt/modeling.py
> +        kwargs["use_safetensors"] = False
```suggestion
        kwargs["use_safetensors"] = kwargs.get("use_safetensors", False)
```

建议使用这个，因为单分片 safetensors 是可以支持 inferencemodel 加载的。

2023-09-20 09:25 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/gpt/modeling.py
> +            attention_mask = (attention_mask - 1) * 1e4
这里建议使用：paddle.finfo(attention_mask.dtype).min 的方式来转化 attention_mask 的值。

在 bf16 和 fp16 下面不同值域不一样，建议用这个来得到该 dtype 下的最小值。

上面的 tgt_attention_mask 也是需要调整一下。

2023-09-20 09:41 UTC, yuanlehome commented
> 代码质量很好，除了以下两个 comment，还有一个小建议：添加单测，等 #7056 合入之后编写一个 test_predictor 的单测呗。

可以的，我想补充单测和comment指出的问题 放在下个PR一块做吧，这个PR先合一版？

2023-09-20 12:51 UTC, wj-Mcat approved these changes

2023-09-20 12:51 UTC, merged