[WIP] Add shard checkpoint save and load
PaddlePaddle/PaddleNLP pull request #7143
Opened 2023-09-27 09:27 UTC by DesmonDay

### PR types
New features

### PR changes
Others

### Description
Add sharded checkpoint for save and load.

2023-09-27 09:40 UTC, ZHUI requested changes

2023-09-27 09:40 UTC, ZHUI commented on paddlenlp/trainer/training_args.py
> +            if self.old_save_load:
不要用这个了

2023-09-27 09:40 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +                if isinstance(unwrap_model(self.model), PretrainedModel):
全部挪出去，不要放trainer里面了

2023-09-27 09:40 UTC, ZHUI commented on paddlenlp/transformers/conversion_utils.py
> +    def merge_tensor_parallel_with_shard(cls, state_dict, config, all_filter_keys) -> None:
不要放这里，全部放你的 sharded ckpt io

2023-09-27 09:46 UTC, DesmonDay commented on paddlenlp/trainer/training_args.py
> +    old_save_load: Optional[bool] = field(
```suggestion
    unify_hybrid_parallel_checkpoint: Optional[bool] = field(
```

2023-09-27 09:57 UTC, ZHUI commented on paddlenlp/trainer/utils/sharded_ckpt_io.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
放到 `paddlenlp/trainer/plugins`文件夹吧，不放utils里

2023-09-27 11:19 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +        self.sharded_ckpt_io = ShardedCkptIO(self.args, self.model)
能否 model 对象也不持有？

2023-10-08 08:55 UTC, DesmonDay commented on paddlenlp/trainer/utils/sharded_ckpt_io.py
> +# Copyright (c) 2023 PaddlePaddle Authors. All Rights Reserved.
done

2023-10-08 08:55 UTC, DesmonDay commented on paddlenlp/trainer/trainer.py
> +        self.sharded_ckpt_io = ShardedCkptIO(self.args, self.model)
done

2023-10-10 07:53 UTC, ZHUI commented on paddlenlp/trainer/training_args.py
> +            if not self.unify_hybrid_parallel_checkpoint:
可以单独写，不要耦合。

2023-10-10 07:53 UTC, ZHUI commented on paddlenlp/trainer/training_args.py
> +    unify_hybrid_parallel_checkpoint: Optional[bool] = field(
```suggestion
    unified_checkpoint: Optional[bool] = field(
```

2023-10-16 08:04 UTC, ZHUI commented
Move to https://github.com/PaddlePaddle/PaddleNLP/pull/7238/files

2023-12-15 07:56 UTC, closed without merging