bloom chatglmv1/2 llm unittest
PaddlePaddle/PaddleNLP pull request #7165
Opened 2023-10-08 09:06 UTC by wtmlon

### PR types

### PR changes

### Description

bloom chatglm v1/2 llm模块单元测试

2023-10-08 09:47 UTC, wtmlon commented
这里ci挂了是因为chatglm的tiny random模型config中没有use_cache=true导致的，涉及到trainer，chatglm modeling的一些实现冲突，具体改法需要讨论下

2023-10-09 02:24 UTC, wj-Mcat requested changes
非常棒，留了几个 comment有时间看看

2023-10-09 02:24 UTC, wj-Mcat commented on tests/llm/test_finetune.py
> +        print(finetune_config)
这里的 print 可以删掉

2023-10-09 02:24 UTC, wj-Mcat commented on tests/llm/test_predictor.py
> +        ["__internal_testing__/tiny-fused-chatglm", ChatGLMForCausalLM],
这里为什么不把 chatglm2 给添加进来，我看上面的 lora 测试都添加了。

2023-10-09 02:24 UTC, wj-Mcat commented on tests/llm/test_predictor.py
> +                full_match += 1
返回空是有可能的，可是不应该所有的推理结果都返回为空，所以这里建议添加一个对于全空的判断：all_empty_count。

2023-10-12 06:06 UTC, wj-Mcat approved these changes
LGTM

2023-10-12 06:06 UTC, merged