[LLM] Support ptq inference
PaddlePaddle/PaddleNLP pull request #7224
Opened 2023-10-13 10:59 UTC by RichardWooSJTU

### PR types

New features
### PR changes

Others
### Description

- Add FusedMultiTransformerA8W8
- Support FusedMultiTransformerA8W8 in Llama model
- Add unit test for ptq

**Attention**:

`quant_type` is used to specify which quant method applied, whose options is modified to
- A8W8
- WINT8
- WINT4

from 

- weight_only_int8
- weight_only_int4

2023-10-23 11:29 UTC, wj-Mcat requested changes, later dismissed

2023-10-23 11:29 UTC, wj-Mcat commented on llm/README.md
> +```shell
这部分的文档可以迁移到： https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/inference.md  中去。

2023-10-23 11:29 UTC, wj-Mcat commented on llm/predictor.py
> +    quant_max_bound: float = field(default=127.0, metadata={"help": "The max bound of float type to int type"})
`quant_max_bound`  和 `quant_min_bound` 应该可以通过 `quant_type` 自动计算出来的吧，这里是否可以减少这两个参数呢？

2023-10-23 11:29 UTC, wj-Mcat commented on llm/predictor.py
> +                    if predictor_args.quant_type.startswith("WINT"):
weight_only_int8/4 相关的配置应该都统一用 weight_only_int 这个来吧，这里为什么要改成：WINT 呢？

因为框架那边的描述都是weight_only_int 系列的，你这里确直接**简化**了，感觉这针对于这个参数是一个breaking_change.

2023-10-23 11:29 UTC, wj-Mcat commented on llm/predictor.py
> +                        config.quant_min_bound = predictor_args.quant_min_bound
同上，这两个值应该可以通过 quant_type 来计算了的吧。

2023-10-23 11:29 UTC, wj-Mcat commented on llm/predictor.py
> +        "Input length is: {}, Output length is: {}, bs is: {}, Generate speed is: {:.3f} tokens/s(ips), time: {}, QPS: {:.3f} requests/s. ".format(
这里的关键字不能改，这个涉及到 benchmark 中的关键字提取，所以这部分的描述尽量不要改，不然会 break 一些东西。

2023-10-23 11:29 UTC, wj-Mcat commented on llm/predictor.py
> +    paddle.base.core.update_autotune_status()
加这两个的作用是什么呢？因为这个是 predictor，不涉及到训练，所以应该不需要添加这两行代码吧。

2023-10-23 11:29 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/fused_transformer_layers.py
> +        self.weight_only_quant_bits = weight_only_quant_bits
这里为什么要改成这个呢？

2023-10-23 11:29 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/llama/modeling.py
> +                    linear_weight_tensor, algo=self.weight_only_quant_algo
这里的 self.weight_only_quant_algo 其实就是 quant_type啊，如果 quant_type 保持为 weight_only_int* 系列的命令，就不需要额外创建一个参数了。

另外，在参数命名上面尽量保持一致，你觉得呢？

2023-10-23 11:29 UTC, wj-Mcat commented on tests/llm/test_ptq.py
> +        self.run_predictor({"inference_model": True})
这里只能保证inference-model 的动静推理结果一致性，没办法和动态图保持一致，所以建议你参考：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/tests/llm/test_predictor.py#L73  来调整一下你这里的单测。

2023-10-23 12:50 UTC, lugimzzz commented on paddlenlp/experimental/transformers/llama/modeling.py
> +                self.transformer_block.qkv_weights[idx].set_value(
这么加载模型参数，会有一个问题加载模型先需要占用两倍的参数，然后cast后再变成一倍参数。比如一个65b的模型，实际int8模型只需65G但因为先加载成fp16参数需要130G单卡就会爆显存

2023-10-25 11:27 UTC, RichardWooSJTU commented on paddlenlp/experimental/transformers/fused_transformer_layers.py
> +        self.weight_only_quant_bits = weight_only_quant_bits
为了避免a8w8模式下quant_bit=-1引起的困惑

2023-10-25 11:29 UTC, RichardWooSJTU commented on llm/predictor.py
> +    paddle.base.core.update_autotune_status()
gemm int8依赖调优达到理想性能

2023-10-28 14:10 UTC, wj-Mcat commented on llm/.gitignore
> +__pycache__/
这个文件就不要加到git管理里面来了

2023-10-28 14:10 UTC, wj-Mcat commented on llm/benchmark.sh
> +    --model_name_or_path ./llama7b-inference_model_fp1 \
你把6弄丢了

2023-10-28 14:10 UTC, wj-Mcat commented on llm/predictor.py
> +        default="", metadata={"help": "Quantization type. Supported values: a8w8, weight_only_int4, weight_only_int8"}
这里的默认值可以设置为None

2023-10-28 14:10 UTC, wj-Mcat commented on llm/predictor.py
> +                weight_only_quant_bits = int(predictor_args.quant_type[-1])
我觉得你可以给PredictorArgument添加一个property: weight_only_quant_bits

2023-10-28 14:10 UTC, wj-Mcat commented on llm/predictor.py
> +                paddle.base.core.enable_autotune()
我看你在benchmark脚本里面添加了一个enable_autotune的环境变量，跟这里的作用应该是类似的吧

2023-10-28 14:10 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/llama/modeling.py
> +            current_work_dir = os.path.dirname(__file__)
这个应该从from_pretrained的目录中加载吧，这个麻烦 @lugimzzz 确认一下

2023-10-30 06:27 UTC, RichardWooSJTU commented on llm/predictor.py
> +                paddle.base.core.enable_autotune()
不是类似，两个必须同时开启

2023-10-30 06:27 UTC, lugimzzz commented on paddlenlp/experimental/transformers/llama/modeling.py
> +            current_work_dir = os.path.dirname(__file__)
是的

2023-10-30 06:28 UTC, RichardWooSJTU commented on llm/predictor.py
> +                weight_only_quant_bits = int(predictor_args.quant_type[-1])
之前泽康的设计是这样的避免给到重复信息，也能避免参数冲突，比如
- quant_type: weight_only_int8
- weight_only_int4

2023-10-30 06:36 UTC, RichardWooSJTU commented on paddlenlp/experimental/transformers/llama/modeling.py
> +            current_work_dir = os.path.dirname(__file__)
要不第一版先这样合入 麻烦 @lugimzzz 后续看下放到模型目录下的工作量

2023-11-13 03:45 UTC, heavengate approved these changes

2023-11-13 07:58 UTC, lugimzzz commented on paddlenlp/experimental/transformers/llama/modeling.py
> +            ffn1_out_scale_attrs = [
如果没有all linear的话不需要linear_out_scale_attrs，ffn1_out_scale_attrs，应该放在if self.shift_smooth_all_linears:分支里面

2023-11-13 08:10 UTC, lugimzzz approved these changes
lgtm

2023-11-13 08:10 UTC, RichardWooSJTU commented on paddlenlp/experimental/transformers/llama/modeling.py
> +            ffn1_out_scale_attrs = [
这里all linear不应该是shift smooth的参数吗 out scale只是ptq的参数

2023-11-13 08:11 UTC, wj-Mcat approved these changes

2023-11-13 08:11 UTC, merged

2023-11-13 08:22 UTC, lugimzzz commented on paddlenlp/experimental/transformers/llama/modeling.py
> +            ffn1_out_scale_attrs = [
确实，后面只是没有smooth shift，但仍然进行了量化