[LLM] use pin memory save optimizer and slove save problem
PaddlePaddle/PaddleNLP pull request #7245
Opened 2023-10-16 10:47 UTC by xysheng-baidu

### PR types

Others
### PR changes

Others
### Description

 [LLM] use pin memory save optimizer and slove save problem

2023-10-16 11:44 UTC, gongweibao requested changes

2023-10-16 11:44 UTC, gongweibao commented on paddlenlp/trainer/trainer.py
> +cpu_optimizer_state_dict = {}
```
g_cpu_optimizer_state_dict={}
```

2023-10-16 11:44 UTC, gongweibao commented on paddlenlp/trainer/trainer.py
>      if sync_other_task:
sync_other_task need to be true

2023-10-16 11:44 UTC, gongweibao commented on paddlenlp/trainer/trainer.py
>          clear_async_save_task_queue()
`clear_async_save_task_queue` need timeout and debug info.

2023-10-17 08:44 UTC, ZHUI approved these changes

2023-10-17 08:46 UTC, merged