[llm]support chatglmv2 in fined FT
PaddlePaddle/PaddleNLP pull request #7253
Opened 2023-10-17 07:38 UTC by zhoutianzi666

### PR types

Others
### PR changes

Others
### Description

2023-10-17 07:53 UTC, vivienfanghuagood commented on paddlenlp/experimental/transformers/chatglm_v2/modeling.py
> +            import numpy as np
移到头文件处

2023-10-17 07:55 UTC, vivienfanghuagood commented on paddlenlp/experimental/transformers/chatglm_v2/modeling.py
> +            if self.use_weight_only:
为啥 if self.use_weight_only: 这个判断要写四遍？放在一起可好？

2023-10-17 08:11 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/chatglm_v2/modeling.py
> +            if self.use_weight_only:
> 为啥 if self.use_weight_only: 这个判断要写四遍？放在一起可好？
放一起感觉不太好，这里按照参数出现的顺序写的，参考的llama的写法

2023-10-17 08:12 UTC, wj-Mcat requested changes
非常感谢实现和添加 chatglm2 的推理模型，也麻烦参照 test_predictor 来实现 chatglm2 的精度验证：https://github.com/PaddlePaddle/PaddleNLP/blob/develop/tests/llm/test_predictor.py

2023-10-17 08:12 UTC, wj-Mcat commented on llm/predictor.py
> +                    config.quant_bits = quant_bits
这部分的逻辑和模型没有关系，建议把这部分代码迁移迁移到：https://github.com/PaddlePaddle/PaddleNLP/blob/505bf153deaba74ba118c4af86ca5e278c925804/llm/predictor.py#L714  这里来，如此其他模型也可以复用这段逻辑。

2023-10-17 08:12 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/chatglm_v2/modeling.py
> +                raise ValueError(
在推理的时候为什么这里必须是等于 2 的呢？

sharding-stage 3（zeros 3）应该只用在训练阶段，推理阶段也用 zeros 3 的吗？ 麻烦  @heavengate   确认一下

2023-10-17 08:12 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/chatglm_v2/modeling.py
> +        # 32768
这样代码是否可以删除吗？

2023-10-17 08:20 UTC, zhoutianzi666 commented on llm/predictor.py
> +                    config.quant_bits = quant_bits
> 这部分的逻辑和模型没有关系，建议把这部分代码迁移迁移到：
> 
> https://github.com/PaddlePaddle/PaddleNLP/blob/505bf153deaba74ba118c4af86ca5e278c925804/llm/predictor.py#L714
> 
> 这里来，如此其他模型也可以复用这段逻辑。

done,感谢

2023-10-17 08:24 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/chatglm_v2/modeling.py
> +        # 32768
> 这样代码是否可以删除吗？

已经删除

2023-10-17 08:27 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/chatglm_v2/modeling.py
> +            import numpy as np
> 移到文件头处

done, thank you

2023-10-17 08:34 UTC, zhoutianzi666 commented on paddlenlp/experimental/transformers/chatglm_v2/modeling.py
> +                raise ValueError(
> 在推理的时候为什么这里必须是等于 2 的呢？
> 
> sharding-stage 3（zeros 3）应该只用在训练阶段，推理阶段也用 zeros 3 的吗？ 麻烦 @heavengate 确认一下

这里抄自散op组网，应该不用

2023-10-19 10:39 UTC, wj-Mcat approved these changes
LGTM

2023-10-19 10:39 UTC, merged