from_aistudio supports chat_template
PaddlePaddle/PaddleNLP pull request #7313
Opened 2023-10-26 06:06 UTC by wtmlon

### PR types

### PR changes

### Description

tokenizer.from_pretrained支持 aistuidio

2023-10-26 06:17 UTC, wj-Mcat requested changes
非常好，留了几个 comment

2023-10-26 06:17 UTC, wj-Mcat commented on paddlenlp/utils/downloader.py
> +            raise e
这块代码建议添加一下单测

2023-10-26 06:17 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils_base.py
> +            vocab_files = copy.deepcopy(vocab_files_target)
之前为什么不是深 copy `vocab_files_target` 的呢？是否可以判定之前的from_aistudio 是有 bug 的：没办法下载 additional_files。请  @sijunhe 确认一下

2023-10-26 06:17 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils_base.py
> +                res, cache_path = aistudio_file_exists_download(
这里的`res` 命名建议使用：file_existed 之类，这样代码可阅读性更好一些。

2023-10-29 05:39 UTC, sijunhe commented on paddlenlp/transformers/tokenizer_utils_base.py
> +            vocab_files = copy.deepcopy(vocab_files_target)
这个branch是之前的代码，我仅仅是把if from_hf_hub改成了if from_hf_hub or from_aistudio. 如果应该是vocab_files_target, 就直接改吧

2023-10-29 05:39 UTC, sijunhe commented on paddlenlp/utils/downloader.py
> +def aistudio_file_exists_download(repo_id: str, file_path: str):
不建议在downloader里面加这一段代码. 
我们暂时先把这个try...except的逻辑加到tokenizer_utils_base.py里去, aistudio_sdk那边我们提需求要求加入file_exists api再改

2024-10-14 16:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=7313) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=7313) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=7313) it.</sub>

2026-01-13 06:39 UTC, closed without merging