Gradio multi
PaddlePaddle/PaddleNLP pull request #7508
Opened 2023-11-23 06:50 UTC by wtmlon

### PR types

### PR changes

### Description

gradio 部署支持多卡，移除共享内存，采用多 flask 服务实现

2023-11-23 12:43 UTC, wj-Mcat requested changes

2023-11-23 12:43 UTC, wj-Mcat commented on llm/flask_server.py
> +                if os.path.exists(FILE_PREFIX):
不用添加这个 os.path.exists，如果文件已经存在了，FileLock 会自动锁住，这部分的逻辑在 FileLock 里面已经给 handle 了。

2023-11-23 12:43 UTC, wj-Mcat commented on llm/flask_server.py
> +                    if cnt == predictor.tensor_parallel_degree - 1:
你这个直接等于 -1 就行了吧，用再用：`cnt == predictor.tensor_parallel_degree - 1:`.

2023-11-23 12:43 UTC, wj-Mcat commented on llm/flask_server.py
> +            self.port = find_free_ports(scan_l, scan_u)
我感觉 with FileLock 的这个逻辑添加到 `find_free_ports` 函数中去，这样可以实现这部分的逻辑复用。

2023-11-23 12:43 UTC, wj-Mcat commented on llm/flask_server.py
> +        for _, peer_port in self.peer_ports.items():
这个函数只会在第一张卡上面调用，所以只需要判断rank 就行了。所以 self.port 其实可以不需要。

2023-11-23 12:43 UTC, wj-Mcat commented on llm/flask_server.py
> +        for _, peer_port in self.peer_ports.items():
另外，你这里的 self.peer_ports.items 可以换成：self.peer_ports.values

2023-11-23 12:43 UTC, wj-Mcat commented on llm/flask_server.py
> +    log_dir = os.environ["PADDLE_LOG_DIR"] if hasattr(os.environ, "PADDLE_LOG_DIR") else "./"
```suggestion
    log_dir = os.getenv("PADDLE_LOG_DIR", "./")
```

2023-11-23 12:43 UTC, wj-Mcat commented on llm/gradio_ui.py
> +            bot_response["utterance"] = bot_response["utterance"].replace("<s>", "")
上面这个不要删除，会影响 gradio 换行符的显示。

llama 的模型为什么会吐出 `<s>` ，predictor 在解码生成出来的内容的时候，已经加上了: `skip_special_tokens=True` 这个参数，所以理论上是不会有这个问题的啊。

2023-11-24 07:28 UTC, sijunhe approved these changes
ok

2023-11-24 07:29 UTC, merged