【WIP】add c3 mrc dataset
PaddlePaddle/PaddleNLP pull request #754
Opened 2021-07-15 08:11 UTC by joey12300

### PR types

New features
### PR changes

Others
### Description

Add C3 dataset. (The first free-form multiple-Choice Chinese machine reading Comprehension dataset.)

2021-07-15 12:30 UTC, ZeyuChen reviewed
需要同步更新dataset 文档的链接。
以及后续PR title全半角符号不要混用。

2021-07-15 12:30 UTC, ZeyuChen commented on paddlenlp/datasets/c3.py
> +    See more details on https://github.com/nlpdata/c3.
最好补充上论文链接。

2021-07-19 12:45 UTC, smallv0221 requested changes

2021-07-19 12:45 UTC, smallv0221 commented on paddlenlp/datasets/c3.py
> +    def get_labels(self):
我理解这个阅读理解单选问题不能直接用传统的分类来做，所以这里数字label是不是没有什么意义。

2021-07-19 12:45 UTC, smallv0221 commented on paddlenlp/datasets/c3.py
> +        return default_root
这里感觉返回一个下载好的文件的列表比较好，比如叫fullnames。然后_read方法直接去列表里找文件，就不用os.listdir了

2021-07-19 12:45 UTC, smallv0221 commented on paddlenlp/datasets/cail2019_scm.py
> +class CAIL2019_SCM(DatasetBuilder):
这里用CAIL2019-SCM吧，类名尽量不用snack case

2021-07-19 12:45 UTC, smallv0221 commented on paddlenlp/datasets/cail2019_scm.py
> +        Return labels of the Imdb object.
这里忘了改了

2021-07-19 12:45 UTC, smallv0221 commented on paddlenlp/datasets/cail2019_scm.py
> +    See more details on https://arxiv.org/abs/1911.08962.
这里最好说一下text_abc的关系，要不可能看不懂数据集咋用

2021-07-19 12:45 UTC, smallv0221 commented on paddlenlp/datasets/cail2019_scm.py
> +            docs = []
这个变量是做啥的

2021-07-20 01:58 UTC, joey12300 commented on paddlenlp/datasets/c3.py
> +    def get_labels(self):
其实就是分类的任务，input_ids组成方式是：`[CLS]-context-[SEP]-question-[SEP]-choice1-[SEP]-[CLS]-context-[SEP]-question-[SEP]-choice2-[SEP]...`，把所有choice都组合成一块，然后预测label。

2021-07-20 02:00 UTC, joey12300 commented on paddlenlp/datasets/cail2019_scm.py
> +class CAIL2019_SCM(DatasetBuilder):
类名中不能使用`-`，所以才使用下划线

2021-07-20 02:01 UTC, joey12300 commented on paddlenlp/datasets/cail2019_scm.py
> +            docs = []
已删

2021-07-20 02:06 UTC, joey12300 commented on paddlenlp/datasets/c3.py
> +        return default_root
done

2021-07-20 02:06 UTC, joey12300 commented on paddlenlp/datasets/cail2019_scm.py
> +        Return labels of the Imdb object.
done

2021-07-20 02:16 UTC, joey12300 commented on paddlenlp/datasets/cail2019_scm.py
> +    See more details on https://arxiv.org/abs/1911.08962.
已添加ABC相互关系的描述

2021-07-20 03:35 UTC, smallv0221 commented on paddlenlp/datasets/c3.py
> +    def get_labels(self):
那在yield出的字段加一个叫label的吧，直接根据choice和answer给出0,1,2,3的label吧。

2021-07-20 04:50 UTC, ZeyuChen commented on paddlenlp/datasets/c3.py
> +    def get_labels(self):
@joey12300 是这个数据集就是只能这样拼接来用，还是这个拼接策略跟模型是有关的？我们的数据集要做到跟模型解耦，不能够要用的时候只有一种拼接策略

2021-07-20 06:30 UTC, joey12300 commented on paddlenlp/datasets/c3.py
> +    def get_labels(self):
@ZeyuChen 拼接策略应该是跟模型有关，跟数据集无关。我所实现的数据集一般不添加任何与模型相关的预处理，尽量返回最原始的数据给用户。

2021-07-20 06:39 UTC, joey12300 commented on paddlenlp/datasets/c3.py
> +    def get_labels(self):
@smallv0221 已添加

2021-07-20 06:39 UTC, joey12300 commented on paddlenlp/datasets/c3.py
> +    See more details on https://github.com/nlpdata/c3.
已添加论文链接

2021-07-20 07:24 UTC, smallv0221 approved these changes
LGTM

2021-07-21 03:17 UTC, merged