Pp reshard develop
PaddlePaddle/PaddleNLP pull request #7629
Opened 2023-12-12 06:33 UTC by liuzhenhai93

### PR types

Others
### PR changes

Others

### Description

pipeline reshard

2023-12-13 03:32 UTC, GuoxiaWang commented on paddlenlp/trainer/training_args.py
> +    ignore_load_lr_and_optim: Optional[bool] = field(
这个地方是不是默认为 False 更合适？

2023-12-13 07:23 UTC, GuoxiaWang approved these changes
LGTM `ignore_load_lr_and_optim`

2023-12-14 03:53 UTC, gongweibao commented on llm/llama/run_sharding_v2.sh
> +#export LD_LIBRARY_PATH=/usr/local/cuda/compat:$LD_LIBRARY_PATH
这个要不要根据runtime版本和驱动版本判断一下？例如
```
cuda_version=`nvidia-smi \|grep "CUDA Version" \|awk '{print $9}' \|awk -F'.' '{print $1}'`
if [ ${cuda_version} != "12" ];then
    export LD_LIBRARY_PATH=/usr/local/cuda/compat:$LD_LIBRARY_PATH
fi
```

2023-12-14 03:53 UTC, gongweibao commented on llm/llama/run_sharding_v2.sh
> +    #--same_data True \
这些注释掉的内容还需要吗？

2023-12-14 04:04 UTC, gongweibao commented on paddlenlp/trainer/utils/sharding_io.py
> +        suffix = f"tp{self.args.tensor_parallel_rank:0>2d}_pp{pp_rank:0>2d}"
这个地方为何要把pp_rank限定到2位？

2023-12-14 04:13 UTC, liuzhenhai93 commented on paddlenlp/trainer/utils/sharding_io.py
> +        suffix = f"tp{self.args.tensor_parallel_rank:0>2d}_pp{pp_rank:0>2d}"
哦是这样的，  目前是按 tp x pp 保存 meta 信息的

2023-12-14 04:16 UTC, gongweibao requested changes
Add some more detailed description of these
```
pipeline reshard
load param only for sharding
```

2023-12-14 04:16 UTC, gongweibao commented on paddlenlp/trainer/utils/sharding_io.py
> +        parallel_config = self._load_distributed_strategy(checkpoint)
可以加一下参数的comment？

2023-12-14 04:16 UTC, gongweibao commented on paddlenlp/trainer/utils/sharding_io.py
> +        assert self.args.tensor_parallel_degree == mp_degree
Add explanation of this assert?
```
assert self.args.tensor_parallel_degree == mp_degree, "xxxx"
```

2023-12-14 06:36 UTC, gongweibao requested changes

2023-12-14 06:36 UTC, gongweibao commented on paddlenlp/trainer/utils/reshard/pp_reshard.py
> +    registered_layers = []
Add some comments of this class ?

2023-12-20 08:18 UTC, ForFishes approved these changes
LGTM

2023-12-20 08:29 UTC, liuzhenhai93 commented on llm/llama/run_sharding_v2.sh
> +#export LD_LIBRARY_PATH=/usr/local/cuda/compat:$LD_LIBRARY_PATH
Done

2023-12-20 08:29 UTC, liuzhenhai93 commented on llm/llama/run_sharding_v2.sh
> +    #--same_data True \
Done

2023-12-20 08:29 UTC, liuzhenhai93 commented on paddlenlp/trainer/utils/sharding_io.py
> +        parallel_config = self._load_distributed_strategy(checkpoint)
Done

2023-12-20 08:29 UTC, liuzhenhai93 commented on paddlenlp/trainer/utils/sharding_io.py
> +        assert self.args.tensor_parallel_degree == mp_degree
Done

2023-12-20 08:30 UTC, liuzhenhai93 commented on paddlenlp/trainer/utils/reshard/pp_reshard.py
> +    registered_layers = []
Done

2023-12-20 11:04 UTC, gongweibao approved these changes
LGTM

2023-12-21 02:24 UTC, merged