[LLM] Support block_attention/cachekv quant for llama
PaddlePaddle/PaddleNLP pull request #7649
Opened 2023-12-14 03:32 UTC by RichardWooSJTU

### PR types

New features
### PR changes

Others
### Description

1. support block attention
2. support cachekv quant

2023-12-14 03:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=7649) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=7649) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: RichardWooSJTU<br/>:x: wufeisheng<br/><hr/>**wufeisheng** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=7649) it.</sub>

2023-12-28 06:38 UTC, wawltor commented on llm/export.sh
> +python -m paddle.distributed.launch \
这个脚本可以先放到llama 模型目录下

2023-12-28 06:38 UTC, wawltor commented on llm/predictor.py
>  import paddle
如沟通先移动到llama目录下，后续等所有的模型都覆盖了，再迁移

2023-12-28 06:38 UTC, wawltor commented on llm/read_res.py
> +import paddle
同上

2023-12-28 06:38 UTC, wawltor commented on llm/run_dygraph.sh
> +#     --block_attn \
同上

2023-12-28 06:38 UTC, wawltor commented on llm/run_static.sh
> +
同上

2023-12-28 06:39 UTC, wawltor commented on paddlenlp/experimental/transformers/generation_utils.py
> +
补充上PaddleNLP CI 和 Paddle CI

2023-12-28 06:43 UTC, vivienfanghuagood commented on csrc/generation/step.cu
> +// 根据上一步计算出的可以复原的query_id进行状态恢复
换成英文注释吧～

2023-12-28 08:45 UTC, wj-Mcat requested changes

2023-12-28 08:45 UTC, wj-Mcat commented on llm/.gitignore
> +max_len.txt
这里是你本地的测试环境下的配置文件，建议回滚一下这个文件。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/benchmark.sh
> +    --src_length ${total_len} \
1. 从语义上面来讲，total_len应该是 src_length + max_length，所以这两个参数的变量命令是不是与--name 对应一致呢？
2. src_length 和 max_length 设置一下默认值： src_length=${src_length:-300}

2023-12-28 08:45 UTC, wj-Mcat commented on llm/export.sh
> +    --use_cachekv_int8 static
我这边的建议是将这个脚本迁移到 ./inference.md 文档里面去，新开一个 cachekv 的 section 来描述这个。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/predictor.py
> +class DygraphBlockInferencePredictor(BasePredictor):
这个模块应该是需要继承：InferencePredictorMixin 吧，这个都是用来处理推理模型的。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/predictor.py
> +            ]
这边有测试过 pre_cache + cache_kv-int8 的组合吗？如果有的话，能够添加一下对应的单测呢？

2023-12-28 08:45 UTC, wj-Mcat commented on llm/predictor.py
> +        self.inputs["seq_lens_this_time"] = paddle.full(shape=[config.batch_size, 1], fill_value=0, dtype="int32")
这块的参数和 `seq_len_decoder` 和 `seq_len_decoder` 有什么区别。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/predictor.py
> +                self.tokenizer.eos_token_id,
这块建议通过 `get_eos_token_id` 函数来初始化，就避免了一些特殊模型的 eos_token 和 tokenizer 里面的 eos_token 不一致的问题。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/predictor.py
> +            print("pre_cache_length: ", self.pre_cache_length)
这个 print 可以删除一下。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/predictor.py
> +        self.inputs["rope_emb"] = self._get_rotary_position_embedding(tmp_position_ids, self.head_dim)
```suggestion
        self.inputs["rope_emb"] = self._get_rotary_position_embedding(
            paddle.arange(self.total_max_length).reshape((1, -1)), 
            self.head_dim
        )
```

下同，尽量避免 tmp_* 这种临时变量。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/predictor.py
> +            print("length: ", length)
如果需要添加一下 print 的话，建议通过 logger.info 的方式来打印比较好一点。这个 print 还是有些临时。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/predictor.py
> +class StaticBlockInferencePredictor(BasePredictor):
你看看这块的代码能否和 StaticInferencePredictor  实现部分的代码复用。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/predictor.py
> +        self.inputs["not_need_stop"] = paddle.full(shape=[1], fill_value=False, dtype="bool").cpu()
这边的静态图和动态图推理的代码感觉很大程度上是可以复用的，所以这块是没必要写两次的。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/predictor.py
> +        分享不拷贝数据
尽量使用中文的 docstring

2023-12-28 08:45 UTC, wj-Mcat commented on llm/read_res.py
> +while True:
这部分的读取是否可以将其迁移到 llm/utils 函数当中，通过一个函数来读取并返回呢，就像 paddle4.6 一样。

2023-12-28 08:45 UTC, wj-Mcat commented on llm/run_dygraph.sh
> +#     --block_attn \
这块的脚本可以迁移到inference.md 文档里面去了。

2023-12-28 08:45 UTC, wj-Mcat commented on paddlenlp/experimental/model_utils.py
> +            print("key_template: ", key_template)
这是一个基础类，所以这里的 print 应该是需要删除的。

2023-12-28 08:45 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/fused_transformer_layers.py
> +        input_ids = kwargs.get("input_ids", None)
这块的代码都是要写单测的。

2023-12-28 08:45 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/fused_transformer_layers.py
> +            # exit(0)
rm

2023-12-28 08:45 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/generation_utils.py
> +        print("use_cachekv_int8", use_cachekv_int8)
其他的 print 我就不一一说了。

2024-01-10 12:28 UTC, wj-Mcat approved these changes

2024-01-10 14:23 UTC, merged