增加llama预训练和微调同时解析json文件和命令行参数的功能
PaddlePaddle/PaddleNLP pull request #7768
Opened 2024-01-03 09:05 UTC by greycooker

增加llama预训练和微调同时解析json文件和命令行参数的功能

2024-01-04 04:14 UTC, gongel commented
需要加到CI脚本中去

2024-01-04 07:55 UTC, greycooker commented
> 需要加到CI脚本中去

单测文件路径是tests/trainer/test_argarser.py

2024-01-08 03:13 UTC, ZHUI requested changes

2024-01-08 03:13 UTC, ZHUI commented on llm/run_pretrain.py
> +    json_indices = [index for index, string in enumerate(sys.argv) if string.endswith(".json")]
别这么找了，没必要。就默认第一个参数需要是 json，其他情况均为非法。

json 后面的其他参数，默认覆盖json 中的参数

2024-01-08 08:31 UTC, ZHUI commented on llm/finetune_generation.py
> +            json_file=os.path.abspath(sys.argv[1])
>= 2 都走你这个分支，==2 的分支删除吧。

这里的规则也加入到注释中，说明一下 支持  args.json --x1 x --x2 y 之类的格式

2024-01-08 08:31 UTC, greycooker commented on llm/run_pretrain.py
> +    json_indices = [index for index, string in enumerate(sys.argv) if string.endswith(".json")]
好的，已按要求修改

2024-01-08 08:32 UTC, greycooker commented on llm/finetune_generation.py
> +            json_file=os.path.abspath(sys.argv[1])
OK

2024-01-08 09:39 UTC, ZHUI commented on paddlenlp/trainer/argparser.py
> +                raise ValueError("The following arguments are required: --output_dir")
为什么这里要 特判 output_dir ？

2024-01-08 09:49 UTC, greycooker commented on paddlenlp/trainer/argparser.py
> +                raise ValueError("The following arguments are required: --output_dir")
比如json文件里有output_dir参数，但是命令行里没有，执行281行vars(self.parse_args())的时候就会报错，但是我们现在不希望让它报错

2024-01-09 02:21 UTC, JunnYu approved these changes, later dismissed
lgtm

2024-01-09 09:30 UTC, ZHUI commented on paddlenlp/trainer/argparser.py
> +                raise ValueError("The following arguments are required: --output_dir")
https://github.com/PaddlePaddle/PaddleNLP/blob/d89c01130a7f27c39d762cefb15926c4c69aa711/paddlenlp/trainer/argparser.py#L177C9-L177C36 

你参考一下这个函数，这个函数也是一样的支持本地文件。
看看这个是怎么处理的。

这个作为通用的parser，在这里做`output_dir`之类的特判是不太合理的。

2024-01-10 04:02 UTC, ZHUI approved these changes
LGTM

2024-01-10 07:15 UTC, merged