[LLM]support QWenVL second part
PaddlePaddle/PaddleNLP pull request #7808
Opened 2024-01-09 07:18 UTC by DanGuge

### PR types

### PR changes

### Description

* 在`qwen/modeling.py`中添加了`QWenForQWenVLInferenceModel`
    * 添加了qwen-vl对应的`generate_text_with_image_features`逻辑
    * 重写了`to_static`函数
* 用户可以通过以下步骤导出模型静态图
    1. 转换`qwen-vl/qwen-vl-7b`权重的key
        * `qwen-vl/qwen-vl-7b`中权重的`key`与`paddlenlp`模型加载需要的`key`存在差异，需要转换
        * 下载`qwen-vl/qwen-vl-7b`模型，拷贝一份`qwen-vl/qwen-vl-7b-inference`
    ```python
    import paddle
    
    state_dict = paddle.load("/path/to/.paddlenlp/models/qwen-vl/qwen-vl-7b-inference/model_state.pdparams")
    new_state_dict = {}
    for key in state_dict.keys():
        if key.startswith("transformer"):
            new_key = key.replace("transformer", "qwen")
            new_state_dict[new_key] = state_dict[key]
        else:
            new_state_dict[key] = state_dict[key]
    paddle.save(new_state_dict, "/path/to/.paddlenlp/models/qwen-vl/qwen-vl-7b-inference/model_state.pdparams")
    ```
    2. 导出静态图
    ```bash
    #!/bin/bash
    
    export CUDA_VISIBLE_DEVICES=0
    export PYTHONPATH=/path/to/PaddleNLP/

    python export_model.py \
        --model_name_or_path "/path/to/.paddlenlp/models/qwen-vl/qwen-vl-7b-inference/" \
        --output_path ./checkpoints/encode_text/ \
        --dtype float16 \
        --inference_model \
        --model_prefix qwen \
        --model_type qwen-img2txt
    ```

2024-01-16 08:58 UTC, wj-Mcat requested changes
代码非常好，留了几个 comment，麻烦有时间看看。

另外，麻烦针对于这里添加一下VL 模型的单测，模型的 forward 和 动转静的过程都是需要编写的。

2024-01-16 08:58 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/qwen/modeling.py
> +        return paddle.ones([batch_size, seq_len], dtype="int64") * bos_token_id
这里就直接使用 paddle.full 的api 来计算会更加高效。

2024-01-16 08:58 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/qwen/modeling.py
> +            raise ValueError("`bos_token_id` should be defined when no " "`input_ids` are provided.")
这里没有传入 input_ids，所以没必要描述与 input_ids 之间的关联吧，你这个 error message 会给开发者一头雾水。

2024-01-16 08:58 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/qwen/modeling.py
> +    # This function is a little different from prepare_input_ids_for_generation in paddlenlp/transformers/generation/utils.py
另外，希望你能够将这里的描述写清楚，到底有哪些区别？

2024-01-16 08:58 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/qwen/modeling.py
> +        if inputs_embeds_dtype == paddle.bfloat16 or inputs_embeds_dtype == paddle.float16:
这里应该是直接判断 ！= paddle.float32 会不会更简洁一点呢？

2024-01-16 08:58 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/qwen/modeling.py
> +        for idx, (i, a, b) in enumerate(img_pos):
代码里面尽量少用：a、b、c、d 这种变量名，阅读起来很难理解。

尽量使用更加清晰的变量命名来，比如说恶：left_index, right_index 之类的，你根据你这边的场景来调整吧。

2024-01-16 08:58 UTC, wj-Mcat commented on paddlenlp/experimental/transformers/qwen/modeling.py
> +        if inputs_embeds_dtype == paddle.bfloat16 or inputs_embeds_dtype == paddle.float16:
同上。

2024-01-16 09:29 UTC, DanGuge commented on paddlenlp/experimental/transformers/qwen/modeling.py
> +            raise ValueError("`bos_token_id` should be defined when no " "`input_ids` are provided.")
这里是在img2txt的模型中，generate中不会传入input_ids，一般发生在第一次进入QWenInferenceModel的forward的时候，所以需要根据inputs_embeds生成一个fake的input_ids，input_ids根据bos_token_id来生成

2024-01-20 23:36 UTC, wj-Mcat commented on tests/llm/test_predictor.py
> +        print(config)
这行代码可以删除。

2024-01-22 06:45 UTC, wj-Mcat approved these changes

2024-01-22 06:51 UTC, xiaoxiaohehe001 approved these changes

2024-01-23 03:03 UTC, wawltor approved these changes
LGTM

2024-01-23 03:04 UTC, merged