Support 5.2 bloom
PaddlePaddle/PaddleNLP pull request #7846
Opened 2024-01-15 02:29 UTC by zhoutianzi666

### PR types

### PR changes

### Description

- 动态图运行代码

python3.8  predictor.py     --model_name_or_path /root/.paddlenlp/models/bigscience/bloom-7b1/     --dtype float16     --src_length 102     --max_length 1024        --batch_size 2    --inference_model

- 动态图运行weight only int8代码

python3.8  predictor.py     --model_name_or_path /root/.paddlenlp/models/bigscience/bloom-7b1/     --dtype float16     --src_length 102     --max_length 1024        --batch_size 2    --inference_model --quant_type weight_only_int8   

- 动转静命令

python3.8 export_model.py --model_name_or_path /root/.paddlenlp/models/bigscience/bloom-7b1/ --inference_model --output_path ./inference --dtype float16 --block_attn

- 静态图推理命令

python3.8  predictor.py --model_name_or_path ./inference --inference_model --dtype "float16" --mode "static" --block_attn

2024-01-16 09:07 UTC, wj-Mcat requested changes
PR 质量很高，除了一个小 comment，我就一点：把单测给加上，直接在 tests/llm/test_predictor.py 里面给加上。

2024-01-16 09:07 UTC, wj-Mcat commented on llm/predictor.py
> +                        BlommForCausalBlockLMInferenceModel as Model,
你这边就仿照 llama block_attn 的写法呗，就直接 `as BloomInferenceModel` ？

2024-01-16 09:07 UTC, wj-Mcat commented on llm/predictor.py
> +                        BloomForCausalLMInferenceModel as Model,
同上。

2024-01-16 10:47 UTC, zhoutianzi666 commented on llm/predictor.py
> +                        BlommForCausalBlockLMInferenceModel as Model,
> 你这边就仿照 llama block_attn 的写法呗，就直接 `as BloomInferenceModel` ？

已经done，感谢review

2024-01-16 10:47 UTC, zhoutianzi666 commented on llm/predictor.py
> +                        BloomForCausalLMInferenceModel as Model,
> 同上。

已经done，感谢review

2024-01-16 10:48 UTC, zhoutianzi666 commented
> PR 质量很高，除了一个小 comment，我就两点点：
> 
> * 把单测给加上，仿照 llama inference 5.2 在 tests/llm/test_predictor.py 里面给加上。
> * 上面的脚本你看看要不要更新到 llm/docs/inference.md  文件里面去。

单测已经加上了。这个命令我觉得可以不放进去，因为和里面已有的命令是类似的。感谢review

2024-01-17 02:00 UTC, wj-Mcat approved these changes
LGTM

2024-01-17 02:33 UTC, merged