[Download] update convert
PaddlePaddle/PaddleNLP pull request #7867
Opened 2024-01-19 07:23 UTC by JunnYu

### PR types

Bug Fixes
### PR changes

APIs
### Description

        # try to detect
        # 1. detect sharded safetensors index
        # 2. detect no sharded safetensors weight
        # 3. detect sharded bin index
        # 4. detect no sharded bin weight
        # 5. detect sharded pdparams index
        # 6. detect no sharded pdparams weight

2024-01-22 03:23 UTC, wj-Mcat requested changes

2024-01-22 03:23 UTC, wj-Mcat commented on paddlenlp/transformers/conversion_utils.py
> -        paddle.save(state_dict, model_weight_file)
别删除，你这样会改变现有 API 的行为：这个不仅仅是在 from_pretrained 里面用到，还可以单独作为api 使用: https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm#6-pytorch%E6%A8%A1%E5%9E%8B%E6%9D%83%E9%87%8D%E8%BD%AC%E6%8D%A2


而且这个还有缓存的作用，你转完一次之后就不用再转化了。

2024-01-22 03:23 UTC, wj-Mcat commented on paddlenlp/transformers/model_utils.py
> +            PYTORCH_WEIGHTS_NAME,
你把 torch 的权重加进去，可是 convert_from_torch = False 怎么办？这里需要先判断 convert_from_torch = True, 然后再把这两个字符串加进去。

2024-01-22 03:23 UTC, wj-Mcat commented on paddlenlp/transformers/model_utils.py
> +    use_safetensors=None,
你为啥把这个默认值改成 None 了呢？你的考虑是什么呢？

2024-01-22 11:48 UTC, ZHUI commented on paddlenlp/transformers/model_utils.py
> +        target_cache_dir = "" if os.path.isdir(pretrained_model_name_or_path) else cache_dir
可以描述一下PR的改动吗？

2024-01-23 05:28 UTC, JunnYu commented on paddlenlp/transformers/model_utils.py
> +        target_cache_dir = "" if os.path.isdir(pretrained_model_name_or_path) else cache_dir
如果是本地路径，那么config.json 和 torch model权重转换后将会保存到本地路径的地址pretraine_model_name_or_path/ filename。否则将会使用cache dir / pretraine_model_name_or_path/ filename

2024-01-25 08:23 UTC, ZHUI approved these changes

2024-04-28 03:04 UTC, closed without merging