Pet
PaddlePaddle/PaddleNLP pull request #802
Opened 2021-07-27 06:29 UTC by leeyy2020

### PR types
New features

### PR changes
Models

### Description
新增pet代码以及README

2021-07-27 13:06 UTC, tianxin1860 requested changes
1. 检查一下有很多无用的注释可以删掉
2. CLUEWSC 的处理逻辑可以和常规任务复用，没必要单独处理

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/data.py
> +        # p_token_ids = tokenizer.convert_tokens_to_ids(p_tokens)
多余的注释可以删掉

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/data.py
> +        # src_ids = p_token_ids + src_ids
多余的注释可以删掉

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/data.py
> +        # calculate mask_positions
Calculate mask_positions

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/data.py
> +        #     example["sentence1"] = example["content"] + u'这些与<unk>有关'
多余的注释

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/data.py
> +        #     example["sentence1"] = example["content"] + u'这些与<unk>有关'
多余的注释

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/evaluate.py
> +        #     masked_positions=masked_positions)
多余的注释

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/model.py
> +            # Ernie sequence_output and new_masked_positions shapes [32, 40, 768] [64]
多余的注释

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/model.py
> +            # prediction_scores shape [64, 18000]
多余的注释

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/model.py
> +class AlbertLMPredictionHead(nn.Layer):
ALBERT 相关代码实验应该都没有用到吧？

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/pet.py
> +            args.language_model)
策略代码里先支持 ernie1.0 即可，和 `EFL`、`P-tuning` 策略实现一致即可.

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/pet.py
> +        help="Language model")
预训练模型当前只支持 ernie1.0 即可，与 `P-tuning` 和 `EFL` 保持一致即可.

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/evaluate.py
> +        # print()
多余的注释

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/evaluate.py
> +        # for index in range(label_length):
多余的注释

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/data.py
> +        #macbert
多余的注释

2021-07-27 13:06 UTC, tianxin1860 commented on examples/few_shot/pet/data.py
> +def convert_cluewsc_example(example,
cluewsc 这里的处理逻辑可以复用 convert_example 的处理逻辑，不需要额外拆出来，最初拆开是为了参加比赛不规范的一种写法.

2021-07-27 14:10 UTC, leeyy2020 commented on examples/few_shot/pet/data.py
> +def convert_cluewsc_example(example,
已修改

2021-07-27 14:11 UTC, leeyy2020 commented on examples/few_shot/pet/data.py
> +        #macbert
已修改

2021-07-27 14:11 UTC, leeyy2020 commented on examples/few_shot/pet/evaluate.py
> +        # for index in range(label_length):
已删除

2021-07-27 14:11 UTC, leeyy2020 commented on examples/few_shot/pet/evaluate.py
> +        # print()
已删除

2021-07-27 14:11 UTC, leeyy2020 commented on examples/few_shot/pet/pet.py
> +        help="Language model")
已修改

2021-07-27 14:11 UTC, leeyy2020 commented on examples/few_shot/pet/pet.py
> +            args.language_model)
已修改

2021-07-27 14:12 UTC, leeyy2020 commented on examples/few_shot/pet/model.py
> +class AlbertLMPredictionHead(nn.Layer):
没有用到，已删除

2021-07-27 14:12 UTC, leeyy2020 commented on examples/few_shot/pet/model.py
> +            # prediction_scores shape [64, 18000]
已删除

2021-07-27 14:12 UTC, leeyy2020 commented on examples/few_shot/pet/model.py
> +            # Ernie sequence_output and new_masked_positions shapes [32, 40, 768] [64]
已删除

2021-07-27 14:12 UTC, leeyy2020 commented on examples/few_shot/pet/evaluate.py
> +        #     masked_positions=masked_positions)
已删除

2021-07-27 14:12 UTC, leeyy2020 commented on examples/few_shot/pet/data.py
> +        #     example["sentence1"] = example["content"] + u'这些与<unk>有关'
已删除

2021-07-27 14:12 UTC, leeyy2020 commented on examples/few_shot/pet/data.py
> +        #     example["sentence1"] = example["content"] + u'这些与<unk>有关'
已删除

2021-07-27 14:12 UTC, leeyy2020 commented on examples/few_shot/pet/data.py
> +        # calculate mask_positions
已删除

2021-07-27 14:12 UTC, leeyy2020 commented on examples/few_shot/pet/data.py
> +        # src_ids = p_token_ids + src_ids
已删除

2021-07-27 14:12 UTC, leeyy2020 commented on examples/few_shot/pet/data.py
> +        # p_token_ids = tokenizer.convert_tokens_to_ids(p_tokens)
已删除

2021-07-27 15:35 UTC, ZeyuChen commented
PR Title需要正式化，Pet这个名称不合规。@leeyy2020

2021-07-28 04:00 UTC, leeyy2020 commented
> PR Title需要正式化，Pet这个名称不合规。@leeyy2020

已修改

2021-07-28 08:20 UTC, tianxin1860 requested changes
1. 依然存在一些无用的注释
2. ClueWSC 的预测逻辑可以和其它任务复用
3. README 有 1 个问题需要修复

2021-07-28 08:20 UTC, tianxin1860 commented on examples/few_shot/pet/README.md
> +#task_name="chid"
README 当中可否给 `task_name` 提供 1 个具体数据集名字作为例子？不用给出所有候选的注释. 参考 EFL 策略 README

2021-07-28 08:20 UTC, tianxin1860 commented on examples/few_shot/pet/README.md
> +#task_name="chid"
同上

2021-07-28 08:20 UTC, tianxin1860 commented on examples/few_shot/pet/evaluate.py
> +        #     masked_positions=masked_positions)
多余的注释

2021-07-28 08:20 UTC, tianxin1860 commented on examples/few_shot/pet/model.py
> +from paddlenlp.transformers.albert.modeling import AlbertPretrainedModel, AlbertMLMHead, AlbertForMaskedLM
无用的 import

2021-07-28 08:20 UTC, tianxin1860 commented on examples/few_shot/pet/predict.py
> +def do_predict_cluewsc(model, tokenizer, data_loader, label_normalize_dict):
cluewsc 的预测逻辑可以和常规任务的预测逻辑复用, 不需要额外处理吧？

2021-07-28 08:20 UTC, tianxin1860 commented on examples/few_shot/pet/predict.py
> +        # # Get max probs label's index
注释多 1 个 `#` 号

2021-07-28 08:20 UTC, tianxin1860 commented on examples/few_shot/pet/predict.py
> +    # return y_pred
无用的注释

2021-07-28 08:20 UTC, tianxin1860 commented on examples/few_shot/pet/predict.py
> +            # {"id": 0, "label": "力学"}
无用的注释

2021-07-28 08:20 UTC, tianxin1860 commented on examples/few_shot/pet/predict.py
> +            # {"id": 0, "label": "力学"}
无用的注释

2021-07-28 08:56 UTC, leeyy2020 commented on examples/few_shot/pet/predict.py
> +            # {"id": 0, "label": "力学"}
已删除

2021-07-28 08:56 UTC, leeyy2020 commented on examples/few_shot/pet/predict.py
> +            # {"id": 0, "label": "力学"}
已删除

2021-07-28 08:56 UTC, leeyy2020 commented on examples/few_shot/pet/predict.py
> +    # return y_pred
已删除

2021-07-28 08:56 UTC, leeyy2020 commented on examples/few_shot/pet/predict.py
> +        # # Get max probs label's index
已删除

2021-07-28 09:08 UTC, leeyy2020 commented on examples/few_shot/pet/predict.py
> +def do_predict_cluewsc(model, tokenizer, data_loader, label_normalize_dict):
已删除

2021-07-28 09:08 UTC, leeyy2020 commented on examples/few_shot/pet/model.py
> +from paddlenlp.transformers.albert.modeling import AlbertPretrainedModel, AlbertMLMHead, AlbertForMaskedLM
已删除

2021-07-28 09:16 UTC, leeyy2020 commented on examples/few_shot/pet/README.md
> +#task_name="chid"
已修改

2021-07-28 09:16 UTC, leeyy2020 commented on examples/few_shot/pet/README.md
> +#task_name="chid"
已修改

2021-07-28 09:16 UTC, leeyy2020 commented on examples/few_shot/pet/evaluate.py
> +        #     masked_positions=masked_positions)
已删除

2021-07-28 11:27 UTC, tianxin1860 submitted a review, later dismissed
LGTM

2021-07-29 05:54 UTC, tianxin1860 approved these changes
LGTM

2021-07-30 04:35 UTC, tianxin1860 commented
add PET for few_shot

2021-07-30 04:35 UTC, merged