add finetune fused & add mc2
PaddlePaddle/PaddleNLP pull request #8139
Opened 2024-03-18 09:22 UTC by NINGBENZHE

2024-03-22 06:22 UTC, wuhuachaocoding commented on paddlenlp/transformers/sequence_parallel_utils.py
MC2的单独放在一个文件？

2024-03-22 06:22 UTC, wuhuachaocoding commented on paddlenlp/transformers/llama/modeling.py
> +                    attention_mask = attention_mask.astype("bool")
这个地方看下在外面判断attn_mask一次，不是bool类型才cast, 可以提高性能。看下不在flash_attn里面cast, 在传入Transformer之前判断并cast一次就行？

2024-03-22 06:22 UTC, wuhuachaocoding commented on paddlenlp/transformers/llama/modeling.py
> +                    is_casual
这里建议别判断casual了，SFT/lora容易出错, 直接给False。或者能确定casual能判断正确。

2024-03-27 08:46 UTC, NINGBENZHE commented on paddlenlp/transformers/llama/modeling.py
> +                    attention_mask = attention_mask.astype("bool")
已解决

2024-03-27 08:47 UTC, NINGBENZHE commented on paddlenlp/transformers/sequence_parallel_utils.py
这两个MC2属于sp的一部分，暂不移动？

2024-03-27 08:47 UTC, NINGBENZHE commented on paddlenlp/transformers/llama/modeling.py
> +                    is_casual
已修改

2024-03-28 10:57 UTC, SylarTiaNII requested changes
需要修改

2024-03-28 10:57 UTC, SylarTiaNII commented on llm/finetune_generation.py
> +class SFTModelArguments(ModelArgument):
整体挪到arguments.py里面，注意pylint。

2024-03-28 10:57 UTC, SylarTiaNII commented on paddlenlp/transformers/llama/modeling.py
> +                    False
is_causal_mask能修复吗？

2024-03-28 10:57 UTC, SylarTiaNII commented on paddlenlp/transformers/llama/modeling.py
> +                is_casual = is_casual_mask(attention_mask)
如果这里没问题，可以从这里下发一个变量传到FA的输入中。

2024-03-28 10:57 UTC, SylarTiaNII commented on paddlenlp/transformers/sequence_parallel_utils.py
> +# Copyright (c) 2022 PaddlePaddle Authors. All Rights Reserved.
为什么会新增文件？

2024-04-01 13:55 UTC, ZHUI commented on paddlenlp/transformers/mc2_seqence_parallel_linear.py
> +import paddle_custom_device
这个默认不安装吧

2024-04-02 03:30 UTC, NINGBENZHE commented on paddlenlp/transformers/mc2_seqence_parallel_linear.py
> +import paddle_custom_device
这个是NPU执行MC2才会引用到的文件

2024-04-02 09:42 UTC, gongweibao commented on paddlenlp/transformers/llama/modeling.py
> +if int(os.getenv("MC2", 0)):
稍微复杂点？
`Paddle_NPU_MC2`

2024-04-02 09:45 UTC, gongweibao commented on paddlenlp/transformers/llama/modeling.py
> +if int(os.getenv("MC2", 0)):
判断一下设备，然后判断`FLAGS`

2024-04-02 09:59 UTC, ZHUI commented on paddlenlp/transformers/mc2_seqence_parallel_linear.py
> +import paddle_custom_device
我知道，可是其他地方import到这个东西的话，会报错。

2024-04-03 11:11 UTC, wawltor commented on llm/argument.py
> +    tokenizer_name_or_path: Optional[str] = field(
后续建议run_pretrain.py也能直接引入arguments的选项

2024-04-03 12:20 UTC, merged