[Tokenizer]Add Chat template
PaddlePaddle/PaddleNLP pull request #8226
Opened 2024-04-03 03:56 UTC by Southpika

### PR types
Function optimization

### PR changes
APIs

### Description
Add `chat_template` in config file to load template

2024-04-03 04:10 UTC, Southpika commented
移除`encode_chat_inputs`中对于`system`的单独处理，并入第一轮对话中合并（作为不可学习的内容）

2024-04-26 10:08 UTC, wj-Mcat reviewed
你可能还需要做以下几个事情：

1. 更新所有支持 chat-template 的 tokenizer_config.json
2. 测试一下先有的多轮对话训练、推理等流程，保证全流程正确。

2024-04-26 10:08 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +        elif isinstance(self.chat_template, ChatTemplate):
这边给一个 warning，提示后续将要删掉 ChatTemplate，请更新本地 tokenizer_config.json 文件。

2024-04-26 10:08 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +    ) -> str | dict[str, numpy.ndarray | paddle.Tensor]:
加上 docstring

2024-04-26 10:08 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +                            conversations.append({"role": "assistant", "content": item[1]})
这块 list[list[str]] -> list[dict[str, str]] 的数据类型转化，可以单独保存为一个函数，因为 Predictor 里面会使用到

2024-04-26 10:08 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +        elif isinstance(conversation, list):
此外，也测试过新旧 chat_template 在 Predictor 中的使用是否符合预期，同时还要测试一下 gradio_ui 能够使用新旧 chat_template。

2024-04-26 10:08 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +                    assert 1 <= len(item) <= 2
这里最好还是加上error_message, 不然真的报错了，用户根本不知道是什么问题问题导致的。

error_message 要说明清楚数据格式是什么？

2024-04-26 10:08 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +    def _encode_chat_inputs(
如果脱离了之前设计的训推一体的 ChatTemplate，这个函数的适用性应该还挺低的，根本用不了。

所以，不太建议将 encode_chat_inputs 这块逻辑写到 tokenizer 里面去，尽量写到前处理里面去。

所以，这块的调整可能 就比较大了。

2024-04-26 10:08 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +        # conversation = []
没用的代码尽量删掉。

2024-04-26 10:08 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +        for round in conversations:
这里尽量多加一些注释，提高代码的阅读性。

2024-04-26 10:08 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +            # print(self.batch_decode(conversation_ids[i]))
删

2024-04-26 10:25 UTC, wj-Mcat commented on tests/transformers/test_chat_template.py
> +    def test_train_format(self):
补一个多轮的case

2024-04-26 10:25 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +        regex_pattern = "|".join(map(re.escape, ans))
重构成一个单独的函数，并添加上单测。

多加 comment

2024-04-28 02:53 UTC, Southpika commented on paddlenlp/transformers/tokenizer_utils.py
> +    def _encode_chat_inputs(
考虑到目前`encode_chat_inputs`函数使用较广，移除造成影响范围可能较大。是否可以考虑以下策略：
默认tgt src切分方式为 src中不含有bot start token:即tgt中含有完整的user轮+bot start token
如果需要重写，则在tokenizer类中单独定义：如qwen

2024-04-28 03:38 UTC, Southpika commented on paddlenlp/transformers/tokenizer_utils.py
> +    ) -> str | dict[str, numpy.ndarray | paddle.Tensor]:
母函数中已有docstring：def apply_chat_template

2024-04-28 03:39 UTC, Southpika commented on paddlenlp/transformers/tokenizer_utils.py
> +                    assert 1 <= len(item) <= 2
数据格式的报错在其他地方已有

2024-04-28 09:39 UTC, wj-Mcat requested changes

2024-04-28 09:39 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +                breakpoint()
这个要删掉

2024-04-28 09:39 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +                conversations = convert_to_dict_chat(conversation)
建议把函数名改成：`convert_to_dict_message`

2024-04-28 09:39 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +        # https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/yKeL8Lljko/YkH5mORwJ3/aeec5d5a3eb84c
这个链接千万不要放

2024-04-28 09:39 UTC, wj-Mcat commented on paddlenlp/transformers/tokenizer_utils.py
> +        non_learnable_parts = self._splited_by_specified_words(origin_msg, ans)
`_splited_by_specified_words` 这个函数名看起来根本不知道是干什么的？建议这边换一个阅读性更好的：`extract_non_learnable_parts`，你觉得呢？

2024-04-28 09:39 UTC, wj-Mcat commented on paddlenlp/transformers/utils.py
> +                # item里只有一个元素，说明为最后一轮
comment 尽量使用英文描述

2024-04-28 11:46 UTC, merged