Support Sharding Overlap
PaddlePaddle/PaddleNLP pull request #8473
Opened 2024-05-21 09:26 UTC by iosmers

### PR types

Performance optimization
### PR changes

Models
### Description

1.支持sharding overlap

2024-05-21 11:19 UTC, ZHUI requested changes

2024-05-21 11:19 UTC, ZHUI commented on paddlenlp/transformers/llama/modeling.py
> -            is_casual = is_casual_mask(attention_mask)
不要删除这个。`if hasattr(self.config, "casual_mask")`

2024-05-21 11:19 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +            sharding_parallel_config = set(self.args.sharding_parallel_config.split(" "))
training_args 文件里面处理好，就别在这里split了

2024-05-21 11:19 UTC, ZHUI commented on llm/run_pretrain.py
> +    casual_mask: Optional[bool] = field(
```suggestion
    use_casual_mask: Optional[bool] = field(
```

2024-05-22 03:17 UTC, ZHUI submitted a review, later dismissed

2024-05-22 03:17 UTC, ZHUI commented on paddlenlp/trainer/trainer.py
> +                self.optimizer._set_all_gather_overlap_forward(True, model)
这个接口需要考虑版本兼容不？

2024-05-22 08:21 UTC, ZHUI submitted a review, later dismissed
LGTM

2024-05-23 03:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=8473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=8473) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: iosmers<br/>:x: yinwei<br/><hr/>**yinwei** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=8473) it.</sub>

2024-05-23 03:40 UTC, sneaxiy approved these changes, later dismissed

2024-05-23 08:33 UTC, ZHUI approved these changes, later dismissed
LGTM

2024-05-23 12:04 UTC, wawltor approved these changes
LGTM

2024-05-24 02:17 UTC, merged