[NPU][LLM] add README & reformat llama scripts
PaddlePaddle/PaddleNLP pull request #8642
Opened 2024-06-20 10:40 UTC by SylarTiaNII

### PR types

Others
### PR changes

Others
### Description

add README for llama training/inference on NPU(910)

2024-06-20 10:45 UTC, ronny1996 approved these changes
LGTM

2024-06-20 12:21 UTC, onecatcn commented
LGTM

2024-06-21 03:14 UTC, ZHUI commented on llm/llama/npu/README.md
> +PaddleNLP在昇腾NPU（[了解昇腾](https://www.hiascend.com/zh/ecosystem/industry)）上对llama2-13B模型进行了深度适配和优化，该套件实现了昇腾NPU和GPU的训推入口基本统一，达到了『无缝切换』的效果。
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/llm/npu/llama

文件放到 llm/npu 下面，我们重构的pr已经合入了

2024-06-21 05:27 UTC, ronny1996 requested changes

2024-06-21 05:27 UTC, ronny1996 commented on llm/llama/npu/README.md
> +```
改为
```
cd PaddleNLP/llm
python predict/export_model.py --model_name_or_path merged_model  --inference_model --output_path ./inference --dtype float16  --device npu  --block_attn
```
当前看必须在 PaddleNLP/llm 才跑得通

2024-06-21 05:27 UTC, ronny1996 commented on llm/llama/npu/README.md
> +# 执行推理代码
改为 
```
# 执行推理代码
python predict/predictor.py  --model_name_or_path ./inference --inference_model --dtype "float16" --mode "static" --block_attn --device npu
```

2024-06-21 05:35 UTC, ronny1996 commented
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/llm/predict/export_model.py#L104 这里帮忙改成 
```
from npu.llama.export_utils import process_params
```

2024-06-22 02:27 UTC, ZHUI requested changes

2024-06-22 02:27 UTC, ZHUI commented on llm/export_npu.sh
> +export PYTHONPATH=../:$PYTHONPATH
刚到 llm/npu

2024-06-22 02:27 UTC, ZHUI commented on llm/predict_npu.sh
> +source /usr/local/Ascend/ascend-toolkit/set_env.sh
放到llm/npu

2024-06-22 03:40 UTC, ZHUI approved these changes

2024-06-22 03:47 UTC, merged