Add MPNet Model
PaddlePaddle/PaddleNLP pull request #869
Opened 2021-08-10 02:07 UTC by JunnYu

飞桨论文复现挑战赛（第四期）MPNet: Masked and Permuted Pre-training for Language Understanding 论文复现提交。

2021-08-31 03:33 UTC, gongel requested changes
Please add docstrings for all your classes and methods which might be utilized by users. You can refer to paddlenlp.transformers.bert.

2021-08-31 03:33 UTC, gongel commented on examples/language_model/mpnet/README.md
> +BERT adopts masked language modeling (MLM) for pre-training and is one of the most successful pre-training models. Since BERT neglects dependency among predicted tokens, XLNet introduces permuted lan
Please translate to Chinese.

2021-08-31 03:33 UTC, gongel commented on examples/language_model/mpnet/README.md
> +### 模型精度对齐
Please remove.

2021-08-31 03:33 UTC, gongel commented on examples/language_model/mpnet/compare.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
Please delete `compare.py`

2021-09-10 10:34 UTC, gongel requested changes
Thanks for your contribution and please give us feedback.

2021-09-10 10:34 UTC, gongel commented on paddlenlp/transformers/mpnet/tokenizer.py
> +            "https://paddlenlp.bj.bcebos.com/models/transformers/mpnet/mpnet-base/vocab.txt",
词表貌似没有ready？

2021-09-10 10:34 UTC, gongel commented on paddlenlp/transformers/mpnet/tokenizer.py
> +            "https://paddlenlp.bj.bcebos.com/models/transformers/mpnet/mpnet-base/vocab.txt",
另外Tokenizer默认会返回`token_type_ids`，但是这个在`MPNet`是不需要的

2021-09-10 10:34 UTC, gongel commented on paddlenlp/transformers/mpnet/modeling.py
> +                                          extended_attention_mask)
`extended_attention_mask `--->`attention_mask `

2021-09-10 10:34 UTC, gongel commented on paddlenlp/transformers/mpnet/modeling.py
> +            The number of classes. Defaults to `2`.
下面的默认值没给哈

2021-09-10 10:46 UTC, yingyibiao commented on paddlenlp/transformers/mpnet/tokenizer.py
> +            "https://paddlenlp.bj.bcebos.com/models/transformers/mpnet/mpnet-base/vocab.txt",
> 词表貌似没有ready？

done

2021-09-10 10:51 UTC, yingyibiao reviewed
图片可以删了哈，保留表格就好

2021-09-10 10:57 UTC, JunnYu commented
好的，过会改

2021-09-10 13:11 UTC, JunnYu commented on paddlenlp/transformers/mpnet/modeling.py
> +                                          extended_attention_mask)
done

2021-09-10 13:11 UTC, JunnYu commented on paddlenlp/transformers/mpnet/modeling.py
> +            The number of classes. Defaults to `2`.
done

2021-09-10 13:11 UTC, JunnYu commented on paddlenlp/transformers/mpnet/tokenizer.py
> +            "https://paddlenlp.bj.bcebos.com/models/transformers/mpnet/mpnet-base/vocab.txt",
done

2021-09-11 02:16 UTC, gongel approved these changes, later dismissed
处理下冲突

2021-09-11 02:16 UTC, gongel commented on paddlenlp/transformers/mpnet/tokenizer.py
> +    def __call__(self,
这个放在`def __init__`后面吧

2021-09-11 02:32 UTC, JunnYu commented on paddlenlp/transformers/mpnet/tokenizer.py
> +    def __call__(self,
done

2021-09-11 02:34 UTC, gongel approved these changes, later dismissed
LGTM😊

2021-09-11 03:46 UTC, gongel commented on paddlenlp/transformers/mpnet/modeling.py
> +# Copyright 2018 The Google AI Language Team Authors and The HuggingFace Inc. team.
Google AI Language Team？

2021-09-11 04:42 UTC, JunnYu commented on paddlenlp/transformers/mpnet/modeling.py
> +# Copyright 2018 The Google AI Language Team Authors and The HuggingFace Inc. team.
我偷懒从别的文件复制的，待会改

2021-09-11 15:49 UTC, gongel approved these changes

2021-09-11 15:50 UTC, merged