add reformer
PaddlePaddle/PaddleNLP pull request #870
Opened 2021-08-10 02:23 UTC by JunnYu

飞桨论文复现挑战赛（第四期）Reformer: The Efficient Transformer 论文复现提交。

2021-09-18 10:57 UTC, yingyibiao commented
前向输出还需要再定位清楚不一致的op！

2021-11-02 08:56 UTC, joey12300 requested changes

2021-11-02 08:56 UTC, joey12300 commented on paddlenlp/transformers/reformer/modeling.py
> +def _logsumexp(x, axis=-1, keepdim=False):
是否可以解释一下为何要二次封装logsumexp呢？如果原有的paddle.logsumexp可以解决问题的话没有必要再封装一层，会影响性能

2021-11-02 08:56 UTC, joey12300 commented on paddlenlp/transformers/reformer/modeling.py
> +            weight.expand(shape=(batch_size, ) + tuple(self.axial_pos_shape) +
这里是否需要加tuple做强制转换呢？本身是否就是tuple?

2021-11-02 08:56 UTC, joey12300 commented on paddlenlp/transformers/reformer/modeling.py
> +            max_position_id = position_ids.max().item()
这里尝试去掉item()，本质上max_position_id在后面代码是作为下标使用，理论上无需使用item()取值也是可以运行的。在训练代码加入item()这种函数会导致无法转成静态图的部署代码

2021-11-02 08:56 UTC, joey12300 commented on paddlenlp/transformers/reformer/modeling.py
> +                attention_mask.sum().item() < batch_size *
同上，理论上也是可以去掉item()

2021-11-02 08:56 UTC, joey12300 commented on paddlenlp/transformers/reformer/modeling.py
> +            self.attention_seed = int(999999999 % sys.maxsize)
这里CPU的seed为何使用固定数值呢？

2021-11-02 08:56 UTC, joey12300 commented on paddlenlp/transformers/reformer/modeling.py
> +            self.feed_forward_seed = int(999999999 % sys.maxsize)
同上

2021-11-03 00:20 UTC, JunnYu commented on paddlenlp/transformers/reformer/modeling.py
> +def _logsumexp(x, axis=-1, keepdim=False):
`paddle.logsumexp` 不支持 5D的Tensor，因此我reshape成4D，再使用。

2021-11-03 00:24 UTC, JunnYu commented on paddlenlp/transformers/reformer/modeling.py
> +            weight.expand(shape=(batch_size, ) + tuple(self.axial_pos_shape) +
要么都使用list，要么都使用tuple。其中`self.axial_pos_shape` 是 list类型，`x.shape`返回的是list类型

2021-11-03 00:32 UTC, JunnYu commented on paddlenlp/transformers/reformer/modeling.py
> +            self.attention_seed = int(999999999 % sys.maxsize)
我当时应该是没找到哪个API能够获取 cpu环境下的seed 。pytorch可以这样获取，torch.seed()

2021-11-03 09:44 UTC, joey12300 commented on paddlenlp/transformers/reformer/modeling.py
> +            weight.expand(shape=(batch_size, ) + tuple(self.axial_pos_shape) +
嗯，了解。那么可以都使用list，只要shape=[batch_size, ]，后面就无需强制转换了

2021-11-03 09:46 UTC, joey12300 commented on paddlenlp/transformers/reformer/modeling.py
> +def _logsumexp(x, axis=-1, keepdim=False):
了解

2021-11-03 10:05 UTC, joey12300 commented on paddlenlp/transformers/reformer/modeling.py
> +            self.attention_seed = int(999999999 % sys.maxsize)
是否可以使用原生random库或者numpy的random模块获取seed呢？

2021-11-07 13:14 UTC, JunnYu commented on paddlenlp/transformers/reformer/modeling.py
> +            self.attention_seed = int(999999999 % sys.maxsize)
当前使用了np.random.randint

2021-11-07 13:14 UTC, JunnYu commented on paddlenlp/transformers/reformer/modeling.py
> +                attention_mask.sum().item() < batch_size *
去掉了

2021-11-08 05:47 UTC, JunnYu commented on paddlenlp/transformers/reformer/modeling.py
> +            max_position_id = position_ids.max().item()
`无法转成静态图的部署代码`，我发现当前很多动态图代码都无法转成静态图的部署代码。因为使用xxx.shape时候，可能某些shape为None，是动态变化的。

2021-11-08 05:48 UTC, JunnYu commented
模型权重链接。
链接：https://pan.baidu.com/s/1ZUxfged0lUavaCBb_uSZHw 
提取码：byg9 
--来自百度网盘超级会员V5的分享

2021-11-08 07:27 UTC, joey12300 submitted a review, later dismissed
LGTM

2021-12-03 13:41 UTC, yingyibiao commented on paddlenlp/transformers/reformer/tokenizer.py
> +    }
这里缺少reformer-enwik8权重加载的tokenizer

2021-12-03 13:42 UTC, yingyibiao commented
权重已上传

2021-12-07 02:46 UTC, JunnYu commented on paddlenlp/transformers/reformer/tokenizer.py
> +    }
reformer-enwik8 不使用`tokenizer`

2021-12-07 03:29 UTC, yingyibiao approved these changes
LGTM

2021-12-07 03:38 UTC, merged