Squeezebert
PaddlePaddle/PaddleNLP pull request #872
Opened 2021-08-10 09:33 UTC by renmada

### PR types
<!-- New features 

### PR changes
add squeezebert model
### Description

2021-08-10 09:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=872) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=872) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=872) it.</sub>

2021-08-10 16:42 UTC, renmada commented
模型权重
链接: https://pan.baidu.com/s/1Jis7In0veo4ODae5OR_FqA 提取码: p5bk

2021-08-15 13:36 UTC, ZeyuChen commented
@renmada  Thanks for your contribution, please sign CLA agreement,  thanks.

2021-08-26 13:10 UTC, smallv0221 requested changes
The mean problem is the use of `config` in layers. Please also provide examples with readme. You can refer to https://github.com/PaddlePaddle/PaddleNLP/blob/develop/examples/language_model/bert/run_glue.py

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/tokenizer.py
> +            tokenizer = SqueezeBertTokenizer.from_pretrained('SqueezeBert-small-discriminator')
Didn't see `SqueezeBert-small-discriminator` .

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/modeling.py
> +    """Construct the embeddings from word, position and token_type embeddings."""
"""
Construct the embeddings from word, position and token_type embeddings.
"""

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/modeling.py
> +        # self.LayerNorm is not snake-cased to stick with TensorFlow model variable name and be able to load
Don't need explanation like this.

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/modeling.py
> +    def __init__(self, config):
Do not pass `config` down to every layer. Please refer to https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/modeling.py

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/modeling.py
> +    def forward(self, input_ids=None, token_type_ids=None, position_ids=None, inputs_embeds=None):
In PaddleNLP, only input_ids is allowed in embedding layer. Please refer to https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/modeling.py

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/modeling.py
> +        self.act = ACT2FN[act]
Please use `getattr(F, activation)` to create activation layer. please refer to https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/gpt/modeling.py

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/modeling.py
> +    def __init__(self, config, cin, q_groups=1, k_groups=1, v_groups=1):
Please declare all perems here instead of using config. Please refer to https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/gpt/modeling.py

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/modeling.py
> +    def __init__(self, config):
The same config problem as above.

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/modeling.py
> +    base_model_prefix = "squeezebert"
Need more documentation here.

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/modeling.py
> +    def __init__(self, **kwargs):
Need more documentation here. Please refer to https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/bert/modeling.py

2021-08-26 13:10 UTC, smallv0221 commented on paddlenlp/transformers/squeezebert/modeling.py
> +    def tie_weights(self):
Why do we need `tie_weights`? I didn't see any layer has `get_output_embeddings` function.

2021-11-02 03:21 UTC, closed without merging