fix #880
PaddlePaddle/PaddleNLP pull request #882
Opened 2021-08-14 06:58 UTC by JunnYu

更新offset mapping计算的方法，主要参考了https://github.com/bojone/bert4keras/blob/master/bert4keras/tokenizers.py#L372。

2021-08-16 05:27 UTC, yingyibiao commented
mark

2021-08-24 06:20 UTC, smallv0221 requested changes
Excellent work! Only a few small problems.

2021-08-24 06:20 UTC, smallv0221 commented on paddlenlp/transformers/tokenizer_utils.py
> +    def rematch(self, text):
Is the name get_offset_mapping better?

2021-08-24 06:20 UTC, smallv0221 commented on paddlenlp/transformers/tokenizer_utils.py
> +            changed from https://github.com/bojone/bert4keras/blob/master/bert4keras/tokenizers.py#L372
Modified from https://github.com/bojone/bert4keras/blob/master/bert4keras/tokenizers.py#L372

2021-08-25 04:50 UTC, smallv0221 approved these changes

2021-08-25 04:50 UTC, smallv0221 commented
LGTM! Thanks for your contribution.

2021-08-25 04:51 UTC, merged