[LLM] Add tools for parameters
PaddlePaddle/PaddleNLP pull request #9137
Opened 2024-09-13 07:28 UTC by Hanyonggong

### PR types
 Others

### PR changes
Others

### Description
add some llm tools:
* llm/tools/convert_gqa_to_mha.py:  convert model from gqa to mha
* llm/tools/merge_satetensors.py:  merge satetensors files to one pdparams file
* llm/tools/split_weights.py:  split model weight

2024-09-13 08:18 UTC, ZHUI commented
emm，你们搞得太复杂了。safetensor本来就支持多文件直接加载，还支持mmap切分load。不需要这么麻烦的。

2024-09-13 08:20 UTC, ZHUI requested changes
@DesmonDay 看看我们已有的方法能不能帮推理直接切分参数。

2024-09-14 03:38 UTC, DesmonDay commented
对safetensors格式的权重做TP切分，我们在 https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/model_utils.py#L2770 这个函数中已经做了实现，直接调用该函数就行，不需要对safetensors合并后再拆分。

2024-09-14 03:39 UTC, DesmonDay commented on llm/tools/convert_gqa_to_mha.py
> +    model = paddle.load(gqa_model_path)
如果对于safetensors格式的权重，就不支持了？

2024-09-14 03:39 UTC, DesmonDay commented on llm/tools/merge_satetensors.py
> +#
这个文件可以直接删掉。

2024-09-14 03:40 UTC, DesmonDay commented on llm/tools/split_weights.py
> +    state_dict = model.convert_tensor_parallel(
前面的切分TP权重这部分，直接调用https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/model_utils.py#L2770

2024-09-19 15:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=9137) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleNLP?pullRequest=9137) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleNLP?pullRequest=9137) it.</sub>

2024-09-19 15:11 UTC, Hanyonggong commented on llm/tools/merge_satetensors.py
> +#
done

2024-09-19 15:11 UTC, Hanyonggong commented on llm/tools/split_weights.py
> +    state_dict = model.convert_tensor_parallel(
已修改

2024-09-20 07:20 UTC, DesmonDay commented on llm/tools/split_weights.py
> +    state_dict = model.convert_tensor_parallel(
感觉你没有理解我的意思。我的意思是切分TP权重的这个函数，convert_tensor_parallel这个东西，不需要你自己调用了，前面的load_tp_checkpoint已经做了这个功能，拿到的state_dict就是切分后的。

2024-09-23 01:37 UTC, Hanyonggong commented on llm/tools/split_weights.py
> +    state_dict = model.convert_tensor_parallel(
已去除

2024-10-09 08:47 UTC, DesmonDay approved these changes
LGTM

2024-10-09 08:51 UTC, yuanlehome approved these changes

2024-10-09 08:57 UTC, ZHUI approved these changes

2024-10-10 03:19 UTC, merged