Add csc task
PaddlePaddle/PaddleNLP pull request #929
Opened 2021-08-26 07:49 UTC by joey12300

### PR types

New features
### PR changes

Models
### Description

Add Chinese spelling correction Task.

2021-08-26 08:00 UTC, ZeyuChen requested changes
应用目录应修正为：examples/text_correction/

2021-08-26 08:00 UTC, ZeyuChen commented on examples/spelling_correction/data.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
应用目录应修正为：examples/text_correction/

2021-08-26 08:03 UTC, joey12300 commented on examples/spelling_correction/data.py
> +# Copyright (c) 2021 PaddlePaddle Authors. All Rights Reserved.
done

2021-09-04 08:35 UTC, ZeyuChen requested changes
新增ernie-csc目录，补充数据记录，修改标题和简介。
数据集调用形式需要大改，不能用csc作为dataset name

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/README.md
> +# 中文文本纠错
新增一个目录层级 examples/text_correction/ernie-csc

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/utils.py
> +                    # if tokens[j].isalnum():
去掉无用注释

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/predict_sighan.py
> +MODEL_CLASSES = {
已验证是ernie最好的话就保留用ernie即可，简化配置。后续exmaples名称改为ernie-csc

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/sighan_evaluate.py
> +    #   correction_writer.write(" ,".join(correction_list) + "\n")
删掉无用注释

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/sighan_evaluate.py
> +        #Only check the correct postion's tokens
井号后面注释要有空格。

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/train.py
> +    train_ds, eval_ds = load_dataset('csc', splits=['train', 'dev'])
数据集名称不能用csc，应该用原始的sighan。如果不区分13，14，15，那么就统一用sighan表示下载全部？这个地方需要当面讨论下。

2021-09-04 08:35 UTC, ZeyuChen commented on paddlenlp/datasets/csc.py
> +class CSC(DatasetBuilder):
是不是应该用Sighan为数据集名称？

2021-09-04 08:35 UTC, ZeyuChen commented on paddlenlp/datasets/csc.py
> +    URL = "https://paddlenlp.bj.bcebos.com/datasets/csc.zip"
讨论下是否需要区分13，14，15。还是将所有数据合并。

2021-09-04 08:35 UTC, ZeyuChen commented on paddlenlp/datasets/csc.py
> +class CSC(DatasetBuilder):
Sighan-cn表示简体数据集，Sighan-tc表示繁体。
tc: tranditional chinese
这是区分简体繁体的标准用法。

2021-09-04 08:35 UTC, ZeyuChen commented on paddlenlp/datasets/csc.py
> +    URL = "https://paddlenlp.bj.bcebos.com/datasets/csc.zip"
文件名改为sighan-cn吧

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/README.md
> +中文文本纠错任务是一项NLP基础任务，其输入是一个可能含有语法错误的中文句子，输出是一个正确的中文句子。语法错误类型很多，有多字、少字、错别字等，目前最常见的错误类型是`错别字`。大部分研究工作围绕错别字这一类型进行研究。百度NLP部门在最新的`ACL 2021`上提出结合拼音特征的Softmask策略的中文错别字纠错模型。PaddleNLP将基于该纠错模型提供中文错别字纠错能力。模型结构如下：
中文文本纠错任务是常见的NLP任务，其输入是一个可能含有语法错误的中文句子，输出是一个正确的中文句子。语法错误类型很多，有多字、少字、错别字等，目前最常见的错误类型是`错别字`。大部分研究工作围绕错别字这一类型进行研究。本文实现了百度在ACL 2021上提出结合拼音特征的Softmask策略的中文错别字纠错的下游任务网络，并提供预训练模型，模型结构如下：

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/README.md
> + Sighan13，Sighan 14，Sighan15是目前中文错别字纠错任务常用的benchmark数据。由于Sighan官方提供的是繁体字数据集，PaddleNLP将提供简体版本的Sighan测试数据。
Sighan的标准写法应该是全大写，SIGHAN，所有文档和注释涉及的一律统一大写。

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/README.md
> +    ![image](https://user-images.githubusercontent.com/10826371/131977272-35cfe428-77ad-4db3-b09f-839a4784823c.png)
代码模块不需要用图片占用repo空间，改为code block方式呈现即可。避免加剧repo size大小增长。

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/model.py
> +class PretrainedModelForCSC(nn.Layer):
ErnieModelForCSC

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/model.py
> +    def __init__(self, pretrained_model, pinyin_vocab_size, pad_pinyin_id=0):
补充类的注释，将代码聚焦于Ernie即可，围绕ernie-csc这个模型结构来实现

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/run_sighan_predict.sh
> +# model_type=ernie_gram
简化，保留ernie-1.0即可

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/sighan_evaluate.py
> +    for i,pred_token in enumerate(pred_tokens) if i%2 ==1]
这一文件似乎不符合python语法，请重新扫描

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/sighan_evaluate.py
> +        # Postpreprocess for ACL2019 csc paper which only deal with last detect positions in test data.
不明白这里的ACL 2019 csc paper指什么，不清晰。

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/train.py
> +from paddlenlp.transformers import ErnieGramModel, ErnieGramTokenizer
保留ernie即可，简化代码

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/README.md
> +- `model_name_or_path` 指示了Fine-tuning使用的具体预训练模型以及预训练时使用的tokenizer，目前支持的预训练模型有："ernie-1.0", "ernie-gram-zh", "roberta-wwm-ext"。预训练模型需要与模型类型对应。若模型相关内容保存在本地，这里也可以提供相应目录地址，例如："./checkpoint/model_xx/"。
简化，默认ernie即可

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/README.md
> +- `model_type` 指示模型使用的预训练模型类型。目前支持的类型有："ernie", "ernie_gram","roberta"。
简化，默认ernie即可

2021-09-04 08:35 UTC, ZeyuChen commented on examples/text_correction/README.md
> +# 中文文本纠错
ERNIE for Chinese Spelling Correction

2021-09-05 03:46 UTC, joey12300 commented on examples/text_correction/sighan_evaluate.py
> +        #Only check the correct postion's tokens
done

2021-09-05 03:46 UTC, joey12300 commented on examples/text_correction/sighan_evaluate.py
> +    #   correction_writer.write(" ,".join(correction_list) + "\n")
done

2021-09-05 03:47 UTC, joey12300 commented on examples/text_correction/utils.py
> +                    # if tokens[j].isalnum():
done

2021-09-06 02:12 UTC, joey12300 commented on examples/text_correction/sighan_evaluate.py
> +    for i,pred_token in enumerate(pred_tokens) if i%2 ==1]
fixed

2021-09-06 02:26 UTC, joey12300 commented on examples/text_correction/train.py
> +from paddlenlp.transformers import ErnieGramModel, ErnieGramTokenizer
done

2021-09-06 02:27 UTC, joey12300 commented on examples/text_correction/README.md
> +- `model_name_or_path` 指示了Fine-tuning使用的具体预训练模型以及预训练时使用的tokenizer，目前支持的预训练模型有："ernie-1.0", "ernie-gram-zh", "roberta-wwm-ext"。预训练模型需要与模型类型对应。若模型相关内容保存在本地，这里也可以提供相应目录地址，例如："./checkpoint/model_xx/"。
done

2021-09-06 02:27 UTC, joey12300 commented on examples/text_correction/README.md
> +- `model_type` 指示模型使用的预训练模型类型。目前支持的类型有："ernie", "ernie_gram","roberta"。
done

2021-09-06 11:58 UTC, joey12300 commented on examples/text_correction/README.md
> +# 中文文本纠错
1. 已把Sighan数据集独立成一个dataset：`sighan-cn`
2. 在README上提供生成数据集的导入方式，提供下载、数据格式转换的脚本，并在训练脚本中提供extra_train_ds_dir命令行参数，用户可以传入相应的数据集路径。

2021-09-06 11:59 UTC, joey12300 commented on examples/text_correction/predict_sighan.py
> +MODEL_CLASSES = {
已删除

2021-09-06 11:59 UTC, joey12300 commented on examples/text_correction/sighan_evaluate.py
> +        # Postpreprocess for ACL2019 csc paper which only deal with last detect positions in test data.
已删除

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/README.md
> +由于Automatic Corpus Generation提供的数据集是以XML形式提供，不满足训练脚本中的对训练数据的要求（输入的文件内容为句子对形式），这里提供一个数据转换脚本，运行以下命令：
`不满足训练脚本中的对训练数据的要求（输入的文件内容为句子对形式），这里提供一个数据转换脚本`

--->

话术上要注重更直接阐明数据组织的需求，而不是说别的不满足。这样开发者得不到正向的结果。

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/README.md
> +![image](https://user-images.githubusercontent.com/10826371/132180831-03b35b03-9eff-4abc-80c3-b43233edfc02.png)
是否可以用code block来呈现，而不是图片。避免增大repo图片存储空间？

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/change_sgml_to_txt.py
> +import xml.dom.minidom
这是pyhton原生依赖吗？

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/run_sighan_predict.sh
> +export CUDA_VISIBLE_DEVICES=3
要改为默认0

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/run_sighan_predict.sh
> +# 下载sighan测试集
不要中文注释

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/train.py
> +from paddlenlp.metrics.sighan import DetectionF1, CorrectionF1
可以考虑降DetectionF1，CorrectionF1提升一个层级
`from paddlenlp.metrics import DetectionF1, CorrectionF1`

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/model.py
> +class PretrainedModelForCSC(nn.Layer):
PretrainedModelForCSC -> ErnieForCSC

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/export_model.py
> +    pretrained_model = ErnieModel.from_pretrained(args.model_name_or_path)
ernie = ErnieModel.from_pretrained ......

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/export_model.py
> +        pretrained_model,
pretrained_model -> ernie

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/README.md
> +使用动态图训练结束之后，还可以将动态图参数导出成静态图参数，具体代码见export_model.py。静态图参数保存在`output_path`指定路径中。
“还可以”这些不适合作为文档用语。这样好像还别的做法一样，其实就这一种做法。
要准确告知用户，预测部署需要导出静态图参数，具体做法是xxx

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/README.md
> +python train.py --batch_size 32 --logging_steps 100 --epochs 10 --learning_rate 5e-5 --model_name_or_path ernie-1.0 --output_dir checkpoints5e-5 --extra_train_ds_dir extra_train_ds
checkpoints5e-5 ->./checkpoints/  or ./ckpt/
不要引导用户这些目录名的命名习惯

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/README.md
> +- `model_name_or_path` 指示了Fine-tuning使用的具体预训练模型以及预训练时使用的tokenizer，目前支持的预训练模型有："ernie-1.0"。预训练模型需要与模型类型对应。若模型相关内容保存在本地，这里也可以提供相应目录地址，例如："./checkpoint/model_xx/"。
目前支持的预训练模型有："ernie-1.0"

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/README.md
> +python export_model.py --params_path checkpoints5e-5/best_model.pdparams
去掉5e-5这些奇怪的后缀

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/export_model.py
> +from paddlenlp.transformers import ErnieGramModel
删除无用的import

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/README.md
> +
需要补充评估指标，用表格方式呈现，便于QA后续回归验证。

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/README.md
> +该脚本会下载Sighan数据集，加载checkpoint的模型参数运行模型，输出SIGHAN测试集的预测结果到predict文件，并输出预测效果。
Sighan -> SIGHAN

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/predict_sighan.py
> +parser.add_argument("--init_checkpoint_path", default=None, type=str, help="The model checkpoint path.", )
常见规则，如果传入的是单个文件，精确到后缀，则使用path。
如果传入的是目录，则使用dir

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/predict_sighan.py
> +parser.add_argument("--init_checkpoint_path", default=None, type=str, help="The model checkpoint path.", )
checkpoint缩写为ckpt， 简化flag命令

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/train.py
> +    pretrained_model = ErnieModel.from_pretrained(args.model_name_or_path)
ernie = ErnieModel

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/train.py
> +    model = PretrainedModelForCSC(
model = ErnieForCSC

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/train.py
> +        pretrained_model,
ernie

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/train.py
> +    if args.extra_train_ds_dir is not None and os.path.exists(
这种特殊操作要增加注释

2021-09-06 15:12 UTC, ZeyuChen commented on examples/text_correction/ernie-csc/train.py
> +            # det_error_probs is producted by softmax
loss环节属于模型关键操作，建议补充注释

2021-09-07 02:05 UTC, joey12300 commented on examples/text_correction/ernie-csc/README.md
> +由于Automatic Corpus Generation提供的数据集是以XML形式提供，不满足训练脚本中的对训练数据的要求（输入的文件内容为句子对形式），这里提供一个数据转换脚本，运行以下命令：
已修改

2021-09-07 02:07 UTC, joey12300 commented on examples/text_correction/ernie-csc/change_sgml_to_txt.py
> +import xml.dom.minidom
是python原生库，无需安装依赖。

2021-09-07 02:08 UTC, joey12300 commented on examples/text_correction/ernie-csc/run_sighan_predict.sh
> +# 下载sighan测试集
done

2021-09-07 02:08 UTC, joey12300 commented on examples/text_correction/ernie-csc/run_sighan_predict.sh
> +export CUDA_VISIBLE_DEVICES=3
done

2021-09-07 02:12 UTC, joey12300 commented on examples/text_correction/ernie-csc/README.md
> +![image](https://user-images.githubusercontent.com/10826371/132180831-03b35b03-9eff-4abc-80c3-b43233edfc02.png)
可以改为code block来呈现。不过这是链接，并没有把图片放在repo中，实际上不会增大repo的体积。

2021-09-07 02:31 UTC, joey12300 commented on examples/text_correction/ernie-csc/train.py
> +from paddlenlp.metrics.sighan import DetectionF1, CorrectionF1
已升级，paddlenlp.metrics __init__.py 导入DetectionF1, CorrectionF1

2021-09-07 02:42 UTC, joey12300 commented on examples/text_correction/ernie-csc/export_model.py
> +        pretrained_model,
done

2021-09-07 02:42 UTC, joey12300 commented on examples/text_correction/ernie-csc/export_model.py
> +    pretrained_model = ErnieModel.from_pretrained(args.model_name_or_path)
done

2021-09-07 02:42 UTC, joey12300 commented on examples/text_correction/ernie-csc/model.py
> +class PretrainedModelForCSC(nn.Layer):
done

2021-09-07 02:55 UTC, joey12300 commented on examples/text_correction/ernie-csc/README.md
> +使用动态图训练结束之后，还可以将动态图参数导出成静态图参数，具体代码见export_model.py。静态图参数保存在`output_path`指定路径中。
done

2021-09-07 02:55 UTC, joey12300 commented on examples/text_correction/ernie-csc/README.md
> +- `model_name_or_path` 指示了Fine-tuning使用的具体预训练模型以及预训练时使用的tokenizer，目前支持的预训练模型有："ernie-1.0"。预训练模型需要与模型类型对应。若模型相关内容保存在本地，这里也可以提供相应目录地址，例如："./checkpoint/model_xx/"。
已简化

2021-09-07 03:04 UTC, joey12300 commented on examples/text_correction/ernie-csc/predict_sighan.py
> +parser.add_argument("--init_checkpoint_path", default=None, type=str, help="The model checkpoint path.", )
init_checkpoint_path-> ckpt_path

2021-09-07 03:04 UTC, joey12300 commented on examples/text_correction/ernie-csc/train.py
> +    pretrained_model = ErnieModel.from_pretrained(args.model_name_or_path)
done

2021-09-07 03:05 UTC, joey12300 commented on examples/text_correction/ernie-csc/train.py
> +    model = PretrainedModelForCSC(
done

2021-09-07 03:05 UTC, joey12300 commented on examples/text_correction/ernie-csc/train.py
> +        pretrained_model,
done

2021-09-07 03:05 UTC, joey12300 commented on examples/text_correction/ernie-csc/README.md
> +该脚本会下载Sighan数据集，加载checkpoint的模型参数运行模型，输出SIGHAN测试集的预测结果到predict文件，并输出预测效果。
done

2021-09-07 03:07 UTC, joey12300 commented on examples/text_correction/ernie-csc/export_model.py
> +from paddlenlp.transformers import ErnieGramModel
done

2021-09-07 03:09 UTC, joey12300 commented on examples/text_correction/ernie-csc/README.md
> +python export_model.py --params_path checkpoints5e-5/best_model.pdparams
已去除

2021-09-07 03:09 UTC, joey12300 commented on examples/text_correction/ernie-csc/README.md
> +python train.py --batch_size 32 --logging_steps 100 --epochs 10 --learning_rate 5e-5 --model_name_or_path ernie-1.0 --output_dir checkpoints5e-5 --extra_train_ds_dir extra_train_ds
已改为./checkpoints/

2021-09-07 03:51 UTC, joey12300 commented on examples/text_correction/ernie-csc/train.py
> +    if args.extra_train_ds_dir is not None and os.path.exists(
已添加详细注释

2021-09-07 06:28 UTC, joey12300 commented on examples/text_correction/ernie-csc/train.py
> +            # det_error_probs is producted by softmax
已添加详细注释

2021-09-07 06:46 UTC, joey12300 commented on examples/text_correction/model.py
> +    def __init__(self, pretrained_model, pinyin_vocab_size, pad_pinyin_id=0):
done

2021-09-07 06:48 UTC, joey12300 commented on examples/text_correction/ernie-csc/README.md
> +
已添加指标效果。

2021-09-07 09:13 UTC, ZeyuChen approved these changes
LGTM

2021-09-07 09:13 UTC, merged